mlrun/ui

package-lock.json
package.json
src/actions/jobs.js
src/serviceWorker.js

Also:
- Move all `eslint` packages to `devDependencies`.
- Fix production linting errors (`no-console`).

Impl [General] Dockerize the web-app, add `npm run docker` script

---

.dockerignore
Dockerfile
nginx/nginx.conf.tmpl
package.json

The files were not committed last time https://github.com/mlrun/ui/pull/11

Impl [General] REALLY dockerize the web-app

---

src/elements/ArtifactsDetailsInfoItem/ArtifactsDetailsInfoItem.js

Fix [Artifacts] Info: Path starts with `://`

---

src/components/DetailsResults/DetailsResults.js

Impl [Jobs] Results: add tooltip to Best Iteration icon

---

src/actions/artifacts.js
src/components/Details/DetailsView.js
src/components/DetailsArtifacts/DetailsArtifactsView.js
src/components/DetailsInfo/DetailsInfo.js
src/elements/ArtifactsTableRow/ArtifactsTableRow.js
src/elements/PreviewModal/PreviewModal.js
src/layout/Content/Content.js
src/utils/createArtifactsContent.js

- Jobs › Artifacts: [bugfix] path in tooltip starts with `://`

Impl [Artifacts] Use `db_key` instead of `key` for name

---

Dockerfile
nginx/nginx.conf.tmpl
package.json
src/setupProxy.js

The path "/function-catalog" is redirected to a static JSON file.

Impl [Config] Use proxy middleware for dev; Add function catalog

---

src/layout/Header/Header.js

Impl [Header] Remove the "UI" from title, leave just "MLRun"

---

src/components/Table/Table.js
src/elements/JobsTableRow/JobsTableRow.js

- [Jobs] Error on clicking job name to open details pane, the pane opens and immediately closes.
- [Jobs] duplicated date cell

Bug with link and nested rows

---

src/App.js
src/utils/createJobsContent.js

- Fixed bug
- Added Loader for Suspense

[Jobs] Fixed wrongly putted WF icon for job when grouped by name

---

src/components/Table/table.scss
src/elements/Chip/Chip.js
src/elements/ChipCell/chipCell.scss
src/elements/TableCell/TableCell.js
src/elements/TableLinkCell/TableLinkCell.js
src/scss/main.scss

https://trello.com/c/aski9Owt/405-jobs-fix-columns-overflowing-each-other
Before:
After:

[Jobs] Fix columns overflowing each other

---

src/components/ArtifactInfoMetadata/ArtifactInfoMetada.js
src/components/ArtifactInfoMetadata/artifactInfoMetadata.scss
src/components/Details/DetailsView.js

Fix scrollbar issue.
Before:
After:

[Artifacts] Refactoring Metadata tab

---

src/components/Table/TableView.js
src/components/Table/table.scss
src/elements/ArtifactsTableRow/ArtifactsTableRow.js
src/elements/TableCell/TableCell.js
src/utils/copyToClipboard.js

https://trello.com/c/J1z6ggtp/410-artifacts-path-add-copy-to-clipboard
Artifacts: click on Path to copy it to clipboard

[Artifacts] Path: add copy-to-clipboard

---

src/components/JobsPanel/JobsPanelView.js

https://trello.com/c/2H8Ap2j7/423-job-wizard-start-accordion-sections-expanded

[Job] Wizard: start accordion sections expanded

---

src/components/Details/details.scss
src/components/DetailsResults/DetailsResults.js
src/components/Table/table.scss
src/scss/mixins.scss

[Jobs] Results: content overflow (Qbr9 lxo1/429)

---

src/components/DetailsInfo/DetailsInfo.js
src/components/FunctionsPage/Functions.js
src/components/JobsPage/Jobs.js
src/elements/DetailsInfoItem/DetailsInfoItem.js

https://trello.com/c/g05ewZAJ/431-jobs-info-link-to-function-is-broken

[Jobs] Info: link to function hash

---

src/common/Accordion/accordion.scss
src/components/ArtifactsPreview/ArtifactsPreviewView.js
src/components/ArtifactsPreview/artifactaPreview.scss
src/components/Details/details.scss
src/components/DetailsArtifacts/detailsArtifacts.scss
src/elements/PreviewModal/previewModal.scss

[Jobs] Artifacts: preview content overflows

---

src/components/Details/DetailsView.js
src/elements/PreviewModal/PreviewModal.js

In the following places the download of artifact is broken:
- Artifacts › Preview modal
- Artifacts › Details panel
- Artifacts › Details panel › Preview tab › Preview modal
- Jobs › Details panel › Artifacts tab › Preview modal

Fix [Artifacts][Jobs] Broken download button for artifacts

---

src/common/Input/Input.js
src/components/JobsPanel/JobsPanel.js
src/components/JobsPanel/JobsPanelView.js
src/components/JobsPanel/jobsPanel.scss
src/components/JobsPanel/jobsPanel.util.js
src/components/ScheduleCron/ScheduleCron.js
src/components/ScheduleCron/scheduleCron.scss
src/components/ScheduleJob/ScheduleJob.js
src/components/ScheduleJob/ScheduleJobView.js
src/components/ScheduleJob/scheduleJob.scss
src/components/ScheduleJobSimple/ScheduleJobSimple.js
src/components/ScheduleJobSimple/scheduleJobSimple.scss
src/scss/borders.scss
src/scss/colors.scss

https://trello.com/c/hpMerpfo/433-jobs-wizard-make-cron-string-editable

[Jobs] Wizard: made cron string editable

---

src/components/DetailsResults/DetailsResults.js

https://trello.com/c/TKBy40W2/426-jobs-results-round-decimals-values
Before:
After:

[Jobs] Results: Round decimals values

---

src/components/FunctionsPage/Functions.js
src/elements/DetailsInfoItem/DetailsInfoItem.js

Originated in PR https://github.com/mlrun/ui/pull/122

Fix [Jobs] Info: function link broken for non-default projects

---

src/components/Artifacts/artifactsData.json
src/components/DetailsInfo/DetailsInfo.js
src/components/DetailsInfo/detailsInfo.scss
src/components/FunctionsPage/functionsData.json
src/components/JobsPage/jobsData.json
src/elements/DetailsInfoItem/DetailsInfoItem.js

[Artifacts] Info: add link to job

---

src/layout/Header/Header.js
src/layout/Header/header.scss

Impl [Header] Add "BETA" next to the title "MLRun"

---

src/elements/TableLinkCell/TableLinkCell.js

https://trello.com/c/pMm9r81f/437-jobs-crash-on-filtering-by-label

[Jobs] Crash on filtering by label

---

src/components/DetailsInfo/DetailsInfo.js
src/components/FunctionsPage/Functions.js
src/components/FunctionsPage/functionsData.json

https://trello.com/c/pgyLgrOd/445-functions-info-add-code-origin

[Functions] Info: added Code Origin

---

src/components/JobsPanel/jobsPanel.util.js
src/components/JobsPanel/panelData.json
src/components/JobsPanelParameters/JobsPanelParameters.js
src/components/JobsPanelParameters/JobsPanelParametersView.js
src/components/JobsPanelParameters/jobsPanelParametersReducer.js
src/elements/EditableParametersRow/EditableParametersRow.js
src/elements/JobsPanelTable/jobsPanelTable.scss

https://trello.com/c/5lcKp5WK/444-jobs-wizard-parameters-switch-value-and-simple-hyper

[Jobs] Wizard: Parameters: switched Value and Simple/Hyper

---

src/components/FilterMenu/FilterMenu.js
src/components/FunctionsPage/Functions.js
src/components/FunctionsPage/functionsData.json
src/components/Table/table.scss

https://trello.com/c/7CXZgbdI/450-functions-always-group-by-name

[Functions] Always group by name

---

src/actions/functions.js
src/api/functions-api.js
src/components/FilterMenu/FilterMenu.js
src/components/FunctionsPage/Functions.js
src/components/FunctionsPage/functionsData.json

https://trello.com/c/ynhyhZOY/449-functions-add-filter-by-name

[Functions] Add filter by name

---

src/components/Artifacts/artifactsData.json
src/components/DetailsInfo/detailsInfo.scss
src/elements/DetailsInfoItem/DetailsInfoItem.js
src/elements/TableCell/TableCell.js
src/utils/createArtifactsContent.js

https://trello.com/c/RQjesWRq/447-artifacts-remove-path-copy-on-clicking-path-in-info

[Artifacts] Remove Path; Copy on clicking path in Info

---

src/components/Artifacts/artifactsData.json
src/components/DetailsInfo/DetailsInfo.js
src/components/Table/table.scss
src/utils/createArtifactsContent.js

https://trello.com/c/d2G0532y/452-artifacts-move-hash-from-list-to-info-tab

[Artifacts] Moved hash from list to Info tab

---

src/elements/ContentMenu/contentMenu.scss
src/layout/Content/Content.js
src/layout/Content/content.scss

https://trello.com/c/XtUVAEWD/446-artifactsfunctions-remove-the-monitor-tab

[Artifacts][Functions] Remove the "monitor" tab

---

src/actions/workflow.js
src/components/Details/details.scss
src/components/Table/TableView.js
src/utils/createJobsContent.js

https://trello.com/c/ezeJBJPQ/455-jobs-infinite-loop-when-no-workflows-returned

[Jobs] Fixed bug with infinite loop when no workflows returned

---

src/components/JobsPanel/JobsPanelView.js
src/components/JobsPanelAdvanced/JobsPanelAdvanced.js
src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
src/components/JobsPanelDataInputs/jobsPanelDataInputsReducer.js
src/components/JobsPanelParameters/JobsPanelParameters.js
src/components/JobsPanelParameters/JobsPanelParametersView.js
src/components/JobsPanelResources/JobsPanelResources.js
src/components/JobsPanelResources/JobsPanelResourcesView.js
src/components/JobsPanelResources/jobsPanelResources.util.js
src/components/JobsPanelResources/jobsPanelResourcesReducer.js
src/elements/JobsPanelTable/JobsPanelTable.js
src/elements/JobsPanelTable/jobsPanelTable.scss
src/elements/JobsPanelTableRow/JobsPanelTableRow.js
src/elements/JobsPanelTableRow/jobsPanelTableRow.scss
src/elements/JobsPanelVolumesTable/JobsPanelVolumesTable.js

https://trello.com/c/rUh5g20Z/464-jobs-wizard-reorder-sections

[Jobs] Wizard: reordered sections

---

src/components/Details/DetailsView.js
src/elements/DetailsMenuItem/DetailsMenuItem.js

https://trello.com/c/k4EcbbhR/468-jobs-details-panel-click-on-tab-headers-closes-panel

[Jobs] Details panel: fixed bug when clicking on tab headers

---

src/components/Artifacts/Artifacts.js
src/components/ArtifactsPreview/ArtifactsPreview.js
src/components/ArtifactsPreview/ArtifactsPreviewView.js
src/components/ArtifactsPreview/artifactaPreview.scss
src/components/Details/DetailsView.js
src/components/DetailsAnalysis/DetailsAnalysis.js
src/components/DetailsArtifacts/detailsArtifacts.scss
src/components/Table/table.scss
src/utils/generateArtifactPreviewData.js

- [Artifacts] Added "Analysis" tab for dataset kind 
- [Artifacts] Preview tab: fixed bug with missing items for Model type
https://trello.com/c/ceufQhfK/466-artifacts-add-analysis-tab-for-dataset-kind
https://trello.com/c/W26txLlV/467-artifacts-preview-tab-missing-items-for-model-type

[Artifacts] Added "Analysis" tab for dataset kind. 

---

.gitattributes

Git line-break detection (LF/CR/CRLF) got image files wrong.

Line breaks bug

---

src/components/DetailsArtifacts/DetailsArtifactsView.js

https://trello.com/c/ZrhNqDtl/474-jobs-artifacts-view-details-link-is-broken

[Jobs] Artifacts: fixed "view details" link

---

src/components/JobsPanelAdvanced/JobsPanelAdvancedView.js
src/elements/JobsPanelSection/JobsPanelSection.js
src/elements/JobsPanelSection/jobsPanelSection.scss

Impl [Jobs] Wizard: reduce vertical spacing in accordion secitons

---

src/components/JobsPanel/JobsPanelView.js

Impl [Jobs] Wizard: Advanced & Resources collapsed by default

---

src/components/JobsPanel/JobsPanelView.js

Impl [Jobs] Wizard: swap places of Advanced & Resources sections

---

src/components/CreateJobPage/CreateJobPage.js

https://trello.com/c/yRoTsQka/477-jobs-wizard-0-at-the-bottom

[Jobs] Wizard: Fixed bug with "0" at the bottom

---

src/utils/measureTime.js

https://trello.com/c/QglcO0Ig/473-jobs-breaks-on-missing-starttime

[Jobs] Fixed bug with negative duration

---

src/common/Input/input.scss
src/components/JobsPanel/panelReducer.js
src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js

https://trello.com/c/IaamZ0wE/478-jobs-wizard-make-output-path-requireddefault

[Jobs] Wizard: made output path required+default

---

src/common/Input/Input.js
src/common/Input/input.scss
src/common/Tip/Tip.js
src/common/Tip/tip.scss
src/elements/RegisterArtifactForm/RegisterArtifactForm.js

https://trello.com/c/7SgLzoD3/479-artifacts-rename-key-to-name-and-add-tip

[Artifacts] Renamed Key to Name and added help text

---

src/components/JobsPanel/JobsPanel.js

https://trello.com/c/kzBc16eA/481-jobs-wizard-missing-handler-in-request-to-create-a-job

[Jobs] Wizard: added handler in request to create a job

---

src/components/JobsPanel/JobsPanel.js

https://trello.com/c/LXMfyYNK/482-jobs-wizard-error-message-does-not-go-away

[Jobs] Wizard: Fixed bug with error message

---

src/components/CreateJobPage/createJobPage.scss
src/components/FilterMenu/FilterMenu.js
src/components/FilterMenu/filterMenu.scss
src/components/ScheduleJob/ScheduleJob.js
src/components/ScheduleJobSimple/scheduleJobSimple.scss

https://trello.com/c/bPOxMl88/483-general-hide-unimplemented-ui-elements

[General] Hide unimplemented UI elements

---

src/elements/MethodDescription/methodDescription.scss

Impl [Create job] Respect newlines in method description

---

src/actions/jobs.js
src/common/RangeInput/RangeInput.js
src/components/CreateJobPage/CreateJobPage.js
src/components/JobsPanel/JobsPanel.js
src/components/ScheduleCron/ScheduleCron.js
src/components/ScheduleJob/ScheduleJob.js
src/components/ScheduleJob/ScheduleJobView.js
src/components/ScheduleJob/recurringReducer.js
src/components/ScheduleJob/scheduleData.json
src/components/ScheduleJob/scheduleJobData.js
src/components/ScheduleJobSimple/ScheduleJobSimple.js
src/elements/ScheduleRecurring/ScheduleRecurring.js
src/reducers/jobReducer.js
src/utils/datePicker.util.js

https://trello.com/c/2UXR7xTd/484-create-job-issues-with-schedule
In "Create job" screen:
- Add missing `task.metadata.project` in POST request
- Simple tab:
- Add missing `schedule` in POST request when using Simple tab
- Default to "10" and "Minute"
- When "Minute" is selected, do not let enter a value less than 10
- Cronstring tab:
- Set default value to `*/10 * * * *`
- Remove field label `15 0-20/2 *`
- Add placeholder text `*/10 * * * *` when input is empty

[Create Job] Issues with schedule

---

src/actions/artifacts.js
src/components/Artifacts/Artifacts.js

https://trello.com/c/sgdmX4tG/486-artifacts-screen-crashes

[Artifacts] Screen crashes when GET fails

---

src/utils/createJobsContent.js
src/utils/generateTableContent.js

https://trello.com/c/WdnzdTZd/487-jobs-incorrectly-saying-not-yet-started-createat-exists
Before:
After:

[Jobs] Incorrectly saying "Not yet started" create_at exists

---

src/elements/ScheduleRecurring/ScheduleRecurring.js
src/elements/ScheduleRecurring/scheduleRecurring.scss

Before:
After:
Relates to PR https://github.com/mlrun/ui/pull/188

Impl [Create Job] Schedule: Simple tab: hide entire "Ends" part

---

src/components/Artifacts/Artifacts.js

https://trello.com/c/DltexuIK/491-artifacts-missing-metadata-tab
Before:
After:

[Artifacts] Fixed bug with missing Metadata tab for dataset artifacts

---

src/components/ArtifactsFilterTree/ArtifactsFilterTree.js
src/components/ArtifactsFilterTree/ArtifactsFilterTreeDropDown.js
src/components/FilterMenu/FilterMenu.js
src/components/FilterMenu/filterMenu.settings.js

https://trello.com/c/wEE5GIrg/490-artifacts-missing-taglatest-query-param-on-refresh

[Artifacts] Missing `tag=latest` query param on refresh

---

src/components/Artifacts/Artifacts.js
src/components/ArtifactsFilterTree/ArtifactsFilterTree.js
src/components/FilterMenu/FilterMenu.js
src/components/RegisterArtifactPopup/RegisterArtifactPopup.js

https://trello.com/c/h52fWP0U/494-artifacts-tree-filter-taglatest-should-not-be-sent
Relates to PR https://github.com/mlrun/ui/pull/200

[Artifacts] Tree filter: `tag=latest` should not be sent

---

src/elements/RegisterArtifactForm/RegisterArtifactForm.js

Impl [Artifact] Register artifact: change "Kind" to "Type"

---

src/layout/Page/Page.js
src/layout/Page/PageView.js
src/scss/main.scss

https://trello.com/c/mMlsHxwo/497-general-remove-left-nav-bar
Before:
After:

[General] Removed left nav bar

---

src/components/JobsPage/jobsData.js
src/components/Table/TableView.js
src/elements/JobsTableRow/JobsTableRow.js

https://trello.com/c/pskG79oI/502-jobs-missing-view-yaml-action
Before:
After:

[Jobs] Fixed bug with missing "View YAML" action

---

src/components/JobsPanel/jobsPanel.util.js

https://trello.com/c/qpV9fe1q/507-job-wizard-parameters-default-to-simple
Before:
After:

[Job] Wizard: Parameters: default to Simple

---

src/components/JobsPanel/JobsPanel.js
src/components/JobsPanel/jobsPanel.util.js

https://trello.com/c/JfeCrLWN/516-create-job-use-hub-for-template-functions

[Create job] Use `hub://` for template functions

---

src/components/JobsPage/jobsData.js
src/elements/TableTypeCell/TableTypeCell.js
src/utils/createFunctionsContent.js
src/utils/createJobsContent.js

https://trello.com/c/ezqTBsXe/517-jobs-schedule-hide-owner-filter
Before:
After:

[Jobs] Schedule: hide Owner filter

---

src/components/ScheduleJob/ScheduleJob.js
src/components/ScheduleJob/scheduleJobData.js
src/elements/ScheduleRecurring/ScheduleRecurring.js

https://trello.com/c/WjrhWY7V/518-create-job-wrong-cron-string-need-to-reset-minute-hours
Before:
After:

[Create Job] Wrong cron string

---

src/components/DetailsResults/DetailsResults.js
src/components/DetailsResults/detailsResults.scss
src/utils/resultsTable.js

https://trello.com/c/LBjOeIYJ/519-jobs-results-no-headers-row
Before:
After:

[Jobs] Results: fixed bug with headers row

---

src/components/JobsPanel/jobsPanel.util.js

https://trello.com/c/MCNoeD5z/522-create-job-resources-empty-untouched-fields-are-populated

[Create Job] Resources: fixed bug with untouched fields

---

src/components/JobsPanel/jobsPanel.util.js
src/components/JobsPanelAdvanced/JobsPanelAdvanced.js
src/components/JobsPanelAdvanced/jobsPanelAdvanced.util.js
src/reducers/jobReducer.js

https://trello.com/c/5Dzl74cb/520-create-job-environment-variables-fix-backend-model

[Create Job] Environment variables: fixed backend model

---

src/elements/EditableParametersRow/EditableParametersRow.js
src/elements/JobsPanelTableRow/jobsPanelTableRow.scss

https://trello.com/c/cUIVb3yx/521-create-job-data-inputs-checkmark-icon-is-mispositioned
Before:
After:

[Create Job] Data Inputs: checkmark icon is mispositioned

---

src/components/JobsPanel/panelReducer.js
src/components/JobsPanelResources/JobsPanelResources.js
src/components/JobsPanelResources/JobsPanelResourcesView.js
src/components/JobsPanelResources/jobsPanelResources.util.js

https://trello.com/c/x9T6AEKB/523-create-job-resources-wrong-gpu-key-no-limit-values

[Create Job] Resources: wrong GPU key, no limit values

---

src/components/JobsPanelAdvanced/jobsPanelAdvanced.util.js

https://trello.com/c/R4mgJ6GA/524-create-job-secrets-wrong-model-structure
In `POST /api/submit_job` request's body in `task.spec.secret_sources`:
Before:
```
[
{
"env": "SOME_SECRET_VALUE"
},
{
"file": "/some/path/to/secret/file"
}
]
```
After:
```
[
{
"kind": "env",
"source": "SOME_SECRET_VALUE"
},
{
"kind": "file",
"source": "/some/path/to/secret/file"
}
]
```

[Create Job] Secrets: changed model structure

---

src/common/Select/select.scss
src/common/TimePicker/TimePicker.js
src/components/ScheduleCron/ScheduleCron.js
src/components/ScheduleJob/ScheduleJob.js
src/components/ScheduleJob/ScheduleJobView.js
src/components/ScheduleJob/recurringReducer.js
src/components/ScheduleJob/scheduleJobData.js
src/components/ScheduleJobSimple/ScheduleJobSimple.js
src/components/ScheduleJobSimple/scheduleJobSimple.scss
src/elements/ProjectDataCard/ProjectDataCard.js
src/elements/ScheduleRecurring/ScheduleRecurring.js
src/elements/ScheduleRecurring/scheduleRecurring.scss
src/utils/datePicker.util.js
src/utils/datetime.js

https://trello.com/c/evAZO0Po/527-create-job-schedule-simple-tab-minor-redesign

[Create Job] Schedule simple tab: minor redesign

---

src/components/ScheduleJob/ScheduleJob.js

- Minute/Hourly: have `*/12 * * * *` instead of `12 * * * *`.
- Weekly: make Monday=0, Tuseday=1, ..., Sunday=6.
- Daily/Weekly/Monthly: have time of day `0 0` instead of `00 00`.

Fix [Create Job] Schedule>Simple: Fix generated cron string

---

src/components/JobsPage/jobsData.js
src/utils/createJobsContent.js

https://trello.com/c/VYPgZYQE/529-jobs-remove-start-time-column
Before:
After:

[Jobs] Removed "Start Time" column

---

src/components/ArtifactsPreview/ArtifactsPreview.js
src/components/ArtifactsPreview/artifactaPreview.scss
src/components/DetailsArtifacts/DetailsArtifacts.js
src/components/DetailsArtifacts/DetailsArtifactsView.js
src/components/DetailsArtifacts/detailsArtifacts.scss

https://trello.com/c/0LqNxhsb/530-jobs-artifacts-click-on-name-to-collapse-expand
Before:
After:

[Jobs] Artifacts: click on name to collapse/expand

---

src/components/JobsPanel/JobsPanel.js
src/components/JobsPanel/jobsPanel.util.js
src/components/JobsPanelResources/JobsPanelResources.js

https://trello.com/c/H7njOq1I/531-create-job-resources-environment-variables-not-populated
Before:
After:

[Create Job] Resources & Environment Variables not populated

---

src/components/Project/ProjectView.js
src/components/Project/project.scss

https://trello.com/c/9seHqttr/544-project-overview-hide-settings-icon-launch-ide-owner

[Project Overview] Hid settings icon, "Launch IDE", Owner

---

src/components/JobsPage/Jobs.js

Backporting https://github.com/mlrun/ui/pull/237 into 0.5.x

Fix [Jobs] Wrong request is sent to fetch workflows - 0.5.x backport

---

Dockerfile
README.md

Impl [General] Nuclio env vars changes

---

src/common/Combobox/Combobox.js
src/common/Combobox/ComboboxView.js
src/common/Combobox/combobox.scss
src/components/CreateJobPage/CreateJobPage.js
src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
src/components/JobsPanelDataInputs/jobsPanelDataInputsReducer.js
src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js
src/elements/JobsPanelTable/jobsPanelTable.scss

https://trello.com/c/DZAIXJm8/545-create-job-data-inputs-add-autocomplete-assistance

[Create Job] Data Inputs: add autocomplete assistance

---

src/components/CreateJobPage/CreateJobPageView.js
src/components/CreateJobPage/createJobPage.scss

https://trello.com/c/qauZniyv/554-create-job-minor-visual-tweaks-to-marketplace
- Horizontally align the tiles with the category name
Before:
After:
- Reduce vertical spacing between category names
Before:
After:

[Create Job] Minor visual tweaks to marketplace

---

src/actions/functions.js
src/components/JobsPanel/JobsPanel.js
src/components/JobsPanel/JobsPanelView.js
src/components/JobsPanel/jobsPanel.scss

https://trello.com/c/14bO4uKR/555-create-job-template-selection-not-working-properly

[Create Job] Fixed bug with template selection

---

nginx/nginx.conf.tmpl
package.json
public/index.html
src/App.js
src/httpClient.js
src/layout/Page/PageView.js
src/scss/main.scss

Also optionally hide the header with `mlrunUi.headerHidden` in `localStorage` set to `'true'`.

Impl [General] On production deploy on /mlrun path

---

src/api/artifacts-api.js
src/components/Artifacts/Artifacts.js
src/components/FilterMenu/FilterMenu.js

Related to PR https://github.com/mlrun/ui/pull/251

[Artifacts] Tree filter: `tag=latest` should not be sent: version 2

---

src/components/ScheduleJob/ScheduleJob.js

https://trello.com/c/xAxUtibm/562-create-job-schedule-cronstring-cannot-edit-value

[Create Job] Schedule: Cronstring: cannot edit value

---

src/components/ScheduleJob/scheduleJobData.js

Impl [Create Job] Schedule: Minute: add 20, remove 12

---

src/App.js

https://trello.com/c/4ZR2bAgZ/560-jobs-clicking-on-jobs-breadcrumb-redirects-to-projects

[Jobs] Clicking on Jobs breadcrumb redirects to Projects

---

src/App.js

Backports PR https://github.com/mlrun/ui/pull/258 from branch **development** to branch **0.5.x**

Fix [Jobs] Clicking on Jobs breadcrumb redirects to Projects

---

src/components/FunctionsPage/Functions.js

Backports PR https://github.com/mlrun/ui/pull/262 from branch **development** to branch **0.5.x**

Fix [Functions] Screen crashes when function is not yet built

---

src/components/ArtifactsPreview/ArtifactsPreview.js
src/components/ArtifactsPreview/artifactaPreview.scss
src/elements/PreviewModal/previewModal.scss
src/scss/main.scss

https://trello.com/c/VYgDb4oJ/559-general-change-loading-error-message

[General] Changed loading error message

---

src/components/Details/DetailsView.js
src/components/Project/Project.test.js
src/components/Project/ProjectView.js
src/components/ProjectsPage/Projects.test.js
src/components/RegisterArtifactPopup/RegisterArtifactPopup.js

Added tests to these components:
- Components:
- DetailsView
- Project
- ProjectView
- Projects
- RegisterArtifactPopUp

add tests to Project and Projects component

---

README.md

Docs [Readme] Development: add environment variables sections

---

src/components/Project/project.scss

Impl [Project Overview] Layout tweaks to use more available room

---

src/components/JobsPage/jobsData.js
src/components/ScheduleCron/ScheduleCron.js

- Jobs: Schedule: Next Run: add "local TZ" note
- Create Job: Schedule: Cronstring: add UTC note

Impl [Scheduled Jobs][Create Job] Add note about timezones

---

src/elements/ScheduleRecurring/ScheduleRecurring.js

**[Create Job › Schedule]**: Simple tab: added a note about all times being in UTC timezone

Impl [Create Job] Schedule: Add note about UTC in Simple tab

---

src/components/Project/project.scss

- **Project Overview**: evenly distribute artifact counters
Before:
After:

Impl [Project Overview] Evenly distribute width of counters

---

src/components/ProjectTable/ProjectTable.js
src/elements/ProjectDataCard/ProjectDataCard.js
src/elements/ProjectStatistics/ProjectStatistics.js

- **Project Overview**: All links to Nuclio UI will be opened in the top window frame, so if MLRun is embedded in an `<iframe>` the links will be opened in the hosting frame

Impl [Project Overview] All Nuclio links to open at top frame

---

src/elements/ProjectJobs/projectJobs.utils.js

https://trello.com/c/qlt6ukAM/599-project-overview-running-jobs-counter-wrong-value

[Project Overview] Running Jobs counter: wrong value

---

src/common/PageActionsMenu/PageActionsMenu.js
src/components/CreateJobPage/CreateJobPageView.js

https://trello.com/c/lK6zCnjY/603-create-job-undefined-job-on-entering-screen
- **Create Job**: when existing the screen the user is redirected to an undefined job

[Create Job] Undefined job on entering screen

---

src/api/jobs-api.js
src/components/JobsPage/Jobs.js
src/components/JobsPage/jobsData.js
src/components/Table/table.scss
src/elements/TableCell/TableCell.js
src/elements/TableProducerCell/TableProducerCell.js
src/utils/createJobsContent.js

https://trello.com/c/ZxuMvnPd/594-jobs-schedule-add-last-run-local-tz-column
- **Scheduled jobs**: Added “Last run” column with the status of last run and its last updated timestamp, and reordered columns

[Jobs] Schedule: Added "Last run (local TZ)" column

---

src/components/JobsPage/jobsData.js
src/utils/createJobsContent.js

https://trello.com/c/3aV64ftT/606-scheduled-jobs-add-labels-column
- **Scheduled Jobs**: added “Labels” column

[Scheduled jobs] Add Labels column

---

src/components/FeatureStore/feaureStore.util.js

Impl [Feature store] Add "Features" and "Feature vectors" tabs

---

src/elements/ProjectFunctions/ProjectFunctions.js

- **Project Overview**: In “Real-time functions (Nuclio)” pane rename “Running functions” counter to “Running”:

Impl [Project Overview] Rename "Running functions" to "Running"

---

src/api/jobs-api.js
src/components/JobsPage/jobsData.js

https://trello.com/c/K1SQKgnE/615-scheduled-jobs-add-labels-filter
- **[Scheduled Jobs]**: Added filter by labels

[Scheduled jobs] Added labels filter

---

src/components/ProjectTable/ProjectTable.js
src/components/ProjectTable/projectTable.scss
src/elements/ProjectFunctions/ProjectFunctions.js

https://trello.com/c/mQDJpIxK/613-project-overview-align-nuclio-function-status-to-nuclio
- **Project Overview**: Adjust the status column of real-time functions (Nuclio) to the same text and colors as in Nuclio itself

[Project Overview] Aligned Nuclio function status to Nuclio

---

src/common/Loader/Loader.js
src/common/Loader/loader.scss
src/components/Project/Project.js
src/components/ProjectsPage/Projects.js
src/components/ProjectsPage/ProjectsView.js
src/elements/ProjectCard/ProjectCard.js
src/elements/ProjectCard/projectCard.util.js
src/elements/ProjectStatistics/projectStatistics.scss
src/elements/ProjectStatisticsCounter/ProjectStatisticsCounter.js
src/reducers/projectReducer.js

https://trello.com/c/qhoZSuTX/619-projects-show-loader-before-value-is-ready
**Projects**: Added a small spinning loader to each counter in a project‘s tile until a value is resolved

[Projects] Show loader before value is ready

---

src/elements/ProjectFunctions/ProjectFunctions.js
src/elements/ProjectJobs/projectJobs.utils.js
src/elements/ProjectStatistics/projectStatistics.scss

https://trello.com/c/vKfAj3k7/626-projectsproject-overview-color-running-counters-in-blue
- **Projects**: Change color of “running” counter to blue instead of green when greater than 0
- **Project Overview**: Change color of “running” counters to blue instead of green when greater than 0

[Projects][Project Overview] Changed the color of running counters to blue

---

src/common/CheckBox/CheckBox.js
src/components/FunctionsPage/Functions.js
src/components/JobsPanel/JobsPanelView.js
src/components/JobsPanel/jobsPanel.util.js
src/components/JobsPanelParameters/JobsPanelParameters.js
src/components/JobsPanelParameters/JobsPanelParametersView.js
src/components/JobsPanelParameters/jobsPanelParameters.util.js
src/components/ScheduleJobSimple/ScheduleJobSimple.js
src/elements/EditableParametersRow/EditableParametersRow.js
src/elements/JobsPanelParametersTable/JobsPanelParametersTable.js
src/elements/JobsPanelParametersTable/JobsPanelParametersTableView.js
src/elements/JobsPanelParametersTable/jobsPanelParametersTable.scss
src/elements/JobsPanelTable/JobsPanelTableView.js
src/elements/JobsPanelTable/jobsPanelTable.scss
src/elements/JobsPanelTableRow/JobsPanelTableRow.js
src/elements/JobsPanelTableRow/jobsPanelTableRow.scss
src/scss/mixins.scss

https://trello.com/c/92yfW1yO/625-create-job-parameters-allow-to-include-exclude-parameters

[Create Job] Parameters: allowed to include/exclude parameters

---

src/App.js
src/actions/functions.js
src/components/Details/DetailsView.js
src/components/FeatureStore/FeatureStore.js
src/components/FeatureStore/feaureStore.util.js
src/components/Table/Table.js
src/components/Table/TableView.js
src/elements/ArtifactsTableRow/ArtifactsTableRow.js
src/elements/DetailsMenuItem/DetailsMenuItem.js
src/elements/TableLinkCell/TableLinkCell.js
src/layout/Content/Content.js
src/scss/main.scss
src/utils/createArtifactsContent.js
src/utils/generateGroupLatestItem.js
src/utils/generateTableContent.js

https://trello.com/c/z3kUI08d/637-feature-sets-group-feature-sets-by-name
- **Feature Sets**: Group feature sets by name, show the one with tag `latest` when group is collapsed, show each group item’s tag when expanded

[Feature sets] Grouped feature sets by name

---

src/components/ArtifactsPreview/ArtifactsPreview.js

https://trello.com/c/4SIAlnJc/644-feature-set-update-preview-tab
- **Feature sets**: Added Preview tab properly

[Feature Set] Updated Preview tab

---

.github/workflows/build.yaml

Backport of https://github.com/mlrun/ui/pull/235 and https://github.com/mlrun/ui/pull/281 + added `'[0-9]+.[0-9]+.x'` as a regex for branches to automatically trigger the workflow on push to them (so it will be automatically triggered when pushing to 0.5.x branch)

Impl [Pkg] Adding GH action to build image per commit [Backport 0.5.x]

---

src/elements/ProjectJobs/projectJobs.utils.js

https://trello.com/c/nAc7rhDz/648-project-overview-count-only-running-workflows
- **Project Overview**: The “Running workflows” counter incorrectly counted _all_ workflows instead of only the _running_ ones

[Project Overview] Count only running workflows

---

src/utils/generateArtifacts.js

- **Artifacts**: the details on the row is now taken from latest instance of the artifact instead of an arbitrary one (applies to Models, Data sets,  & File)

Impl [Artifacts] Show latest instance in the row

---

src/actions/projects.js
src/actions/workflow.js
src/api/projects-api.js
src/api/workflow-api.js
src/components/JobsPage/Jobs.js
src/elements/ProjectJobs/ProjectJobs.js

- **Workflows**: Use new endpoint `GET /api/projects/{project-name}/pipelines` instead of `GET /api/workflows`
Accommodates to PR https://github.com/mlrun/mlrun/pull/626

Impl [Project Overview][Jobs] Accommodate to new pipelines API

---

src/components/DetailsInfo/DetailsInfo.js
src/components/JobsPage/Jobs.js
src/components/Table/table.scss
src/elements/JobsTableRow/JobsTableRow.js
src/elements/TableCell/TableCell.js
src/elements/TableLinkCell/TableLinkCell.js
src/utils/createJobsContent.js

https://trello.com/c/bwPe60Bd/660-scheduled-jobs-link-last-run-to-job-instead-of-function
- **Scheduled Jobs**: Next Run’s timestamp is now a link to that job

[Scheduled Jobs] Link Last Run to job instead of function

---

src/common/PopUpDialog/popUpDialog.scss
src/components/ProjectsPage/Projects.js
src/components/ProjectsPage/ProjectsView.js
src/components/ProjectsPage/projectsData.js

https://trello.com/c/FtaIAyEh/663-projects-add-confirmation-on-archiving-project
- **Projects**: add a confirmation pop-up before archiving a project

[Projects] Add confirmation on archiving project

---

src/components/FeatureStore/FeatureStore.js

- **Feature Sets**: Added new Transformations & Targets tab headers (no tab content yet), and always show Analysis tab header even when there is no content to show

Impl [Feature Sets] Add Transformations & Targets tab headers

---

src/components/ProjectsPage/Projects.js

https://trello.com/c/sFlf5vdC/667-projects-hide-archived-projects-from-all-projects
- **Projects**: Hide archived projects when "All projects" is selected.

[Projects] Hide archived projects from All Projects

---

src/components/Table/table.scss
src/elements/TableCell/TableCell.js
src/scss/main.scss

https://trello.com/c/SLiaEXpx/657-jobs-monitor-add-status-indicator-to-workflows
- **Jobs**: Added status indicator with a tooltip to workflow name when grouping jobs by workflow

[Jobs] Monitor: add status indicator to workflows

---

src/components/Project/project.utils.js

- **Project Overview**: Appended “ (Nuclio)” to the “API gateways” quick-link
Jira ticket 14478

Impl [Project Overview] Append "(Nuclio)" to API GWs quick link

---

src/components/ProjectsPage/projectsData.js

- **Projects**: Show “Delete” action for unarchived projects
Reverts PR https://github.com/mlrun/ui/pull/329
Jira: 16757

Revert [Projects] Allow delete for archived projects only

---

src/components/FunctionsPage/Functions.js

https://trello.com/c/kARFF7xt/656-ml-functions-sort-list-by-updated-in-descending-order
- **Functions**: List of functions is now sorted by Updated column in descending order (from latest to earliest)
Before:
After:
Jira ticket 17857

[ML Functions] Sort list by Updated in descending order

---

src/elements/JobsTableRow/JobsTableRow.js

Before:
After:
PR to branch `development`: https://github.com/mlrun/ui/pull/273

Fix [Jobs] Columns unaligned with nested rows

---

src/components/ProjectsPage/Projects.js

Backports PR https://github.com/mlrun/ui/pull/321 from branch `development` into branch `0.5.x`

Fix [Projects] Missing "No data to show" message when no projects

---

src/components/Project/ProjectView.js
src/elements/ProjectCard/projectCard.util.js
src/elements/ProjectFunctions/ProjectFunctions.js
src/elements/ProjectJobs/projectJobs.utils.js
src/utils/groupByUniqName.js

https://trello.com/c/GiWNdlP7/665-projectsproject-overview-counters-count-distinct-names
- **Projects**: Counters to count only distinct entity names to match the number of items shown in the corresponding list on the relevant screen (before, you saw X items in the counter, but _less_ than X items in the actual relevant screen, because the counter counted all versions of items)
Jira ticket 17629

[Projects][Project Overview] Counters: count distinct names

---

src/components/JobsPanel/panelReducer.js

- **Create Job**: Update the initial value in “Default Artifact Path” filed in “Data Inputs” section from `v3io:///users/{{run.user}}/artifacts/{{run.project}}` to `v3io:///projects/{{run.project}}/artifacts/{{run.uid}}`
Before:
After:
Jira ticket 17861

Impl [Create Job] Update default artifact path

---

src/components/JobsPanel/JobsPanel.js
src/components/JobsPanel/JobsPanelView.js
src/elements/JobsPanelTitle/JobsPanelTitle.js
src/elements/JobsPanelTitle/JobsPanelTitleView.js
src/scss/main.scss

https://trello.com/c/VzqfKmX0/676-create-job-empty-name-is-unexpectedly-valid
- **Create Job**: Job creation was unexpectedly allowed when job name was empty. Now the job name field is invalid in case it is empty.

[Create Job] Empty name is unexpectedly valid

---

src/components/FilterMenu/FilterMenu.js

- **General**: Reword “Label” filter’s placeholder to “key or key=value”

Impl [General] Reword Label placeholder to "key or key=value"

---

src/components/Project/ProjectView.js

- **Project Overview**: Rename the “Features” counter to “Datasets”
Before:
After:
Jira ticket 17993

Impl [Project Overview] Features counter: rename to Datasets

---

.eslintrc.js
src/components/JobsPage/Jobs.js
src/components/JobsPage/jobsData.js
src/components/ProjectsPage/Projects.js
src/components/ProjectsPage/ProjectsView.js

https://trello.com/c/g1xsPJjc/671-projectsscheduled-jobs-add-confirmation-before-delete
- **Projects**: Added confirmation for deletion action on projects and scheduled jobs

[Projects][Scheduled Jobs] Add confirmation before delete

---

src/components/FeatureStore/feaureStore.util.js

Replaces PR https://github.com/mlrun/ui/pull/375

Impl [General] Rename "labels" filter to "label" + merge development

---

src/common/Input/Input.js
src/common/Input/input.scss
src/common/Tip/tip.scss
src/components/ProjectsPage/Projects.js
src/components/ProjectsPage/ProjectsView.js

- **Projects**: Added validation rules to “Name” field to “Create project” pop-up:
Jira ticket IG-18038

Impl [Projects] Creation pop-up: add name validation tooltip

---

src/components/Details/details.util.js
src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
src/components/DetailsRequestedFeatures/detailsRequestedFeatures.scss

https://trello.com/c/DKIpRaFI/684-feature-vectors-requested-features-convert-to-a-table
- **Feature Vectors**: Display requested features in a table
Before:
After:

[Feature Vectors] Requested Features: converted to a table

---

src/elements/TableCell/TableCell.js

Fix [General] Failed to build production build due to console.log

---

src/common/Input/input.scss
src/components/ProjectsPage/ProjectsView.js

- **Projects**: Added max length of 63 to “Name” field to “Create project” pop-up
Relates to https://github.com/mlrun/ui/pull/382
Jirat ticekt ML-72

Impl [Projects] Create project: limit length of Name to 63

---

src/common/Combobox/Combobox.js
src/common/Combobox/ComboboxView.js
src/common/Combobox/combobox.scss
src/components/JobsPanel/jobsPanel.util.js
src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
src/components/JobsPanelDataInputs/jobsPanelDataInputsReducer.js
src/constants.js
src/elements/EditableDataInputsRow/EditableDataInputsRow.js
src/elements/EditableDataInputsRow/EditableDataInputsRow.utils.js
src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js
src/elements/JobsPanelTable/JobsPanelTable.js
src/elements/JobsPanelTable/JobsPanelTableView.js
src/elements/JobsPanelTable/jobsPanelTable.scss
src/elements/JobsPanelTableRow/JobsPanelTableRow.js
src/scss/mixins.scss

https://trello.com/c/Nmo6u7h0/649-create-job-data-inputs-add-auto-completion-on-edit
- **Create Job**: Data Inputs: added auto-completion when editing, not only when creating.
Jira ticket ML-73

[Create Job] Data Inputs: Add auto-completion on edit

---

src/components/Project/Project.js
src/components/Project/ProjectDescription/ProjectDescription.js
src/components/Project/ProjectGoals/ProjectGoals.js
src/components/Project/ProjectLinks/ProjectLinks.js
src/components/Project/ProjectName/ProjectName.js
src/components/Project/ProjectSource/ProjectSource.js
src/components/Project/ProjectView.js
src/components/Project/project.scss
src/elements/ProjectFunctions/ProjectFunctions.js

https://trello.com/c/2MeYGl7a/695-project-overview-add-refresh-button
- **Project Overview**: Added a “Refresh” button to update view with up-to-date data from backend
Jira ticket ML-156

[Project Overview] Added Refresh button

---

src/common/Input/Input.js
src/common/Tip/Tip.js
src/common/Tip/tip.scss
src/components/JobsPanel/JobsPanel.js
src/components/ProjectsPage/ProjectsView.js
src/elements/JobsPanelTitle/JobsPanelTitleView.js
src/elements/JobsPanelTitle/jobsPanelTitle.scss

https://trello.com/b/b41OXMcG/gl-tasks

[Create Job] Added job name pattern and max length validation

---

src/components/Details/details.scss

Reverts PR https://github.com/mlrun/ui/pull/403

Revert[General]Details panel:actions not sticking to top on scroll

---

src/components/ArtifactsPreview/ArtifactsPreview.js
src/components/Details/Details.js
src/components/Details/details.util.js
src/components/DetailsAnalysis/DetailsAnalysis.js

https://trello.com/c/aKZfkOk3/704-analysis-remove-popout-icon-button
- **Feature Sets**: Removed popout icon-button from “Analysis” tab
- **Feature Vectors**: Removed popout icon-button from “Analysis” tab
Before:
After:

[Analysis] Removed popout icon button

---

src/actions/projects.js
src/components/Project/Project.js
src/components/Project/ProjectView.js
src/components/ScheduleJob/ScheduleJobView.js
src/components/ScheduleJob/scheduleJob.scss
src/elements/ProjectFunctions/ProjectFunctions.js
src/elements/ProjectJobs/ProjectJobs.js

https://trello.com/c/10Lbk4KR/701-project-overview-jobs-list-shows-all-iterations-of-same-job
- **Project Overview**: All different iterations of the same job run were listed in the “Jobs and Workflows” pane instead of having a single instance per job run (its best iteration).
Before:
After:

[Project Overview] Jobs list shows all iterations of same job

---

src/components/DetailsInfo/DetailsInfoView.js

https://trello.com/c/J32waOTy/711-files-crash-on-selecting-another-file
- **Artifacts**: Crashes when switching between some different items
Jira ticket ML-228

[Files] Crash on selecting another file

---

src/common/Download/Download.js
src/components/Details/DetailsView.js
src/components/Details/details.util.js
src/components/FeatureStore/featureStore.util.js
src/components/Files/Files.js
src/components/Models/models.util.js
src/elements/DetailsInfoItem/DetailsInfoItem.js
src/elements/PreviewModal/PreviewModal.js
src/elements/TableCell/TableCell.js
src/utils/downloadFile.js
src/utils/generateArtifactPreviewData.js
src/utils/generateArtifacts.js

- **Models,Datasets,Files**: “Path” filed in “Overview” tab missing value, “Preview” tab not working, downloading artifact not working
Before:
After:

Fix [Modles][Datasets][Files] Overview: Path value is missing

---

src/components/Models/models.util.js

- **Models**: Added “Model file” field to “Overview” tab in the details panel, since model‘s target path is a directory, and the model file completes the info

Impl [Models] Overview: add "Model file" field

---

src/common/Download/Download.js
src/components/Details/DetailsView.js
src/components/DetailsArtifacts/DetailsArtifactsView.js
src/elements/PreviewModal/PreviewModal.js
src/elements/TableCell/TableCell.js
src/utils/downloadFile.js

- **Models/Datasets/Files**: Changed name of downloaded file from the model/dataset/file‘s name to the actual file name at the target path. For example, downloaded file of a Model named “abc” with target path “/User/a/b/c/123” will have a the name “123”.

Impl [Models][Datasets][Files] Reflect actual downloaded filename

---

src/utils/generateTemplatesCategories.js

- **Create Job**: Removed functions of kind "remote" from marketplace
Relates to PR https://github.com/mlrun/ui/pull/400
Jira ticket ML-261

Impl [Create Job] Filter out function templates of kind Remote

---

package.json
src/colorConstants.js
src/common/Chart/MlChart.js
src/common/Chart/mlChart.scss
src/common/Chart/mlChart.util.js
src/common/Download/Download.js
src/common/Input/input.scss
src/common/Loader/Loader.js
src/common/Loader/loader.scss
src/components/Details/Details.js
src/components/DetailsStatistics/DetailsStatistics.js
src/components/DetailsStatistics/detailsStatistics.scss
src/components/DetailsStatistics/detailsStatistics.util.js
src/elements/ProjectDataCard/ProjectDataCard.js
src/elements/ProjectStatistics/projectStatistics.scss
src/elements/ProjectStatisticsCounter/ProjectStatisticsCounter.js
src/scss/colors.scss

https://trello.com/c/0OrWlwWq/692-features-sets-statistics-tab-add-histogram-column
- **Feature Sets**: Added “Histogram” column to “Statistics” tab
Jira ticket ML-270

[Features Sets] Statistics tab: add histogram column

---

src/components/FilterMenu/FilterMenu.js

https://trello.com/c/pclBqZtt/715-general-filters-not-cleared-on-switching-tabs
- **Jobs,Models,Feature Store**: The filters were unexpectedly not reset when switching tabs in a multi-tab screen.
Jira ticket ML-277

[General] Filters not cleared on switching tabs

---

src/common/Combobox/Combobox.js
src/common/Combobox/ComboboxView.js
src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
src/components/JobsPanelDataInputs/jobsPanelDataInputsReducer.js
src/elements/EditableDataInputsRow/EditableDataInputsRow.js
src/elements/EditableDataInputsRow/EditableDataInputsRow.utils.js
src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js

https://trello.com/c/PhhILY0l/719-create-job-data-inputs-feature-vectors-selection-in-store
- **Create job**: Data inputs: now feature vectors could be selected, too. Once selecting the “MLRun Store” option, the user first needs to select between adding an artifact or a feature vector, then the project and the specific item.
Jira ticket ML-251

[Create Job] Data Inputs: feature vectors selection in store

---

src/components/Details/details.util.js
src/components/DetailsInfo/DetailsInfoView.js
src/components/Models/models.util.js
src/components/Table/table.scss
src/utils/createArtifactsContent.js

https://trello.com/c/RzeEgHCD/727-models-add-metrics-column
- **Models**: Added “Metrics” column (and reduced width of “Labels” column to show only 1 chip with count of labels)
Jira ticket ML-288

[Models] Add Metrics column

---

src/elements/ArtifactsTableRow/ArtifactsTableRow.js
src/elements/TableLinkCell/TableLinkCell.js

https://trello.com/c/6hXmiuWU/730-features-search-by-name-crashes-ui
- **Features**: Filtering by “Name” crashed UI. It is now fixed.
Jira ticket ML-250

[Features] Search by name crashes UI

---

src/common/Breadcrumbs/Breadcrumbs.js
src/components/ProjectsPage/Projects.js
src/reducers/projectReducer.js

https://trello.com/c/yz1sLt3B/725-projects-nuclio-functions-not-re-fetched-on-refresh
- **Projects**: Nuclio function details were not re-fetched when clicking the “Refresh” button (so some counters on the screen could be out-of-date)
Jira ticket ML-282

[Projects] Nuclio functions not re-fetched on refresh

---

Dockerfile

Bug originates in PR https://github.com/mlrun/ui/pull/407

Fix [Feature Store] "Beta" note does not appear by default

---

src/actions/app.js
src/api/app-api.js
src/common/Button/Button.js
src/common/Button/Button.stories.js
src/common/Button/button.scss
src/common/TableActionsMenu/TableActionsMenu.js
src/common/TableActionsMenu/tableActionsMenu.scss
src/common/Tooltip/Tooltip.js
src/components/FeatureStore/featureStore.util.js
src/components/FilterMenu/FilterMenu.js
src/components/JobsPage/Jobs.js
src/components/JobsPage/jobsData.js
src/constants.js
src/layout/Content/Content.js
src/layout/Page/Page.js
src/reducers/appReducer.js
src/reducers/reducers.js

https://trello.com/c/U3ClsBID/732-jobs-monitor-add-links-to-performance-reports
- **Jobs**: Added resource monitoring in the project level and in the job level (new action “Monitoring”)
Jira ticket ML-142

[Jobs] Monitor: add links to performance reports

---

src/actions/artifacts.js
src/common/Tooltip/Tooltip.js
src/components/Details/DetailsView.js
src/components/Details/details.util.js
src/components/DetailsInfo/DetailsInfoView.js
src/components/DetailsInfo/detailsInfo.util.js
src/components/Models/models.util.js
src/elements/ArtifactsTableRow/ArtifactsTableRow.js
src/elements/TableLinkCell/TableLinkCell.js
src/utils/createArtifactsContent.js
src/utils/index.js

- **Model Endpoints**: Accommodated to new API changes, added new fields for “Model artifact” (with link) and “Function URI”, rename “Error ratio” to “Error count”, use “-” instead of “N/A” for missing values

Impl [Model endpoints] Add fields: Model artifact, Function URI

---

src/components/Details/DetailsView.js
src/components/Details/details.util.js
src/components/DetailsInfo/detailsInfo.util.js
src/components/Models/models.util.js
src/utils/createArtifactsContent.js

- **Model endpoints**: Accommodate to yet _more_ API changes, and added more fields in “Overview” tab, and make “Function URI” a link to the relevant function page

Impl [Model endpoints] Accommodate to more API changes+more fields

---

src/components/Details/details.util.js
src/components/DetailsInfo/detailsInfo.scss
src/components/FeatureStore/FeatureStore.js
src/components/FeatureStore/featureStore.util.js
src/components/Files/Files.js
src/components/Files/files.util.js
src/components/Models/models.util.js
src/constants.js
src/elements/DetailsInfoItem/DetailsInfoItem.js
src/utils/generateUri.js

https://trello.com/c/odzmjCTN/733-general-add-uri-field-and-copy-uri-action
- **Models, Datasets, Files, Feature sets, Feature vectors**: Added “Copy URI” action to action menu, which copies to clipboard the URI of the item, for example: `store://models/default/mymodel-0@226dd4edcaea4a7e9edac734670ffbc2 `, `store://datasets/default/mydf-1:some-tag` and `store://feature-vectors/default/my-vec:latest`
Jira ticket ML-252

[General] Add "URI" field and "Copy URI" action

---

src/components/JobsPanel/jobsPanel.util.js

https://trello.com/c/hpNMWcUQ/742-jobs-schedule-edit-crashes
- **Jobs**: In “Schedule” tab, firing “Edit” action sometimes results in an error
Jira ticket ML-325

[Jobs] Schedule: edit crashes

---

src/layout/Page/Page.js

https://trello.com/c/2leBknJr/735-general-poll-for-frontend-spec-every-60-seconds
- **Jobs**: In “Monitor” tab, update “Resource monitoring” button and “Monitoring” action of a job periodically (every 60 seconds) to see if it should become enabled/disabled.
Jira ticket ML-316

[General] Poll for frontend spec every 60 seconds

---

src/components/DetailsArtifacts/DetailsArtifactsView.js
src/components/DetailsArtifacts/detailsArtifacts.scss
src/components/DetailsInfo/detailsInfo.scss
src/components/Project/ProjectLinks/ProjectLinks.js
src/components/Project/project.scss
src/components/ProjectTable/ProjectTable.js
src/components/ProjectTable/projectTable.scss
src/components/ScheduleCron/ScheduleCron.js
src/components/ScheduleCron/scheduleCron.scss
src/components/Table/table.scss
src/elements/DetailsInfoItem/DetailsInfoItem.js
src/elements/ProjectDataCard/ProjectDataCard.js
src/elements/TableLinkCell/TableLinkCell.js
src/elements/TableProducerCell/TableProducerCell.js
src/scss/main.scss
src/stories/Link.stories.js

https://trello.com/c/SCQf6Zqb/741-general-links-style-add-underline-on-hover
- **General**: Added hover effect for links — underline

[General] Links style: add underline on hover

---

src/components/ProjectTable/ProjectTable.js
src/components/ProjectTable/projectTable.scss

- **Project**: In “Real-time functions (Nuclio)” pane, the cells of “Status” column are incorrectly empty.
Before:
After:
Jira ticket ML-349
[Trello card](https://trello.com/c/Yy9YWkA1)

Fix [Project] Real-time functions: missing status values

---

Dockerfile

- **Build**: Improve performance of Dockerfile so building Docker image takes less time.

Impl [Config] Improve performance of Dockerfile

---

src/common/TableActionsMenu/TableActionsMenu.js
src/components/Details/DetailsView.js
src/components/JobsPage/jobsData.js
src/components/Table/TableView.js
src/elements/JobsTableRow/JobsTableRow.js

- **Jobs**: In “Monitor” tab, the “Monitoring” action is now disabled for jobs of kind “Dask”
Jira ticket ML-350

Impl [Jobs] Monitor: disable "Monitoring" action for Dask jobs

---

src/components/Details/Details.js
src/components/Details/DetailsView.js
src/components/JobsPage/jobsData.js
src/elements/JobsTableRow/JobsTableRow.js

- **Jobs**: In “Schedule” tab, there was some error in the console (though no visible usability issue occurred)
Bug originated in PR https://github.com/mlrun/ui/pull/472

Fix [Jobs] Schedule: console error

---

src/components/JobsPanel/jobsPanel.util.js

https://trello.com/c/piQwvMYb/756-jobs-schedule-edit-not-working-for-job-with-secrets
- **Jobs**: In “Schedule” tab, an error occurred on firing the “Edit” action for a scheduled job that has secrets
Jira ticket ML-355

[Jobs] Schedule: edit not working for job with secrets

---

src/components/JobsPage/jobsData.js

https://trello.com/c/kkGNX6lo/752-jobs-monitor-rename-rerun-to-re-run
- **Jobs**: In “Monitor” tab, rename the “Rerun” action to “Re-run”
Before:
After:
Jira ticket ML-360

[Jobs] Monitor: Rename “Rerun” to “Re-run”

---

src/common/Button/Button.js
src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js

https://trello.com/c/NWSv3EhD/762-projects-create-new-project-submitted-on-invalid-input
- **Projects**: In “Create new project”, the “Create” button was enabled when “Name” field was invalid
Before:
After:
Jira ticket ML-370

[Projects] Create new project: submitted on invalid input

---

src/elements/JobsTableRow/JobsTableRow.js

Since PR https://github.com/mlrun/ui/pull/489 this chunk of code is no longer needed.

Cleanup [Jobs] Remove redundant code for hiding actions

---

src/components/FeatureStore/FeatureStore.js
src/components/FeatureStore/featureStore.util.js

https://trello.com/c/zmL1XwFh/772-feature-store-crashes-on-expanding-feature-sets
- **Feature store**: Fixed error that occurred on navigating to “Features” tab, then to “Feature sets” or “Feature vectors” and expanding one of the grouped rows
Jira ticket ML-434

[Feature Store] Crashes on expanding feature sets

---

.gitignore
package.json
scripts/testui.js
tests/config.js
tests/features/common-tools/common-tools.js
tests/features/common/actions/action-menu.action.js
tests/features/common/actions/common.action.js
tests/features/common/actions/dropdown.action.js
tests/features/common/actions/table.action.js
tests/features/common/components/action-menu.component.js
tests/features/common/components/dropdown.component.js
tests/features/common/components/table.component.js
tests/features/common/page-objects.js
tests/features/projectsPage.feature
tests/features/step-definitions/steps.js
tests/features/support/hooks.js
tests/features/support/world.js
tests/report.js

Collecting the following PRs from **tests** branch into **development** branch:
https://github.com/mlrun/ui/pull/507

Impl [e2e-tests] Add e2e-tests infra + project scripts

---

src/actions/artifacts.js
src/api/artifacts-api.js
src/components/Details/Details.js
src/components/Details/DetailsView.js
src/components/Details/details.util.js
src/components/Details/detailsReducer.js
src/components/DetailsArtifacts/DetailsArtifacts.js
src/components/DetailsInfo/DetailsInfo.js
src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
src/components/DetailsRequestedFeatures/detailsRequestedFeatures.scss
src/components/DetailsRequestedFeatures/detailsRequestedFeatures.utils.js
src/components/DetailsRequestedFeatures/detailsRequestedFeaturesReducer.js
src/components/FeatureStore/FeatureStore.js
src/components/FeatureStore/featureStore.util.js
src/elements/DetailsInfoItem/DetailsInfoItem.js

https://trello.com/c/R7efI1hO/779-feature-vectors-requested-features-remove-and-edit-alias
- **Feature vectors**: In “Requested feature” tab, the user can now remove requested features and set their alias
Jira ticket ML-431

[Feature Vectors] Requested features: remove and edit alias

---

src/elements/ProjectJobs/projectJobs.utils.js

https://trello.com/c/BdRdUnjW/778-project-overview-count-aborted-jobs-in-failed-counter

[Project Overview] Count aborted jobs in Failed counter

---

src/common/Download/Download.js
src/components/FeatureStore/featureStore.util.js
src/components/JobsPage/Jobs.js

- **General**: Reworded a few messages of success/failure notifications.

Impl [General] Reword success/failure notification texts

---

src/api/artifacts-api.js
src/common/Download/Download.js
src/components/Details/DetailsView.js
src/components/DetailsAnalysis/DetailsAnalysis.js
src/components/DetailsInfo/DetailsInfoView.js
src/components/DetailsPreview/DetailsPreview.js
src/elements/DetailsInfoItem/DetailsInfoItem.js
src/elements/TableCell/TableCell.js
src/utils/createArtifactPreviewContent.js
src/utils/generateArtifactPreviewData.js
src/utils/generateArtifacts.js
src/utils/getArtifactPreview.js

https://trello.com/c/uVQkzfIP/783-models-preview-does-not-show-extra-data
- **Models**: Preview of models stopped working

[Models] Preview does not show extra data

---

src/components/DetailsArtifacts/DetailsArtifactsView.js
src/components/DetailsArtifacts/detailsArtifacts.util.js

- **Jobs**: There was an error in “Artifacts” tab of a selected job when expanding an artifact to see its preview

[Jobs] Fixed bug on Artifacts preview

---

src/utils/createArtifactsContent.js

- **Model Endpoints**: Error on selecting a model endpoint
Originates in PRs https://github.com/mlrun/ui/pull/521 [v0.6.3-RC6](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc6) and relates to PR https://github.com/mlrun/ui/pull/392 [v0.6.1-RC2](https://github.com/mlrun/ui/releases/tag/v0.6.1-rc2)
Jira ticket ML-480

Fix [Model Endpoints] Error on selecting a model endpoint

---

Dockerfile
config.js.tmpl
config.json.tmpl
nginx/run_nginx
public/config.js
public/config.json
public/index.html
src/index.js

- **General**: The entire app acted weird when MLRun service was upgraded/restarted. This was caused by the `config.js` script not properly running. Now renamed `config.js` to `config.json` and UI fetches it from within the JS code instead of via a `<script>` tag.
Jira ticket ML-339

Fix [General] config.js not always loading and all breaks

---

src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
src/components/FeatureSetsPanel/FeatureSetsPanelView.js

- **Feature sets**: In “Create feature set” panel, in “Targets” section, for “Other” option, in “Kind” dropdown menu, remove the “Stream” option
Before:
After:
- **Feature sets**: In “Create feature set” panel, rename “Start ingestion” button to “Save & ingest”
Before:
After:
Continues feature https://github.com/mlrun/ui/pull/510 [v0.6.3-RC4](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc4) ML-231
Jira ticket ML-506

Impl [Feature sets] Create: Remove Stream target & rename button

---

src/index.js

- **General**: Only “Projects” screen loaded properly, the rest do not load
Bug originates in https://github.com/mlrun/ui/pull/539 [v0.6.3-rc9](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc9) ML-339
Jira ticket ML-508

Fix [General] Only Projects screen load properly, others fail

---

src/elements/AddFeatureButton/AddFeatureButton.js

https://trello.com/c/obJLhwnV/794-features-error-on-adding-a-feature-to-empty-feature-vectors
- **Features**: An error occurred on adding features to an empty feature vector (a feature vector that had no requested features)
Relates to feature https://github.com/mlrun/ui/pull/514 [v0.6.3-RC5](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc5) ML-13
Jira ticket ML-491

[Features] Error on adding a feature to empty feature vectors

---

src/common/Select/Select.js
src/components/ArtifactsFilterTree/ArtifactsFilterTree.js
src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
src/scss/mixins.scss

https://trello.com/c/ZkCvQd4F/793-features-newly-created-vector-not-showing-for-selection
- **Features**: After creating a new vector using the “Add to feature vector” button, the newly-created vector was not listed in the existing vectors list of the current project when clicking on “Add to feature vector”
Relates to feature https://github.com/mlrun/ui/pull/514 [v0.6.3-RC5](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc5) ML-13
Jira ticket ML-491

[Features] Newly-created vector not showing for selection

---

src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js

- **Feature vectors**: In “Requested features” tab, removed the “Delete” action and made alias non-editable
Reverts https://github.com/mlrun/ui/pull/513 [v0.6.3-RC5](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc5) ML-431
Jira tickets ML-487, ML-488, ML-489

Revert [Feature vectors] Requested features: remove and edit alias

---

src/common/DatePicker/DatePicker.js
src/components/FilterMenu/FilterMenu.js

https://trello.com/c/Ll1VNqaZ/791-jobs-monitor-filters-applying-start-time-disregards-name

[Jobs] Monitor: Filters: applying start time disregards name

---

src/elements/DeployModelPopUp/DeployModelPopUp.js

- **Models**: Rename “Select serving function” heading to “Deploy model”
Before:
After:
Continues https://github.com/mlrun/ui/pull/554
Jira ticket ML-405

Impl [Models] Rename "Select serving function" to "Deploy model"

---

src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js

Re-introducing:
- **Feature vectors**: In “Requested features” tab, added “Delete” action with confirmation message and made alias editable
Reverts https://github.com/mlrun/ui/pull/548 [v0.6.3-RC11](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc11)
Re-introduces https://github.com/mlrun/ui/pull/513 [v0.6.3-RC5](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc5) ML-431
Jira ticket ML-431

Redo [Feature vectors] Requested features: remove and edit alias

---

src/components/JobsPage/jobsData.js

- **Jobs**: In “Schedule” tab, rename “Remove” action to “Delete” and move it to be the last action on the menu
Before:
After:
Jira ticket ML-546

Impl [Jobs] Schedule: Rename Remove to Delete and move to last

---

src/common/ActionsMenu/ActionsMenu.js
src/common/ActionsMenu/actionsMenu.scss

https://trello.com/c/lhnVOKug/800-general-action-menu-icon-hover-overflow
- **General**: Action icon background was overflowing on hover
Before:
After:
Jira ticket ML-551

[General] Action menu icon hover overflow

---

src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js

https://trello.com/c/oahRYG2F/813-feature-vectors-requested-features-delete-not-working

[Feature vectors] Requested Features: Delete not working

---

src/components/FunctionsPage/Functions.js

https://trello.com/c/9aMG65aF/814-functions-add-confirmation-to-delete-action
- **Functions**: Added confirmation pop-up to “Delete” action
Relates to https://github.com/mlrun/ui/pull/267 [v0.6.0-RC1](https://github.com/mlrun/ui/releases/tag/v0.6.0-rc1)
Jira ticket ML-568

[Functions] Add confirmation to Delete action

---

.gitignore
tests/features/common-tools/common-consts.js
tests/features/common/actions/action-menu.action.js
tests/features/common/actions/checkbox.action.js
tests/features/common/actions/common.action.js
tests/features/common/actions/dropdown.action.js
tests/features/common/actions/input-group.action.js
tests/features/common/actions/radio-button.action.js
tests/features/common/actions/tab-selector.action.js
tests/features/common/actions/table.action.js
tests/features/common/components/action-menu.component.js
tests/features/common/components/checkbox.component.js
tests/features/common/components/dropdown.component.js
tests/features/common/components/input-group.component.js
tests/features/common/components/radio-button.component.js
tests/features/common/components/table.component.js
tests/features/common/page-objects.js
tests/features/common/page-objects/feature-store.po.js
tests/features/common/page-objects/info-pane.po.js
tests/features/common/page-objects/interactive-popup.po.js
tests/features/common/page-objects/project.po.js
tests/features/common/page-objects/projects.po.js
tests/features/common/page-objects/side-panel.po.js
tests/features/featureStore.feature
tests/features/projectPage.feature
tests/features/projectsPage.feature
tests/features/step-definitions/steps.js

Merges into branch **development** PR https://github.com/mlrun/ui/pull/578 from branch **tests**.

Impl [e2e-tests] Sprint 122

---

src/common/RangeInput/RangeInput.js
src/common/RangeInput/rangeInput.scss
src/common/Select/Select.js
src/common/Select/select.scss
src/components/CreateJobPage/createJobPage.scss
src/elements/FunctionsPanelResources/FunctionsPanelResources.js
src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
src/elements/FunctionsPanelResources/functionsPanelResources.scss

https://trello.com/c/FFMgQmfX/819-function-panel-resources-change-layout-to-take-less-space
- **Function panel**: Update “Resources” layout to match the design mockup, it is now much more dense and wastes much less space
Before:
After:
Continues feature https://github.com/mlrun/ui/pull/565 [v0.6.4-RC2](https://github.com/mlrun/ui/releases/tag/v0.6.4-rc2) ML-257

[Function panel] Resources: changed layout to take less space

---

src/components/FunctionsPage/Functions.js
src/components/FunctionsPanel/FunctionsPanel.js

https://trello.com/c/xwfqDBWW/818-functions-auto-select-newly-created-function
- **Functions**: Auto-select newly-created function
Continues feature https://github.com/mlrun/ui/pull/565 [v0.6.4-rc2](https://github.com/mlrun/ui/releases/tag/v0.6.4-rc2) ML-257

[Functions] Auto-select newly-created function

---

src/common/KeyValueTable/KeyValueTable.js

https://trello.com/c/5PMNgQYI/827-models-console-error-on-deploy
- **Models**: An error in the console occurred on deploying a model.

[Models] Console error on deploy

---

src/actions/functions.js
src/components/CreateJobPage/CreateJobPage.js
src/components/JobsPanel/JobsPanel.js

https://trello.com/b/b41OXMcG/gl-tasks
- **Create Job**: Added an error notification in case of an error while loading and parsing the selected function template.
Jira ticket ML-605

[Job panel] Show error on loading template error

---

src/components/JobsPanel/jobsPanel.scss
src/components/JobsPanel/panelReducer.js
src/components/JobsPanelResources/JobsPanelResourcesView.js

https://trello.com/c/uGQJUBvu/832-job-panel-condense-resources-layout
- **Job panel**: Reconstructed “Resources” layout to match the layout of “Resources” in function panel.
Before:
After:
Jira ticket ML-618

[Job panel] Condense resources layout

---

src/components/FilterMenu/FilterMenu.js

https://trello.com/c/OGUe6zGN/839-general-rename-expand-action-to-expand-all
- **General**: Renamed action “Expand” to “Expand all”, to better reflect what it actually does.
Before:
After:
Jira ticket ML-622

[General] Rename "Expand" action to "Expand all"

---

src/components/JobsPanelDataInputs/JobsPanelDataInputs.js

https://trello.com/c/ZnKTuzhT/835-data-inputs-crash-on-editing-the-project-name
- **Data inputs**: Error occurred on typing a different project name on an existing data input.
Before:
After:
Jira tikcet ML-623

[Data Inputs] Crash on editing the project name

---

src/common/Breadcrumbs/Breadcrumbs.js
src/components/Project/ProjectView.js
src/utils/projects.js

https://trello.com/c/AcgJoDjc/838-breadcrumbs-sort-projects-by-name
- **Breadcrumbs**: Sorted project list alphabetically in ascending order.
Before:
After:
Jira ticket ML-642

[Breadcrumbs] Sort projects by name

---

src/components/JobsPanel/jobsPanel.util.js
src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
src/components/JobsPanelDataInputs/jobsPanelDataInputsReducer.js
src/elements/EditableDataInputsRow/EditableDataInputsRow.js
src/elements/EditableDataInputsRow/EditableDataInputsRow.utils.js

https://trello.com/c/mtmDCK0o/841-data-inputs-allow-values-not-from-autocomplete
- **Data inputs**: Allow to enter values not from autocomplete dropdown menus.
Jira ticket ML-627

[Data Inputs] Allow values not from autocomplete

---

src/components/JobsPanel/jobsPanel.util.js

https://trello.com/c/EfEp1nUV/848-job-panel-error-on-schedule
- **Jobs**: Attempting to re-run a job whose function is not found, and scheduling it for later ended up with an error.
Jira ticket ML-660

[Job panel] Error on schedule

---

src/components/FilterMenu/FilterMenu.js

https://trello.com/c/2KyrqpD3/849-functions-show-new-button-only-on-demotrue
- **Functions**: Hide the “New” button. Show it only when passing URL query param `demo=true`.
Continues feature https://github.com/mlrun/ui/pull/565 [v0.6.4-RC2](https://github.com/mlrun/ui/releases/tag/v0.6.4-rc2) ML-257
Jira ticket ML-658

[Functions] Show New button only on demo=true

---

src/components/Models/models.util.js
src/utils/createArtifactsContent.js

https://trello.com/c/80sIn3pF/857-models-add-framework-algorithm-column
- **Models**: Added ”Framework & Algorithm” column
Jira ticket ML-527

[Models] Added "Framework & algorithm" column

---

src/components/JobsPanel/jobsPanel.util.js
src/utils/panelResources.util.js

- **Jobs**: Error occurred on firing the “Re-run” action and the job‘s function had only part of its resources defined and the rest not.
Jira ticket ML-677

Fix [Jobs] Re-run fails on loading function resources

---

src/components/JobsPanel/jobsPanel.util.js

- **Create Job**: Error occurred on creating a new job when the function had only part of its resources defined and the rest not.
Relates to PR https://github.com/mlrun/ui/pull/628 ML-677

Fix [Create Job] Error on loading function resources

---

src/components/Project/ProjectView.js
src/components/Project/project.scss

https://trello.com/c/ml1kOQuc/865-project-overview-add-creation-time
- **Project Overview**: Added “Created At“ filed on left column
Jira ticket ML-698

[Project Overview] Add creation time

---

src/components/Project/ProjectView.js
src/utils/createArtifactsContent.js

https://trello.com/c/no7R5oO8/867-features-crash-on-entering-the-page

[Features] Crash on entering the page

---

src/common/RangeInput/RangeInput.js

https://trello.com/c/ZmDv9EsC/864-jobs-re-run-resources-not-loaded
- **Job panel**: When re-running a job, the values of “Resources” part of its function were not properly populated.

[Jobs] Re-run: resources not loaded

---

src/setupProxy.js

- **Config**: Set proxies only when the relevant environment variable is non-empty.

Impl [Dev Server] Do not fail on missing environment variables

---

src/common/Tooltip/Tooltip.js
src/common/Tooltip/tooltip.scss

https://trello.com/c/jU7PKo5k/885-general-long-tooltip-is-cropped

Fix [General] Long Tooltip is cropped

---

src/elements/TableCell/TableCell.js
src/elements/TableProducerCell/TableProducerCell.js

https://trello.com/c/zI5iKiCy/886-modelsdatasetsfiles-wrong-link-to-jobs-overview-in-producer-column

[Models][Datasets][Files] Wrong link to Jobs/Overview in Producer column

---

src/common/Breadcrumbs/Breadcrumbs.js
src/common/Breadcrumbs/breadcrums.scss
src/common/Tooltip/tooltip.scss
src/components/Details/DetailsView.js
src/components/Details/details.scss
src/components/DetailsInfo/detailsInfo.scss
src/elements/TooltipTemplate/textTooltipTemplate.scss

https://trello.com/c/7tkZntja/884-general-long-names-are-cropped

Fix [General] Long names are cropped

---

src/components/ArtifactsPreview/ArtifactsPreview.js
src/components/ArtifactsPreview/ArtifactsPreviewView.js
src/components/ArtifactsPreview/artifactsPreview.scss
src/components/Details/Details.js
src/components/DetailsArtifacts/detailsArtifacts.scss
src/components/DetailsPreview/DetailsPreview.js

https://trello.com/c/OiRFlGlt/883-models-model-preview-in-pop-out-is-broken

Fix [Models] Model Preview in Pop-out is broken

---

src/components/Details/DetailsView.js
src/elements/DetailsMenuItem/DetailsMenuItem.js
src/utils/createArtifactsContent.js
src/utils/generateLinkToDetailsPanel.js

https://trello.com/c/Aay1W8Jl/879-modelsfilesdatasets-details-menu-navigation-is-broken

Fix [Models][Files][Datasets] Details menu navigation is broken

---

src/components/FeatureStore/featureStore.util.js
src/utils/createArtifactsContent.js

https://trello.com/c/rvsSVXRG/882-features-remove-target-column-hide-validator-column

Impl [Features] Remove Target column, hide Validator column

---

src/components/FeatureSetsPanel/FeatureSetsPanelSchema/FeatureSetsPanelSchemaView.js
src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
src/elements/FunctionsPanelCode/FunctionsPanelCode.js
src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js
src/elements/FunctionsPanelGeneral/FunctionsPanelGeneralView.js

https://trello.com/c/adfSvwHr/881-feature-sets

Fix [Feature sets Panel] [Functions Panel] Unnecessary re-render after some fields onBlur

---

src/components/Files/Files.js

https://trello.com/c/Or8r1OSC/878-files-click-on-show-iterations-doesnt-close-details-pane

Fix [Files] Click on "Show iterations" doesn't close Details pane

---

src/layout/Content/Content.js

https://trello.com/c/AhV604mo/880-feature-setsfunctions-refreshing-the-page-breaks-expand-all-button

Fix [Feature sets][Functions] Refreshing the page breaks "Expand all" button

---

src/elements/ArtifactsTableRow/ArtifactsTableRow.js
src/utils/createArtifactsContent.js
src/utils/getArtifactIdentifier.js

https://trello.com/c/9JMZ1xik/877-model-endpoints-bug-with-rows-displaying

Fix [Model Endpoints] Fixed bug with rows displaying

---

src/utils/createArtifactsContent.js

https://trello.com/c/B5KtoVgj/872-models-empty-tooltip-is-displayed

Fix [Models] Empty tooltip is displayed

---

src/common/ChipCell/ChipCell.js
src/common/ChipCell/ChipCellView.js
src/elements/HiddenChipsBlock/HiddenChipsBlock.js

https://trello.com/c/FeDaHiBH/875-project-labels-arent-editable

Fix [Project] Labels aren't editable

---

src/common/ChipCell/chipCell.scss
src/elements/ChipForm/chipForm.scss

https://trello.com/c/kDOJ7E8Z/876-create-function-long-label-overflows-the-panel

Fix [Create function] Long label overflows the panel

---

src/common/KeyValueTable/KeyValueTable.js
src/common/KeyValueTable/keyValueTable.scss
src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.scss
src/elements/FunctionsPanelEnvironmentVariables/functionPanelEnviromnetVariables.scss

https://trello.com/c/guse817u/874-general-keyvalue-table-inputs-bugs

Fix [General] Fixed KeyValue table inputs bugs

---

src/utils/createArtifactsContent.js

https://trello.com/c/rv7EgYym/871-features-link-to-feature-set-disappears

Fix [Features] Link to feature set disappears

---

src/common/ChipCell/ChipCellView.js
src/components/Project/project.scss
src/elements/HiddenChipsBlock/HiddenChipsBlock.js
src/elements/HiddenChipsBlock/hiddenChipsBlock.scss
src/scss/mixins.scss

https://trello.com/c/KcXVORKc/873-general-chips-pop-up-is-cropped

Fix [General] Chips pop-up is cropped

---

src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js

https://trello.com/c/cJMLqzFl/888-requested-features-show-project-name

Impl [Requested Features] Show project name

---

src/components/ArtifactsPreview/ArtifactsPreviewView.js
src/utils/getArtifactPreview.js

https://trello.com/c/niUAkqgo/894-jobs-app-crashes-on-selecting-artifacts-item-model

Fix [Jobs] App crashes on selecting Artifacts item "model"

---

src/components/DetailsTransformations/DetailsTransformations.js

https://trello.com/c/NAmOJFZi/893-feature-sets-transformation-tab-all-steps-arent-displayed

Fix [Feature Sets] Transformation tab all steps aren`t displayed

---

src/components/Details/details.util.js
src/components/FeatureStore/featureStore.util.js

https://trello.com/c/Gi8HrNat/889-feature-vectors-remove-timestamp-key-hide-preview-and-analysis-tabs

Impl [Feature Vectors] remove Timestamp key, hide Preview and Analysis tabs

---

src/elements/DetailsInfoItem/DetailsInfoItem.js

https://trello.com/c/k5cH4mdg/891-models-warning-occurs-on-visiting-details-pane

Fix [Models] Warning occurs on visiting Details pane

---

tests/features/common-tools/common-consts.js
tests/features/common/actions/date-picker.action.js
tests/features/common/actions/dropdown.action.js
tests/features/common/actions/table.action.js
tests/features/common/components/date-picker.component.js
tests/features/common/components/table.component.js
tests/features/common/page-objects.js
tests/features/common/page-objects/feature-store.po.js
tests/features/common/page-objects/interactive-popup.po.js
tests/features/common/page-objects/jobs-and-workflows.po.js
tests/features/common/page-objects/side-panel.po.js
tests/features/featureStore.feature
tests/features/jobsAndWorkflows.feature
tests/features/projectsPage.feature
tests/features/step-definitions/steps.js
tests/mockServer/backend_synchronizator.py
tests/mockServer/mock.js

Collects PR https://github.com/mlrun/ui/pull/666 from branch **tests** to branch **development**.

Impl [e2e-tests] Sprint 124

---

src/components/Artifacts/Artifacts.js
src/components/FeatureStore/featureStore.util.js
src/components/Files/Files.js
src/components/FunctionsPage/Functions.js
src/components/JobsPage/Jobs.js
src/components/Models/models.util.js
src/utils/isDetailsTabExists.js

https://trello.com/c/kxFWgI2G/900-general-history-navigation-is-blocked
- **General**: When redirecting to non-existing resources, clicking the browser‘s Back button did not work properly.

[General] History navigation is blocked

---

src/components/FeatureStore/featureStore.util.js
src/utils/createArtifactsContent.js

- **Features**: Re-introduce “Validator” column.
Partially reverts https://github.com/mlrun/ui/pull/653 [v0.6.5-RC11](https://github.com/mlrun/ui/releases/tag/v0.6.5-rc15)

Impl [Features] Re-introduce Validtor column

---

src/components/Details/DetailsView.js
src/components/Details/details.util.js
src/components/DetailsInfo/DetailsInfoView.js
src/components/FeatureStore/featureStore.util.js
src/components/FunctionsPage/Functions.js
src/components/JobsPage/Jobs.js
src/components/JobsPage/jobsData.js
src/components/Models/models.util.js
src/elements/SelectOption/selectOption.scss
src/elements/TableLinkCell/TableLinkCell.js
src/scss/main.scss
src/scss/mixins.scss
src/utils/createJobsContent.js
src/utils/getState.js
src/utils/parseFeatureSets.js
src/utils/parseFeatureStoreDataRequest.js
src/utils/parseFeatureVectors.js

https://trello.com/c/IQSvJ2kv/869-functions-show-status-indicator-for-more-states

[Functions] Show status indicator for more states

---

src/components/DetailsTransformations/ConfigFunctionTemplate/ConfigFunctionTemplate.js
src/components/DetailsTransformations/ConfigSource/ConfigSource.js
src/components/DetailsTransformations/ConfigTargets/ConfigTargets.js

https://trello.com/c/IYZU8qpf/896-feature-sets-transformations-collapse-sections-by-default

[Feature sets] Transformations: Collapse sections by default

---

src/components/ArtifactInfoSources/ArtifactInfoSources.js
src/components/ArtifactInfoSources/artifactInfoSources.scss
src/components/ArtifactInfoSources/artifactInfoSources.utils.js
src/components/Artifacts/artifactsData.json
src/components/Details/details.util.js
src/components/DetailsInfo/DetailsInfoView.js
src/components/DetailsInfo/detailsInfo.scss
src/components/FeatureStore/featureStore.util.js
src/components/Files/files.util.js
src/components/Models/models.util.js

https://trello.com/c/ydMa1Hb0/897-feature-sets-overview-hide-relations-field

[Feature sets] Overview: hide Relations field

---

src/utils/generateUsageSnippets.js

https://trello.com/c/Fx3MdPwX/904-feature-sets-vectors-overview-usage-example-plant-entity
- **Feature sets**: In “Overview” tab, plant the first entity name instead of the static “customer_id” key in the “Usage example” field.
Before:
After:
Jira ticket ML-795

[Feature sets] Overview: Usage example: plant entity

---

src/components/Details/details.util.js
src/components/DetailsInfo/DetailsInfoView.js
src/components/FilterMenu/FilterMenu.js
src/components/FunctionsPage/Functions.js
src/components/FunctionsPage/functions.util.js
src/components/JobsPage/jobsData.js
src/layout/Content/Content.js
src/reducers/filtersReducer.js
src/utils/createJobsContent.js

https://trello.com/c/AthqVkOe/902-files-functions-filters-arent-cleared-on-project-change
- **Filters**: The filters were not cleared on changing projects.

[Files, Functions] Filters aren't cleared on project change

---

src/components/Details/DetailsView.js
src/components/Details/details.scss

https://trello.com/c/79c97MDz/913%20-details-tooltip-is-broken

[Details] Tooltip is broken

---

src/common/CheckBox/checkBox.scss
src/components/FeatureSetsPanel/FeatureSetsPanel.js
src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
src/components/FeatureSetsPanel/FeatureSetsPanelSchema/FeatureSetsPanelSchema.js
src/components/FeatureSetsPanel/FeatureSetsPanelSchema/FeatureSetsPanelSchemaView.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
src/components/FeatureSetsPanel/FeatureSetsPanelView.js
src/reducers/featureStoreReducer.js

https://trello.com/c/3D4ccyv1/909-feature-set-panel-various-changes

[Feature set panel] Various changes

---

src/components/DetailsMetadata/DetailsMetadata.js

https://trello.com/c/pc5DbTAI/917-feature-sets-app-crashes-on-features-tab

[Feature Sets] App crashes on Features tab

---

src/components/DetailsTransformations/detailsTransformations.scss

https://trello.com/c/CWa4XcdB/920-feature-sets-horizontal-scroll-on-transformations-tab

[Feature sets] Horizontal scroll on Transformations tab

---

src/common/Search/Search.js
src/components/ProjectsPage/ProjectsView.js

https://trello.com/c/SYghAN2b/915-projects-page-refresh-erases-the-search-value
- **Projects**: Name filter was cleared when firing the “Refresh” action.

[Projects] Page refresh erases the search value

---

src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js

Originated in PR https://github.com/mlrun/ui/pull/699

Fix [Build] Broken build

---

src/components/DetailsInfo/detailsInfo.scss
src/components/Table/table.scss
src/elements/JobsPanelTable/jobsPanelTable.scss
src/layout/Content/content.scss
src/scss/mixins.scss

- **General**: Reduce vertical spacing in various places.
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Jira ticket ML-924

Impl [General] Reduce vertical spacing

---

src/components/JobsPanelAdvanced/JobsPanelAdvanced.js
src/components/JobsPanelAdvanced/jobsPanelAdvanced.util.js
src/elements/EditableAdvancedRow/EditableAdvancedRow.js
src/elements/JobsPanelParametersTable/JobsPanelParametersTableView.js
src/elements/JobsPanelTable/JobsPanelTable.js
src/elements/JobsPanelTable/JobsPanelTableView.js
src/elements/JobsPanelTableRow/JobsPanelTableRow.js
src/utils/string.js

https://trello.com/c/8A1dCBa5/929-create-new-job-panel-app-crashes-on-adding-empty-secret
- **Job panel**: App crashed when adding a new secret with an empty value.

[Create new Job panel] App crashes on  adding empty secret

---

src/components/FunctionsPage/Functions.js

- **Functions**: Show “Edit” action for functions of kind Local.
Jira ticket ML-956

Impl [Fucntions] Show "Edit" action for kind Local

---

src/components/DetailsStatistics/detailsStatistics.util.js

https://trello.com/c/KdBYKPaR/936-feature-vectors-statistics-add-histogram
- **Feature vectors**: Added “Histogram” column to “Statistics” tab.
Jira ticket ML-950

[Feature vectors] Statistics: added Histogram

---

src/components/FunctionsPage/Functions.js
src/components/FunctionsPage/functions.util.js

https://trello.com/c/s0wWImqC/935-functions-hide-run-action-when-not-in-ready-state

[Functions] Hide Run action when not in Ready state

---

src/components/Details/DetailsView.js
src/components/Details/details.util.js
src/components/FunctionsPage/Functions.js
src/components/FunctionsPage/functions.util.js
src/components/JobsPage/Jobs.js
src/components/JobsPage/jobsData.js
src/elements/TableLinkCell/TableLinkCell.js
src/scss/main.scss
src/utils/getState.js

https://trello.com/c/chbmVWCe/931-function-status-wrong-or-not-updated
- **Functions**: After deploying a function and being redirected to this function‘s details view, the status of the function was invisible, though it had a tooltip on hovering it.
Before:
After:
Jira ticket ML-895

[Function] Status wrong or not updated

---

package.json
tests/features/common-tools/common-consts.js
tests/features/common-tools/common-tools.js
tests/features/common/actions/common.action.js
tests/features/common/actions/input-group.action.js
tests/features/common/actions/number-input-group.action.js
tests/features/common/actions/table.action.js
tests/features/common/components/label.component.js
tests/features/common/components/number-input-group.component.js
tests/features/common/page-objects.js
tests/features/common/page-objects/feature-store.po.js
tests/features/common/page-objects/info-pane.po.js
tests/features/common/page-objects/jobs-and-workflows.po.js
tests/features/common/page-objects/projects.po.js
tests/features/common/page-objects/side-panel.po.js
tests/features/featureStore.feature
tests/features/jobsAndWorkflows.feature
tests/features/step-definitions/steps.js

Collecting the following PRs from **tests** branch:
https://github.com/mlrun/ui/pull/731

Impl [e2e-tests] Sprint 125

---

src/elements/EditableVolumesRow/EditableVolumesRow.js
src/elements/VolumesTable/VolumesTable.js
src/elements/VolumesTable/VolumesTableView.js

https://trello.com/c/Jcm42xCl/941-function-paneljob-panel-volumes-all-fields-mandatory
- **Function panel, Job panel**: In “Volumes” section, the required fields were marked as mandatory with a red asterisk.
Jira ticket ML-949

[Function panel][Job panel] Volumes: all fields mandatory

---

src/elements/EditableVolumesRow/EditableVolumesRow.js
src/elements/VolumesTable/VolumesTable.js
src/elements/VolumesTable/VolumesTableView.js
src/elements/VolumesTable/volumesTable.util.js

https://trello.com/c/rLhHnpXN/943-volumes-add-uniqueness-validity-for-path
- **Function panel, Job panel**: In “Volumes” section, enforce uniqueness of paths so multiple volumes cannot share a common path.
Jira ticket ML-975

[Volumes] Added uniqueness validity for path

---

src/components/Details/details.util.js
src/components/DetailsInfo/DetailsInfo.js
src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js

https://trello.com/c/A2psO3ax/945-feature-vectors-change-the-labelfeature-on-editing-the-feature
- **Feature vectors**: In “Requested features”, when changing the alias of a feature, if this is the label feature, then the label feature is no longer marked as such in the features list.

[Feature vectors] Change the label_feature on editing the feature

---

src/components/FunctionsPage/Functions.js
src/components/FunctionsPage/functions.util.js

https://trello.com/c/91KYJGCL/951-functions-show-edit-for-created-state
- **Functions**: A created function could not be deployed, since the Edit action was hidden for functions in Created state.
Jira ticket ML-995

[Functions] Show Edit for Created state

---

src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.scss

- **Feature set panel**: In “Source” section, reword description:
Before:
After:
Jira ticket ML-865

Impl [Feature set panel] Source: Reword description

---

src/actions/artifacts.js
src/api/artifacts-api.js
src/components/Models/models.util.js

https://trello.com/c/fJAEXdSa/947-model-endpoints-retrieve-average-latency

[Model Endpoints] Retrieve average latency

---

src/common/Breadcrumbs/Breadcrumbs.js
src/elements/BreadcrumbsDropdown/BreadcrumbsDropdown.js

https://trello.com/c/SfPk5QGV/949-models-unexpected-redirection-to-models-from-endpoints
- **Model Endpoints**: Switching to another project unexpectedly redirected to “Models” tab.

merged changes[Models] Unexpected redirection to Models from Endpoints

---

src/components/JobsPanel/JobsPanel.js

https://trello.com/c/21Om3vrU/954-job-panel-stuck-when-function-resources-not-empty
- **Job Panel**: UI was hanging when the function spec has non-empty resources.
Jira ticket ML-942

[Job Panel] Stuck when function resources not empty

---

src/components/FunctionsPanel/FunctionsPanel.js
src/components/FunctionsPanel/FunctionsPanelView.js
src/components/JobsPanel/JobsPanel.js
src/components/JobsPanel/JobsPanelView.js
src/components/JobsPanel/jobsPanel.scss
src/components/JobsPanel/jobsPanel.util.js
src/components/JobsPanelResources/JobsPanelResources.js
src/components/JobsPanelResources/JobsPanelResourcesView.js
src/components/JobsPanelResources/jobsPanelResources.util.js
src/elements/FunctionsPanelResources/FunctionsPanelResources.js
src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
src/elements/FunctionsPanelResources/functionsPanelResources.scss
src/elements/FunctionsPanelResources/functionsPanelResources.util.js

https://trello.com/c/XOPaejg8/963-resources-add-validation-and-grow-width
- **Job panel, Function panel**: In “Resources” section, made room for 3 digits in fields, and added validation tests: values must be 1 or larger, and Request must be less than or equal to its corresponding Limit.
Before:
After:
Jira ticket ML-1014, ML-1015

[Resources] Add validation and grow width

---

src/common/Input/Input.js
src/common/Input/input.scss
src/components/FunctionsPanel/FunctionsPanelView.js
src/elements/FunctionsPanelGeneral/FunctionsPanelGeneral.js
src/elements/FunctionsPanelGeneral/FunctionsPanelGeneralView.js

https://trello.com/c/lQ3ONMiP/969-function-panel-disable-name-and-tag-on-edit
- **Function panel**: Disabled “Name” and “Tag” fields when editing an existing function.
Jira tickets ML-953, ML-970

[Function panel] Disable name and tag on edit

---

src/components/FunctionsPage/functions.util.js

- **Functions**: Show “Edit” action to functions in failed/error state.
Relates to PR https://github.com/mlrun/ui/pull/745
Jira ticket ML-1043

Impl [Functions] Show "Edit" action for error state

---

src/elements/ArtifactsTableRow/ArtifactsTableRow.js

https://trello.com/c/OV6RpBhY/971-modelsfilesdatasets-selected-item-is-not-highlighted
- **Models, Files, Datasets**: Selected item was not highlighted.

[Models][Files][Datasets] Selected item is not highlighted

---

src/actions/artifacts.js
src/components/Files/Files.js

https://trello.com/c/JlnEfUda/975-files-details-pane-cannot-be-opened
- **Files**: Failed to open details panel for tag-less versions (when “show iterations” is checked)

[Files] Details pane cannot be opened

---

src/components/DetailsStatistics/DetailsStatistics.js

https://trello.com/c/vyyHD2Gj/974-feature-sets-app-crashes-on-entering-statistics-tab
- **Feature sets**: The “Statistics” tab sometimes crashed

[Feature Sets] App crashes on entering Statistics tab

---

src/actions/artifacts.js
src/actions/filters.js
src/api/artifacts-api.js
src/components/FeatureStore/FeatureStore.js
src/components/Files/Files.js
src/components/FilterMenu/FilterMenu.js
src/components/Models/Models.js
src/constants.js
src/reducers/filtersReducer.js

https://trello.com/c/60DZxoOp/979-feature-vectors-pre-populate-tag-filter
- **Feature vectors**: Populated drop-down of “Tag” filter with all tags of feature vectors in the project.
Jira ticket ML-744

[Feature vectors] Pre-populate Tag filter

---

src/actions/artifacts.js
src/actions/featureStore.js
src/api/artifacts-api.js
src/api/featureStore-api.js
src/components/FeatureStore/FeatureStore.js

https://trello.com/c/oB0CQmYP/984-features-pre-populate-tag-filter
- **Features**: Populated drop-down of “Tag” filter with all tags of feature sets in the project.
Jira ticket ML-744

[Features] Pre-populate Tag filter

---

package.json
scripts/collectUITestsSteps.js
tests/features/common/components/combo-box.component.js
tests/features/common/page-objects/side-panel.po.js
tests/features/featureStore.feature
tests/features/step-definitions/steps.js
tests/features/step-definitions/table.steps.js

Collecting the following PR from branch **tests** into branch **development**:
https://github.com/mlrun/ui/pull/787

Impl [e2e-tests] Sprint 126

---

src/components/JobsPanel/JobsPanel.js
src/components/JobsPanel/jobsPanel.util.js

https://trello.com/c/VWr0itdS/976-job-panel-function-parts-are-not-reflected
- **Job Panel**: The fields of the parts coming from the selected function to run — Volumes, Memory, CPU, GPU, and Environment Variables — were not pre-populated in the panel. Also if these values were changed in the job panel, the older values were sent on submitting the form, instead of the new values.
Jira tickets ML-976, ML-977, ML-1024

[Job Panel] Function parts are not reflected

---

src/components/FunctionsPanel/FunctionsPanel.js

https://trello.com/c/9eMTG8wz/999-functions-error-on-editing-functions-of-type-job
- **Functions**: Error occurred when attempting to edit a function of type job.
Bug originated in PR https://github.com/mlrun/ui/pull/747

[Functions] Error on editing functions of type job

---

src/components/DetailsInfo/detailsInfo.scss
src/components/FeatureStore/FeatureStore.js
src/components/FeatureStore/featureStore.scss
src/components/FeatureStore/featureStore.util.js
src/components/Files/Files.js
src/components/Files/files.util.js
src/components/FunctionsPage/Functions.js
src/components/FunctionsPage/functions.util.js
src/components/JobsPage/Jobs.js
src/components/JobsPage/jobsData.js
src/components/Models/Models.js
src/components/Models/models.util.js
src/components/Table/Table.js
src/components/Table/table.scss
src/elements/FeaturesTablePanel/FeatureTablePanleRow/FeaturesTablePanelRow.js
src/elements/FeaturesTablePanel/FeatureTablePanleRow/featuresTablePanelRow.scss
src/elements/FeaturesTablePanel/featuresTablePanel.scss
src/elements/JobsTableRow/JobsTableRow.js
src/layout/Content/content.scss
src/scss/mixins.scss
src/utils/createArtifactsContent.js
src/utils/createFeatureStoreContent.js
src/utils/createFunctionsContent.js
src/utils/createJobsContent.js
src/utils/generateTableContent.js

https://trello.com/c/WAg8yWzA/996-features-table-panel-is-cropped
- **Features**: When the feature vector panel is open, scrolling down was endless, you could scroll forever.
Before:
After:
- **Jobs**: The sticky headers stopped wokring.
Before:
After:

[Features] Endless scroll down

---

src/components/Project/ProjectView.js

- **Project Overview**: Added `row-name` CSS class to the values of “Owner” and “Members” fields.

Impl [Project Overview] Owner and Members: Add missing CSS class

---

src/actions/jobs.js
src/components/JobsPage/Jobs.js

https://trello.com/c/6FNk6FZC/1010-jobs-error-when-failed-to-fetch-jobs
- **Jobs**: Error occurred in UI when it failed to fetch jobs list or scheduled list. Now a notification will be shown and UI will not crash.

[Jobs] Error when failed to fetch jobs

---

src/components/FilterMenu/FilterMenu.js

https://trello.com/c/vT6zTrQ3/1016-general-row-isnt-collapsed-on-filter-change
- **General**: Changing filters values did not collapse the expanded rows.

[General] Row is not collapsed on filter change

---

src/components/Project/ProjectView.js
src/components/Project/project.scss

https://trello.com/c/bmOOdW9f/1013-project-project-data-overflows-container
- **Project Overview**: Screen contents overflew the screen wrapper on a small screen when scrolling to the right.
Before:
After:

[Project] Project data overflows container

---

src/common/ChipCell/ChipCell.js
src/common/ChipCell/SizeChips.js
src/components/FeatureStore/featureStore.util.js
src/utils/createFeatureStoreContent.js

https://trello.com/c/K3lsbnJ0/1006-features-list-all-entities
- **Features**: Renamed “Entity” column header to “Entities”, and showing a chip list of all entities instead of just one.
Jira ticket ML-1013

[Features] List all entities

---

src/common/KeyValueTable/KeyValueTable.js
src/common/KeyValueTable/KeyValueTableView.js
src/common/RangeInput/RangeInput.js
src/elements/EditableVolumesRow/EditableVolumesRow.js
src/elements/FunctionPanelTopologyModelTable/AddRouteRow.js
src/elements/FunctionPanelTopologyModelTable/EditableRouteRow.js
src/elements/FunctionPanelTopologyModelTable/FunctionPanelTopologyModelTable.js
src/elements/FunctionPanelTopologyModelTable/FunctionPanelTopologyModelTableView.js
src/elements/FunctionPanelTopologyModelTable/functionPanelTopologyModelTable.scss
src/elements/FunctionPanelTopologyModelTable/functionPanelTopologyModelTable.util.js
src/elements/FunctionsPanelParameters/AddFunctionParameterRow.js
src/elements/FunctionsPanelParameters/EditableFunctionParameterRow.js
src/elements/FunctionsPanelParameters/FunctionsPanelParameters.js
src/elements/FunctionsPanelParameters/FunctionsPanelParametersView.js
src/elements/FunctionsPanelParameters/functionsPanelParameters.util.js

https://trello.com/c/AXu5AoCA/1024-function-panel-topology-missing-discard-button
- **Function panel**: For “Serving” type, in the “Models” and “Parameters” lists a “Discard changes” button was missing when starting to add a new item. In “Parameters” list “Value” had an “Invalid” tooltip instead of “This field is required” tooltip, when leaving it empty and the type is “Number”.
Before:
After:

[Function panel] Topology: missing discard button

---

src/components/JobsPage/Jobs.js
src/components/JobsPage/jobsData.js
src/components/Table/Table.js
src/components/Table/TableView.js
src/components/Table/table.scss
src/components/Workflow/Workflow.js
src/components/Workflow/workflow.scss
src/components/Workflow/workflow.util.js
src/elements/JobsTableRow/JobsTableRow.js
src/layout/Content/Content.js
src/utils/createJobsContent.js
src/utils/generateGroupLatestItem.js
src/utils/generateTableContent.js

https://trello.com/c/cvqG2M8C/1029-workflows-add-columns-to-list-view-of-workflow
- **Monitor Workflows**:
- Move table columns from main workflow list, to the individual workflow view when in list mode.
- Added columns “Created At” & “Finished At“ and removed columns to workflow list.
- Removed columns “Owner”, “Labels”, “Parameters”, & “Results” from workflow list.
- Removed the collapse-expand of rows from the workflow list.
Continues https://github.com/mlrun/ui/pull/804 [v0.8.0-rc3](https://github.com/mlrun/ui/releases/tag/v0.8.0-rc3)
Jira ticket ML-688

[Workflows] Add columns to list view of workflow

---

src/common/KeyValueTable/KeyValueTableView.js
src/common/Select/Select.js
src/common/Select/select.scss
src/elements/FunctionsPanelSecrets/FunctionsPanelSecrets.js

https://trello.com/c/ycJUNnub/1038-functions-panel-cannot-edit-single-secret-value
- **Function panel**: In “Secrets” section of a serving function, it was impossible to edit one secret. When you tried to edit a secret you ended up editing all other secrets, too.
Before:
After:
Continuing https://github.com/mlrun/ui/pull/747 [v0.8.0-rc1](https://github.com/mlrun/ui/releases/tag/v0.8.0-rc1)

[Functions panel] Cannot edit single secret value

---

src/components/JobsPanelAdvanced/JobsPanelAdvanced.js
src/components/JobsPanelAdvanced/JobsPanelAdvancedView.js
src/elements/FunctionsPanelRuntime/FunctionsPanelRuntime.js
src/elements/FunctionsPanelRuntime/FunctionsPanelRuntimeView.js

https://trello.com/c/PSNdP938/1040-job-panelfunction-panel-remove-secrets
- **Job panel, Function panel**: Removed “Secrets” section when in demo mode (`demo=true` URL query param present). Project secrets should be available to jobs and functions.
Relates to https://github.com/mlrun/ui/pull/831 [v0.8.0-rc4](https://github.com/mlrun/ui/releases/tag/v0.8.0-rc4) ML-1039

[Job panel][Function panel] Remove Secrets

---

src/components/ProjectSettings/ProjectSettings.js
src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
src/elements/ProjectSettingsSecrets/ProjectSettingsSecretsView.js

https://trello.com/b/b41OXMcG/gl-tasks

[Build] ESLint warnings

---

src/components/JobsPanelAdvanced/JobsPanelAdvancedView.js
src/elements/FunctionsPanelRuntime/FunctionsPanelRuntimeView.js

https://trello.com/c/BblznIsI/1048-job-panelfunction-panel-show-secrets-in-demo-mode-only
- **Job panel, Function panel**: Hide “Secrets” by default, show then only in demo mode (`demo=true`)

[Job panel][Function panel] Show Secrets in demo mode only

---

src/common/PageActionsMenu/PageActionsMenu.js
src/components/Artifacts/Artifacts.js
src/components/FeatureStore/FeatureStore.js
src/components/FeatureStore/featureStore.util.js
src/components/Files/Files.js
src/components/Files/files.util.js
src/components/JobsPage/Jobs.js
src/components/JobsPage/jobsData.js
src/components/Models/Models.js
src/components/Models/models.util.js
src/components/Project/Project.js
src/components/Project/project.utils.js
src/components/ProjectsPage/ProjectsView.js
src/layout/Content/Content.js

https://trello.com/c/qDNo34cm/1047-feature-sets-shift-create-out-of-demo-mode
- **Features**: Shift feature-set creation from demo to production.
In “Feature Sets” tab:
In “Project Overview” screen:
Jira ticket ML-643

[Feature Sets] Shift "Create" out of demo mode

---

src/components/FunctionsPage/Functions.js

https://trello.com/c/uH3Hb7lU/1063-functions-show-edit-for-serving-kind-in-demo-only
- **Functions**: Moved “Edit” action for serving functions to demo mode.
Jira ticket ML-919

[Functions] Show Edit for serving kind in demo only

---

src/components/Details/Details.js
src/components/Models/Models.js
src/components/Models/models.util.js

https://trello.com/c/RtVt5CPt/1069-models-error-when-selecting-a-model
- **Models**: In “Models” tab, error occurred when selecting a specific model.
Jira ticket ML-1249

[Models] Error when selecting a model

---

src/elements/ProjectSettingsGeneral/ProjectSettingsGeneralView.js

- **Project Settings**: In “General” tab, added description to “Parameters” section.
Continuing https://github.com/mlrun/ui/pull/831 [v0.8.0-rc4](https://github.com/mlrun/ui/releases/tag/v0.8.0-rc4)

Impl [Project Settings] Parameters: Add description

---

src/elements/FunctionsPanelEnvironmentVariables/FunctionsPanelEnvironmentVariables.js

https://trello.com/c/nJMVpGlC/1079-function-panel-empty-environment-variables-list
- **Function panel**: In “Environment Variables” section, the list was always empty even when editing a function that _has_ environment variables.
Before:
After:
Continuing https://github.com/mlrun/ui/pull/851 [v0.8.0-rc8](https://github.com/mlrun/ui/releases/tag/v0.8.0-rc8)

[Function panel] Empty environment variables list

---

generate-release-notes.js
package.json

Impl [Config] `generate-rn`: Clone repo to temp dir

---

src/common/PopUpDialog/popUpDialog.scss
src/elements/MembersPopUp/MembersPopUp.js
src/elements/MembersPopUp/membersPopUp.scss

Jira: https://jira.iguazeng.com/browse/ML-1342

ML-1342 fix duplicate are you sure popups

---

src/elements/FunctionsPanelCode/FunctionsPanelCode.js

https://trello.com/c/6ytOwGoQ/1128-functions-app-crashes-on-function-edit

[Functions] App crashes on function edit

---

src/common/ActionsMenu/ActionsMenu.js
src/common/ActionsMenu/actionsMenu.scss

https://trello.com/c/vpB7WIDj/1118-general-action-menu-closes-unexpectedly

Fix [General] Action menu closes unexpectedly

---

src/common/Select/select.scss

https://trello.com/c/U4h8mjon/1117-features-unexpected-scroll-exists

[Features] Unexpected scroll exists

---

src/components/FilterMenu/FilterMenu.js

https://trello.com/c/FE2lWKuO/1131-filters-expand-button-has-wrong-icon-on-refresh

[Filters] Expand button has wrong icon on refresh

---

src/elements/TableLinkCell/TableLinkCell.js

https://trello.com/c/BfkB66Xf/1113-tooltip-wrong-tooltip-position

[Tooltip] Wrong tooltip position

---

src/components/Project/Project.js

https://trello.com/c/nDZAaGjH/1127-project-ui-sends-two-requests-on-refresh

[Project] UI sends two requests on refresh

---

src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSource.js
src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.scss
src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.util.js

https://trello.com/c/CMDT5K4B/1096-feature-set-panel-re-introduce-schedule-for-parquet-source

[Feature set panel] Re-introduce schedule for parquet source

---

src/api/jobs-api.js
src/components/JobsPage/Jobs.js

https://trello.com/c/d5Ej8wze/1129-jobs-filters-arent-applies-after-re-run

[Jobs] Filters aren't applied after re-run

---

src/components/JobsPage/Jobs.js
src/components/JobsPanel/JobsPanel.js
src/components/JobsPanel/jobsPanel.util.js
src/utils/parseJob.js

https://trello.com/c/TQP2X8yO/1111-jobs-delegate-handler-on-re-run

[Jobs] Delegate handler on re-run

---

src/actions/featureStore.js
src/components/FeatureStore/featureStore.util.js

https://trello.com/c/ErZQgwMQ/1115-feature-vectors-cant-open-details-for-not-latest-item

[Feature Vectors] Can't open details for not latest item

---

src/common/PopUpDialog/PopUpDialog.js
src/common/PopUpDialog/popUpDialog.scss
src/common/RoundedIcon/RoundedIcon.js
src/common/RoundedIcon/roundedIcon.scss

https://trello.com/c/zRGqHoXw/1136-general-close-icon-in-popup-dialog-in-wrong-position

[General] Close icon in popup dialog in wrong position

---

src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.util.js
src/components/FeatureSetsPanel/FeatureSetsPanelSchema/FeatureSetsPanelSchemaView.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js

https://trello.com/c/bib9JVHs/1132-ui-feature-set-unnecessary-validation-for-timestamp

[UI] [Feature Set] Unnecessary validation for timestamp

---

src/components/ProjectsPage/Projects.js
src/components/ProjectsPage/ProjectsView.js
src/elements/ActionMenuItem/ActionsMenuItem.js

https://trello.com/c/N8WE7t4o/1135-projects-actions-menu-doesnt-work

[Projects] Actions menu doesn't work

---

src/actions/projects.js
src/components/FeatureStore/FeatureStore.js
src/components/FeatureStore/featureStore.util.js
src/components/FunctionsPage/Functions.js
src/components/Models/models.util.js
src/constants.js
src/layout/Content/Content.js

https://trello.com/c/yXpZDTIL/1137-wrong-error-message-when-creating-a-project-that-is-duplicated-with-existing-project

[Projects] Wrong error message when creating a project that is duplicated with existing project

---

src/components/ArtifactsPreview/artifactsPreview.scss

https://trello.com/c/h0CkhAIu/1134-feature-sets-grid-header

[Feature sets] grid header

---

src/components/Models/models.util.js

https://trello.com/c/0sVFjcmc/1146-empty-features-for-model-without-feature-vector

[Models] Empty features for model without feature vector

---

src/components/JobsPage/Jobs.js

https://trello.com/c/Kq8tz9XY/1147-edit-scheduled-job-doesnt-work

[Jobs] Edit scheduled job doesn't work

---

src/common/PopUpDialog/popUpDialog.scss

https://trello.com/c/MLFIZu1R/1160-view-yaml-close-button-unaligned

[View Yaml] Close button unaligned

---

src/common/Input/Input.js

https://trello.com/c/COvxgA4g/1165-general-no-tips-in-the-input-if-name-is-not-unique

[General] No tips in the input if name is not unique

---

src/common/Input/Input.js
src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
src/components/FeatureStore/FeatureStore.js
src/components/Table/Table.js

https://trello.com/c/kIZZpeQ9/1157-uifeature-vector-user-cant-add-features-from-non-current-project

[UI][Feature Vector] User can't add features from non-current project

---

src/components/Details/Details.js

https://trello.com/c/hkMyqJBS/1106-feature-sets-apply-changes-button-issue

[Feature Sets] "Apply changes" button issue

---

src/elements/AddFeatureButton/AddFeatureButton.js

https://trello.com/c/qIWTLyc0/1156-ui-feature-vector-the-getofflinefeatures-and-getonlinefeatureservice-failed-on-keyerror-for-fv-created-in-ui

[Feature Vector] The "get_offline_features" and "get_online_feature_service" failed on 'KeyError' for FV created in UI

---

src/components/ProjectsPage/ProjectsView.js
src/elements/ProjectCard/ProjectCard.js
src/elements/ProjectCard/ProjectCardView.js

https://trello.com/c/FukkxXVO/1177-general-errors-in-console-related-to-actions-menu

[General] Errors in console related to Actions menu

---

src/components/FeatureStore/FeatureStore.js
src/components/FeatureStore/featureStore.util.js
src/components/JobsPage/Jobs.js
src/components/JobsPage/jobsData.js
src/components/Models/Models.js
src/components/Models/models.util.js
src/components/Workflow/Workflow.js

https://trello.com/c/8FU5gyMy/1178-workflows-app-crash-on-workflow-open

[Workflows] App crash on workflow open

---

src/components/Models/models.util.js

https://trello.com/c/GTxS9uE5/1179-models-empty-button-on-real-time-pipelines-tab

[Models] Empty button on Real-Time Pipelines tab

---

src/elements/FeaturesTablePanel/FeaturesTablePanel.js

https://trello.com/c/SUqLySml/1184-ui-feature-vector-fv-has-features-from-single-projectlatest

[UI] [Feature Vector] FV has features from single project(latest)

---

src/common/Button/button.scss
src/common/Input/input.scss
src/common/OptionsMenu/ValidationTemplate/ValidationTemplate.module.scss
src/common/OptionsMenu/optionsMenu.scss
src/common/ReactFlow/mlReactFlow.scss
src/common/Search/search.scss
src/common/SplitButton/splitButton.scss
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
src/components/ProjectsPage/projects.scss
src/components/Workflow/Workflow.js
src/elements/RegisterArtifactForm/registerArtifactForm.scss
src/elements/SelectOption/selectOption.scss

https://trello.com/c/2chqhcUa/1167-uijobs-workflow-reportunclear-relations-in-the-workflow-chart

[UI][Jobs workflow report]Unclear relations in the Workflow chart

---

src/common/Chip/Chip.js
src/common/Chip/chip.scss
src/common/ChipCell/ChipCell.js
src/common/ChipCell/ChipCellView.js
src/common/ChipCell/chipCell.scss
src/elements/HiddenChipsBlock/HiddenChipsBlock.js
src/elements/HiddenChipsBlock/hiddenChipsBlock.scss
src/elements/TableCell/TableCell.js

https://trello.com/c/ecQTeYON/1149-uifeature-vector-unnecessary-trimming-of-label-in-feature-vector-list-ui

[UI][Feature Vector] Unnecessary trimming of Label in Feature vector list UI

---

src/actions/projects.js
src/constants.js

https://trello.com/c/nvNYMwBg/1172-unclear-error-message-on-attempt-to-create-project-upon-reaching-projects-amount-limit

unclear error message on attempt to create project upon reaching projects amount limit

---

src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js

https://trello.com/c/W7eX0K0q/1181-uifeature-vector-missing-name-validation-for-feature-vector

[UI][Feature Vector] Missing name validation for Feature vector

---

src/common/KeyValueTable/KeyValueTable.js

https://trello.com/c/K7FK4qYs/1186-models-can-add-invalid-value-in-the-deploy-model-popup-table

[Models] Can add invalid value in the Deploy model popup table

---

src/components/JobsPanelAdvanced/JobsPanelAdvanced.js
src/components/JobsPanelParameters/JobsPanelParameters.js
src/elements/JobsPanelParametersTable/JobsPanelParametersTable.js
src/elements/JobsPanelTable/JobsPanelTable.js

https://trello.com/c/9Jgzk2YN/1187-create-job-app-crashes-on-removing-row-from-data-inputs-table

[Create Job] App crashes on removing row from Data Inputs table

---

src/common/Accordion/Accordion.js
src/common/Accordion/accordion.scss
src/common/RoundedIcon/roundedIcon.scss
src/elements/JobsPanelTitle/JobsPanelTitleView.js
src/elements/JobsPanelTitle/jobsPanelTitle.scss
src/scss/main.scss
src/scss/mixins.scss

https://trello.com/c/piBD0fyZ/1124-job-panel-click-at-edit-icon-makes-it-disappear

[Job panel] Click at "Edit" icon makes it disappear

---

src/components/Details/details.util.js
src/components/DetailsCode/DetailsCode.js
src/utils/parseFunction.js

https://trello.com/c/784XFrrz/1193-jobs-monitor-workflow-code-exists-on-yaml-but-there-is-a-message-no-data-to-show

[Jobs Monitor Workflow] Code exists on YAML but there is a message No data to show

---

src/common/ChipInput/ChipInput.js
src/components/JobsPage/Jobs.js
src/components/JobsPage/jobsData.js
src/components/Workflow/workflow.scss

https://trello.com/c/XpE18DKw/1195-jobs-remove-group-by-workflow

[Jobs] Remove group by workflow

---

src/components/JobsPage/Jobs.js
src/components/Workflow/Workflow.js

https://trello.com/c/qrXCj856/1196-workflows-project-stuck-on-opening-details-for-build-node

[Workflows] Project stuck on opening details for "build" node

---

src/common/ReactFlow/MlReactFlow.js
src/common/ReactFlow/MlReactFlowNode.js
src/common/ReactFlow/mlReactFlow.scss
src/common/ReactFlow/mlReactFlow.util.js
src/common/Tooltip/Tooltip.js
src/components/Details/DetailsView.js
src/components/DetailsTransformations/DetailsTransformations.js
src/components/JobsPage/Jobs.js
src/components/Pipeline/Pipeline.js
src/components/Workflow/Workflow.js
src/constants.js
src/utils/getState.js
src/utils/parseFunction.js

https://trello.com/c/xunybR1W/1185-workflow-jobs-add-status-tooltip

[Workflow jobs] Add status tooltip

---

src/api/artifacts-api.js
src/api/featureStore-api.js
src/api/jobs-api.js
src/common/DatePicker/DatePicker.js
src/common/TagFilter/TagFilter.js
src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
src/components/FeatureStore/FeatureStore.js
src/components/Files/Files.js
src/components/FilterMenu/FilterMenu.js
src/components/FilterMenu/filterMenu.settings.js
src/components/JobsPage/Jobs.js
src/components/JobsPage/jobsData.js
src/components/Models/Models.js
src/components/Table/Table.js
src/components/Table/TableView.js
src/constants.js
src/layout/Content/Content.js
src/layout/Content/content.util.js
src/reducers/filtersReducer.js
src/utils/datePicker.util.js
src/utils/generateTableContent.js
src/utils/handleArtifactTreeFilterChange.js

https://trello.com/c/5RCvGIe0/1158-ui-feature-vectorwrong-error-message-for-empty-filter-result

[UI] [Feature Vector]Wrong error message for empty filter result

---

src/components/Project/ProjectView.js

https://trello.com/c/YT0tdzoG/1188-project-cant-open-settings-for-new-project

[Project] Can't open Settings for new project

---

src/components/JobsPage/Jobs.js

https://trello.com/c/YH9no5r2/1202-jobs-http-request-to-undefined-in-monitor-jobs-and-monitor-workflows-tabs

[Jobs] HTTP request to undefined in monitor jobs and monitor workflows tabs

---

src/common/Breadcrumbs/Breadcrumbs.js
src/common/Breadcrumbs/breadcrumbs.util.js
src/components/Files/Files.js
src/components/Files/files.util.js
src/components/Project/ProjectView.js
src/components/Project/project.utils.js
src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
src/components/RegisterArtifactPopup/messagesByKind.js

https://trello.com/c/bLuZ2i2A/1182-ui-cosmetic-09

UI cosmetic 0.9

---

src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.scss
src/components/FeatureSetsPanel/ScheduleFeatureSet/ScheduleFeatureSet.js
src/components/FeatureSetsPanel/ScheduleFeatureSet/ScheduleFeatureSetView.js
src/components/FeatureSetsPanel/ScheduleFeatureSet/scheduleFeatureSet.scss

https://trello.com/c/t9RVK8Ec/1206-feature-sets-ui-fixes-for-scheduling-when-creating-a-new-feature-set

[Feature Sets] UI fixes for scheduling when creating a new feature set

---

src/components/JobsPage/Jobs.js

https://trello.com/c/qaARR5sZ/1218-workflows-app-crashes-on-switching-jobs

[Workflows] App crashes on switching jobs

---

src/elements/CreateNewSecretPopUp/CreateNewSecretPopUp.js

https://trello.com/c/nO7ZQeXa/1205-project-settings-can-add-a-non-unique-row-on-secrets-table
https://jira.iguazeng.com/browse/ML-1593

[Project Settings] Can add a non-unique row on Secrets table

---

src/elements/TooltipTemplate/TextTooltipTemplate.js

https://trello.com/c/hkEMiqve/1189-general-wrong-presentation-for-tooltips-with-new-lines
https://jira.iguazeng.com/browse/ML-1522

[General] Wrong presentation for tooltips with new lines (fixed tooltip width)

---

src/components/JobsPanel/jobsPanel.scss
src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
src/components/JobsPanelParameters/JobsPanelParametersView.js

https://trello.com/c/S5Gabs8E/1208-jobs-panel-tip-icon-overflows-container

[Jobs Panel] Tip icon overflows container

---

src/components/JobsPanelParameters/JobsPanelParameters.js
src/components/JobsPanelParameters/JobsPanelParametersView.js
src/elements/EditableParametersRow/EditableParametersRow.js
src/elements/JobsPanelParametersTable/jobsPanelParametersTable.scss

https://trello.com/c/vaFdEstd/1209-jobs-panel-parameters-missing-validation

[Jobs panel] "Parameters" missing validation

---

src/components/AddToFeatureVectorPage/addToFeatureVectorPage.util.js
src/components/FeatureStore/featureStore.util.js
src/elements/FeaturesTablePanel/FeaturesTablePanel.js
src/elements/FeaturesTablePanel/featuresTablePanel.scss
src/utils/createFeatureStoreContent.js

https://trello.com/c/fYnBEtus/1210-feature-vectors-trimmed-feature-vector-name

[Feature Vectors] Trimmed feature vector name

---

src/common/ChipInput/ChipInput.js
src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js

https://trello.com/c/8hWEcipd/1213-ui-search-for-user-in-the-change-owner-and-members-screens-should-be-case-insensitive
https://jira.iguazeng.com/browse/ML-1341

[UI] Search for user in the 'Change owner' and 'Members' screens should be case insensitive

---

src/components/FeatureSetsPanel/FeatureSetsPanel.js
src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitle.js
src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
src/components/FeatureSetsPanel/FeatureSetsPanelView.js
src/components/FeatureSetsPanel/featureSetPanel.util.js
src/components/FunctionsPanel/FunctionsPanel.js
src/components/FunctionsPanel/FunctionsPanelView.js
src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
src/components/JobsPanelResources/JobsPanelResourcesView.js
src/elements/FunctionsPanelAdvanced/FunctionsPanelAdvanced.js
src/elements/FunctionsPanelCode/FunctionsPanelCode.js
src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js
src/elements/FunctionsPanelRuntime/FunctionsPanelRuntime.js
src/elements/FunctionsPanelRuntime/FunctionsPanelRuntimeView.js
src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js
src/elements/NewFunctionPopUp/NewFunctionPopUp.js
src/elements/PartitionFields/PartitionFields.js

https://trello.com/c/EtuNqYdu/1215-general-missing-validation-on-panel

[General] Missing validation on panel

---

src/common/Combobox/Combobox.js

https://trello.com/c/MD2M8ffj/1217-create-feature-set-panel-click-on-save-save-and-ingest-buttons-doesnt-validate-combobox

[Create Feature Set panel] Click on "Save"/ "Save and ingest" buttons doesn`t validate combobox

---

src/components/DetailsTransformations/detailsTransformations.scss
src/elements/FeaturesTablePanel/featuresTablePanel.scss

https://trello.com/c/CNbRfBIo/1220-add-to-feature-vector-strange-accordion-button-animation

[Add to Feature Vector] Strange accordion button animation

---

src/common/ChipCell/ChipCellView.js

https://trello.com/c/HcRlMC9Q/1223-general-chip-value-overflows-chip-body
https://jira.iguazeng.com/browse/ML-1597

[General] Chip value overflows chip body

---

src/components/FeatureStore/featureStore.util.js
src/utils/parseFeatureSets.js

https://trello.com/c/kkL1hFC9/1214-feature-sets-labels-in-the-ui
https://jira.iguazeng.com/browse/ML-1359

Feature sets labels in the UI

---

src/components/JobsPanel/jobsPanel.util.js

https://jira.iguazeng.com/browse/ML-1455

[Jobs workflow report] Rerun job failed with FileNotFoundError

---

src/utils/measureTime.js

https://jira.iguazeng.com/browse/ML-1417

[UI] [Jobs workflow report] Unexpected 'Duration' format in UI

---

src/common/Tooltip/Tooltip.js
src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js

https://jira.iguazeng.com/browse/ML-1498

UI][Feature Vector] Tag setting issues for FV during creation and editing

---

src/utils/parseFeatureVectors.js

https://jira.iguazeng.com/browse/ML-1494
Before: 
After:

[Feature Vector] The Feature Vector status should not be presented in UI

---

src/components/Details/Details.js
src/components/Details/details.util.js
src/components/DetailsInfo/DetailsInfo.js
src/components/DetailsInfo/DetailsInfoView.js
src/components/DetailsInfo/detailsInfo.scss
src/components/DetailsInfo/detailsInfoReducer.js
src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
src/components/Project/ProjectMonitorView.js
src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
src/elements/DetailsInfoItem/DetailsInfoItem.js
src/elements/DetailsInfoItemChip/DetailsInfoItemChip.js
src/elements/FunctionsPanelGeneral/FunctionsPanelGeneralView.js
src/elements/JobsPanelTitle/JobsPanelTitleView.js

https://jira.iguazeng.com/browse/ML-1443
https://trello.com/c/AJsI95EU/1163-uifeature-sets-adding-multiple-labels-from-the-ui-doesnt-work-for-a-feature-set

Adding multiple labels from the UI doesn't work for a feature set

---

src/elements/AddFeatureButton/AddFeatureButton.js

Jira: https://jira.iguazeng.com/browse/ML-1617
Jira: https://jira.iguazeng.com/browse/ML-1470
Reverted From: https://github.com/mlrun/ui/commit/7948d748f2db5c83d941965c8c33c25a2ca15b2f

Fix [Feature Vector] Revert using tags

---

src/components/Details/details.scss
src/components/DetailsInfo/detailsInfo.scss
src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
src/components/DetailsRequestedFeatures/detailsRequestedFeatures.scss
src/elements/DetailsInfoItem/DetailsInfoItem.js
src/elements/DetailsInfoItemChip/DetailsInfoItemChip.js

https://jira.iguazeng.com/browse/ML-1602
https://trello.com/c/LJbbeTRJ/1221-details-apply-button-on-labels-row-disappears-on-the-small-screen

[Details] Apply button on Labels row disappears on the small screen

---

src/components/FunctionsPage/Functions.js
src/components/JobsPage/Jobs.js
src/components/Table/Table.js
src/components/Table/TableView.js
src/components/Workflow/Workflow.js
src/layout/Content/Content.js

https://jira.iguazeng.com/browse/ML-1601
Before:
After:

[Add to feature vector] Unnecessary scroll

---

src/elements/FeaturesTablePanel/FeatureTablePanleRow/FeaturesTablePanelRow.js
src/elements/FeaturesTablePanel/FeaturesTablePanel.js

https://jira.iguazeng.com/browse/ML-1478

[UI][Feature Vector] The 'Label feature' is deleted after deletion of another feature from the list

---

src/common/TagFilter/TagFilterDropdown.js

https://jira.iguazeng.com/browse/ML-1619
Before: 
After:

[Feature Vector] Wrong items are highlighted

---

src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
src/elements/ProjectSettingsGeneral/ProjectSettingsGeneralView.js

aritfact path can be set but it isn't saved

Fix [project][general][setting][UI] aritfact path can't be saved

---

src/actions/featureStore.js
src/api/featureStore-api.js
src/components/FeatureStore/FeatureStore.js
src/components/FeatureStore/featureStore.util.js
src/components/FilterMenu/FilterMenu.js

https://jira.iguazeng.com/browse/ML-1474
Before: 
After:

[UI][Feature Vector] Delete Feature vector option is missing in the List of FVs screen

---

src/components/Project/ProjectMonitorView.js

Jira: https://jira.iguazeng.com/browse/ML-1583
Before:
After:

Impl [Project][Monitor] remove settings icon

---

src/utils/resultsTable.js

https://jira.iguazeng.com/browse/ML-1630
Before:
After:

Fix [Jobs][Monitor] crash when "status.iterations" has a null value

---

src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
src/elements/JobsPanelTitle/JobsPanelTitleView.js
src/utils/validationService.js

Jira: https://jira.iguazeng.com/browse/ML-1657
- field validation considers "0aaa" as a valid project name and tries to send it to API.
however looks like project can not begin with number.

Fix [Projects] incorrect project name validation

---

src/common/ReactFlow/MlReactFlow.js
src/components/JobsPage/Jobs.js
src/components/Workflow/Workflow.js

https://jira.iguazeng.com/browse/ML-1591
- **Workflows**: On entering the screen graph was displayed on the left side, now it is centered.

[Workflows] Wrong position of the graph

---

src/scss/mixins.scss

https://jira.iguazeng.com/browse/ML-1660
- **ML Function**: Does not open Action Menu for Volumes Table.

[UI][ML Function][Create Jobs] Does not open Action Menu for Volumes Table

---

test_pr.groovy

DEVOPS-342 adding test PR pipeline

DEVOPS-342 adding test PR pipeline

---

src/components/JobsPage/jobsData.js

Jira: https://jira.iguazeng.com/browse/ML-1438
- **Jobs Workflow**: The sorting by field assist the user, when the large number of WFs are created. Add the filtering by period ,by status  and by name/part of name

Impl [Jobs workflow] filter menu

---

src/actions/projects.js
src/components/Project/ProjectOverview/ProjectOverview.js
src/components/ProjectsPage/Projects.js

https://jira.iguazeng.com/browse/ML-1610 
- **Project Screen**: Missing error message when archive action failed with error 403

[UI][Project Screen] Missing error message when archive action failed with error 403

---

ci_start_ui_tests.sh
test_pr.groovy

DEVOPS-342 adding test PR pipeline update

DEVOPS-342 adding test PR pipeline update

---

src/components/DetailsArtifacts/detailsArtifacts.util.js
src/elements/DetailsInfoItem/DetailsInfoItem.js
src/utils/generateArtifactPreviewData.js
src/utils/generateArtifacts.js

- **Models Overview**:  Incorrect target_path in YAML file
https://jira.iguazeng.com/browse/ML-1626

Fix [Models][Overview] Incorrect target_path in YAML file

---

test_pr.groovy

DEVOPS-342 changing image for runner for PR tests

DEVOPS-342 changing image for runner

---

test_pr.groovy

DEVOPS-342 changing image for runner to centos 7 to enable PR tests

DEVOPS-342 changing image for runner to centos 7

---

src/utils/createArtifactPreviewContent.js

- **Jobs Artifacts**: UI crash on Artifact with type txt
https://jira.iguazeng.com/browse/ML-1705

[Jobs][Artifacts] UI crash on Artifact with type txt

---

src/components/FeatureStore/FeatureStore.js
src/components/Jobs/Jobs.js
src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
src/reducers/featureStoreReducer.js

- **Features**: UI tries to load features from the previously selected project with features and shows a part of them for a project without features
https://jira.iguazeng.com/browse/ML-1645

Fix [UI][Features] Strange features behavior on project change

---

src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
src/elements/ProjectSettingsGeneral/ProjectSettingsGeneralView.js
src/elements/ProjectSettingsGeneral/projectSettingsGeneral.utils.js

- **Project Settings**: Incorrect values shown on project change
https://jira.iguazeng.com/browse/ML-1740

Fix [Project Settings] Incorrect values

---

src/layout/Content/Content.js

- **Real-time-pipelines**: Expand button has wrong icon
https://jira.iguazeng.com/browse/ML-1738
Before:
After:

Fix [UI][Real-time-pipelines] Expand button has wrong icon

---

src/components/Details/Details.js
src/components/Jobs/Jobs.js

- **Workflows**: Can't open function
When trying to open a function on Monitor Workflows graph there is a white screen.
https://jira.iguazeng.com/browse/ML-1715

Fix [UI][Workflows] Can't open function

---

src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
src/utils/string.js

- **Owner**: The owner cannot be changed by typing a username
https://jira.iguazeng.com/browse/ML-1141
Before:
After:

Fix [UI] The owner cannot be changed by typing a username

---

src/api/featureStore-api.js

- **Feature set**: User can't create Feature set with more than one version from UI
https://jira.iguazeng.com/browse/ML-1527

Fix [Feature set] User can't create Feature set with more than one version from UI 

---

src/components/FeatureStore/FeatureStore.js

- **Feature set**: New tag presents in the Tags filter list after reload page.
https://jira.iguazeng.com/browse/ML-1688

Fix [Feature set]New tag presents in the Tags filter list after reload page.

---

src/elements/TableProducerCell/TableProducerCell.js
src/utils/createJobsContent.js

- **Datasets**: Wrong redirection on clicking the producer cell
https://jira.iguazeng.com/browse/ML-1749

Fix [UI][Datasets] Wrong redirection on clicking the producer cell

---

src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js

- **Feature Vector**: `MLRunAccessDeniedError` for creating Feature Vector by user where user is member with viewer role.
https://jira.iguazeng.com/browse/ML-1502
- Add an error message

Fix [Feature Vector] MLRunAccessDeniedError` for creating Feature Vector by user where user is member with viewer role

---

src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.util.js

- **Feature Sets**: Add Google storage to the data source dropdown in the feature store
https://jira.iguazeng.com/browse/ML-1514
Before:
After:

Impl [Feature Sets] Add Google storage to the data source dropdown in the feature store

---

src/components/DetailsArtifacts/DetailsArtifacts.js
src/components/DetailsArtifacts/DetailsArtifactsView.js

- **Jobs**: Click on show details doesn't open the right info
https://jira.iguazeng.com/browse/ML-1533

Fix [Artifacts] Click on show details doesn't open the right info

---

src/components/Jobs/Jobs.js

- **Jobs**: Filter by date resets when choosing a job
https://jira.iguazeng.com/browse/ML-1750

Fix [Jobs] Filter by date resets when choosing a job

---

src/actions/jobs.js
src/common/ErrorMessage/ErrorMessage.js
src/common/ErrorMessage/errorMessage.scss

- **Jobs**: The 'Run' job and Rerun job options are available for project user with role "viewer"
https://jira.iguazeng.com/browse/ML-1413

Fix [Jobs] The 'Run' job and Rerun job options are available for project user with role "viewer"

---

src/actions/projects.js
src/api/projects-api.js

- **Project Monitor**: optimize the project overview screen
Improve performance by leveraging the new list runs by params `partition-by` `partition-sort-by` `rows-per-partition` `last` 
Jira: [ML-1686](https://jira.iguazeng.com/browse/ML-1686)

Impl [Project Monitor] optimize the project overview screen

---

src/components/Table/Table.js
src/components/Table/TableView.js

- **Jobs**: Monitor Jobs crash when undefined (reading 'value')
https://jira.iguazeng.com/browse/ML-1789

Fix [Jobs] Monitor Jobs crash when undefined (reading 'value')

---

src/components/FeatureStore/FeatureStore.js
src/components/Files/Files.js
src/components/Files/files.util.js
src/components/Models/Models.js
src/hooks/useGetTagOptions.hook.js

- **Models**: Details panel closes unexpectedly
https://jira.iguazeng.com/browse/ML-1777

Fix [Models] Details panel closes unexpectedly

---

src/components/Models/models.util.js

- **Realtime Pipelines**: Duplicated real time function
https://jira.iguazeng.com/browse/ML-1786
Before:
After:

Fix [Realtime Pipelines] Duplicated real time function

---

src/components/FeatureStore/FeatureStore.js

- **Feature Store**: Wrong request for tags
https://jira.iguazeng.com/browse/ML-1821

Fix [UI][Feature Store] Wrong request for tags

---

src/components/Jobs/Jobs.js
src/components/Table/Table.js

- **Jobs**: Monitor workflows shows small subset of the full list of workflows
https://jira.iguazeng.com/browse/ML-1832

Fix [Jobs] Monitor workflows shows small subset of the full list of workflows

---

src/api/jobs-api.js

- **Jobs**: Hyper parameters task run isn't presented properly in UI
Jira: [ML-1818](https://jira.iguazeng.com/browse/ML-1818)

Fix [Jobs] Hyper parameters task run isn't presented properly

---

src/components/DetailsLogs/DetailsLogs.js

- **Jobs**: Loader doesn't appear
- Press the "Refresh" button, Request is sent but loader doesn't appear
Jira: https://jira.iguazeng.com/browse/ML-1846

Fix [Jobs] Loader doesn't appear

---

src/components/FeatureSetsPanel/FeatureSetsPanel.js
src/components/FeatureStore/FeatureStore.js
src/components/FilterMenu/FilterMenu.js

- **Feature Set**: Feature set creation via UI failed with error 404
Jira: https://jira.iguazeng.com/browse/ML-1816

Fix [Feature Set] Feature set creation via UI failed with error 404

---

src/api/jobs-api.js
src/components/Jobs/Jobs.js

- **Jobs**: job run status is not being updated in "Monitor Jobs" tab
https://jira.iguazeng.com/browse/ML-1866

Fix [Jobs] job run status is not being updated in "Monitor Jobs" tab

---

tests/features/common-tools/common-consts.js
tests/features/common/actions/dropdown.action.js
tests/features/common/actions/table.action.js
tests/features/common/page-objects/commonPagesHeader.po.js
tests/features/common/page-objects/feature-store.po.js
tests/features/common/page-objects/info-pane.po.js
tests/features/common/page-objects/jobs-and-workflows.po.js
tests/features/common/page-objects/side-panel.po.js
tests/features/featureStore.feature
tests/features/jobsAndWorkflows.feature
tests/features/projectPage.feature
tests/features/support/hooks.js
tests/features/support/world.js
tests/mockServer/backendSynchronizator.js
tests/mockServer/mock.js

Collecting PRs into branch development from branch **tests**
#1146

Impl [tests] QA Sprint 135

---

src/components/Project/project.scss
src/components/ProjectsPage/ProjectsView.js
src/components/ProjectsPage/projects.scss

- **Projects**: Align the color of Create New button in projects > default
Jira: [ML-1853](https://jira.iguazeng.com/browse/ML-1853)
* Align button color for Projects
* Align button color for project monitor
* align buttons height in projects
Before:
After:

Fix [Projects] Align the color of Create New button in projects > default

---

src/components/DetailsArtifacts/DetailsArtifactsView.js
src/components/DetailsInputs/DetailsInputs.js

- **Jobs**: Missing No Data message
Jira: https://jira.iguazeng.com/browse/ML-1876
Before: 
After:

Fix [Jobs] Missing No Data message

---

src/actions/projects.js
src/common/ErrorMessage/ErrorMessage.js
src/common/ErrorMessage/errorMessage.scss
src/common/PopUpDialog/popUpDialog.scss
src/components/FunctionsPanel/FunctionsPanelView.js
src/components/FunctionsPanel/functionsPanel.scss
src/components/JobsPanel/JobsPanelView.js
src/components/JobsPanel/jobsPanel.scss
src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
src/components/ProjectsPage/CreateProjectDialog/createProjectDialog.scss
src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
src/constants.js

- **Projects**: unclear error message on attempt to create project upon reaching projects amount limit
Jira: https://jira.iguazeng.com/browse/ML-1481
Before:
After:

Fix [Projects] unclear error message on attempt to create project upon reaching projects amount limit

---

src/components/Jobs/Jobs.js
src/utils/object.js

- **Jobs Schedule**:  App crashes on scheduled job deletion
Jira: https://jira.iguazeng.com/browse/ML-1887
Before:
After:

Fix [Jobs] App crashes on scheduled job deletion

---

src/components/ProjectSettings/ProjectSettings.js

- **Project Settings**: Applying new owner should load main projects screen
Jira: https://jira.iguazeng.com/browse/ML-1851

Fix [Project Settings] Applying new owner should load main projects screen

---

src/components/Details/details.util.js
src/components/DetailsMetadata/detailsMetadata.util.js
src/components/DetailsStatistics/detailsStatistics.util.js
src/components/Models/models.util.js

- **Models**: Empty features for model without feature vector
Jira: https://jira.iguazeng.com/browse/ML-1392

Fix [Models] Empty features for model without feature vector

---

src/api/workflow-api.js

- **Jobs workflow report**: Wrong APIs are sent for all WF filters
https://jira.iguazeng.com/browse/ML-1696

Bug [Jobs workflow report] Wrong APIs are sent for all WF filters

---

src/api/workflow-api.js

- **Jobs workflow report**: Wrong APIs are sent for all WF filters
https://jira.iguazeng.com/browse/ML-1696

Fix [Jobs workflow report] Wrong APIs are sent for all WF filters

---

src/components/Details/details.util.js
src/components/FeatureStore/featureStore.util.js
src/utils/createFeatureStoreContent.js

- **Feature Vector**: The Entity is missing in the FV presentation in UI
Jira: https://jira.iguazeng.com/browse/ML-1512

Fix [Feature Vector] The Entity is missing in the FV presentation in UI

---

src/components/FunctionsPanel/FunctionsPanel.js
src/components/JobsPanel/JobsPanel.js
src/components/JobsPanel/JobsPanelView.js
src/components/JobsPanel/jobsPanel.util.js
src/components/JobsPanelResources/JobsPanelResources.js
src/elements/FunctionsPanelResources/FunctionsPanelResources.js

- **Functions**: Show default limits & requests for MLRun functions and services
Jira: https://jira.iguazeng.com/browse/ML-375

Impl [UI] Show default limits & requests for MLRun functions and services

---

src/components/Details/details.scss
src/elements/PreviewModal/PreviewModal.js

- **Artifact preview**: Long names isn't cropped
Jira: https://jira.iguazeng.com/browse/ML-1915
Before:
After:

Fix [Artifact preview] Long names isn't cropped

---

src/components/ProjectsPage/projects.scss
src/elements/ContentMenu/contentMenu.scss

- **Project settings**: align tabs view by Figma
Align tabs view according to Figma design.
- Increase font-size: 20px
- Decrease bottom border: 2px
- Remove grey border under blue border
Match tabs view across app. (Projects, settings, jobs...)
Jira: [ML-1925](https://jira.iguazeng.com/browse/ML-1925)
Before:
After:

Impl [Project settings] align tabs view by Figma

---

src/components/Models/models.util.js
src/elements/TableLinkCell/TableLinkCell.js
src/utils/createArtifactsContent.js
src/utils/createFeatureStoreContent.js
src/utils/createFunctionsContent.js
src/utils/createJobsContent.js

- **Real-Time Pipelines**: Add a new `Function` column to the Real-Time Pipelines page
Jira: [ML-1035](https://jira.iguazeng.com/browse/ML-1035)

Impl [Real-Time Pipelines] Add a `function` column

---

src/elements/FunctionsPanelResources/FunctionsPanelResources.js
src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js

- **Functions**: User can't change ml function pod priority from UI
Jira: https://jira.iguazeng.com/browse/ML-1965

Fix [Functions] User can't change ml function pod priority from UI

---

src/common/KeyValueTable/keyValueTable.scss
src/scss/mixins.scss

- **Jobs Panel**: Table headers font size are not aligned
Jira: https://jira.iguazeng.com/browse/ML-1949
Before:
After:

Fix [Jobs Panel] Table headers font size are not aligned

---

src/components/FunctionsPanel/FunctionsPanel.js
src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js

- **Function**: The handler of ML function is empty for function deployed from Jupyter
Jira: [ML-965](https://jira.iguazeng.com/browse/ML-965)
Before:
After:

Fix [Functions] The handler of ML function is empty for function deployed from Jupyter

---

src/components/Datasets/Datasets.js
src/components/FeatureStore/FeatureStore.js
src/components/Files/Files.js
src/components/Models/Models.js

- **Feature Vector**: The Filter for "latest" tag presents all tags
Jira: https://jira.iguazeng.com/browse/ML-1483
Before:
After:

Fix [Feature Vector] The Filter for "latest" tag presents all tags

---

src/components/FeatureSetsPanel/FeatureSetsPanel.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
src/components/FeatureSetsPanel/FeatureSetsPanelView.js
src/reducers/featureStoreReducer.js

- **Feature Sets**: Wrong default Path for Online and Offline Target store
Jira: https://jira.iguazeng.com/browse/ML-1089
Before: 
After:

Fix [Feature Sets] Wrong default Path for Online and Offline Target store

---

src/elements/FunctionsPanelResources/FunctionsPanelResources.js

Fix [Functions] Empty default value of Pod priority field

---

src/common/ChipCell/ChipCell.js
src/components/Models/models.util.js
src/components/Project/project.scss
src/components/ProjectSettings/projectSettings.scss
src/components/ProjectsPage/ProjectsView.js
src/components/ProjectsPage/projects.scss
src/layout/Content/content.scss
src/layout/Navbar/Navbar.scss
src/layout/Page/PageView.js
src/layout/Page/PageView.scss
src/scss/main.scss
src/utils/createFunctionsContent.js

- **UI**: Fix layout in small resolution
Jira: [ML-1990](https://jira.iguazeng.com/browse/ML-1990)
Before:
After:

Fix [UI] layout in small resolutions

---

src/common/ChipCell/ChipCell.js
src/layout/Page/PageView.js
src/utils/getTransitionEndEventName.js

- **Models**: Chips are not resized when toggling left menu
Jira: [ML-2048](https://jira.iguazeng.com/browse/ML-2048)
Before:
After:

Fix [Models] Chips are not resized when toggling left menu

---

src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
src/components/DetailsRequestedFeatures/detailsRequestedFeatures.scss
src/components/DetailsRequestedFeatures/detailsRequestedFeatures.utils.js

- **Feature Vector**: Missing feature_label icon in the feature list after Feature vector creation
Jira: https://jira.iguazeng.com/browse/ML-1482
Before:
After:

Fix [Feature Vector] Missing feature_label icon in the feature list after Feature vector creation

---

src/components/JobsPanel/jobsPanel.util.js

- **Functions**: Pod priority is changed to default (Medium) after running a mlrun function
Jira: https://jira.iguazeng.com/browse/ML-2011

Fix [UI] Pod priority is changed to default (Medium) after running a mlrun function

---

src/common/Combobox/Combobox.js
src/components/FeatureSetsPanel/FeatureSetsPanel.js
src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSource.js
src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
src/components/FeatureSetsPanel/FeatureSetsPanelView.js
src/components/FeatureSetsPanel/featureSetPanel.util.js

- **Feature Set Panel**: Problem with validation on save
Jira: https://jira.iguazeng.com/browse/ML-1931
Before:
After:

Fix [Feature Set Panel] Problem with validation on save

---

src/components/Table/Table.js

- **Feature Store**: Add to feature vector - Incorrect right panel height
Jira: [ML-2063](https://jira.iguazeng.com/browse/ML-2063)
Before:
After:

Fix [Feature Store] Add to feature vector - Incorrect right panel height

---

src/components/Table/Table.js
src/layout/Page/PageView.js
src/layout/Page/PageView.scss

Fix related to #1200

---

src/components/ConsumerGroup/ConsumerGroup.js
src/components/ConsumerGroup/consumerGroup.util.js
src/components/ConsumerGroups/ConsumerGroups.js
src/components/ConsumerGroups/consumerGroups.util.js
src/components/Table/TableView.js
src/elements/ConsumerGroupShardLagTableRow/ConsumerGroupShardLagTableRow.js
src/elements/ConsumerGroupTableRow/ConsumerGroupTableRow.js

- **Consumer groups**: Unnecessary YAML file for consumer groups page
Jira: [ML-2077](https://jira.iguazeng.com/browse/ML-2077)
Before:
After:

Fix [Consumer groups] Unnecessary YAML file for consumer groups page

---

tests/features/MLFunction.feature
tests/features/common-tools/common-consts.js
tests/features/common/actions/api.actions.js
tests/features/common/actions/input-with-autocomplete.action.js
tests/features/common/actions/table.action.js
tests/features/common/components/input-with-autocomplete.component.js
tests/features/common/components/table.component.js
tests/features/common/page-objects.js
tests/features/common/page-objects/commonPagesHeader.po.js
tests/features/common/page-objects/feature-store.po.js
tests/features/common/page-objects/info-pane.po.js
tests/features/common/page-objects/interactive-popup.po.js
tests/features/common/page-objects/jobs-and-workflows.po.js
tests/features/common/page-objects/project-settings.po.js
tests/features/common/page-objects/project.po.js
tests/features/common/page-objects/projects.po.js
tests/features/common/page-objects/side-panel.po.js
tests/features/featureStore.feature
tests/features/files.feature
tests/features/jobsAndWorkflows.feature
tests/features/models.feature
tests/features/projectPage.feature
tests/features/projectSettings.feature
tests/features/step-definitions/steps.js
tests/features/step-definitions/table.steps.js
tests/mockServer/data/frontendSpec.json
tests/mockServer/mock.js

Collecting PRs into branch development from branch tests:
[Impl [tests] QA Sprint 136](https://github.com/mlrun/ui/pull/1204)

Impl [tests] QA Sprint 136

---

src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js

- **Feature set**: Create a feature set from the UI where the source is parquet on V3io fail
Jira: https://jira.iguazeng.com/browse/ML-2031

Fix [UI] Create a feature set from the UI where the source is parqueton V3io fail

---

src/components/Details/details.util.js
src/components/Jobs/jobs.util.js

- **Monitor jobs**: Wrong iteration number
Jira: https://jira.iguazeng.com/browse/ML-1902
Before:
After:

Fix [Monitor jobs] Wrong iteration number

---

src/components/JobsPanel/jobsPanel.scss
src/components/JobsPanelResources/JobsPanelResourcesView.js
src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
src/elements/FunctionsPanelResources/functionsPanelResources.scss

- **Jobs**: misleading 'PODS TOLERATION' in mlrun UI job wizard
Jira: [ML-2088](https://jira.iguazeng.com/browse/ML-2088)
Before:
After:

Fix [Jobs] misleading 'PODS TOLERATION' in mlrun UI job wizard

---

src/common/Combobox/Combobox.js
src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSource.js
src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
src/utils/panelPathScheme.js

- **Jobs Panel**: Dataset input interaction in the jobs wizard is broken
Jira: https://jira.iguazeng.com/browse/ML-2096

Fix [Jobs Panel] Dataset input interaction in the jobs wizard is broken

---

src/App.js
src/common/Input/Input.js
src/components/Project/ProjectMonitor.js
src/components/Project/ProjectMonitorView.js
src/components/ProjectsPage/Projects.js
src/elements/ProjectFunctions/ProjectFunctions.js
src/elements/ProjectSummaryCard/ProjectSummaryCard.js
src/hooks/nuclioMode.hook.js

- **UI** Projects summaries show N/A in environment without Nuclio
Jira: https://jira.iguazeng.com/browse/ML-2106

Fix [UI] Projects summaries show N/A in environment without Nuclio

---

src/actions/projects.js
src/components/JobsPanel/jobsPanel.util.js

- **Project Monitor**: The main project screen doesn't show the status for all running jobs
Jira: https://jira.iguazeng.com/browse/ML-2114
Before:
After:

Fix [Project Monitoring] The main project screen doesn't show the status for all running jobs

---

src/elements/ProjectFunctions/ProjectFunctions.js
src/elements/ProjectSummaryCard/ProjectSummaryCard.js

UI Projects summaries show N/A in environment without Nuclio
Related To: https://github.com/mlrun/ui/pull/1224
Fix To: #1228 
Jira: https://jira.iguazeng.com/browse/ML-2106

Fix [Jobs Panel] The Pods Priority dropdown doesn't have selected value

---

src/utils/panelResources.util.js

Related To:  #1241 
https://jira.iguazeng.com/browse/ML-2110

Impl [UI] Missing unit in the New MLRun function and New job wizard and wrong handling of defaults

---

src/components/JobsPanel/jobsPanel.util.js

- **Jobs**: Selecting a method in the new job panel cause a hang
Backported to: 1.0.0
Jira: https://jira.iguazeng.com/browse/ML-2129

Fix [Jobs] Selecting a method in the new job panel cause a hang

---

tests/features/MLFunction.feature
tests/features/common-tools/common-consts.js
tests/features/common-tools/common-tools.js
tests/features/common/actions/api.actions.js
tests/features/common/actions/common.action.js
tests/features/common/page-objects/feature-store.po.js
tests/features/common/page-objects/info-pane.po.js
tests/features/common/page-objects/interactive-popup.po.js
tests/features/common/page-objects/jobs-and-workflows.po.js
tests/features/common/page-objects/models.po.js
tests/features/common/page-objects/projects.po.js
tests/features/common/page-objects/side-panel.po.js
tests/features/datasets.feature
tests/features/featureStore.feature
tests/features/files.feature
tests/features/jobsAndWorkflows.feature
tests/features/models.feature
tests/features/projectSettings.feature
tests/features/projectsPage.feature
tests/features/step-definitions/api.steps.js
tests/features/step-definitions/steps.js
tests/mockServer/mock.js

Collecting PRs into branch development from branch **tests**
[Impl [tests] QA Sprint 136 (new tests) #1238](https://github.com/mlrun/ui/pull/1238)

Impl [tests] QA Sprint 136 Done

---

config/webpack.config.js

[Bug] Fixed conflicting order between styles

---

src/components/FunctionsPanel/FunctionsPanel.js
src/elements/FunctionsPanelResources/FunctionsPanelResources.js
src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
src/utils/parseFunction.js

- **Functions**: missing spot drop down in update existing mlrun function screen
Jira: [ML-2127](https://jira.iguazeng.com/browse/ML-2127)
Before:
After:

Fix [Functions] missing spot drop down in update existing mlrun function screen

---

src/actions/jobs.js

- **Schedule Job**: The 'Request failed with status code 400' presents for same scheduler set
Jira: [ML-55](https://jira.iguazeng.com/browse/ML-55)
Before:
After:

Fix [Schedule Job] The 'Request failed with status code 400' presents for same scheduler set

---

src/elements/FeaturesTablePanel/FeaturesTablePanel.js
src/elements/FeaturesTablePanel/FeaturesTablePanelView.js
src/reducers/tableReducer.js
src/utils/createFeatureStoreContent.js

- **Feature Store**: Feature vector creation from the UI is broken when selecting an entity field
Jira: https://jira.iguazeng.com/browse/ML-2111
Before: 
After:

Fix [Features] Feature vector creation from the UI is broken when selecting an entity field

---

src/utils/createJobsContent.js

- **Jobs** Click on a scheduled name opens up the entire list of functions
Jira: https://jira.iguazeng.com/browse/ML-2098

Fix [Jobs] Click on a scheduled name opens up the entire list of functions

---

src/api/projects-iguazio-api.js
src/common/ChipInput/chipInput.scss
src/elements/MembersPopUp/MembersPopUp.js
src/elements/MembersPopUp/membersPopUp.scss

- **Settings Members**: "Invite new members" returns up to 50 users
Jira: https://jira.iguazeng.com/browse/ML-2167

Fix [Settings] Members: "Invite new members" returns up to 50 users

---

src/actions/projects.js
src/components/Jobs/Jobs.js

- **Project Overview**: Some runs not shown in project overview screen
Jira: https://jira.iguazeng.com/browse/ML-2122

Fix [Project Overview] Some runs not shown in project overview screen

---

src/utils/panelResources.util.js

- **Functions/Jobs**: Wrong validation for CPU units
Jira: https://jira.iguazeng.com/browse/ML-2171
Before:
After:

Fix [Functions/Jobs] Wrong validation for CPU units

---

package.json
src/common/KeyValueTable/KeyValueTableView.js

- **UI** Change icon plus to check when applying new key-value
Before:
After:

Fix [UI] Change icon plus to check when applying new key-value

---

src/api/projects-iguazio-api.js
src/elements/MembersPopUp/MembersPopUp.js
src/elements/MembersPopUp/membersPopUp.scss

- **Settings Members**: 'Invite new members' returns up to 50 users
Use: `filter[username]=[$match-i]^.*SEARCH QUERY STRING.*$&page[size]=200` 
Jira: [ML-2169](https://jira.iguazeng.com/browse/ML-2169)

Fix [Settings Members] 'Invite new members' returns up to 50 users

---

src/components/DetailsArtifacts/detailsArtifacts.util.js
src/components/Jobs/Jobs.js
src/components/Jobs/MonitorJobs/MonitorJobsView.js
src/components/Jobs/MonitorJobs/monitorJobs.util.js
src/components/Jobs/MonitorWorkflows/MonitorWorkflowsView.js
src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js

- **Jobs**: Crash on attempt to open "Artifacts" tab - TypeError: Cannot read properties of undefined (reading 'match')
Jira: https://jira.iguazeng.com/browse/ML-2188
Before:
After:

Fix [Jobs] Crash on attempt to open "Artifacts" tab - TypeError: Cannot read properties of undefined (reading 'match')"

---

src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
src/components/Workflow/Workflow.js

- **Jobs**: Cannot View Build Image Step in Pipeline UI
Jira: https://jira.iguazeng.com/browse/ML-2180
Before:
After:

Fix [UI] Cannot View Build Image Step in Pipeline UI

---

src/api/projects-iguazio-api.js
src/components/ProjectSettings/ProjectSettings.js
src/components/ProjectSettings/projectSettings.util.js
src/elements/MembersPopUp/MembersPopUp.js

- **Project Overview**: Changes in members are reflected only after a refresh
Jira: https://jira.iguazeng.com/browse/ML-1152

Fix [Project Overview] Changes in members are reflected only after a refresh

---

src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss

- **Feature Store**: Feature Set Panel Error when change Partition checkboxes
Jira: https://jira.iguazeng.com/browse/ML-2215

Fix [Feature Set Panel] Error when change Partition checkboxes

---

src/components/Details/details.util.js
src/components/Jobs/MonitorJobs/MonitorJobs.js
src/components/Jobs/MonitorJobs/monitorJobs.util.js
src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
src/components/Jobs/jobs.util.js
src/elements/DetailsInfoItem/DetailsInfoItem.js
src/utils/parseJob.js

- **Jobs**: Show the Spark UI URL in the spark Job
Jira: https://jira.iguazeng.com/browse/ML-2170
After:

Impl [Jobs] Show the Spark UI URL in the spark Job

---

src/components/FunctionsPage/Functions.js
src/components/JobsPanel/jobsPanel.util.js
src/components/JobsPanel/panelReducer.js
src/components/JobsPanelResources/JobsPanelResources.js
src/components/JobsPanelResources/JobsPanelResourcesView.js
src/elements/FunctionsPanelResources/FunctionsPanelResources.js
src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
src/elements/PanelResourcesUnits/PanelResourcesUnits.js
src/utils/panelResources.util.js

- **Jobs/Functions**: Add support modification of already existing function with different GPU type
Jira: https://jira.iguazeng.com/browse/ML-2182

Impl [UI] Add support modification of already existing function with different GPU type

---

Dockerfile

Backport from development to 1.0.x
Related To: #1282

Security and vulnerabilities fixes - Backport 1.0.x

---

package.json

Fix npm vulnerabilities

---

src/common/ReactFlow/MlReactFlow.js
src/common/ReactFlow/mlReactFlow.scss
src/components/Workflow/Workflow.js

- **Jobs**: Change steps color in the workflow to reflect their status
Jira: https://jira.iguazeng.com/browse/ML-1988
Before:
After:

Impl [Workflows] Change steps color in the workflow to reflect their status

---

src/components/RegisterArtifactPopup/RegisterArtifactPopup.js

- **Models**: Register model doesn't post Target path
Jira: https://jira.iguazeng.com/browse/ML-2247

Fix [Models] Register model doesn't post Target path

---

src/components/Jobs/Jobs.js

- **Jobs**: Blank screen on trying to access Monitor Workflows
Jira: https://jira.iguazeng.com/browse/ML-2271

Fix [Jobs] Blank screen on trying to access Monitor Workflows

---

src/components/Jobs/MonitorJobs/MonitorJobsView.js

- **Jobs**: Filters resets after selecting a job
https://jira.iguazeng.com/browse/ML-2275

Fix [Jobs] Filters resets after selecting a job

---

src/components/ConsumerGroups/consumerGroups.util.js
src/components/Table/table.scss
src/elements/TableLinkCell/TableLinkCell.js
src/elements/TableLinkCell/tableLinkCell.scss
src/utils/createFeatureStoreContent.js
src/utils/createJobsContent.js

- **Jobs**: Chips overflows table
Jira: [ML-2244](https://jira.iguazeng.com/browse/ML-2244)
Before:
After:

Fix [Jobs] Chips overflows table

---

package.json
src/common/Select/Select.js
src/components/Details/DetailsView.js
src/components/DetailsRequestedFeatures/DetailsRequestedFeaturesView.js
src/components/FeatureSetsPanel/FeatureSetsPanelView.js
src/components/FeatureStore/FeatureStore.js
src/components/FunctionsPage/Functions.js
src/components/FunctionsPanel/FunctionsPanelView.js
src/components/Jobs/Jobs.js
src/components/Project/ProjectMonitorView.js
src/components/Project/ProjectOverview/ProjectOverview.js
src/components/ProjectsPage/ProjectsView.js
src/elements/MembersPopUp/MembersPopUp.js

- **General**:  Add `isOpen` prop to  `ConfirmDialog` component
Jira: [ML-2301](https://jira.iguazeng.com/browse/ML-2301)

Fix [UI] blank screen on attempt to archive project

---

src/elements/EnvironmentVariables/AddEnvironmentVariablesRow.js
src/elements/EnvironmentVariables/EditableEnvironmentVariablesRow.js
src/elements/EnvironmentVariables/environmentVariables.util.js
src/elements/FunctionsPanelResources/FunctionsPanelResources.js
src/elements/FunctionsPanelSecrets/FunctionsPanelSecrets.js

- **Functions Panel**: Issues with editing rows
Jira: https://jira.iguazeng.com/browse/ML-2249

Fix [Functions Panel] Issues with editing rows

---

src/common/ReactFlow/mlReactFlow.scss
src/components/ArtifactsPreview/artifactsPreview.scss
src/components/Datasets/Datasets.js
src/components/Datasets/datasets.util.js
src/components/Details/DetailsView.js
src/components/Details/details.scss
src/components/Details/details.util.js
src/components/DetailsFeaturesAnalysis/DetailsFeaturesAnalysis.js
src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.scss
src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.util.js
src/components/DetailsInfo/DetailsInfo.js
src/components/DetailsInfo/DetailsInfoView.js
src/components/DetailsResults/detailsResults.scss
src/components/FeatureStore/Features/FeaturesView.js
src/components/Files/Files.js
src/components/Files/files.util.js
src/components/Models/Models.js
src/components/Models/models.util.js
src/components/ProjectsPage/Projects.js
src/components/ProjectsPage/ProjectsView.js
src/components/ProjectsPage/projectsData.js
src/utils/generateProducerDetailsInfo.js
src/utils/parseJob.js

- **UI**: UI cosmetic 1.1.0
Jira: https://jira.iguazeng.com/browse/ML-1720
Before:
After:
Before:
After:
Before:
After:

Impl [UI] Cosmetic 1.1.0

---

src/components/FeatureStore/FeatureSets/featureSets.util.js

- **UI**: UI cosmetic 1.1.0
Related to: #1307 
Jira: https://jira.iguazeng.com/browse/ML-1720

Fix [Models endpoints] tip text mistake

---

src/components/Models/Models.js
src/components/Models/models.util.js
src/reducers/detailsReducer.js

https://jira.iguazeng.com/browse/ML-2248
Before: 
After:

Fix [Models] The Model page isn't open when log_model run without tag

---

src/common/DatePicker/DatePickerView.js
src/common/DatePicker/datePicker.scss
src/components/Jobs/MonitorJobs/MonitorJobsView.js
src/components/Jobs/MonitorWorkflows/MonitorWorkflowsView.js
src/components/Jobs/ScheduledJobs/ScheduledJobsView.js

- **Workflows**: App crash on Workflow re-run
Jira: https://jira.iguazeng.com/browse/ML-2333
Before:
After:

Fix [Workflows] App crash on Workflow re-run

---

.github/workflows/build.yaml

Same as https://github.com/mlrun/mlrun/pull/2077 just for mlrun/ui

Impl [Pkg] Support pushing to multiple registries in github actions build workflow

---

src/App.js
src/actions/workflow.js
src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js

- **UI**: Broken links redirection
Jira: https://jira.iguazeng.com/browse/ML-2349

Fix [UI] Broken links redirection

---

.github/workflows/build.yaml

Similar to https://github.com/mlrun/mlrun/pull/2101

Impl [Pkg] Enable overriding the version when triggering the build workflow

---

.github/workflows/build.yaml

Following https://github.com/mlrun/ui/pull/1329 - had a little typo there - fixing it

Fix [Pkg] Build workflow typo

---

src/components/FeatureStore/FeatureVectors/FeatureVectors.js
src/components/FeatureStore/Features/FeaturesView.js
src/utils/defaultCloseModalHandler.js

Build fails due to wrong path.
Fix #1327

Fix build fails due to wrong constants import path

---

src/api/artifacts-api.js

- **Artifacts**: View YAML is broken on artifact expand
Jira: https://jira.iguazeng.com/browse/ML-2377

Fix [Artifacts] View YAML is broken on artifact expand

---

src/components/RegisterArtifactModal/RegisterArtifactModal.js

- **Artifact**: default artifact type is empty in register artifact dialog
Jira: [ML-2400](https://jira.iguazeng.com/browse/ML-2400)
Before:   
After:

Fix [Artifact] default artifact type is empty in register artifact dialog

---

src/components/RegisterArtifactModal/RegisterArtifactModal.js
src/elements/DeployModelPopUp/DeployModelPopUp.js
src/hooks/useBlockHistory.hook.js

- **UI**: Redundant "All changes will be lost" dialog upon register dataset / artifact
Jira: [ML-2399](https://jira.iguazeng.com/browse/ML-2399)

Fix [UI] redundant 'All changes will be lost' dialog upon register dataset / artifact

---

Dockerfile

Fixes https://jira.iguazeng.com/browse/ML-2439

[Build] Fix nuclio UI URL redirection when security context is not root

---

Dockerfile

Fixes https://jira.iguazeng.com/browse/ML-2439

[Build] Fix nuclio UI URL redirection when security context is not root [1.0.x]

---

src/components/Project/ProjectOverview/ProjectOverview.util.js
src/components/RegisterArtifactModal/RegisterArtifactModal.js

- **Project Overview**: Redirect to relevant page after submitting new wizards
Jira: [ML-2446](https://jira.iguazeng.com/browse/ML-2446)

Fix [Project Overview] redirect to relevant page after submitting new wizards

---

src/components/Project/ProjectOverview/ProjectOverview.util.js

Fix [Project overview] error when submitting empty form

---

src/common/DatePicker/DatePickerView.js

Fix [UI] console error when using selectOptions

---

src/components/DetailsArtifacts/DetailsArtifactsView.js
src/components/DetailsArtifacts/detailsArtifacts.util.js

- **Artifacts**: "Show Details" for artifacts with no "latest" tag is broken and forwards to the main projects screen
Jira: https://jira.iguazeng.com/browse/ML-2477

Fix [Artifacts] "Show Details" for artifacts with no "latest" tag is broken and forwards to the main projects screen

---

src/components/Models/Models.js
src/components/Project/ProjectOverview/ProjectOverview.js
src/components/Project/ProjectOverview/ProjectOverview.util.js
src/elements/RegisterModelPopUp/RegisterModelPopUp.js

- **Project Overview**: Register model wizard (project home)
Jira: [ML-2094](https://jira.iguazeng.com/browse/ML-2094)

Impl [Project Overview] Register model wizard (project home)

---

src/utils/roundFloats.js

- **UI**: Label value is not being displayed   
https://jira.iguazeng.com/browse/ML-2490
**Fix related to:**
- **Jobs**: State column is empty in Results tab
Related to Fix: #1361 
Jira: [ML-2492](https://jira.iguazeng.com/browse/ML-2492)
Before:
After:
Before:
After:

Fix [UI] Label value is not being displayed

---

src/api/jobs-api.js
src/components/Jobs/MonitorJobs/MonitorJobs.js

- **Jobs**: 'Failed to fetch jobs' error appears on attempt to rerun job via UI
Jira: [ML-2485](https://jira.iguazeng.com/browse/ML-2485)

Fix [Jobs] 'Failed to fetch jobs' error appears on attempt to rerun job via UI

---

src/components/DetailsArtifacts/DetailsArtifacts.js

- **UI**: Blank screen with TypeError after switching between iterations with open artifact preview screen
Jira: https://jira.iguazeng.com/browse/ML-2469

Fix [UI] Blank screen with TypeError after switching between iterations with open artifact preview screen

---

src/components/DetailsArtifacts/detailsArtifacts.util.js

- **UI**: Cannot read property 'tag' of undefined" on attempt to open artifacts tab
Jira: https://jira.iguazeng.com/browse/ML-2504

Fix [UI] Cannot read property 'tag' of undefined" on attempt to open artifacts tab

---

src/elements/DetailsInfoItem/DetailsInfoItem.js

- **Models**: Missing class "details-item__data" the html for model
Jira: https://jira.iguazeng.com/browse/ML-2520

Fix [Models] Missing class "details-item__data" the html for model

---

src/components/FeatureSetsPanel/FeatureSetsPanelView.js

- **UI**: user can't use edit option for scheduler job
Jira: https://jira.iguazeng.com/browse/ML-2454

Fix [UI] User can't use edit option for scheduler job

---

.github/workflows/ci.yaml
.licenserc.json

Add a check to the CI/CD for copyright

[CI] Add copyright checker

---

src/utils/generateArtifacts.js

- **Artifacts**: Artifacts not shown in UI although present in BE response
Jira: https://jira.iguazeng.com/browse/ML-2535

Fix [Artifacts] Artifacts not shown in UI although present in BE response

---

src/common/Select/Select.js
src/components/JobsPanel/jobsPanel.util.js

- **Jobs**: User can't use edit option for scheduler job
Jira: [ML-2454](https://jira.iguazeng.com/browse/ML-2454)

Fix [Jobs] user can't use edit option for scheduler job

---

package.json
src/common/TextArea/TextArea.js
src/common/TextArea/textArea.scss
src/components/DetailsInfo/detailsInfo.scss
src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
src/components/FeatureSetsPanel/FeatureSetsPanelTitle/featureSetsPanelTitle.scss
src/components/FunctionsPanel/FunctionsPanel.js
src/components/Project/ProjectDescription/ProjectDescription.js
src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
src/elements/DetailsInfoItem/DetailsInfoItem.js
src/elements/FunctionsPanelGeneral/FunctionsPanelGeneral.js
src/elements/FunctionsPanelGeneral/FunctionsPanelGeneralView.js
src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
src/elements/RegisterModelPopUp/RegisterModelPopUp.js

- **Feature Vector**: Wrong presentation for description tooltips for long description text
Jira: https://jira.iguazeng.com/browse/ML-1522

Fix [Feature Vector] Wrong presentation for description tooltips for long description text

---

src/layout/Navbar/Navbar.utils.js
src/utils/parseUri.js

- Redirect Nuclio UI back to MLRun UI when clicking on Projects
Jira: https://jira.iguazeng.com/browse/CEML-23

Impl [UI] Redirect Nuclio UI back to MLRun UI when clicking on Projects

---

src/common/Breadcrumbs/breadcrumbs.util.js
src/components/Project/ProjectOverview/ProjectOverview.util.js
src/elements/ProjectFunctions/ProjectFunctions.js
src/utils/createConsumerGroupsContent.js

Redirect Nuclio UI back to MLRun UI when clicking on Projects
Jira: https://jira.iguazeng.com/browse/CEML-23

Impl [UI] Redirect Nuclio UI back to MLRun UI when clicking on Projects - fix

---

src/index.js

This reverts commit 0a2f5c624b3216dae3672aea5e2ebbb2207f6395.

Revert "Fix [UI] MLRun UI not accessible via `/` only via `/mlrun` (#1385)"

---

src/common/Breadcrumbs/breadcrumbs.util.js
src/components/Project/ProjectOverview/ProjectOverview.util.js
src/elements/ProjectFunctions/ProjectFunctions.js
src/layout/Navbar/Navbar.utils.js
src/utils/createConsumerGroupsContent.js
src/utils/parseUri.js

Revert "Impl [UI] Redirect Nuclio UI back to MLRun UI when clicking on Projects"

---

src/components/DetailsInfo/DetailsInfoView.js
src/utils/generateArtifacts.js

- **Models**: Blank screen after clicking on model name
Jira: https://jira.iguazeng.com/browse/ML-2563

Fix [Models] Blank screen after clicking on model name

---

src/components/DetailsInfo/DetailsInfoView.js
src/utils/generateArtifacts.js

- **Feature Store**: App crash when trying to drill down or create new set
Related to fix #1388 
Jira: https://jira.iguazeng.com/browse/ML-2567

Fix [Feature Store] App crash when trying to drill down or create new set

---

src/index.js

- **UI** MLRun UI not accessible via / only via /mlrun
Related to Mlrun community + #1395 
Jira: https://jira.iguazeng.com/browse/CEML-22 + https://jira.iguazeng.com/browse/CEML-23

Fix [UI] MLRun UI not accessible via / only via /mlrun

---

src/actions/functions.js
src/common/ReactFlow/MlReactFlow.js
src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js

- **Monitor Workflows**: Loader stuck when failed to fetch a function
Backported to `1.1.0` from #1401 
Jira: https://jira.iguazeng.com/browse/ML-2576

Fix [Monitor Workflows] Loader stuck when failed to fetch a function

---

public/index.html
src/App.js
src/components/ErrorBoundary/ErrorBoundary.js
src/index.js
src/lazyWithRetry.js
src/setupProxy.js

- **UI**: blank screen on attempt to browse Projects
Happened during testing. Error messages:
- Failed to load resource: net::ERR_FAILED
- ChunkLoadError: Loading chunk
Added lazy load handling and Error Boundaries
Jira: [ML-2437](https://jira.iguazeng.com/browse/ML-2437)

Fix [UI] blank screen on attempt to browse Projects

---

src/actions/artifacts.js
src/api/artifacts-api.js
src/components/Details/Details.js
src/components/Details/DetailsView.js
src/components/Details/details.util.js
src/components/Models/Models.js
src/components/Models/models.util.js
src/utils/generateArtifacts.js

- **Models**: Add option to edit labels for models
Backported to `1.1.1` from #1406 
Jira: https://jira.iguazeng.com/browse/ML-2565
Before:
After:

Impl [Models] Add option to edit labels for models

---

src/elements/DetailsInfoItemChip/DetailsInfoItemChip.js

- **UI**: In Feature store/Models add hover indication to labels apply check Icon
Before:
After:

Impl [UI] add hover indication to labels apply check Icon

---

src/components/Details/details.scss
src/elements/DetailsInfoItemChip/DetailsInfoItemChip.js

Impl [UI] Change apply icon in details

---

src/components/CreateJobPage/CreateJobPage.js
src/components/FunctionsPage/Functions.js
src/components/Jobs/MonitorJobs/monitorJobs.util.js

- **Functions**: Error 400 for re-runing the serving ml function
Jira: https://jira.iguazeng.com/browse/ML-2165

Fix [Jobs & Functions] Error 400 for re-runing the serving ml function

---

src/components/RegisterArtifactModal/RegisterArtifactModal.js
src/hooks/useBlockHistory.hook.js
src/hooks/useModalBlockHistory.hook.js

Refactor `useModalBlockHistory` hook used in `Register Artifact`

Impl [UI] useModalBlockHistory.hook refactoring

---

src/common/ChipCell/ChipCell.js

-  **Labels**: The 'space' key and value label should be restricted
Backported to `1.1.1` from #1412 
Jira: [ML-2649](https://jira.iguazeng.com/browse/ML-2649)

Fix [Labels] The 'space' key and value label should be restricted

---

package.json
src/elements/RegisterModelPopUp/RegisterModelPopUp.js
src/utils/convertChipsData.js

- **Models** add label validation to "Register Model"
Jira: https://jira.iguazeng.com/browse/ML-2496
After:

Impl [Models] add labels validation

---

src/components/RegisterArtifactModal/RegisterArtifactModal.js
src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
src/elements/RegisterModelPopUp/RegisterModelPopUp.js

- **UI**: Add labels to dataset and artifacts wizard
https://jira.iguazeng.com/browse/ML-2335
After:

Impl [Artifacts, Dataset] Add labels to dataset and artifacts wizard

---

src/components/RegisterArtifactModal/RegisterArtifactModal.js

- **Register Artifact**: Set form Initial values on function init. Removed `useState`

Clean [Register Artifact] set initial Values on init

---

src/actions/artifacts.js

- **Artifacts**: "Cannot read properties of undefined (reading 'extra_data')" on attempt to expand artifact
Jira: https://jira.iguazeng.com/browse/ML-2668

Fix [Artifacts] "Cannot read properties of undefined (reading 'extra_data')" on attempt to expand artifact

---

src/api/artifacts-api.js
src/api/projects-api.js

- **Artifacts**: UI to work with new Artifact REST APIs
Jira: https://jira.iguazeng.com/browse/ML-2584

Impl [Artifacts] UI to work with new Artifact REST APIs

---

src/components/Details/Details.js
src/components/Details/details.util.js
src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
src/components/DetailsRequestedFeatures/DetailsRequestedFeaturesView.js
src/components/DetailsRequestedFeatures/detailsRequestedFeatures.utils.js
src/components/FeatureStore/FeatureSets/FeatureSets.js
src/components/FeatureStore/FeatureVectors/FeatureVectors.js
src/hooks/useBlockHistory.hook.js

- **Feature Store**: Confirm dialog doesn't work properly
Jira: https://jira.iguazeng.com/browse/ML-2379

Fix [Feature Store] Confirm dialog doesn't work properly

---

src/components/DetailsInfo/detailsInfo.scss
src/elements/DetailsInfoItem/DetailsInfoItem.js

- **Feature store** add edit icon to next to an existing description
Jira: [ML-2680](https://jira.iguazeng.com/browse/ML-2680)
Before:
After:

Impl [Feature store] add edit icon to description

---

src/api/featureStore-api.js
src/components/FeatureStore/featureStore.util.js

- **Feature store**: update/delete labels
Jira: [ML-2642](https://jira.iguazeng.com/browse/ML-2642)

Fix [Feature store] update/delete labels

---

src/components/DetailsTransformations/DetailsTransformations.js

- **Feature Set**: error on attempt to open 'Feature set' 'Transformations' tab
Jira: [ML-2718](https://jira.iguazeng.com/browse/ML-2718)

Fix [Feature Set] error on attempt to open 'Feature set' 'Transformations' tab

---

src/components/Pipeline/Pipeline.js

- **Models**: UI crash when clicking on function in 'Real Time Pipelines' tab
Jira: [ML-2721](https://jira.iguazeng.com/browse/ML-2721)

Fix [Models] UI crash when clicking on function in 'Real Time Pipelines' tab

---

src/components/DetailsTransformations/DetailsTransformations.js
src/components/Pipeline/Pipeline.js

fix error length

---

src/App.js

- **Models**: "Go back" browser button does not take effect when focused on "Models" tab
Jira: https://jira.iguazeng.com/browse/ML-2739

Fix [Models] "Go back" browser button does not take effect when focused on "Models" tab

---

src/components/ProjectsPage/projects.scss
src/elements/ProjectCard/projectCard.scss

- **Projects**: unexpected project cards resizing
Jira: [ML-2734](https://jira.iguazeng.com/browse/ML-2734)

Fix [Projects] unexpected project cards resizing

---

src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
src/components/ModelsPage/Models/Models.js
src/components/ModelsPage/ModelsPage.context.js
src/components/ModelsPage/ModelsPage.js
src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
src/components/ModelsPage/modelsPage.util.js

- **Models: register model fails with 'Model failed to initiate'
Jira: [ML-2736](https://jira.iguazeng.com/browse/ML-2736)

Fix [Models] register model fails with 'Model failed to initiate'

---

src/components/Datasets/datasets.util.js
src/components/Details/details.util.js
src/components/DetailsInfo/DetailsInfoView.js
src/components/DetailsInfo/detailsInfo.scss
src/elements/DetailsInfoItem/DetailsInfoItem.js

- **Artifacts**: tagging does not work properly
Jira: https://jira.iguazeng.com/browse/ML-2726

Fix [Artifacts] tagging does not work properly

---

src/common/TargetPath/TargetPath.js
src/common/TargetPath/targetPath.util.js
src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
src/elements/RegisterModelPopUp/RegisterModelPopUp.js

- **Models**: Unnecessary option on artifact registry Target path
Depends on: https://github.com/iguazio/dashboard-react-controls/pull/74
In: [v0.0.24](https://github.com/iguazio/dashboard-react-controls/releases/tag/v0.0.24)
Jira: [ML-2731](https://jira.iguazeng.com/browse/ML-2731)

Fix [Models] Unnecessary option on artifact registry Target path

---

src/components/Datasets/Datasets.js
src/components/Files/Files.js
src/components/ModelsPage/Models/Models.js

- **UI**: Wrong navigation after deleting artifact/datasets tag
Jira: https://jira.iguazeng.com/browse/ML-2751

Fix [UI] Wrong navigation after deleting artifact/datasets tag

---

src/common/TargetPath/TargetPath.js
src/components/ModelsPage/Models/Models.js
src/components/ModelsPage/ModelsPage.context.js
src/components/ModelsPage/ModelsPage.js

- **Logic**: Fix dependecies in useEffect

Fix dependecies in useEffect

---

src/components/FunctionsPanel/FunctionsPanel.js

- **Functions**: 'Request failed with status code 404' error appears on attempt to save new ML function
Jira: [ML-2750](https://jira.iguazeng.com/browse/ML-2750)

Fix [Functions] 'Request failed with status code 404' error appears on attempt to save new ML function

---

src/App.js
src/components/Datasets/Datasets.js
src/components/Datasets/datasets.util.js
src/components/FeatureStore/FeatureSets/FeatureSets.js
src/components/FeatureStore/FeatureVectors/FeatureVectors.js
src/components/FeatureStore/Features/Features.js
src/components/Files/Files.js
src/components/Files/files.util.js
src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
src/components/ModelsPage/Models/Models.js
src/components/ModelsPage/Models/models.util.js
src/components/Table/TableHead.js
src/components/Table/TableView.js
src/components/Table/table.scss
src/elements/ArtifactsTableRow/ArtifactsTableRow.js
src/elements/FeatureStoreTableRow/FeatureStoreTableRow.js
src/elements/TableCell/TableCell.js
src/elements/TableLinkCell/TableLinkCell.js
src/elements/TableProducerCell/TableProducerCell.js
src/elements/TableTypeCell/TableTypeCell.js
src/utils/createArtifactsContent.js
src/utils/createFeatureStoreContent.js
src/utils/generateTableContent.js

- **Artifacts**: information row is missing
Jira: https://jira.iguazeng.com/browse/ML-2747

Fix [Artifacts] information row is missing

---

src/components/Datasets/datasets.util.js
src/components/Files/files.util.js
src/components/ModelsPage/Models/models.util.js
src/utils/artifacts.util.js

- **Artifacts**:  Editing tag for model causes to changing tags for all models with this tag
Jira: https://jira.iguazeng.com/browse/ML-2743

Fix [Artifacts] Editing tag for model causes to changing tags for all models with this tag

---

src/elements/FeatureStoreTableRow/FeatureStoreTableRow.js

- **Features**: Wrong presentation of expanded content
Jira: https://jira.iguazeng.com/browse/ML-2761

Fix [Features] Wrong presentation of expanded content

---

src/components/Datasets/Datasets.js
src/components/Datasets/datasets.util.js
src/components/Files/Files.js
src/components/Files/files.util.js
src/components/ModelsPage/Models/Models.js
src/components/ModelsPage/Models/models.util.js

- **Dataset/Model/Artifact**: The added tag is presented only after refresh page
Jira: https://jira.iguazeng.com/browse/ML-2777

Fix [Dataset/Model/Artifact] The added tag is presented only after refresh page

---

src/components/Details/Details.js
src/components/FeatureStore/FeatureSets/FeatureSets.js
src/components/FeatureStore/FeatureSets/FeatureSetsView.js
src/components/FeatureStore/featureStore.util.js

- **Feature Sets**: Can't edit feature sets without a tag
Jira: https://jira.iguazeng.com/browse/ML-2724

Fix [Feature Sets] Can't edit feature sets without a tag

---

package.json

- **Projects**: when clicking on Register Artifact button - the Projects screen becomes blank
Jira: [ML-2803](https://jira.iguazeng.com/browse/ML-2803)

Fix [Projects] when clicking on Register Artifact button - the Projects screen becomes blank

---

src/components/Project/ProjectOverview/ProjectOverview.util.js
src/elements/NewFunctionPopUp/NewFunctionPopUp.js

- **Project home**:  "Create New Function" and "Deploy serving function" navigates to the same dialog
Jira: [ML-2787](https://jira.iguazeng.com/browse/ML-2787)

Fix [Project home] Add runtime to function popup

---

src/common/Chip/Chip.js
src/common/ChipCell/ChipCell.js
src/common/ChipCell/ChipCellView.js
src/constants.js
src/elements/HiddenChipsBlock/HiddenChipsBlock.js
src/layout/Navbar/Navbar.js
src/layout/Navbar/Navbar.scss
src/layout/Page/Page.js
src/scss/main.scss

- **Dataset**: Trimmed tooltips of dataset labels
Jira: https://jira.iguazeng.com/browse/ML-2690
Before:
After:

Fix [UI] Trimmed tooltips of dataset labels

---

src/common/ChipInput/ChipInput.js

- **Project Setting**: page crash on adding member
Jira: [ML-2816](https://jira.iguazeng.com/browse/ML-2816)

Fix [Project Setting] page crash on adding member

---

src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js

- **Artifacts**: fix error message for duplicated tag name

Fix [Artifacts] fix error message for duplicated tag name

---

scripts/mockServer.js
src/common/Input/Input.js
src/components/Details/details.util.js
src/elements/DetailsInfoItem/DetailsInfoItem.js
tests/mockServer/mock.js

- **Artifacts**: missing input validation logic in "edit tag" dialog
Depends on: [v0.0.27](https://github.com/iguazio/dashboard-react-controls/releases/tag/v0.0.27)
Jira: https://jira.iguazeng.com/browse/ML-2828

Fix [Artifacts] missing input validation logic in "edit tag" dialog

---

src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js

- **Artifacts**: The iterations are created for adding tag
Jira: https://jira.iguazeng.com/browse/ML-2855

Fix [Artifacts] The iterations are created for adding tag

---

src/utils/createJobsContent.js

- **Jobs**: Change "Name" -> "UID"
Jira:  https://jira.iguazeng.com/browse/ML-2943

Fix [Jobs] Change "Name" -> "UID"

---

src/components/ProjectsPage/Projects.js
src/components/ProjectsPage/projectsData.js

- **Projects**: unclear error 'Failed to delete project' when user does not have enough permissions
Jira: [ML-2940](https://jira.iguazeng.com/browse/ML-2940)
Before:
After:

Fix [Projects] unclear error 'Failed to delete project' when user does not have enough permissions

---

src/components/RegisterArtifactModal/RegisterArtifactModal.js
src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
src/elements/RegisterModelModal/RegisterModelModal.js

- **UI**: Remove new target path from mode=demo after QA test
Jira: [ML-2708](https://jira.iguazeng.com/browse/ML-2708)

Impl [UI] Remove new target path from mode=demo after QA test

---

src/components/ArtifactsPreview/ArtifactsPreview.js
src/components/ArtifactsPreview/artifactsPreview.scss
src/components/DetailsPreview/DetailsPreview.js
src/elements/PreviewModal/PreviewModal.js
src/utils/generateArtifacts.js
src/utils/getArtifactPreview.js

- **Datasets**: upon log_dataset with extra_data UI "Preview" tab does not show actual data but extra_data
Jira: https://jira.iguazeng.com/browse/ML-2910

Fix [Datasets] upon log_dataset with extra_data UI "Preview" tab does not show actual data but extra_data

---

src/components/FeatureStore/FeatureSets/FeatureSets.js
src/components/FeatureStore/FeatureVectors/FeatureVectors.js
src/constants.js
src/elements/TableCell/TableCell.js
src/utils/createArtifactsContent.js
src/utils/createFeatureStoreContent.js

- **FeatureStore**: Wrong URI in the `Copy to clipboard` action
Jira: https://jira.iguazeng.com/browse/ML-2915

Fix [FeatureStore] Wrong URI in the `Copy to clipboard` action

---

src/components/AddToFeatureVectorPage/AddToFeatureVectorView.js
src/components/ConsumerGroup/ConsumerGroup.js
src/components/Datasets/DatasetsView.js
src/components/FeatureStore/FeatureSets/FeatureSetsView.js
src/components/FeatureStore/FeatureVectors/FeatureVectorsView.js
src/components/FeatureStore/Features/FeaturesView.js
src/components/Files/FilesView.js
src/components/Jobs/MonitorJobs/MonitorJobsView.js
src/components/Jobs/MonitorWorkflows/MonitorWorkflowsView.js
src/components/Jobs/ScheduledJobs/ScheduledJobsView.js
src/components/ModelsPage/ModelEndpoints/ModelEndpointsView.js
src/components/ModelsPage/Models/ModelsView.js
src/components/ModelsPage/RealTimePipelines/RealTimePipelinesView.js
src/layout/Content/Content.js
src/layout/Content/content.util.js
src/utils/getNoDataMessage.js

- **UI**: The warning "No data to show" should be augmented with the applied filter
Backported to `1.2.x` from #1499 
Jira: https://jira.iguazeng.com/browse/ML-2913
After:

Fix  [UI] The warning "No data to show" should be augmented with the applied filter

---

src/components/Datasets/Datasets.js
src/components/Files/files.util.js

- **Artifacts**: Show iterations checkbox doesn't show any additional information
Jira: https://jira.iguazeng.com/browse/ML-2939

Fix [Artifacts] Show iterations checkbox doesn't show any additional information

---

src/components/Details/details.scss

- **Jobs**: Can not refresh logs after scrolling down
Backported to `1.2.1` from #1514 
Jira: https://jira.iguazeng.com/browse/ML-2975

Fix [Jobs] can't refresh logs after scrolling down

---

src/components/CreateJobPage/CreateJobPage.js
src/components/JobsPanel/jobsPanel.util.js

- **Jobs**: The job is being created in the wrong project
Backported to `1.2.1` from #1516 
Jira: https://jira.iguazeng.com/browse/ML-2996

Fix [Jobs] The job is being created in the wrong project

---

src/elements/ProjectDataCard/ProjectDataCard.js

- **Project Monitor**: Change 'See all' -> 'See all recent'
Jira: [ML-3020](https://jira.iguazeng.com/browse/ML-3020)

Fix [Project Monitor] Change 'See all' -> 'See all recent'

---

src/utils/getNoDataMessage.js

- **UI**: The warning 'No data to show' should be augmented with the applied filter
Jira: [ML-2913](https://jira.iguazeng.com/browse/ML-2913)
Before: 
After:

Fix [UI] The warning 'No data to show' should be augmented with the applied filter

---

src/hooks/useModalBlockHistory.hook.js
src/utils/getNoDataMessage.js

- **UI**: The warning 'No data to show' should be augmented with the applied filter
Backported to `1.2.1` from #1517 
Jira: [ML-2913](https://jira.iguazeng.com/browse/ML-2913)
Before: 
After:

Fix [UI] The warning 'No data to show' should be augmented with the applied filter 1.2.x

---

src/api/artifacts-api.js
src/components/DetailsPreview/DetailsPreview.js
src/utils/createArtifactsContent.js
src/utils/createFeatureStoreContent.js
src/utils/createFunctionsContent.js
src/utils/generateModelEndpoints.js
src/utils/getArtifactPreview.js
src/utils/parseArtifacts.js
src/utils/parseFeatureSets.js
src/utils/parseFeatureVectors.js
src/utils/parseFeatures.js
src/utils/parseFunction.js

- **Dataset**: "Extra Data" appears for datasets without it
Jira: https://jira.iguazeng.com/browse/ML-2982

Fix [Dataset] "Extra Data" appears for datasets without it

---

src/components/ArtifactsPreview/ArtifactsPreviewView.js
src/components/ArtifactsPreview/artifactsPreview.scss
src/utils/createArtifactPreviewContent.js

- **Models**: Preview of model shows irrelevant json with 'listdir' to the customer
Jira: [ML-2999](https://jira.iguazeng.com/browse/ML-2999)

Fix [Models] Preview of model shows irrelevant json with 'listdir' to the customer

---

src/utils/getArtifactPreview.js

- **Artifacts**: Wrong logic for displaying preview
Jira: https://jira.iguazeng.com/browse/ML-3049

Fix [Artifacts] Wrong logic for displaying preview

---

src/components/FunctionsPage/Functions.js
src/utils/getNoDataMessage.js

- **Functions**: writes "show untagged: true" though the checkbox is not selected
Jira: https://jira.iguazeng.com/browse/ML-3053

Fix [Functions] writes "show untagged: true" though the checkbox is not selected

---

src/components/Details/DetailsView.js
src/components/Details/details.util.js
src/components/DetailsInfo/detailsInfo.util.js
src/components/Project/ProjectMonitorView.js
src/elements/PreviewModal/PreviewModal.js
src/elements/ProjectJobs/projectJobs.utils.js
src/utils/createArtifactsContent.js
src/utils/createFeatureStoreContent.js
src/utils/createFunctionsContent.js
src/utils/createJobsContent.js
src/utils/datetime.js

- **Model-endpoints**: Time is wrong in model endpoint
Jira: https://jira.iguazeng.com/browse/ML-2984

Fix [Model-endpoints] Time is wrong in model endpoint

---

src/components/ModelsPage/ModelsPage.js
src/components/Project/ProjectOverview/ProjectOverview.util.js
src/components/Project/project.utils.js

- **UI**: Hide Register model in UI [until not all parameters of the model enabled to register]
Jira: [ML-3000](https://jira.iguazeng.com/browse/ML-3000)

Fix [UI] Hide Register model in UI [until not all parameters of the model enabled to register]

---

src/layout/Header/Header.js
src/layout/Header/header.scss

- **UI** Change MLRun header
Follow up to #1496 
Jira: [ML-3044](https://jira.iguazeng.com/browse/ML-3044)
Before:
After:

Impl [UI] Change MLRun header

---

src/elements/DeployModelPopUp/DeployModelPopUp.js

- **Models**: Deploy Model doesn't work
Jira: https://jira.iguazeng.com/browse/ML-3055
Before:
After:

Fix [Models] Deploy Model doesn't work

---

src/App.js
src/layout/Navbar/Navbar.js
src/layout/Navbar/Navbar.utils.js

- **Project home**: Remove page from  mode
Jira: [ML-3087](https://jira.iguazeng.com/browse/ML-3087)

Impl [Project home] remove page from `demo`  mode

---

src/utils/parseFeatureVectors.js
src/utils/parseFeatures.js

- **Feature Vector**: UI crash when selecting feature vector
Jira: https://jira.iguazeng.com/browse/ML-3079

Fix [UI] UI crash when selecting feature vector

---

src/utils/parseFeatureVectors.js
src/utils/parseFeatures.js

- **Feature Vector**: UI crash when selecting feature vector
Backported to `1.2.1` from #1549 
Jira: https://jira.iguazeng.com/browse/ML-3079

Fix [UI] UI crash when selecting feature vector `1.2.1`

---

src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js

- **Artifacts:** Unnecessary confirm dialog
Jira: https://jira.iguazeng.com/browse/ML-3065

Fix [Artifacts] Unnecessary confirm dialog

---

src/elements/ProjectDataCard/ProjectDataCard.js

- **Project Monitor**: Change 'See all' -> 'See all recent' 
Jira: [ML-3091](https://jira.iguazeng.com/browse/ML-3091)

Fix [Project Monitor] Change 'See all recent' -> 'See all'

---

package.json
src/components/RegisterArtifactModal/RegisterArtifactModal.js
src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
src/elements/RegisterModelModal/RegisterModelModal.js
src/utils/artifacts.util.js

- **Artifacts**: Missing validation for an existing artifact name
- Model/Artifact creation with same name and tag to Artifact/Model removing tag
Jira: [ML-3121](https://jira.iguazeng.com/browse/ML-3121)
Before: 
After:

Fix [Artifacts] Missing validation for an existing artifact name

---

src/components/ArtifactsPreview/ArtifactsPreviewView.js
src/components/ArtifactsPreview/artifactsPreview.scss
src/utils/createArtifactPreviewContent.js
src/utils/getArtifactPreview.js

- **Artifacts**: Bytes Artifact fails to show in "Preview" tab
Jira: [ML-3074](https://jira.iguazeng.com/browse/ML-3074)
After:

Fix [UI] Bytes Artifact fails to show in "Preview" tab

---

src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js

- **Jobs and Workflows**: K8s Pod Info Not Shown in Workflow View
Jira: https://jira.iguazeng.com/browse/ML-3117
After:

Fix [UI] K8s Pod Info Not Shown in Workflow View

---

src/components/FilterMenu/FilterMenu.js
src/components/Jobs/MonitorJobs/MonitorJobs.js
src/components/ModelsPage/RealTimePipelines/RealTimePipelinesView.js

- **General** : The input label overlaps the placeholder
Jira: https://jira.iguazeng.com/browse/ML-3174

Fix [General] The input label overlaps the placeholder

---

src/elements/FunctionsTableRow/FunctionsTableRow.js
src/utils/createFunctionsContent.js

- **Functions**: Retain selected tab on switching items
Jira:  https://jira.iguazeng.com/browse/ML-3183

Fix [Functions] Retain selected tab on switching items

---

src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js

- **CE** Align default paths in the jobs
Jira: https://jira.iguazeng.com/browse/CEML-74
After:

Fix [General] Align default paths in the jobs for CE

---

src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js

- **CE** Align default paths in the jobs
Backported to `1.2.1` from #1582 
Jira: https://jira.iguazeng.com/browse/CEML-74
After:

Fix [General] Align default paths in the jobs for CE `1.2.1`

---

src/common/TagFilter/TagFilter.js

- **Artifacts**: typing in 'Version tag:' does not take effect
Jira: https://jira.iguazeng.com/browse/ML-3188

Fix [UI] typing in 'Version tag' does not take effect

---

src/components/Project/ProjectMonitor.js
src/components/Project/ProjectMonitorView.js

- **Project Monitor**: new layout changes in `demo mode`
Jira: [ML-3253](https://jira.iguazeng.com/browse/ML-3253)

Fix [Project Monitor] new layout changes in demo mode

---

src/components/Project/ProjectAction/ProjectAction.scss
src/components/Project/ProjectOverview/ProjectOverview.scss
src/components/Project/ProjectOverview/ProjectOverview.util.js

- **Project Home**: Update project home description + tooltips
Jira: [ML-3231](https://jira.iguazeng.com/browse/ML-3231), [ML-2814](https://jira.iguazeng.com/browse/ML-2814), [ML-3238](https://jira.iguazeng.com/browse/ML-3238)
After:

Impl [Project Home] Update project home description + tooltips

---

src/components/ModelsPage/ModelsPage.js
src/components/Project/ProjectOverview/ProjectOverview.util.js
src/components/Project/project.utils.js

- **UI**: Hide Display Register Model in 1.3.0
Jira: [ML-3186](https://jira.iguazeng.com/browse/ML-3186)

Impl [UI] Hide Display Register Model in 1.3.0

---

src/utils/createArtifactsContent.js

- **Models**: Adjust the Average Latency calculation in model endpoints tab
Jira: [ML-3278](https://jira.iguazeng.com/browse/ML-3278)
Before:
After:

Impl [Models] Adjust the Average Latency calculation in model endpoints tab

---

src/common/ReactFlow/MlReactFlow.js

- **Workflow report**: Pipeline graph is override by the Overview page
Jira: https://jira.iguazeng.com/browse/ML-3259

Fix [Workflow report] Pipeline graph is override by the Overview page

---

src/actions/functions.js
src/common/Chip/Chip.js
src/components/FilterMenuModal/FilterMenuModal.js
src/components/FilterMenuModal/HubCategoriesFilter/HubCategoriesFilter.js
src/components/FilterMenuModal/HubCategoriesFilter/hubCategoriesFilter.scss
src/components/FilterMenuModal/filterMenuModal.scss
src/components/JobWizard/JobWizard.js
src/components/JobWizard/JobWizard.util.js
src/components/JobWizard/JobWizardSteps/JobWizardAdvanced/JobWizardAdvanced.js
src/components/JobWizard/JobWizardSteps/JobWizardDataInputs/JobWizardDataInputs.js
src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/jobWizardFunctionSelection.scss
src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/jobWizardFunctionSelection.util.js
src/components/JobWizard/JobWizardSteps/JobWizardJobDetails/JobWizardJobDetails.js
src/components/JobWizard/JobWizardSteps/JobWizardParameters/JobWizardParameters.js
src/components/Jobs/jobs.util.js
src/constants.js
src/elements/CreateJobCardTemplate/createJobCardTemplate.scss
src/elements/FunctionCardTemplate/FunctionCardTemplate.js
src/elements/FunctionCardTemplate/functionCardTemplate.scss
src/reducers/filtersReducer.js
src/reducers/functionReducer.js
src/scss/main.scss
src/utils/generateTemplatesCategories.js

- **Job Wizard**: Batch run changes
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/111
Jira: https://jira.iguazeng.com/browse/ML-2815

Impl [Job Wizard] Batch run changes

---

src/components/DetailsPreview/DetailsPreview.js
src/components/ModelsPage/Models/models.util.js

- **Models**: Unnecessary preview tab for register model
Jira: [ML-2867](https://jira.iguazeng.com/browse/ML-2867)
Before:
After:

Fix [Models] Unnecessary preview tab for register model

---

src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
src/components/Workflow/Workflow.js
src/constants.js

- **Monitor Workflows**: Page crashes on selecting the job in the list view
Jira: https://jira.iguazeng.com/browse/ML-3310

Fix [Monitor Workflows] Page crashes on selecting the job in the list view

---

src/elements/FunctionsTableRow/FunctionsTableRow.js

- **Functions**: Quick links hidden on row expand
Jira: https://jira.iguazeng.com/browse/ML-3325

Fix [Functions] Quick links hidden on row expand

---

src/components/Project/ProjectOverview/ProjectOverview.util.js

- **Project home**: The tooltips description has been cut
Jira: [ML-3371](https://jira.iguazeng.com/browse/ML-3371)
Before:
After:

Fix [Project home] The tooltips description has been cut

---

src/api/app-api.js
src/reducers/appReducer.js

- **UI**: Project screen shows empty list after an upgrade
Backported to `1.2.x` from #1611 
Jira: https://jira.iguazeng.com/browse/ML-3287

Fix [UI] Project screen shows empty list after an upgrade `1.2.x`

---

src/api/app-api.js
src/reducers/appReducer.js

- **UI**: Project screen shows empty list after an upgrade
Jira: https://jira.iguazeng.com/browse/ML-3287

Fix [UI] Project screen shows empty list after an upgrade

---

src/components/FilterMenu/filterMenu.settings.js
src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js

- **Monitor Workflows**: Filtering by status Error does not work for workflows in Failed state
Jira: https://jira.iguazeng.com/browse/ML-3140

Fix [Monitor Workflows] Filtering by status Error does not work for workflows in Failed state

---

src/components/Table/table.scss

- **Feature Store**: unable to add features in 'Add to feature vector' dialog
Jira: [ML-3401](https://jira.iguazeng.com/browse/ML-3401)

Fix [Feature Store] unable to add features in 'Add to feature vector' dialog

---

src/actions/projects.js
src/elements/ProjectStatisticsCounter/ProjectStatisticsCounter.js
src/utils/parseSummaryData.js

- **UI**: Support 'None' in project summaries response counters
Jira: [ML-3365](https://jira.iguazeng.com/browse/ML-3365)
Related to: [ML-3349](https://jira.iguazeng.com/browse/ML-3349)

Impl [UI] Support 'None' in project summaries response counters

---

src/components/ProjectSettings/ProjectSettings.js

- **Project Setting**: Cannot add members to project
Jira: https://jira.iguazeng.com/browse/ML-3316

Fix [Settings] Cannot add members to project

---

src/components/Jobs/Jobs.js
src/components/Jobs/MonitorJobs/MonitorJobs.js
src/constants.js

- **Jobs workflow**: Back and Close buttons don't work when ui is opened from Jupyter link
Jira: https://jira.iguazeng.com/browse/ML-3388

Fix [Jobs workflow] Back and Close buttons don't work when ui is opened from Jupyter link

---

src/common/ReactFlow/mlReactFlow.util.js
src/components/ArtifactsPreview/ArtifactsPreviewView.js
src/components/Details/details.util.js
src/components/DetailsResults/DetailsResults.js
src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
src/components/ModelsPage/Models/Models.js
src/components/Table/Table.js
src/components/Table/TableHead.js
src/components/Table/TableView.js
src/components/Workflow/JobsFunctionsTableRow/JobsFunctionsTableRow.js
src/components/Workflow/Workflow.js
src/components/Workflow/workflow.util.js
src/elements/TableCell/TableCell.js
src/hooks/useSortTable.hook.js
src/utils/createJobsContent.js
src/utils/generateTableContent.js
src/utils/getUniqueIdentifier.js
src/utils/parseJob.js

- **Monitor Workflow**: Create new table row view for Run and Deploy
Jira: [ML-3399](https://jira.iguazeng.com/browse/ML-3399)
After:

Impl [Monitor Workflow] Create new table row view for Run and Deploy

---

src/actions/workflow.js
src/api/workflow-api.js
src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js

- **Monitor Workflows** unable to open workflow graph/details
Jira: https://jira.iguazeng.com/browse/ML-3406

Fix [Monitor Workflows] unable to open workflow graph/details

---

src/components/DetailsArtifacts/DetailsArtifactsView.js

- **Monitor Workflows**: Different artifact name in the list and in the preview screen
Jira: https://jira.iguazeng.com/browse/ML-3261

Fix [Workflows] Different artifact name in the list and in the preview screen

---

src/components/Project/ProjectOverview/ProjectOverview.util.js

- **Project Home**: incorrect label names
Jira: https://jira.iguazeng.com/browse/ML-3433
After:

Fix [Project Home] incorrect label names

---

src/components/CreateJobPage/CreateJobPage.js
src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
src/components/Jobs/MonitorJobs/monitorJobs.util.js
src/components/Jobs/jobs.util.js

https://jira.iguazeng.com/browse/ML-1391

Fix [Monitor Jobs] The job with `handler` kind has rerun option

---

src/elements/MembersPopUp/MembersPopUp.js

- **Project Settings**: Duplicated keys error when adding same name members
Jira: [ML-3428](https://jira.iguazeng.com/browse/ML-3428)

Fix [Project Settings] Duplicated keys error when adding same name members

---

src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
src/components/Workflow/Workflow.js
src/components/Workflow/workflow.util.js
src/constants.js

- **Workflows**: deploy step is not clickable in the workflow
Jira: https://jira.iguazeng.com/browse/ML-2974

Fix [Workflows] deploy step is not clickable in the workflow

---

src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
src/components/Datasets/Datasets.js
src/components/FeatureStore/FeatureSets/FeatureSets.js
src/components/FeatureStore/FeatureVectors/FeatureVectors.js
src/components/FeatureStore/Features/Features.js
src/components/Files/Files.js
src/components/FunctionsPage/Functions.js
src/components/ModelsPage/Models/Models.js
src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
src/components/Table/Table.js
src/elements/FunctionsTableRow/FunctionsTableRow.js
src/hooks/groupContent.hook.js
src/layout/Content/Content.js
src/utils/generateGroupLatestItem.js

- **Functions**: The function with not latest tag is presented on initialization
Jira: https://jira.iguazeng.com/browse/ML-3422

Fix [Functions] The function with not latest tag is presented on initialization

---

src/components/JobWizard/JobWizard.util.js

- **Jobs**: MLRunNotFoundError on job submit via UI from "saved" function
Jira: https://jira.iguazeng.com/browse/ML-65

Fix [Jobs] MLRunNotFoundError on job submit via UI from "saved" function

---

src/components/Workflow/Workflow.js

- **Workflows**: Clicking on a pipeline graph step does not open details
Jira: https://jira.iguazeng.com/browse/ML-2979

Fix [Workflows] Clicking on a pipeline graph step does not open details

---

src/components/DetailsArtifacts/DetailsArtifacts.js

- **Jobs**: Hyper params run does not present artifacts iteration
Jira: https://jira.iguazeng.com/browse/ML-3389

Fix [Jobs] Hyper params run does not present artifacts iteration

---

src/components/DetailsArtifacts/DetailsArtifactsView.js

- **Jobs**: Artifacts name aren't displayed
Jira: https://jira.iguazeng.com/browse/ML-3491

Fix [Jobs] Artifacts name aren't displayed

---

src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/jobWizardFunctionSelection.scss
src/elements/FunctionCardTemplate/FunctionCardTemplate.js
src/elements/FunctionCardTemplate/functionCardTemplate.scss

- **Batch Run**: Align function selection by Figma
Jira: [ML-3475](https://jira.iguazeng.com/browse/ML-3475)
Before:
After:

Impl [Batch Run] Align function selection by Figma

---

src/components/FeatureStore/FeatureVectors/FeatureVectors.js

- **Feature Vectors**: Duplicated items appearing after applying changes on Details pane Requested Features tab.
Jira: https://jira.iguazeng.com/browse/ML-3452

Fix [Feature Vectors] Duplicated items appearing after applying changes on Details pane

---

src/common/Chip/Chip.js

- **Chips**: In the table chips wrap on the second row
Jira: https://jira.iguazeng.com/browse/ML-3494

Fix [Chips] In the table chips wrap on the second row

---

src/components/Table/table.scss
src/utils/createFeatureStoreContent.js

- **Feature Sets**: align targets header and fix icons displaying
Jira: https://jira.iguazeng.com/browse/ML-3514

Fix [Feature store] misaligned headers in "Feature sets" screen

---

src/elements/FormResourcesUnits/formResourcesUnits.util.js

- **Jobs**: UI fails on attempt to re-run job
Jira: https://jira.iguazeng.com/browse/ML-3517

Fix [Jobs] UI fails on attempt to re-run job

---

src/elements/DeployModelPopUp/DeployModelPopUp.js
src/elements/DeployModelPopUp/deployModelPopUp.scss

- **Models**: Prevent deploy model option for non-serving function
Jira: https://jira.iguazeng.com/browse/ML-2723

Fix [Models] Prevent deploy model option for non-serving function

---

src/components/Table/table.scss
src/elements/TableCell/TableCell.js
src/utils/createFeatureStoreContent.js

- **Feature Sets**: spacing between icon
Jira: https://jira.iguazeng.com/browse/ML-3514
After:

Fix [Feature Sets] spacing between icons

---

src/components/ModelsPage/Models/models.util.js
src/utils/convertChipsData.js

- **Models**: Apply changes button isn't clickable
Jira: https://jira.iguazeng.com/browse/ML-3531

Fix [Models] Apply changes button isn't clickable

---

src/common/ProjectDetailsHeader/ProjectDetailsHeader.js
src/common/ProjectDetailsHeader/ProjectDetailsHeader.scss
src/components/Project/ProjectOverview/ProjectOverview.scss

- **Project Overview**: Fix UI view in smaller resolutions
Jira: [ML-3538](https://jira.iguazeng.com/browse/ML-3538)
Before: 
After:

Fix [Project Overview] Fix UI view in smaller resolutions

---

src/reducers/notificationReducer.js

Fixed an issue that appeared after this PR: https://github.com/mlrun/ui/pull/1645

Fix [Build] Fixed an error during project build

---

src/utils/createArtifactsContent.js

Revert #1596 
Depends on: https://github.com/mlrun/mlrun/pull/2685

Revert [Models] Adjust the Average Latency calculation in model endpoints tab

---

src/components/Details/Details.js
src/elements/TableCell/TableCell.js

- **Feature set**: Details loop of for unsaved changes warning
Jira: https://jira.iguazeng.com/browse/ML-3556

Fix [Details] loop of for unsaved changes warning

---

src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js

- **Feature set**: Wrong default path for offline target 
Jira: https://jira.iguazeng.com/browse/ML-3554

Fix [Feature set] Wrong default path for offline target

---

src/components/Details/details.util.js

- **Feature Set**: Unable to update description
Jira: https://jira.iguazeng.com/browse/ML-3576

Fix [Feature Set] unable to update description

---

src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
src/reducers/featureStoreReducer.js

- **Feature set**: Wrong default path for offline partition target
Jira: https://jira.iguazeng.com/browse/ML-3570

Fix [Feature set] Wrong default path for offline partition target

---

src/components/DetailsInfo/DetailsInfo.js
src/elements/DetailsInfoItem/DetailsInfoItem.js

- **Details**: "Apply changes" button unexpectedly becomes disabled
Jira: https://jira.iguazeng.com/browse/ML-3581

Fix [Details] "Apply changes" button unexpectedly becomes disabled

---

src/actions/featureStore.js
src/actions/functions.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
src/components/FunctionsPanel/FunctionsPanel.js
src/components/JobWizard/JobWizard.util.js
src/components/JobWizard/JobWizardSteps/JobWizardResources/JobWizardResources.js
src/components/JobsPanel/jobsPanel.util.js
src/elements/FunctionsPanelCode/FunctionsPanelCode.js
src/elements/FunctionsPanelResources/FunctionsPanelResources.js
src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
src/layout/Page/Page.js
src/reducers/appReducer.js
src/utils/getPreemptionMode.js

- **General**: "Something went wrong" displayed on attempt to click "Create feature set" from Project home"
Depends On: [v0.0.38](https://github.com/iguazio/dashboard-react-controls/releases/tag/v0.0.38)
Jira: https://jira.iguazeng.com/browse/ML-3465
Result:

Fix [General] "Something went wrong" displayed on attempt to click "Create feature set" from Project home

---

src/utils/getNoDataMessage.js

- **Workflows**: Change "Jobs" -> "Workflows" in UI
Jira: https://jira.iguazeng.com/browse/ML-3590
After:

Fix [Workflows] Change "Jobs" -> "Workflows" in UI

---

src/layout/Page/Page.js
src/reducers/appReducer.js

- **UI** frontendSpec failed pop-up keeps rendering
Related to: #1657 
Jira: https://jira.iguazeng.com/browse/ML-3591

Fix [UI] frontendSpec failed pop-up keeps rendering

---

src/components/Jobs/Jobs.js
src/components/Jobs/jobs.util.js
src/components/Project/ProjectOverview/ProjectOverview.util.js
src/components/Project/project.utils.js

- **Jobs**: Change 'Batch run" to 'Create Job' in 1.3
Jira: https://jira.iguazeng.com/browse/ML-3606

Fix [Jobs] change 'Batch run" to 'New Job' in 1.3

---

src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js

- **Feature set**: Discard button for edit path doesn't work as expected
Jira: https://jira.iguazeng.com/browse/ML-3600

Fix [Feature set] Discard button for edit path doesn't work as expected

---

src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js

- **Feature set**: Wrong default path for offline target
Jira: https://jira.iguazeng.com/browse/ML-3554

Fix [Feature set] Wrong default path for offline target (fix)

---

src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js

- **Feature Set**: Change The target path for partition parquet tooltip
Jira: https://jira.iguazeng.com/browse/ML-3614
Aftre:

Fix [Feature Set] Change The target path for partition parquet tooltip

---

src/components/Jobs/MonitorJobs/MonitorJobs.js
src/components/Jobs/MonitorJobs/monitorJobs.util.js
src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js

- **Jobs**: Change 'Batch run" to 'New Job' in 1.3
Related to: #1663 
Jira: https://jira.iguazeng.com/browse/ML-3606

Fix [Jobs] change 'Batch run" to 'New Job' in 1.3 (fix)

---

src/components/DetailsPods/DetailsPods.js
src/components/DetailsPods/detailsPods.scss
src/utils/generatePods.js

- **Jobs:** Empty string for pod status in case the status isn't Pending
Jira: https://jira.iguazeng.com/browse/ML-511
After:

Impl [Jobs] Empty string for pod status in case the status isn't Pending

---

src/components/Project/ProjectMonitor.js
src/components/Project/ProjectMonitorView.js

- **Project Monitor:** remove "Project Monitoring" layout from demo mode
Jira: https://jira.iguazeng.com/browse/ML-3262
After:

Impl [Project Monitor] remove "Project Monitoring" layout change from demo mode

---

src/components/DetailsStatistics/detailsStatistics.util.js

- **Feature Sets**: Add 50th percentile (median) to stats
Jira: https://jira.iguazeng.com/browse/ML-3177
After:

Impl [UI] Add 50th percentile (median) to stats

---

src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js

- **Feature Sets Panel**: Target path for partition parquet should be taken as Folder
Jira: https://jira.iguazeng.com/browse/ML-3619
After:

Fix [Feature Set] Target path for partition parquet should be taken as Folder

---

src/reducers/projectReducer.js

- **Project settings**: "Something went wrong" during project creation
Jira: https://jira.iguazeng.com/browse/ML-3694

Fix [Project settings] "Something went wrong" during project creation

---

src/api/artifacts-api.js
src/common/TagFilter/TagFilter.js
src/components/Datasets/Datasets.js
src/components/Datasets/datasets.util.js
src/components/Files/Files.js
src/components/Files/files.util.js
src/components/FilterMenu/FilterMenu.js
src/components/ModelsPage/Models/Models.js
src/components/ModelsPage/Models/models.util.js
src/components/ModelsPage/ModelsPage.context.js
src/elements/FeatureStoreTableRow/FeatureStoreTableRow.js
src/hooks/useGetTagOptions.hook.js
src/reducers/artifactsReducer.js
src/reducers/filtersReducer.js
src/utils/artifacts.util.js
tests/mockServer/mock.js

- **UI**: Multiple filtering options
Jira: https://jira.iguazeng.com/browse/ML-2856

Fix [Artifacts] Multiple filtering options

---

src/common/Input/Input.js

- **UI**: Input validation rules weird behavior
Depends On: [v0.0.39](https://github.com/iguazio/dashboard-react-controls/releases/tag/v0.0.39)
Jira: https://jira.iguazeng.com/browse/ML-3681

Fix [General] Input validation rules weird behavior

---

src/components/FilterMenuModal/FilterMenuModal.js
src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/jobWizardFunctionSelection.scss

- **Batch Run**: UI minor fix to DD component
Depends On: [v0.0.39](https://github.com/iguazio/dashboard-react-controls/releases/tag/v0.0.39)
Jira: https://jira.iguazeng.com/browse/ML-3476

Fix [Batch Run] UI minor fix

---

src/common/CopyToClipboard/CopyToClipboard.js
src/components/DetailsArtifacts/DetailsArtifactsView.js
src/components/DetailsInfo/detailsInfo.scss
src/elements/DetailsInfoItem/DetailsInfoItem.js
src/elements/TableCell/TableCell.js
src/utils/createArtifactsContent.js
src/utils/createFeatureStoreContent.js

- **UI**: Add notification when copy to clipboard
Jira: [ML-3712](https://jira.iguazeng.com/browse/ML-3712)
After:

Impl [UI] Add notification when copy to clipboard

---

.github/workflows/build.yaml

(cherry picked from commit e88745d20800d79978c4ec6eea7918d08a5475b5)

uncomment side branches from build flow (#1694)

---

src/common/TargetPath/TargetPath.js
src/common/TargetPath/targetPath.util.js
src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.util.js
src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
src/elements/EditableDataInputsRow/EditableDataInputsRow.js
src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js
src/utils/panelPathScheme.js

- **Jobs**, **Feature sets**: Add "store://datasets/" format as an input to the function
Jira: https://jira.iguazeng.com/browse/ML-3635

Fix [Jobs] [Feature sets] UI should get "store://datasets/" format as an input to the function

---

src/common/Download/Download.js
src/common/Download/download.scss
src/components/Datasets/Datasets.js
src/components/Datasets/datasets.util.js
src/components/Files/Files.js
src/components/Files/files.util.js
src/components/ModelsPage/Models/Models.js
src/components/ModelsPage/Models/models.util.js
src/components/Table/Table.js
src/components/Table/table.scss
src/elements/TableCell/TableCell.js
src/utils/createArtifactsContent.js
src/utils/generateTableContent.js

- **Artifacts**: Disable preview and download buttons for not allowed prefixes
Backported to `1.3.x` from #1699 
Jira: https://jira.iguazeng.com/browse/ML-3596

Fix [Artifacts] Disable `preview` and `download` buttons for not allowed prefixes `1.3.x`

---

src/common/CopyToClipboard/CopyToClipboard.js
src/common/Download/Download.js
src/common/Download/download.scss
src/components/Datasets/Datasets.js
src/components/Datasets/datasets.util.js
src/components/Files/Files.js
src/components/Files/files.util.js
src/components/ModelsPage/Models/Models.js
src/components/ModelsPage/Models/models.util.js
src/components/Table/Table.js
src/components/Table/table.scss
src/elements/TableCell/TableCell.js
src/utils/createArtifactsContent.js
src/utils/generateTableContent.js

- **Artifacts**: Disable preview and download buttons for not allowed prefixes
Jira: https://jira.iguazeng.com/browse/ML-3596

Fix [Artifacts] Disable `preview` and `download` buttons for not allowed prefixes

---

src/components/Details/DetailsHeader/DetailsHeader.js
src/components/Jobs/MonitorJobs/MonitorJobs.js
src/components/Jobs/MonitorJobs/monitorJobs.util.js

- **Jobs and workflows:** Add Button in Job's details view to Grafana
Jira: [ML-3549](https://jira.iguazeng.com/browse/ML-3549)
Before:
After:

Impl [Jobs and workflows] Add Button in Job's details view to Grafana

---

src/actions/projects.js
src/api/projects-api.js
src/common/ActionsMenu/ActionsMenu.js
src/components/ProjectsPage/Projects.js
src/components/ProjectsPage/ProjectsView.js
src/components/ProjectsPage/projectsData.js
src/elements/ActionMenuItem/ActionsMenuItem.js
src/elements/ContentMenu/contentMenu.scss

- **Projects**: Projects screen may explode the system
Backported to `1.2.x` from #1714 
Fix: Added new param to `projects` request
Jira: https://jira.iguazeng.com/browse/ML-3798

Fix [Projects] Projects screen may explode the system `1.2.x`

---

src/actions/projects.js
src/api/projects-api.js
src/common/ActionsMenu/ActionsMenu.js
src/components/ProjectsPage/Projects.js
src/components/ProjectsPage/ProjectsView.js
src/components/ProjectsPage/projectsData.js
src/elements/ActionMenuItem/ActionsMenuItem.js

- **Projects**: Projects screen may explode the system
Backported to `1.3.x` from #1714 
Fix: Added new param to `projects` request
Jira: https://jira.iguazeng.com/browse/ML-3798

Fix [Projects] Projects screen may explode the system

---

src/actions/projects.js
src/api/projects-api.js
src/common/ActionsMenu/ActionsMenu.js
src/components/ProjectsPage/Projects.js
src/components/ProjectsPage/ProjectsView.js
src/components/ProjectsPage/projectsData.js
src/elements/ActionMenuItem/ActionsMenuItem.js

- **Projects**: Projects screen may explode the system
Backported to `1.3.x` from #1714 
Fix: Added new param to `projects` request
Jira: https://jira.iguazeng.com/browse/ML-3798

Fix [Projects] Projects screen may explode the system `1.3.x`

---

src/components/ProjectSettings/projectSettings.scss

- **Project settings**: Project setting screen does not displayed properly
Jira: [ML-3801](https://jira.iguazeng.com/browse/ML-3801)

Fix [Project settings] Project setting screen does not displayed properly `1.2.2`

---

src/common/TagFilter/TagFilter.js

- **Feature store**: error when selecting a version tag
Jira: [ML-3770](https://jira.iguazeng.com/browse/ML-3770)

Fix [Feature store] error when selecting a version tag

---

src/components/Details/Details.js
src/elements/DetailsInfoItemChip/DetailsInfoItemChip.js

- **Feature set**: Not saved labels disappear without warning after switch to another tab
Jira: https://jira.iguazeng.com/browse/ML-3567

Fix [Feature set] Not saved labels disappear without warning after switch to another tab

---

src/components/JobWizard/JobWizard.js
src/components/JobWizard/JobWizardSteps/JobWizardParameters/JobWizardParameters.js
src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
src/components/Project/ProjectOverview/ProjectOverview.util.js

- **Batch Inference**: New UI
Jira: https://jira.iguazeng.com/browse/ML-2811

Impl [Batch Inference] New UI

---

src/components/Table/table.scss
src/utils/createArtifactsContent.js

- **Models**: UI crash on attempt to open Models screen
Backported to `1.3.x` from #1708 
Jira: [ML-3780](https://jira.iguazeng.com/browse/ML-3780)

Fix [Models] UI crash on attempt to open Models screen `1.3.x`

---

src/components/Table/table.scss
src/utils/createArtifactPreviewContent.js
src/utils/createArtifactsContent.js

- **Models**: UI crash on attempt to open Models screen
Jira: [ML-3780](https://jira.iguazeng.com/browse/ML-3780)

Fix [Models] UI crash on attempt to open Models screen

---

src/components/ArtifactsPreview/ArtifactsPreviewController.js
src/components/ArtifactsPreview/artifactsPreviewController.scss
src/components/Details/DetailsTabsContent/DetailsTabsContent.js
src/components/Details/details.util.js
src/components/DetailsArtifacts/DetailsArtifacts.js
src/components/DetailsArtifacts/DetailsArtifactsView.js
src/components/DetailsArtifacts/detailsArtifacts.scss
src/components/DetailsInputs/DetailsInputs.js
src/components/DetailsInputs/detailsInputs.scss

- **Jobs**: Change Input (under jobs) to be a link
Jira: https://jira.iguazeng.com/browse/ML-748
After:

Impl [Jobs] Change Input (under jobs) to be a link

---

src/scss/main.scss

- **Table**: selected item bg color

Fix [Table] selected item bg color

---

src/components/DetailsResults/DetailsResults.js

- **Table**: missing table body in jobs results

Fix [Table] missing table body in jobs results

---

src/utils/object.js

- **Jobs and Workflows**: incorrect boolean chips view
Jira: https://jira.iguazeng.com/browse/ML-3842
After:

Fix [Jobs and Workflows] incorrect boolean chips view

---

src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
src/components/FeatureStore/Features/FeaturesView.js

- **Feature store:** add vector panel
Jira https://jira.iguazeng.com/browse/ML-3822
After:

Fix [Feature store] add vector panel

---

src/components/Jobs/jobs.util.js
src/components/JobsPanel/JobsPanel.js
src/components/JobsPanel/jobsPanel.util.js
src/components/JobsPanelParameters/JobsPanelParameters.js
src/components/JobsPanelParameters/jobsPanelParameters.util.js
src/reducers/jobReducer.js
src/utils/parseJob.js

- **Jobs**: Add new parameters for the job creation
Jira: https://jira.iguazeng.com/browse/ML-3872

Fix [Jobs] Add new parameters for the job creation

---

src/components/Details/details.scss
src/components/DetailsInfo/detailsInfo.scss
src/components/DetailsRequestedFeatures/detailsRequestedFeatures.scss
src/components/Pipeline/PipelineView.js
src/components/Pipeline/pipeline.scss
src/elements/TableLinkCell/TableLinkCell.js
src/elements/TableLinkCell/tableLinkCell.scss
src/elements/TableProducerCell/TableProducerCell.js
src/scss/main.scss

- **UI**: Firefox table view
- Artifacts, Feature store table view in firefox
- Removed scroll when editing a label in "Feature store" details view

Fix [UI] Firefox table view

---

src/common/CheckBox/CheckBox.js
src/common/CheckBox/checkBox.scss
src/components/FeatureSetsPanel/FeatureSetsPanel.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
src/components/FeatureSetsPanel/featureSetPanel.util.js

- **UI**:  Feature set register
- "Offline" and "External offline" targets should be grayed out when "passthrough" is checked
Jira: [ML-3176](https://jira.iguazeng.com/browse/ML-3176)

Impl [UI] Feature set register

---

src/hooks/yaml.hook.js

- **Models**: UI crash on attempt to view yaml
Jira: https://jira.iguazeng.com/browse/ML-3906

Fix [Models] UI crash on attempt to view yaml

---

src/common/DatePicker/DatePickerView.js
src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FilterParameters.js
src/components/FeatureSetsPanel/featureSetPanel.util.js
src/components/FilterMenu/filterMenu.scss

- **Feature set**: Missing validation : End_time > Start_time
Jira: [ML-3844](https://jira.iguazeng.com/browse/ML-3844)
Before:
After:

Fix [Feature set] Missing validation : End_time > Start_time

---

src/App.js
src/layout/Navbar/Navbar.js
src/reducers/appReducer.js
src/utils/localStorageService.js

- **UI**: Hide Mlrun header in Dashboard
- Fix `localStorageService.getStorageValue` 
Jira: [ML-3909](https://jira.iguazeng.com/browse/ML-3909)

Fix [UI] Hide Mlrun header in Dashboard

---

src/api/functions-api.js
src/api/projects-api.js
src/common/DatePicker/DatePickerView.js
src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FilterParameters.js
src/components/FeatureSetsPanel/featureSetPanel.util.js

UI needs to update its request to the following endpoints :
`LIST`: change from `/funcs` -> to  `/projects/{project-name}/functions` ( note that you will need to move the project that you were passing until now as query param to the URL path instead )
`GET`: change from `/func/{project}/{name}` ->  to `/projects/{project}/functions/{name}`
`STORE` change from `/func/{project}/{name}` ->  to `/projects/{project}/functions/{name}`

Impl [UI] Use new functions endpoints

---

src/common/TabsSlider/TabsSlider.js
src/common/TabsSlider/tabsSlider.scss
src/components/Datasets/Datasets.js
src/components/Datasets/DatasetsView.js
src/components/Datasets/datasets.util.js
src/components/Details/Details.js
src/components/Details/DetailsHeader/DetailsHeader.js
src/components/Details/details.scss
src/components/Details/details.util.js
src/components/DetailsInfo/DetailsInfo.js
src/components/DetailsInfo/DetailsInfoView.js
src/components/DetailsInfo/detailsInfo.scss
src/components/Files/Files.js
src/components/Files/FilesView.js
src/components/Files/files.util.js
src/components/ModelsPage/Models/Models.js
src/components/ModelsPage/Models/ModelsView.js
src/components/ModelsPage/Models/models.util.js
src/components/ProjectsPage/Projects.js
src/components/Table/TableView.js
src/constants.js
src/elements/ContentMenu/contentMenu.scss
src/elements/DetailsInfoItem/DetailsInfoItem.js
src/scss/main.scss
src/utils/helper.js

- **UI**: Revamp Details new view for datasets/models/artifacts
Jira: https://jira.iguazeng.com/browse/ML-3932
After:

Impl [UI] Revamp Details new view for datasets/models/artifacts

---

src/components/ArtifactsPreview/ArtifactsPreviewView.js
src/components/DetailsResults/DetailsResults.js

- **Details**: Fix results no data position

Fix [Details] results no data

---

src/components/Details/DetailsHeader/DetailsHeader.js
src/hooks/mode.hook.js

Fix [Hook] demo mode

---

src/elements/TableCell/TableCell.js
src/elements/TableLinkCell/tableLinkCell.scss
src/scss/main.scss

- **Table**: align status to the right
Before: 
After:

Fix [Table] align status to the right

---

src/utils/artifacts.util.js

- **General**: Functionality change for tag searching between 1.3.2 and 1.4.0
Jira: https://jira.iguazeng.com/browse/ML-3947

Fix [General] Functionality change for tag searching between 1.3.2 and 1.4.0

---

src/components/Details/DetailsHeader/DetailsHeader.js

- **Details**: Hide 'Full view' Icon in 1.4.0 - demo mode
Jira: https://jira.iguazeng.com/browse/ML-3980

Impl [Details] Hide 'Full view' Icon in 1.4.0 - demo mode

---

src/components/DetailsResults/DetailsResults.js

- **Jobs**: UI crash on attempt to view job "Results" tab
Jira: https://jira.iguazeng.com/browse/ML-3927

Fix [Jobs] UI crash on attempt to view job "Results" tab

---

src/common/NameFilter/NameFilter.js
src/components/ArtifactsActionBar/ArtifactsActionBar.js
src/components/Datasets/Datasets.js
src/components/Datasets/DatasetsView.js
src/components/Files/Files.js
src/components/Files/FilesView.js
src/components/ModelsPage/Models/Models.js
src/components/ModelsPage/Models/ModelsView.js
src/hooks/useGetTagOptions.hook.js

- **General**: Tag filter is broken when Details panel is opened
Jira: https://jira.iguazeng.com/browse/ML-3975

Fix [General] Tag filter is broken when Details panel is opened

---

src/utils/generateProducerDetailsInfo.js

- **UI**: The URI label - URI should be in uppercase
Jira: [ML-4005](https://jira.iguazeng.com/browse/ML-4005)

Fix [UI] The URI label - URI should be in uppercase

---

src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
src/utils/generateModelEndpoints.js

- **Model Endpoints**: Browser refreshes after closing the details panel
Jira: https://jira.iguazeng.com/browse/ML-4021

Fix [Model Endpoints] Browser refreshes after closing the details panel

---

src/components/FeatureStore/featureStore.util.js

- **Feature store**: UI crash on alias change 
Jira: https://jira.iguazeng.com/browse/ML-3888

Fix [Feature store] UI crash on alias change

---

src/components/DetailsResults/DetailsResults.js

- **Artifacts**: Duplicated keys error
Jira: https://jira.iguazeng.com/browse/ML-3926

Fix [Artifacts] Duplicated keys error

---

src/App.js
src/components/Details/details.util.js
src/components/FunctionsPage/Functions.js

- **Model endpoints**: Function URI doesn't redirect to function overview
Jira: https://jira.iguazeng.com/browse/ML-3723

Fix [Model endpoints] Function URI doesn't redirect to function overview

---

src/components/Workflow/Workflow.js
src/components/Workflow/workflow.util.js

- **Workflow**: Error on attempt to select deploy step
Jira: https://jira.iguazeng.com/browse/ML-3951

Fix [Workflow] Error on attempt to select deploy step

---

src/common/RangeInput/RangeInput.js

- **Jobs Panel**: Unexpected input possibility for MEMORY, CPU, GPU limits and request fields
Jira: https://jira.iguazeng.com/browse/ML-4019

Fix [Jobs Panel] Unexpected input possibility for MEMORY, CPU, GPU limits and request fields

---

src/components/Details/details.util.js

- **Feature set**: Apply changes button presents for empty label field on Details pane
Depends On: [v1.2.3](https://github.com/iguazio/dashboard-react-controls/releases/tag/v1.2.3)
Jira: https://jira.iguazeng.com/browse/ML-3578

Fix [Feature set] Apply changes button presents for empty label field on Details pane

---

src/components/FunctionsPage/functions.util.js
src/constants.js
src/scss/main.scss
src/utils/getState.js

- **Functions**: Change 'created' state to 'creating'
Jira: https://jira.iguazeng.com/browse/ML-3427

Fix [Functions] Change 'created' state to 'creating'

---

src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js

- **Project Settings**: "Something went wrong." error on project settings screen when setting project params value as object
Jira: https://jira.iguazeng.com/browse/ML-4063

Fix [Project Settings] "Something went wrong." error on project settings screen when setting project params value as object

---

src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js

- **Feature Sets panel**: Update tooltip for online target
Jira: https://jira.iguazeng.com/browse/ML-4067

Fix [Feature Sets panel] update tooltip for online target

---

src/utils/createArtifactsContent.js
src/utils/createFeatureStoreContent.js
src/utils/createFunctionsContent.js
src/utils/createJobsContent.js
src/utils/validateArguments.js

- **Model Endpoints**: CORS error after drilldown
Jira: https://jira.iguazeng.com/browse/ML-3866

Fix [Model Endpoints] CORS error after drilldown

---

src/components/Datasets/datasets.util.js
src/components/Files/files.util.js
src/components/ModelsPage/Models/models.util.js
src/utils/datetime.js

- **Artifacts**: Runs are listed old to new
Jira: https://jira.iguazeng.com/browse/ML-4118
Before:
After:

Fix [Artifacts] Runs are listed old to new

---

src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js

- **Feature set**: User can't set online target in passthrough mode
Jira: https://jira.iguazeng.com/browse/ML-4099

Fix [Feature set] User can't set online target in passthrough mode

---

src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js

- **Feature sets**: Unexpected data required when passthrough is checked after setting offline targets on Create feature set panel
Jira: https://jira.iguazeng.com/browse/ML-4058

Fix [Feature sets] Unexpected data required when passthrough is checked after setting offline targets

---

src/components/ProjectsPage/Projects.js

- **Project home**: The "Job and workflow" link from project page navigates to Projects screen
Jira: https://jira.iguazeng.com/browse/ML-4133

Fix [Project home] The "Job and workflow" link from project page navigates to Projects screen

---

src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
src/components/JobsPanel/JobsPanel.js
src/components/JobsPanel/jobsPanel.util.js

- **Workflows**: The "Undefined " API is sent and failed for rerun job from WF
Jira: https://jira.iguazeng.com/browse/ML-4150

Fix [Workflows] The "Undefined " API is sent and failed for rerun job from WF

---

src/components/Datasets/DatasetsView.js
src/components/FeatureStore/FeatureSets/FeatureSetsView.js
src/components/FunctionsPage/FunctionsView.js
src/components/ModelsPage/Models/ModelsView.js
src/components/ModelsPage/RealTimePipelines/RealTimePipelinesView.js
src/elements/ArtifactsTableRow/ArtifactsTableRow.js
src/elements/FeatureStoreTableRow/FeatureStoreTableRow.js
src/elements/FunctionsTableRow/FunctionsTableRow.js
src/utils/generateTableRowTestId.js

- **UI**: Add the Test ID to the artifacts table row elements
Jira: https://jira.iguazeng.com/browse/ML-4169
**After:**

Impl [UI] Add attribute data-testid to the artifacts table row elements

---

src/components/Datasets/DatasetsView.js
src/components/FeatureStore/FeatureSets/FeatureSetsView.js
src/components/FunctionsPage/FunctionsView.js
src/components/ModelsPage/Models/ModelsView.js
src/components/ModelsPage/RealTimePipelines/RealTimePipelinesView.js
src/elements/ArtifactsTableRow/ArtifactsTableRow.js
src/elements/FeatureStoreTableRow/FeatureStoreTableRow.js
src/elements/FunctionsTableRow/FunctionsTableRow.js
src/utils/generateTableRowTestId.js

- **UI**: Add the Test ID to the artifacts table row elements
Backported to `1.4.x` from #1796 
Jira: https://jira.iguazeng.com/browse/ML-4169
**After:**

Impl [UI] Add attribute data-testid to the artifacts table row elements `1.4.x`

---

src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
src/components/JobsPanel/JobsPanel.js
src/components/JobsPanel/jobsPanel.util.js

- **Workflows**: The "Undefined " API is sent and failed for rerun job from WF
Backported to `1.4.x` from #1793 
Jira: https://jira.iguazeng.com/browse/ML-4150

Fix [Workflows] The "Undefined " API is sent and failed for rerun job from WF `1.4.x`

---

src/actions/projects.js

- **UI**: Wrong navigation to the "Job and workflow"from new Project
Jira: https://jira.iguazeng.com/browse/ML-4189

Fix [UI] Wrong navigation to the "Job and workflow"from new Project

---

src/components/ArtifactsPreview/ArtifactsPreview.js
src/components/ArtifactsPreview/ArtifactsPreviewView.js
src/components/DetailsPreview/DetailsPreview.js
src/components/DetailsResults/DetailsResults.js
src/scss/main.scss
src/utils/createArtifactPreviewContent.js

- **UI**: Preview table is hidden from view
Jira: [ML-4193](https://jira.iguazeng.com/browse/ML-4193)
Before:
After:

Fix [UI] Preview table is hidden from view

---

src/components/FeatureSetsPanel/UrlPath.utils.js
src/utils/panelPathScheme.js

- **Feature Store**: Input hint missing in URL_Combobox
Jira: https://jira.iguazeng.com/browse/ML-3996
After:

Fix [Feature Store] Input hint missing in URL_Combobox

---

src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js

- **Feature Store**: Path formation for Online and Offline placeholder
Jira: https://jira.iguazeng.com/browse/ML-4018
After:

Fix [Feature Store] Path formation for Online and Offline placeholder

---

src/components/FunctionsPage/Functions.js
src/components/FunctionsPage/FunctionsView.js
src/components/Jobs/Jobs.js
src/components/Jobs/MonitorJobs/MonitorJobs.js
src/components/Jobs/MonitorJobs/monitorJobs.util.js
src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
src/components/Jobs/ScheduledJobs/ScheduledJobs.js
src/components/Jobs/ScheduledJobs/scheduledJobs.util.js
src/components/Jobs/jobs.util.js
src/components/Project/ProjectMonitor.js
src/components/Project/ProjectOverview/ProjectOverview.util.js
src/components/Project/project.utils.js

- **Batch run**: Take the Batch run wizard out of the demo mode
Jira: [ML-4229](https://jira.iguazeng.com/browse/ML-4229)

Impl [Batch run] Take the Batch run wizard out of the demo mode

---

src/components/Project/ProjectOverview/ProjectOverview.util.js

- **Batch inference**: Add Batch Inference Icon to Project Home
Jira: [ML-4115](https://jira.iguazeng.com/browse/ML-4115)

Impl [Batch inference] Add Batch Inference Icon to Project Home

---

src/common/TabsSlider/tabsSlider.scss
src/components/ArtifactsPreview/ArtifactsPreview.js
src/components/ArtifactsPreview/artifactsPreview.scss
src/components/ArtifactsPreview/artifactsPreviewController.scss
src/components/Details/Details.js
src/components/Details/details.scss
src/components/DetailsArtifacts/DetailsArtifactsView.js
src/components/DetailsArtifacts/detailsArtifacts.scss
src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.scss
src/components/DetailsInfo/DetailsInfoView.js
src/components/DetailsInfo/detailsInfo.scss
src/components/DetailsLogs/DetailsLogs.js
src/components/DetailsMetadata/detailsMetadata.scss
src/components/DetailsPods/DetailsPods.js
src/components/DetailsPods/detailsPods.scss
src/components/DetailsPreview/DetailsPreview.js
src/components/DetailsRequestedFeatures/detailsRequestedFeatures.scss
src/components/DetailsResults/detailsResults.scss
src/components/DetailsStatistics/detailsStatistics.scss
src/components/FilterMenu/filterMenu.scss
src/components/Table/table.scss
src/elements/TableLinkCell/tableLinkCell.scss
src/elements/TableTop/tableTop.scss
src/scss/main.scss

- **Table**: Fix tables view, scroll, css
Jira: [ML-4216](https://jira.iguazeng.com/browse/ML-4216)

Fix [Tables] view, scroll, css
