mlrun/ui

- package.json
- src/components/Details/DetailsHeader/DetailsHeader.js
- **Details**: Change the view toggle icons
Jira: [ML-4274](https://jira.iguazeng.com/browse/ML-4274)
> Impl [Details] Change the view toggle icons

- src/components/FeatureSetsPanel/FeatureSetsPanel.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
- src/components/FeatureSetsPanel/featureSetPanel.util.js
- **Feature set**: Failed target store validation for create feature set
Jira: [ML-4246](https://jira.iguazeng.com/browse/ML-4246)
Before:
After:
> Fix [Feature set] Failed target store validation for create feature set

- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
- src/constants.js
- **Feature store**: Add type Redis to online types list
Jira: [ML-4066](https://jira.iguazeng.com/browse/ML-4066)
Before:
After:
> Fix [Feature store] Add type Redis to online types list

- src/components/Details/details.util.js
- src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.js
- **Model Endpoints**: Display function tag in model endpoint
Jira: https://jira.iguazeng.com/browse/ML-3584
After:
> Impl [Model Endpoints] Display function tag in model endpoint

- src/elements/FormEnvironmentVariablesTable/FormEnvironmentVariablesRow/FormEnvironmentVariablesRow.js
- **Batch run**: Can't change the type in the existing Environment variables
Jira: https://jira.iguazeng.com/browse/ML-4228
> Fix [Batch run] Can't change the type in the existing Environment variables

- src/utils/getNoDataMessage.js
- **UI**: Filter with no result should include the labels
Jira: https://jira.iguazeng.com/browse/ML-4212
After:
> Fix [UI] Filter with no result should include the labels

- src/components/JobWizard/JobWizard.util.js
- src/elements/FormEnvironmentVariablesTable/FormEnvironmentVariablesRow/FormEnvironmentVariablesRow.js
- **Batch run** an attempt to run "batch run" fails with "runtime error: (422) Reason: Unprocessable Entity"
Jira: https://jira.iguazeng.com/browse/ML-4250
> Fix [Batch run] an attempt to run "batch run" fails with "runtime error: (422) Reason: Unprocessable Entity"

- src/components/FeatureSetsPanel/ScheduleFeatureSet/ScheduleFeatureSet.js
- src/components/FeatureSetsPanel/ScheduleFeatureSet/ScheduleFeatureSetView.js
- src/components/FilterMenuModal/filterMenuModal.scss
- src/elements/ScheduleRecurring/scheduleRecurring.scss
- **Feature set**: Error during schedule data source
Jira: [ML-4258](https://jira.iguazeng.com/browse/ML-4258)
Before:
After:
> Fix [Feature set] Error during schedule data source

- src/common/Combobox/combobox.scss
- src/common/TargetPath/targetPath.util.js
- src/components/FeatureSetsPanel/UrlPath.js
- src/components/FeatureSetsPanel/UrlPath.utils.js
- src/constants.js
- src/scss/main.scss
- **UI**: Support DBFS as a data item
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/146
Jira: [ML-4185](https://jira.iguazeng.com/browse/ML-4185)
After:
> Impl [UI] Support DBFS as a data item

- package.json
- tests/features/common-tools/common-consts.js
- tests/features/common/actions/checkbox.action.js
- tests/features/common/actions/table.action.js
- tests/features/common/page-objects/feature-store.po.js
- tests/features/common/page-objects/files.po.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/models.po.js
- tests/features/common/page-objects/side-panel.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/files.feature
- tests/features/models.feature
- tests/features/projectPage.feature
- tests/features/projectsPage.feature
- tests/features/step-definitions/steps.js
- tests/features/step-definitions/table.steps.js
- tests/features/support/world.js
- Datasets, Artifacts, Models pages - updated "FilterBy" popup
- Datasets, Artifacts, Models pages - for filter by Labels created capturing for overlay and row labels.
- Updated tests for filtering with extend button
- Feature sets tab  - added tests for feature set creation (Passthrough, TARGET STORE, Save and ingest functionality)
> QA Sprint 144 done

- src/components/ArtifactsPreview/ArtifactsPreviewView.js
- src/components/ArtifactsPreview/artifactsPreview.scss
- **Artifacts**: v3io dir artifact blank preview
Jira: https://jira.iguazeng.com/browse/ML-3766
After:
> Fix [Artifacts] v3io dir artifact blank preview

- src/components/JobWizard/JobWizard.js
- src/components/JobWizard/JobWizardSteps/JobWizardAdvanced/JobWizardAdvanced.js
- src/components/JobWizard/JobWizardSteps/JobWizardDataInputs/JobWizardDataInputs.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- src/components/JobWizard/JobWizardSteps/JobWizardParameters/JobWizardParameters.js
- src/components/JobWizard/JobWizardSteps/JobWizardResources/JobWizardResources.js
- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- src/elements/FormResourcesUnits/formResourcesUnits.scss
- **Batch run**: The GPU resources card does not adapt to different screen sizes
Jira: [ML-4322](https://jira.iguazeng.com/browse/ML-4322)
Before: 
After:
> Fix [Batch run] The GPU resources card does not adapt to different screen sizes

- src/elements/FormVolumesTable/FormVolumesTable.js
- **Batch run**: Button 'Add volume' displays as 'Add custom parameter' for adding new volume during setting the resources in Batch Run
Jira: [ML-4311](https://jira.iguazeng.com/browse/ML-4311)
> Fix [Batch run] Button 'Add volume' displays as 'Add custom parameter' for adding new volume during setting the resources in Batch Run

- src/scss/main.scss
- **BatchRun**: Inconsistent Fonts of Resource headers sections
- Fixed margin between step sections
Jira: [ML-4325](https://jira.iguazeng.com/browse/ML-4325)
> Fix [BatchRun] Inconsistent Fonts of Resource headers sections

- src/components/JobWizard/JobWizard.util.js
- **Batch run**: Request Payload does not contain env var value
Jira: [ML-4320](https://jira.iguazeng.com/browse/ML-4320)
> Fix [Batch run] Request Payload does not contain env var value

- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/jobWizardFunctionSelection.scss
- **Batch run**: add vertical scroll to function list
Jira: [ML-4284](https://jira.iguazeng.com/browse/ML-4284)
> Fix [Batch run] add vertical scroll to function list

- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- **Batch run**: The chosen method should be present in the first row
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/149
Jira: [ML-4314](https://jira.iguazeng.com/browse/ML-4314)
> Fix [Batch run] The chosen method should be present in the first row

- src/components/Jobs/jobs.util.js
- src/components/Project/ProjectMonitor.js
- **Monitor Jobs**: Error on navigating to job after deleting function
Jira: [ML-4335](https://jira.iguazeng.com/browse/ML-4335)
> Fix [Monitor Jobs] Error on navigating to job after deleting function

- src/components/SheduleWizard/ScheduleWizard.js
- src/components/SheduleWizard/ScheduleWizardSimple.js
- src/components/SheduleWizard/scheduleWizard.scss
- src/constants.js
- **Batch run**: Error during schedule
Jira: https://jira.iguazeng.com/browse/ML-4293
After:
> Fix [Batch run] Error during schedule

- src/common/Breadcrumbs/Breadcrumbs.js
- src/elements/BreadcrumbsDropdown/BreadcrumbsDropdown.js
- **Breadcrumbs**: project search value persists after list closing
Jira: [ML-4377](https://jira.iguazeng.com/browse/ML-4377)
> Fix [Breadcrumbs] project search value persists after list closing

- src/common/Search/Search.js
- src/components/ProjectsPage/Projects.js
- src/components/ProjectsPage/ProjectsView.js
- **Projects**: search project is case sensitive
Jira: [ML-4378](https://jira.iguazeng.com/browse/ML-4378)
Before:
After:
> Fix [Projects] search project is case sensitive

- src/common/Chart/mlChart.scss
- **Details Statistics**: The scrollbar appears for a few seconds
Jira: https://jira.iguazeng.com/browse/ML-4362
> Fix [Details Statistics] The scrollbar appears for a few seconds

- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
- src/components/FeatureSetsPanel/featureSetPanel.util.js
- **Feature set**: inaccurate default path for redis
Jira: [ML-4277](https://jira.iguazeng.com/browse/ML-4277)
Before:
After:
> Fix [Feature set] inaccurate default path for redis

- src/common/TargetPath/targetPath.util.js
- **Batch run**: autofilled dataset store path is invalid
Jira: https://jira.iguazeng.com/browse/ML-4288
> Fix [Batch run] autofilled dataset store path is invalid

- src/components/Project/ProjectOverview/ProjectOverview.util.js
- **Project home**:  Added Model Training Icon
Jira: https://jira.iguazeng.com/browse/ML-4116
> Impl [Project home] Add Model Training Icon

- src/components/Details/details.scss
- src/elements/TableTypeCell/TableTypeCell.js
- **UI**: "Type" inconsistency for databricks job
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/159
Jira: [ML-4399](https://jira.iguazeng.com/browse/ML-4399)
> Fix [UI] "Type" inconsistency for databricks job 

- src/components/Files/Files.js
- **UI**: Filter by tag isn't performed when version tag was edited
Jira: https://jira.iguazeng.com/browse/ML-4158
> Fix [UI] Filter by tag isn't performed when version tag was edited

- src/App.js
- src/components/ConsumerGroup/ConsumerGroup.js
- src/utils/createConsumerGroupsContent.js
- tests/mockServer/data/nuclioStreams.json
- **Consumer groups**: UI does not show the right detalis
Jira: [ML-4391](https://jira.iguazeng.com/browse/ML-4391)
> Fix [Consumer groups] UI does not show the right detalis

- src/components/JobWizard/JobWizard.js
- src/components/JobWizard/JobWizard.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardAdvanced/JobWizardAdvanced.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- src/elements/FormEnvironmentVariablesTable/FormEnvironmentVariablesRow/FormEnvironmentVariablesRow.js
- src/elements/FormEnvironmentVariablesTable/FormEnvironmentVariablesTable.js
- **Batch run**: Move Type for Env vars out of the staging mode
Jira: [ML-4382](https://jira.iguazeng.com/browse/ML-4382)
> Fix [Batch run] Move `Type` for Env vars out of the staging mode

- src/components/JobWizard/JobWizard.util.js
- **Batch run**: Add missing fields to volumes
Jira: [ML-4383](https://jira.iguazeng.com/browse/ML-4383)
> Fix [Batch run] Add missing fields to volumes

- src/components/JobWizard/JobWizard.util.js
- **Batch Run**: Run failed after edit/remove GPU limit from UI
Jira: https://jira.iguazeng.com/browse/ML-4429
> Fix [Batch Run] Run failed after edit/remove GPU limit from UI

- src/components/JobWizard/JobWizard.util.js
- src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
- **Batch run**: Function param without type is being shown as "str"
Jira: [ML-4371](https://jira.iguazeng.com/browse/ML-4371)
> Fix [Batch run] Function param without type is being shown as "str"

- src/components/ProjectsPage/projectsData.js
- **Projects**: Remove 'Export YAML' from demo mode
Jira: [ML-4433](https://jira.iguazeng.com/browse/ML-4433)
> Impl [Projects] Remove 'Export YAML' from demo mode

- src/components/JobWizard/JobWizard.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardHyperparameterStrategy/JobWizardHyperparameterStrategy.js
- src/components/JobWizard/JobWizardSteps/JobWizardHyperparameterStrategy/jobWizardHyperparameterStrategy.util.js
- src/components/JobsPanelParameters/jobsPanelParameters.util.js
- src/constants.js
- **Batch Run**: The UI should prevent the "Max Iterations" field from being set unless the strategy is random
Jira: [ML-4452](https://jira.iguazeng.com/browse/ML-4452)
Before:
After:
> Fix [Batch Run] The UI should prevent the "Max Iterations" field from being set unless the strategy is random

- src/components/JobWizard/JobWizard.util.js
- src/components/JobWizard/jobWizard.scss
- src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
- src/elements/FormParametersTable/FormParametersTable.js
- **Batch Run**: It's not clear what the 'Hyper' toggle does
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/164
Jira: [ML-4454](https://jira.iguazeng.com/browse/ML-4454) + [ML-4508](https://jira.iguazeng.com/browse/ML-4508)
Before:
After:
> Fix [Batch Run] It's not clear what the 'Hyper' toggle does

- src/components/JobWizard/JobWizardSteps/JobWizardHyperparameterStrategy/jobWizardHyperparameterStrategy.util.js
- **Batch Run**: Remove "Custom" strategy from Hyperparameter strategy
Jira: [ML-4507](https://jira.iguazeng.com/browse/ML-4507)
> Fix [Batch Run] Remove "Custom" strategy from Hyperparameter strategy

- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- **UI**: labels are failing validations upon "Batch Re-Run"
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/166
Jira: https://jira.iguazeng.com/browse/ML-4251
After:
> Fix [UI] labels are failing validations upon "Batch Re-Run"

- src/elements/FormResourcesUnits/FormResourcesUnits.js
- **Batch Run**: CPU value in Resources panel increase/decrease by ones with "millicpu" type
Jira: https://jira.iguazeng.com/browse/ML-4510
> Fix [Batch Run] CPU value in Resources panel increase/decrease by ones with "millicpu" type

- src/components/JobWizard/JobWizard.js
- src/components/JobWizard/JobWizard.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- src/constants.js
- **Batch Infer**: Enable 'change image' or 'add a new requirements'
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/167
Jira: [ML-4511](https://jira.iguazeng.com/browse/ML-4511)
> Impl [Batch Infer] Enable 'change image' or 'add a new requirements'

- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- **Batch run**: Redundant 'Are you sure?' dialog when changing the 'Method'
Jira: [ML-4456](https://jira.iguazeng.com/browse/ML-4456)
> Fix [Batch run] Redundant 'Are you sure?' dialog when changing the 'Method'

- src/components/JobWizard/JobWizard.util.js
- **Job Wizard**: Uncheck predefined parameters
Jira: https://jira.iguazeng.com/browse/ML-4518
> Fix [Job Wizard] Uncheck predefined parameters

- src/components/Details/details.scss
- src/components/DetailsInfo/detailsInfo.scss
- src/components/Table/TableView.js
- src/components/Table/table.scss
- src/components/Workflow/Workflow.js
- src/components/Workflow/workflow.scss
- **Monitor Workflows**: Missing padding in graph view details panel
Jira: [ML-4538](https://jira.iguazeng.com/browse/ML-4538)
Before:
After:
> Fix [Monitor Workflows] Missing padding in graph view details panel

- src/actions/functions.js
- src/components/FunctionsPanel/FunctionsPanel.js
- **ML Functions**: Capital letters on function name gives error
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/169
Jira: [ML-4533](https://jira.iguazeng.com/browse/ML-4533)
Before:
After:
> Fix [ML Functions] Capital letters on function name gives error

- src/utils/convertChipsData.js
- src/utils/object.js
- **Jobs**: Inconsistency between "Results" in "Overview" vs "Results" tab
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/170
Jira: https://jira.iguazeng.com/browse/ML-4408
> Fix [Jobs] Inconsistency between "Results" in "Overview" vs "Results" tab

- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- **Batch run**: Selected function isn't hinted
Jira: https://jira.iguazeng.com/browse/ML-4527
> Fix [Batch run] Selected function isn't hinted

- src/components/CreateJobPage/CreateJobPage.js
- src/components/FunctionsPage/Functions.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- src/components/Jobs/MonitorJobs/monitorJobs.util.js
- src/components/Jobs/jobs.util.js
- src/utils/generateTemplatesCategories.js
- **Jobs**: Allow to run and re-run functions only with job kind
Jira: [ML-4346](https://jira.iguazeng.com/browse/ML-4346)
> Fix [Jobs] Allow to run and re-run functions only with `job` kind

- src/components/JobWizard/JobWizard.js
- **Batch infer**: Adjust batch infer to the new function
Jira: [ML-4485](https://jira.iguazeng.com/browse/ML-4485)
> Impl [Batch infer] Adjust batch infer to the new function

- src/actions/jobs.js
- src/components/Jobs/ScheduledJobs/ScheduledJobs.js
- src/components/Jobs/jobs.util.js
- **Jobs**: redundant error on attempt to run job after deleting its function
Jira: [ML-4430](https://jira.iguazeng.com/browse/ML-4430)
> Fix [Jobs] redundant error on attempt to run job after deleting its function

- src/components/Jobs/ScheduledJobs/ScheduledJobs.js
- **Jobs**: error missing details when job fails to start
Jira: https://jira.iguazeng.com/browse/ML-4431
> Fix [Jobs] error missing details when job fails to start

- src/components/RegisterArtifactModal/RegisterArtifactModal.js
- **Artifacts**: Missing description data in Register requests 
Jira: [ML-4583](https://jira.iguazeng.com/browse/ML-4583)
> Fix [Artifacts] Missing description data in Register requests

- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
- src/components/FeatureSetsPanel/UrlPath.js
- **Feature Store**: Target store checkboxes don't work properly
Jira: https://jira.iguazeng.com/browse/ML-4230
> Fix [Feature Store] Target store checkboxes don't work properly

- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
- src/components/FeatureSetsPanel/UrlPath.js
- **Feature Store**: Target store checkboxes don't work properly
Backported to `1.5.x` from #1917 
Jira: https://jira.iguazeng.com/browse/ML-4230
> Fix [Feature Store] Target store checkboxes don't work properly `1.5.x`

- src/common/ChipCell/ChipCell.js
- src/common/ChipCell/HiddenChipsBlock/HiddenChipsBlock.js
- src/common/ReactFlow/MlReactFlowEdge.js
- src/elements/FormDataInputsTable/FormDataInputsTable.js
- src/elements/FormEnvironmentVariablesTable/FormEnvironmentVariablesTable.js
- src/elements/FormParametersTable/FormParametersTable.js
- src/elements/FormVolumesTable/FormVolumesTable.js
- **Batch Run**: Number input for int and float parameters is malfunctioning
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/176
Backported to `1.5.x` from #1918 
Jira: [ML-4549](https://jira.iguazeng.com/browse/ML-4549)
> Fix [Batch Run] Number input for int and float parameters is malfunctioning `1.5`

- src/common/TargetPath/TargetPath.js
- src/common/TargetPath/targetPath.util.js
- src/components/FeatureSetsPanel/UrlPath.js
- src/components/FeatureSetsPanel/UrlPath.utils.js
- src/utils/panelPathScheme.js
- **Combobox**: unable to pass model as data input using store path
Jira: https://jira.iguazeng.com/browse/ML-4520
> Fix [Combobox] unable to pass model as data input using store path

- src/common/TargetPath/TargetPath.js
- src/common/TargetPath/targetPath.util.js
- src/components/FeatureSetsPanel/UrlPath.js
- src/components/FeatureSetsPanel/UrlPath.utils.js
- src/utils/panelPathScheme.js
- **Combobox**: unable to pass model as data input using store path
Backported to `1.5.x` from #1921 
Jira: https://jira.iguazeng.com/browse/ML-4520
> Fix [Combobox] unable to pass model as data input using store path `1.5.x`

- src/common/Chart/MlChart.js
- src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.util.js
- **Features Analysis**: Large float values are not presented
Jira: https://jira.iguazeng.com/browse/ML-4445
> Fix [Features Analysis] Large float values are not presented

- src/components/JobWizard/JobWizard.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- src/scss/main.scss
- **Batch run**: Hide 'Build image' option, add message for 'Image name'
1. Hide 'Build a new image' option for 'Batch inference' and 'Batch run'
2. Add an explanation message for 'Image name' input
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/177
Jira: [ML-4606](https://jira.iguazeng.com/browse/ML-4606)
> Fix [Batch run] Hide 'Build image' option, add message for 'Image name'

- src/components/JobWizard/JobWizard.util.js
- src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
- **Batch run**: Changed parameter types aren't saved for rerun
Jira: [ML-4612](https://jira.iguazeng.com/browse/ML-4612)
> Fix [Batch run] Changed parameter types aren't saved for rerun

- src/actions/jobs.js
- src/api/jobs-api.js
- src/components/Jobs/MonitorJobs/MonitorJobs.js
- src/constants.js
- **Jobs**: UI is stuck on attempt to list runs for job with many runs `1.5.x`
Backported to `1.5.x` from #1934 
Jira: https://jira.iguazeng.com/browse/ML-4604
After:
> Fix [Jobs] UI is stuck on attempt to list runs for job with many runs `1.5.x`

- src/actions/jobs.js
- src/api/jobs-api.js
- src/components/Jobs/MonitorJobs/MonitorJobs.js
- src/constants.js
- **Jobs**: UI is stuck on attempt to list runs for job with many runs `1.5.x`
Jira: https://jira.iguazeng.com/browse/ML-4604
After:
> Fix [Jobs] UI is stuck on attempt to list runs for job with many runs

- src/components/Jobs/ScheduledJobs/ScheduledJobs.js
- src/utils/parseJob.js
- **Scheduled workflow**: Workflow (and not job) should have different icon and minimal editing
Jira: [ML-4628](https://jira.iguazeng.com/browse/ML-4628)
Before:
After:
> Fix [Scheduled workflow] Workflow (and not job) should have different icon and minimal editing

- src/components/Details/details.util.js
- **Jobs**: Batch Model Endpoint => overview - model, function and Feature set links are broken
Jira: https://jira.iguazeng.com/browse/ML-4569
> Fix [Jobs] Batch Model Endpoint => overview - model, function and Featureset links are broken

- src/components/Details/details.util.js
- src/utils/createArtifactsContent.js
- src/utils/generateFunctionDetailsLink.js
- src/utils/parseUri.js
- **Model Endpoints**: Invalid Function URI link in model endpoints screen
https://jira.iguazeng.com/browse/ML-4637
> Fix [Model Endpoints] Invalid Function URI link in model endpoints screen

- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
- **Feature set**:  The target store path is incorrect
Jira: https://jira.iguazeng.com/browse/ML-4373
> Fix [Feature set] the target store path is incorrect

- src/components/JobWizard/JobWizard.util.js
- src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
- **Batch run**: Mandatory parameters should be selected
Jira: [ML-4657](https://jira.iguazeng.com/browse/ML-4657)
> Fix [Batch run] Mandatory parameters should be selected

- src/components/JobWizard/JobWizard.util.js
- src/components/JobsPanel/jobsPanel.util.js
- **Batch run**Ж Remove the '$' from Batch Inference version presentation
Jira: https://jira.iguazeng.com/browse/ML-4591
> Fix [Batch run] Remove the '$' from Batch Inference version presentation

- src/components/JobWizard/JobWizard.util.js
- **Batch run**: Batch run labels are incorrect
Jira: [ML-4663](https://jira.iguazeng.com/browse/ML-4663)
> Fix [Batch run] Batch run labels are incorrect

- src/actions/functions.js
- src/components/JobWizard/JobWizard.js
- src/components/JobWizard/JobWizard.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- **Wizard steps**: Next to step should be clickable
Backported to `1.5.x` from #1943 
Jira: [ML-4633](https://jira.iguazeng.com/browse/ML-4633)
> Impl [Wizard steps] Next to step should be clickable `1.5.x`

- src/common/Search/search.scss
- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- src/elements/FormDataInputsTable/FormDataInputsRow/FormDataInputsRow.js
- src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
- src/scss/main.scss
- **Batch Run**: UI minor fix
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/184
Jira: [ML-4619](https://jira.iguazeng.com/browse/ML-4619)
> Fix [Batch Run] UI minor fix `1.5.x`

- src/components/JobWizard/JobWizard.util.js
- **Batch run**: Add "monitoring" to categories mapping
Backported to `1.5.x` from #1955 
Jira: [ML-4677](https://jira.iguazeng.com/browse/ML-4677)
> Impl [Batch run] Add "monitoring" to categories mapping `1.5.x`

- src/actions/functions.js
- src/components/JobWizard/JobWizard.js
- src/components/JobWizard/JobWizard.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- **Wizard steps**: Next to step should be clickable
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/181
Jira: [ML-4633](https://jira.iguazeng.com/browse/ML-4633)
> Impl [Wizard steps] Next to step should be clickable

- src/components/JobWizard/JobWizard.util.js
- **Batch run**: Add "monitoring" to categories mapping
Jira: [ML-4677](https://jira.iguazeng.com/browse/ML-4677)
> Impl [Batch run] Add "monitoring" to categories mapping

- src/components/DetailsInputs/DetailsInputs.js
- src/components/JobWizard/JobWizard.util.js
- **Batch run**:  inputs issues 
1. when using batch run wizard on a stored function with an empty input, the UI pass the empty input with a value similar to the key
2. Inputs are not displayed in the inputs job tab if there has been an error with a previous input store path
Jira: https://jira.iguazeng.com/browse/ML-4659, https://jira.iguazeng.com/browse/ML-4658, https://jira.iguazeng.com/browse/ML-4657
> Fix [Batch run] inputs issues

- src/components/Datasets/Datasets.js
- src/components/ModelsPage/Models/Models.js
- **Datasets, Models** :Filter by tag isn't performed when version tag was edited
Jira: https://jira.iguazeng.com/browse/ML-4158
> Fix [Datasets and Models] Filter by tag isn't performed when version tag was edited

- src/components/JobWizard/JobWizard.util.js
- **Batch run**: Mandatory parameters should be selected v2
Jira: [ML-4661](https://jira.iguazeng.com/browse/ML-4661)
> Fix [Batch run] Mandatory parameters should be selected v2

- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
- **Feature Sets Panel**: Checking "Passthrough" unchecks "Online" target
Backported to `1.5.x` from #1970 
https://jira.iguazeng.com/browse/ML-4154
> Fix [Feature Sets Panel] Checking "Passthrough" unchecks "Online" target `1.5.x`

- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
- **Feature Sets Panel**: Checking "Passthrough" unchecks "Online" target
https://jira.iguazeng.com/browse/ML-4154
> Fix [Feature Sets Panel] Checking "Passthrough" unchecks "Online" target

- src/components/JobWizard/JobWizardSteps/JobWizardHyperparameterStrategy/JobWizardHyperparameterStrategy.js
- **Batch Run**: Number input for Max iterations, Max errors and Parallel runs is malfunctioning `1.5.x`
Backported to `1.5.x` from #1971 
https://jira.iguazeng.com/browse/ML-4674
> Fix [Batch Run] Number input for Max iterations, Max errors and Parallel runs is malfunctioning `1.5.x`

- src/components/JobWizard/JobWizardSteps/JobWizardHyperparameterStrategy/JobWizardHyperparameterStrategy.js
- **Batch Run**: Number input for Max iterations, Max errors and Parallel runs is malfunctioning
https://jira.iguazeng.com/browse/ML-4674
> Fix [Batch Run] Number input for Max iterations, Max errors and Parallel runs is malfunctioning

- src/common/Search/Search.js
- src/common/Search/search.scss
- **Search**: The search item list closing on scroll `1.5.x`
Backported to `1.5.x` from #1960 
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/187
https://jira.iguazeng.com/browse/ML-4670
> Fix [Search] The search item list closing on scroll `1.5.x`

- src/common/Search/Search.js
- src/common/Search/search.scss
- **Search**: The search item list closing on scroll 
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/188
https://jira.iguazeng.com/browse/ML-4670
> Fix [Search] The search item list closing on scroll

- package.json
- tests/features/MLFunction.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/actions/common.action.js
- tests/features/common/page-objects/feature-store.po.js
- tests/features/common/page-objects/files.po.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/jobs-and-workflows.po.js
- tests/features/common/page-objects/models.po.js
- tests/features/common/page-objects/side-panel.po.js
- tests/features/datasets.feature
- tests/features/files.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/projectsPage.feature
- tests/features/step-definitions/steps.js
- tests/features/step-definitions/table.steps.js
- tests/features/support/world.js
- tests/mockServer/data/artifacts.json
- tests/mockServer/data/itemsCatalog.json
- tests/mockServer/mock.js
I
1. Added tests to check Version tag is filled when editing
- artifacts/dataset/model details view MLD009, MLA009, MLM020
- Jira: ML-4004
2. Check Minimum CPU value on Batch Run wizard
- Batch Run wizard - Resources
- Jira: ML-4308
3. Check tip and warning messages in Volumes section on Batch Run wizard
- Batch Run wizard - Resources
- Jira: ML-4310
II
Added test to ML Function feature
1. Check requirements field in Code Accordion on Create New Function page
- Jira: ML-4009
III
Added test to Jobs And Workflows feature, update mock API with hub functions
1. Check redirect to project's Function Info pane from Job Overview
- current project
- Jira: ML-4332
2. Check mandatory of Container and Resource Path fields for V3IO volume
- Resources section in Batch Run
- Jira: ML-4355
3. Check …
> QA Sprint 147 done

- package.json
- tests/features/MLFunction.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/actions/common.action.js
- tests/features/common/page-objects/feature-store.po.js
- tests/features/common/page-objects/files.po.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/jobs-and-workflows.po.js
- tests/features/common/page-objects/models.po.js
- tests/features/common/page-objects/side-panel.po.js
- tests/features/datasets.feature
- tests/features/files.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/projectsPage.feature
- tests/features/step-definitions/steps.js
- tests/features/step-definitions/table.steps.js
- tests/features/support/world.js
- tests/mockServer/data/artifacts.json
- tests/mockServer/data/itemsCatalog.json
- tests/mockServer/mock.js
#1975 
* Updated tests related to 1.5
1. added tests to check Version tag is filled when editing
- artifacts/dataset/model details view MLD009, MLA009, MLM020
- Jira: ML-4004
2. Check Minimum CPU value on Batch Run wizard
- Batch Run wizard - Resources
- Jira: ML-4308
3. Check tip and warning messages in Volumes section on Batch Run wizard
- Batch Run wizard - Resources
- Jira: ML-4310
* Added test to ML Function feature
- Check requirements field in Code Accordion on Create New Function page
- Jira: ML-4009
* Added test to Jobs And Workflows feature, update mock API with hub functions
1. Check redirect to project`s Function Infopane from Job Overview
- current project
- Jira: ML-4332
2. Check mandatory of Container and …
> Impl [Tests] Sprint 147

- package.json
- tests/features/MLFunction.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/actions/common.action.js
- tests/features/common/page-objects/feature-store.po.js
- tests/features/common/page-objects/files.po.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/jobs-and-workflows.po.js
- tests/features/common/page-objects/models.po.js
- tests/features/common/page-objects/side-panel.po.js
- tests/features/datasets.feature
- tests/features/files.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/projectsPage.feature
- tests/features/step-definitions/steps.js
- tests/features/step-definitions/table.steps.js
- tests/features/support/world.js
- tests/mockServer/data/artifacts.json
- tests/mockServer/data/itemsCatalog.json
- tests/mockServer/mock.js
Collecting PRs into branch **1.5.x** from branch **tests**:
#1975 
* Updated tests related to 1.5
1. added tests to check Version tag is filled when editing
- artifacts/dataset/model details view MLD009, MLA009, MLM020
- Jira: ML-4004
2. Check Minimum CPU value on Batch Run wizard
- Batch Run wizard - Resources
- Jira: ML-4308
3. Check tip and warning messages in Volumes section on Batch Run wizard
- Batch Run wizard - Resources
- Jira: ML-4310
* Added test to ML Function feature
- Check requirements field in Code Accordion on Create New Function page
- Jira: ML-4009
* Added test to Jobs And Workflows feature, update mock API with hub functions
1. Check redirect to project`s Function Infopane from Job Overview
- current project
- Jira: ML-4332
2. Check mandatory of Container and Resource …
> Impl [Tests] Sprint 147 `1.5.x`

- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- **Batch run**: Fixed labels length
Jira: https://jira.iguazeng.com/browse/ML-4644
> Fix [Batch run] Labels issues on Bach run wizard

- src/api/details-api.js
- src/components/Details/details.util.js
- src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
- src/components/Jobs/ScheduledJobs/ScheduledJobs.js
- src/components/Jobs/jobs.util.js
- src/components/Workflow/Workflow.js
- src/constants.js
- src/elements/DeployModelPopUp/DeployModelPopUp.js
- src/elements/NewFunctionPopUp/NewFunctionPopUp.js
- src/elements/NewFunctionPopUp/newFuctionPopUp.util.js
- src/elements/TableTypeCell/TableTypeCell.js
- src/hooks/usePods.hook.js
- src/reducers/artifactsReducer.js
- src/reducers/functionReducer.js
- src/utils/createJobsContent.js
- src/utils/parseJob.js
- src/utils/parseWorkflows.js
- **Jobs**: Print 400 error message when running local job
Backported to `1.5.x` from #1989 
Jira: https://jira.iguazeng.com/browse/ML-4702
> Fix [Jobs] print 400 error message when running local job `1.5.x`

- src/components/Details/details.scss
- src/components/Table/TableView.js
- src/components/Table/table.scss
- **Consumer groups**: Table width
Jira: https://jira.iguazeng.com/browse/ML-4695
> Fix [Consumer groups] Table width

- src/api/details-api.js
- src/components/Details/details.util.js
- src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
- src/components/Jobs/ScheduledJobs/ScheduledJobs.js
- src/components/Jobs/jobs.util.js
- src/components/Workflow/Workflow.js
- src/constants.js
- src/elements/DeployModelPopUp/DeployModelPopUp.js
- src/elements/NewFunctionPopUp/NewFunctionPopUp.js
- src/elements/NewFunctionPopUp/newFuctionPopUp.util.js
- src/elements/TableTypeCell/TableTypeCell.js
- src/hooks/usePods.hook.js
- src/reducers/artifactsReducer.js
- src/reducers/functionReducer.js
- src/utils/createJobsContent.js
- src/utils/parseJob.js
- src/utils/parseWorkflows.js
- **Jobs**: Print 400 error message when running local job
Jira: https://jira.iguazeng.com/browse/ML-4702
> Fix [Jobs] print 400 error message when running local job

- src/components/JobWizard/JobWizard.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- **Batch run**: Selected function from the project list hint the samefunction from the hub
Backported to `1.5.x` from #1992 
Jira: https://jira.iguazeng.com/browse/ML-4727
> Fix [Batch run] Selected function from the project list hint the same function from the hub `1.5.x`

- src/components/JobWizard/JobWizard.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- **Batch run**: Selected function from the project list hint the samefunction from the hub
Jira: https://jira.iguazeng.com/browse/ML-4727
> Fix [Batch run] Selected function from the project list hint the same function from the hub

- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
- **Feature Sets**: Passthrough popup appears
Jira:https://jira.iguazeng.com/browse/ML-4154
> Fix [Feature Sets] Passthrough popup appears

- src/common/TargetPath/targetPath.util.js
- **Batch run**: The wrong iMessage for dataset input path
Jira: https://jira.iguazeng.com/browse/ML-4731
After:
> Fix [Batch run] The wrong iMessage for dataset input path

- src/components/Jobs/MonitorJobs/MonitorJobs.js
- **Jobs**: Incorrect runs list is loaded after trying to load 'Heavy' runs
Backported to `1.5.x` from #1999 
Jira: https://jira.iguazeng.com/browse/ML-4745
> Fix [Jobs] Incorrect runs list is loaded after trying to load 'Heavy' runs `1.5.x`

- src/components/Jobs/MonitorJobs/MonitorJobs.js
- **Jobs**: Incorrect runs list is loaded after trying to load 'Heavy' runs
Jira: https://jira.iguazeng.com/browse/ML-4745
> Fix [Jobs] Incorrect runs list is loaded after trying to load 'Heavy' runs

- src/common/Notification/Notification.js
- src/common/Notification/NotificationView.js
- src/common/Notification/notificationView.scss
- **Notifications**: Add closing/removing manually
Jira: [ML-4743](https://jira.iguazeng.com/browse/ML-4743)
After:
> Impl [Notifications] Add closing/removing manually

- src/components/JobWizard/JobWizard.util.js
- src/elements/FormDataInputsTable/FormDataInputsRow/FormDataInputsRow.js
- src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
- src/elements/FormVolumesTable/FormVolumesRow/formVolumeRow.scss
- src/scss/main.scss
- **Batch run**: Show function's inputs on re-run and mark mandatory items
1. Define mandatory data inputs and parameters with a red asterisk.
2. Remove the checkbox for mandatory parameters.
3. Disable the "Delete" action for mandatory data inputs.
4. Display all function's data inputs on Re-run.
5. Show mandatory data inputs and parameters at the beginning of the list
Backported to `1.5.x` from #2003 
Jira: [ML-4681](https://jira.iguazeng.com/browse/ML-4681)
> Fix [Batch run] Show function's inputs on re-run and mark mandatory items `1.5.x`

- src/components/JobWizard/JobWizard.util.js
- src/elements/FormDataInputsTable/FormDataInputsRow/FormDataInputsRow.js
- src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
- src/elements/FormVolumesTable/FormVolumesRow/formVolumeRow.scss
- src/scss/main.scss
- **Batch run**: Show function's inputs on re-run and mark mandatory items
1. Define mandatory data inputs and parameters with a red asterisk.
2. Remove the checkbox for mandatory parameters.
3. Disable the "Delete" action for mandatory data inputs.
4. Display all function's data inputs on Re-run.
5. Show mandatory data inputs and parameters at the beginning of the list
Jira: [ML-4681](https://jira.iguazeng.com/browse/ML-4681)
> Fix [Batch run] Show function's inputs on re-run and mark mandatory items

- src/actions/functions.js
- src/components/JobWizard/JobWizard.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- src/components/Jobs/jobs.util.js
- src/hooks/usePods.hook.js
- src/reducers/functionReducer.js
- **Batch run**: Sort function names a-z
Backported to `1.5.x` from #2006 
Jira: https://jira.iguazeng.com/browse/ML-4713
> Fix [Batch run] sort function names a-z `1.5.x`

- src/actions/functions.js
- src/components/JobWizard/JobWizard.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- src/hooks/usePods.hook.js
- src/reducers/functionReducer.js
- **Batch run**: Sort function names a-z
Jira: https://jira.iguazeng.com/browse/ML-4713
> Fix [Batch run] sort function names a-z

- src/components/ModelsPage/RealTimePipelines/RealTimePipelinesView.js
- src/reducers/artifactsReducer.js
- src/utils/getCloseDetailsLink.js
- **Jobs** Go back to list redirects to Overview page
Jira: https://jira.iguazeng.com/browse/ML-4746
> Fix [Jobs] Go back to list redirects to Overview page

- src/components/ArtifactsActionBar/ArtifactsActionBar.js
- src/components/FilterMenuModal/FilterMenuModal.js
- src/components/FilterMenuModal/HubCategoriesFilter/HubCategoriesFilter.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- **Filter**: Add default "Apply" button
Backported to `1.5.x` from #2009 
Jira: https://jira.iguazeng.com/browse/ML-4294
Before:
After:
> Fix [Filter] Add default "Apply" button `1.5.x`

- src/components/ArtifactsActionBar/ArtifactsActionBar.js
- src/components/FilterMenuModal/FilterMenuModal.js
- src/components/FilterMenuModal/HubCategoriesFilter/HubCategoriesFilter.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- **Filter**: Add default "Apply" button
Jira: https://jira.iguazeng.com/browse/ML-4294
Before:
After:
> Fix [Filter] Add default "Apply" button

- src/common/TargetPath/targetPath.util.js
- src/constants.js
- src/elements/FormDataInputsTable/FormDataInputsRow/FormDataInputsRow.js
- **Batch inference**: The model_path input only supports store paths
Jira: https://jira.iguazeng.com/browse/ML-4697
> Fix [Batch inference] The model_path input only supports store paths

- src/common/TargetPath/TargetPath.js
- src/components/JobWizard/JobWizard.util.js
- **Batch Run** App crashes on an attempt to delete Data input
Jira: https://jira.iguazeng.com/browse/ML-4764
> Fix [Batch Run] App crashes on an attempt to delete Data input

- src/common/TargetPath/TargetPath.js
- src/components/JobWizard/JobWizard.util.js
- **Batch Run** App crashes on an attempt to delete Data input
Backported to `1.5.x` from #2014 
Jira: https://jira.iguazeng.com/browse/ML-4764
> Fix [Batch Run] App crashes on an attempt to delete Data input `1.5.x`

- src/elements/FormDataInputsTable/FormDataInputsRow/FormDataInputsRow.js
- src/elements/FormDataInputsTable/FormDataInputsTable.js
- src/elements/FormEnvironmentVariablesTable/FormEnvironmentVariablesRow/FormEnvironmentVariablesRow.js
- src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
- src/elements/FormParametersTable/FormParametersRow/formParametersRow.scss
- src/elements/FormParametersTable/FormParametersTable.js
- src/elements/FormVolumesTable/FormVolumesRow/FormVolumesRow.js
- src/scss/main.scss
- **Batch run**: Require mandatory data inputs and parameters before running the job
Backported to `1.5.x` from #2016 
Jira: [ML-4752](https://jira.iguazeng.com/browse/ML-4752)
> Fix [Batch run] Require mandatory data inputs and parameters before running the job `1.5.x`

- src/elements/FormDataInputsTable/FormDataInputsRow/FormDataInputsRow.js
- src/elements/FormDataInputsTable/FormDataInputsTable.js
- src/elements/FormEnvironmentVariablesTable/FormEnvironmentVariablesRow/FormEnvironmentVariablesRow.js
- src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
- src/elements/FormParametersTable/FormParametersRow/formParametersRow.scss
- src/elements/FormParametersTable/FormParametersTable.js
- src/elements/FormVolumesTable/FormVolumesRow/FormVolumesRow.js
- src/scss/main.scss
- **Batch run**: Require mandatory data inputs and parameters before running the job
Jira: [ML-4752](https://jira.iguazeng.com/browse/ML-4752)
> Fix [Batch run] Require mandatory data inputs and parameters before running the job

- src/App.js
- src/common/Breadcrumbs/breadcrumbs.util.js
- src/common/ProjectDetailsHeader/ProjectDetailsHeader.js
- src/constants.js
- src/elements/ProjectCard/ProjectCardView.js
- src/layout/Navbar/Navbar.utils.js
- **Navigation**: Change project monitoring to be the default project view
Jira: [ML-4667](https://jira.iguazeng.com/browse/ML-4667)
> Impl [Navigation] Change project monitoring to be the default project view

- src/common/ActionsMenu/ActionsMenu.js
- src/common/ActionsMenu/actionsMenu.scss
- src/components/Datasets/Datasets.js
- src/components/Files/Files.js
- src/components/ModelsPage/Models/Models.js
- src/elements/ArtifactsTableRow/ArtifactsTableRow.js
- src/scss/main.scss
- src/utils/copyToClipboard.js
- src/utils/createArtifactsContent.js
- **Quick Links**: Revamp tables quick links and action icons
Jira:https://jira.iguazeng.com/browse/ML-3808
Before:
After:
> Impl [Quick Links] Revamp tables quick links and action icons

- src/components/JobWizard/JobWizard.js
- **Batch Inference**:  Add Tech preview text
Jira: https://jira.iguazeng.com/browse/ML-4781
> Impl [Batch Inference] Add Tech preview text

- src/components/JobWizard/JobWizard.js
- **Batch Inference**:  Add Tech preview text
Backported to `1.5.x` from #2025 
Jira: https://jira.iguazeng.com/browse/ML-4781
> Impl [Batch Inference] Add Tech preview text `1.5.x`

- src/layout/Navbar/Navbar.utils.js
- **Navigation**: Adjust Route to new path
Jira: https://jira.iguazeng.com/browse/ML-4719
> Fix [Navigation] Adjust Route to new path

- src/components/JobWizard/JobWizardSteps/JobWizardParameters/JobWizardParameters.js
- src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
- src/elements/FormParametersTable/FormParametersTable.js
- **Batch run**: "Next" button is disabled when hyperparams selected from file
Jira: [ML-4774](https://jira.iguazeng.com/browse/ML-4774)
> Fix [Batch run] "Next" button is disabled when hyperparams selected from file

- src/components/Project/project.scss
- src/elements/ProjectDataCard/ProjectDataCard.js
- Project monitor: Change quotes to parenthesis
Backported from #2033 
Related to #2024
> Fix [Project monitor] change quotes to parenthesis `1.5.x`

- src/components/Project/project.scss
- src/elements/ProjectDataCard/ProjectDataCard.js
- Project monitor: Change quotes to parenthesis
Related to #2023
> Fix [Project monitor] change quotes to parenthesis

- src/components/Datasets/DatasetsView.js
- src/components/Files/FilesView.js
- src/components/Table/Table.js
- **Table**: Bug with scroll
Jira: https://jira.iguazeng.com/browse/ML-4788
> Fix [Table] Bug with scroll

- src/components/Jobs/MonitorJobs/MonitorJobs.js
- src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
- src/elements/ProjectStatistics/ProjectStatistics.js
- src/reducers/filtersReducer.js
- **Project monitoring**: Wrong filter for running jobs
Jira: https://jira.iguazeng.com/browse/ML-4662
> Fix [UI] Project monitoring - wrong filter for running jobs

- src/common/ActionsMenu/ActionsMenu.js
- src/components/Datasets/Datasets.js
- src/components/FeatureStore/FeatureSets/FeatureSets.js
- src/components/FeatureStore/FeatureVectors/featureVectors.util.js
- src/components/FeatureStore/Features/Features.js
- src/components/Files/Files.js
- src/components/FunctionsPage/Functions.js
- src/components/Jobs/MonitorJobs/monitorJobs.util.js
- src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
- src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
- src/components/ProjectsPage/projectsData.js
- src/components/Table/Table.js
- src/elements/ArtifactsTableRow/ArtifactsTableRow.js
- src/types.js
- **Models/Datasets/Artifacts**: Errors occur on opening actions menu
Jira: https://jira.iguazeng.com/browse/ML-4800
> Fix [Models/Datasets/Artifacts] Errors occur on opening actions menu

- tests/features/common-tools/common-consts.js
- tests/features/common/actions/input-group.action.js
- tests/features/common/actions/table.action.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/jobs-and-workflows.po.js
- tests/features/common/page-objects/side-panel.po.js
- tests/features/datasets.feature
- tests/features/files.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/step-definitions/steps.js
- tests/features/step-definitions/table.steps.js
- tests/mockServer/mock.js
I
1. Added test to Jobs And Workflows feature
- Check click on default interval on simple scheduler in Advanced section
- Jira: ML-4426
II
1. Updated tests on Batch Run feature
- Check next to the side step should be enabled in Batch Run
- Jira: ML-4633
III
Updated test for Jobs And Workflows feature
1. Check redirection to function list from job Overview after deleting ML function
- Jira:ML-4335, 4501
2. Check Batch-Run running after edit GPU limit in Resources section
- Jira: ML-4429
3. Check "Max Iterations", "Max errors" inputs field availability according to the strategy type in Hyperparameter strategy
- Jira: ML-4452, ML-4509
IV
Updated test for Batch Run wizard
1. Check "Custom" strategy is removed as a Hyperparameter strategy in Batch Run
- Jira: ML-4507
2. Check back navigation …
> QA Sprint 148 done

- tests/features/common-tools/common-consts.js
- tests/features/common/actions/input-group.action.js
- tests/features/common/actions/table.action.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/jobs-and-workflows.po.js
- tests/features/common/page-objects/side-panel.po.js
- tests/features/datasets.feature
- tests/features/files.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/step-definitions/steps.js
- tests/features/step-definitions/table.steps.js
- tests/mockServer/mock.js
* Added test to Jobs And Workflows feature
- Check click on default interval on simple scheduler in Advanced section
- Jira: ML-4426
* Updated tests on Batch Run feature
- Check next to the side step should be enabled in Batch Run
- Jira: ML-4633
* Updated test for Jobs And Workflows feature
1. Check redirection to function list from job Overview after deleting ML function
- Jira:ML-4335, 4501
2. Check Batch-Run running after edit GPU limit in Resources section
- Jira: ML-4429
3. Check "Max Iterations", "Max errors" inputs field availability according to the strategy type in Hyperparameter strategy
- Jira: ML-4452
* Updated test for Batch Run wizard
1. Check "Custom" strategy is removed as a Hyperparameter strategy in Batch Run
- Jira: ML-4507
2. Check back navigation from Job overview to …
> Impl [Tests] Sprint 148

- src/components/Jobs/ScheduledJobs/ScheduledJobs.js
- src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
- **ScheduleJobs/Model Endpoints**: UI craches with error
Jira: https://jira.iguazeng.com/browse/ML-4814
> Fix [Schedule Jobs/Model Endpoints] UI craches with error

- src/common/Accordion/Accordion.js
- src/common/ActionsMenu/ActionsMenu.js
- src/common/Breadcrumbs/Breadcrumbs.js
- src/common/KeyValueTable/KeyValueTableView.js
- src/components/ConsumerGroup/ConsumerGroup.js
- src/components/Datasets/Datasets.js
- src/components/Details/DetailsHeader/DetailsHeader.js
- src/components/DetailsArtifacts/DetailsArtifactsView.js
- src/components/DetailsInputs/DetailsInputs.js
- src/components/DetailsPreview/DetailsPreview.js
- src/components/Files/Files.js
- src/components/FilterMenu/FilterMenu.js
- src/components/ModelsPage/Models/Models.js
- src/components/ProjectsPage/ProjectsView.js
- src/elements/FunctionsPanelTitle/FunctionsPanelTitle.js
- src/elements/JobsPanelTitle/JobsPanelTitleView.js
- src/layout/Navbar/Navbar.js
- **UI**: Add data-testid for buttons in models/artifacts/datasets screens
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/204
Jira: [ML-4831](https://jira.iguazeng.com/browse/ML-4831)
> Fix [UI] add data-testid for buttons in models/artifacts/datasets screens

- src/common/ProjectDetailsHeader/ProjectDetailsHeader.js
- src/elements/ProjectDataCard/ProjectDataCard.js
- **Project monitoring, Quick actions**: Change instance name capitalization
Jira: [ML-4812](https://jira.iguazeng.com/browse/ML-4812)
> Fix [Project monitoring, Quick actions] Change instance name capitalization

- src/common/ActionsMenu/actionsMenu.scss
- src/scss/main.scss
- **Models**: Actions aren't aligned
Jira: [ML-4801](https://jira.iguazeng.com/browse/ML-4801)
Before:
After:
> Fix [Models] Actions aren't aligned

- src/elements/FormDataInputsTable/FormDataInputsTable.js
- src/elements/FormParametersTable/FormParametersTable.js
-**Batch run**: is broken for parameters-less functions
Jira: [ML-4860](https://jira.iguazeng.com/browse/ML-4860)
> Fix [Batch run] is broken for parameters-less functions `1.5.x`

- src/components/JobWizard/JobWizard.js
- src/components/JobWizard/JobWizard.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardAdvanced/JobWizardAdvanced.js
- src/components/JobWizard/JobWizardSteps/JobWizardDataInputs/JobWizardDataInputs.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/jobWizardFunctionSelection.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardHyperparameterStrategy/JobWizardHyperparameterStrategy.js
- src/components/JobWizard/JobWizardSteps/JobWizardParameters/JobWizardParameters.js
- src/components/JobWizard/JobWizardSteps/JobWizardResources/JobWizardResources.js
- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- src/constants.js
- src/elements/FormDataInputsTable/FormDataInputsTable.js
- src/elements/FormEnvironmentVariablesTable/FormEnvironmentVariablesTable.js
- src/elements/FormParametersTable/FormParametersTable.js
- src/elements/FormResourcesUnits/FormResourcesUnits.js
- src/elements/FormVolumesTable/FormVolumesTable.js
- **Wizards**: should work as a single logical screen
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/207
Jira: [ML-4664](https://jira.iguazeng.com/browse/ML-4664)
> Impl [Wizards] should work as a single logical screen

- src/elements/EnvironmentVariables/EnvironmentVariables.js
- src/elements/FunctionPanelTopologyModelTable/FunctionPanelTopologyModelTable.js
- src/elements/FunctionsPanelParameters/FunctionsPanelParameters.js
- src/elements/VolumesTable/VolumesTable.js
- **Action menu**: App crash when trying to 'edit' an ML function
Jira: https://jira.iguazeng.com/browse/ML-4856
> Fix [Action menu] App crash when trying to 'edit' an ML function

- src/common/Download/Download.js
- src/components/Datasets/Datasets.js
- src/components/Files/Files.js
- src/components/ModelsPage/Models/Models.js
- **General**: Issue with UI build job
Jira: https://jira.iguazeng.com/browse/ML-3984
> Fix [General] Issue with UI build job

- src/components/JobWizard/JobWizard.util.js
- **Batch Run**: Show function's inputs on re-run
Jira: https://jira.iguazeng.com/browse/ML-4877
> Fix [Batch Run] Show function's inputs on re-run

- src/components/ArtifactInfoSources/ArtifactInfoSources.js
- src/components/ArtifactInfoSources/artifactInfoSources.scss
- src/components/ArtifactsActionBar/ArtifactsActionBar.js
- src/components/Datasets/Datasets.js
- src/components/Datasets/DatasetsView.js
- src/components/Datasets/datasets.util.js
- src/components/DetailsInfo/DetailsInfoView.js
- src/components/DetailsInfo/detailsInfo.scss
- src/components/DetailsInfo/detailsInfo.util.js
- src/components/Files/Files.js
- src/components/Files/FilesView.js
- src/components/Files/files.util.js
- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/Models/ModelsView.js
- src/components/ModelsPage/Models/models.util.js
- src/components/ModelsPage/ModelsPage.context.js
- src/components/ModelsPage/ModelsPage.js
- src/components/Table/TableHead.js
- src/elements/TableLinkCell/tableLinkCell.scss
- src/scss/main.scss
- **Models/Datasets/Artifacts**: change UI according to Figma new design
Jira: https://jira.iguazeng.com/browse/ML-3984, https://jira.iguazeng.com/browse/ML-3983, 
https://jira.iguazeng.com/browse/ML-2921
After:
> Revamp [Models/Datasets/Artifacts] change UI according to Figma new design

- src/components/Table/TableView.js
- src/elements/TableLinkCell/tableLinkCell.scss
- src/scss/main.scss
- **Table**: Workflow name is not expandable
Jira: [ML-4825](https://jira.iguazeng.com/browse/ML-4825)
> Fix [Table] workflow name is not expandable

- src/common/ActionsMenu/ActionsMenu.js
- src/common/ActionsMenu/actionsMenu.scss
- src/components/DetailsResults/detailsResults.scss
- src/components/Table/table.scss
- src/elements/ActionMenuItem/ActionsMenuItem.js
- src/elements/ActionMenuItem/actionsMenuItem.scss
- src/scss/main.scss
- **Action Menu**: Row background color on option hover
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/208
Jira: [ML-4850](https://jira.iguazeng.com/browse/ML-4850)
Before:
After:
> Fix [Action Menu] Row background color on option hover

- src/components/ArtifactsPreview/ArtifactsPreviewController.js
- src/components/ArtifactsPreview/ArtifactsPreviewView.js
- src/components/ArtifactsPreview/artifactsPreview.scss
- src/components/Datasets/DatasetsView.js
- src/components/DetailsArtifacts/DetailsArtifacts.js
- src/components/DetailsArtifacts/detailsArtifacts.scss
- src/components/DetailsArtifacts/detailsArtifacts.util.js
- src/components/DetailsInputs/DetailsInputs.js
- src/components/DetailsInputs/detailsInputs.scss
- src/components/DetailsInputs/detailsInputs.util.js
- src/components/DetailsResults/DetailsResults.js
- src/components/DetailsResults/detailsResults.scss
- src/components/Files/FilesView.js
- src/components/Jobs/Jobs.js
- src/components/ModelsPage/ModelsPage.js
- src/components/Table/table.scss
- src/elements/PreviewModal/PreviewModal.js
- src/hooks/useSortTable.hook.js
- src/layout/Content/Content.js
- src/scss/main.scss
- src/utils/getArtifactPreview.js
- src/utils/resultsTable.js
- **Job Details**: Add header in the Artifact, Input and Result tabs
Jira: [ML-3260](https://jira.iguazeng.com/browse/ML-3260)
> Impl [Job][Details] Add header in the Artifact, Input and Result tabs

- src/httpClient.js
- **API**: browser caching
Jira: [ML-4960](https://jira.iguazeng.com/browse/ML-4960)
> Fix [API] browser caching

- package.json
- tests/features/common-tools/common-consts.js
- tests/features/common/actions/api.actions.js
- tests/features/common/page-objects/feature-store.po.js
- tests/features/common/page-objects/jobs-and-workflows.po.js
- tests/features/common/page-objects/side-panel.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/step-definitions/table.steps.js
- tests/mockServer/data/frontendSpec.json
I
1. Updated tests for HUB functions in Batch Run
- Categories mapping in "Filter by category" of HUB functions in Batch Run 
- Jira: ML-4677
- "Batch-inference" is not shown among Hub functions in Function Selection section of Batch Run 
- Jira: ML-4580
- "Apply" button in "Filter by category" of HUB functions in Batch Run 
- Jira: ML-4294
II
1. Create test for Feature Store
- Check type Redis in online types of Target Store section of Create Set
- Jira: ML-4066, ML-4277
III
1. Updated tests for Dataset 
- UI changes  according to Figma new design (register button, download icon)
- Jira: ML-3984, ML-4215
> QA Sprint 150 done

- package.json
- tests/features/common-tools/common-consts.js
- tests/features/common/actions/api.actions.js
- tests/features/common/page-objects/feature-store.po.js
- tests/features/common/page-objects/jobs-and-workflows.po.js
- tests/features/common/page-objects/side-panel.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/step-definitions/table.steps.js
- tests/mockServer/data/frontendSpec.json
* Update ts for HUB functions in Batch Run
- Categories mapping in "Filter by category" of HUB functions in Batch Run
- Jira: ML-4677
- "Batch-inference" is not shown among Hub functions in Function Selection section of Batch Run
- Jira: ML-4580
- "Apply" button in "Filter by category" of HUB functions in Batch Run
- Jira: ML-4294ests for HUB functions in Batch Run
- Categories mapping in "Filter by category" of HUB functions in Batch Run
- Jira: ML-4677
- "Batch-inference" is not shown among Hub functions in Function Selection section of Batch Run
- Jira: ML-4580
- "Apply" button in "Filter by category" of HUB functions in Batch Run
- Jira: ML-4294
* Create test for Feature Store
- Check type Redis in online types of …
> Impl [Tests] Sprint 150 done

- src/api/projects-iguazio-api.js
- src/components/ProjectSettings/ProjectSettings.js
- src/components/ProjectSettings/projectSettings.util.js
- src/elements/MembersPopUp/membersReducer.js
- src/elements/ProjectSettingsGeneral/projectSettingsGeneral.scss
- src/elements/ProjectSettingsMembers/ProjectSettingsMembers.js
- **Project settings**: Fix members tab display logic
Jira: https://jira.iguazeng.com/browse/ML-4987
Jira: https://jira.iguazeng.com/browse/ML-4961
> Fix [Project settings] Fix members tab display logic

- src/components/Project/ProjectDescription/ProjectDescription.js
- src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
- **Project**: Validation on project's description in UI
Jira: [ML-5049](https://jira.iguazeng.com/browse/ML-5049)
> Fix [Project] Validation on project's description in UI

- src/components/JobWizard/JobWizard.util.js
- src/constants.js
- src/elements/FunctionsPanelCode/FunctionsPanelCode.js
- **New function**: No default for handler
Jira: [ML-5000](https://jira.iguazeng.com/browse/ML-5000)
> Fix [New function] No default for handler

- src/components/Details/details.util.js
- src/components/FunctionsPage/functions.util.js
- src/utils/createFunctionsContent.js
- **Functions**: Default handler is not displayed for functions
Jira: [ML-5020](https://jira.iguazeng.com/browse/ML-5020)
> Fix [Functions] Default handler is not displayed for functions

- src/elements/FunctionsPanelResources/FunctionsPanelResources.js
- src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
- src/utils/parseFunction.js
- **Functions panel**: Show "Volumes" dropdown on function edit
Jira: https://jira.iguazeng.com/browse/ML-4950
> Fix [Functions panel] Show "Volumes" dropdown on function edit

- src/constants.js
- src/elements/ProjectSettingsGeneral/ProjectSettingsGeneralView.js
- src/elements/ProjectSettingsGeneral/projectSettingsGeneral.scss
- src/elements/ProjectSettingsGeneral/projectSettingsGeneral.utils.js
- **Project settings**: does not present Default image of a project
Jira: https://jira.iguazeng.com/browse/ML-5002
After:
> Fix [Project settings] does not present Default image of a project

- src/components/FunctionsPage/Functions.js
- src/components/JobWizard/JobWizard.js
- src/components/JobWizard/JobWizard.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- src/constants.js
- src/utils/generateGroupLatestItem.js
- **Batch run**: Disable version selection on function run
Jira: [ML-4949](https://jira.iguazeng.com/browse/ML-4949)
> Fix [Batch run] Disable version selection on function run

- src/components/ArtifactsPreview/ArtifactsPreview.js
- src/components/ArtifactsPreview/ArtifactsPreviewController.js
- src/components/ArtifactsPreview/artifactsPreview.scss
- src/components/DetailsPreview/DetailsPreview.js
- src/elements/ArtifactExtraData/ArtifactExtraData.js
- src/elements/ArtifactsExtraData/ArtifactsExtraData.js
- src/elements/ArtifactsExtraData/artifactsExtraData.scss
- src/elements/PreviewModal/PreviewModal.js
- src/utils/getArtifactPreview.js
- **Models**: Wrong preview presentation
Jira: https://jira.iguazeng.com/browse/ML-2196
Before: 
After:
> Impl [Models] Wrong preview presentation

- src/elements/ActionMenuItem/ActionsMenuItem.js
- **Projects**: an attempt to delete / archive project redirects to project screen
Jira: https://jira.iguazeng.com/browse/ML-4941
> Fix [Projects] an attempt to delete / archive project redirects to project screen

- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- **Batch run**: Remove the 'No data to show'
Jira: [ML-4866](https://jira.iguazeng.com/browse/ML-4866)
Before:
After:
> Fix [Batch run] remove the 'No data to show'

- src/components/DetailsInputs/DetailsInputs.js
- **Jobs**: UI crash on 'pathname'
Jira: https://jira.iguazeng.com/browse/ML-5183
> Fix [Jobs] UI crash on 'pathname'

- tests/features/common-tools/common-consts.js
- tests/features/common-tools/common-tools.js
- tests/features/common/actions/common.action.js
- tests/features/common/actions/table.action.js
- tests/features/common/components/combo-box.component.js
- tests/features/common/page-objects.js
- tests/features/common/page-objects/feature-store.po.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/side-panel.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/step-definitions/table.steps.js
- tests/mockServer/mock.js
I
Updated tests for Feature Store
- updated tests according to Revamp UI changes
- changed "Apply_Changes_Button" and "Cancel_Button" implementation on Feature Store Info Pane
- Jira:ML-4215
II
Updated tests for Dataset
- changed Register button locator
- changed input hint for validation rules
- updated func deleteTags, putTags on mock
- Jira: ML-4835
- 
III
Updated tests for Feature Store page
> QA Sprint 151 done

- src/elements/ArtifactsExtraData/ArtifactsExtraData.js
- **Models**: Wrong preview presentation Part 1 - fixed bugs with click on name
Jira: https://jira.iguazeng.com/browse/ML-2196
> Fix [Models] Wrong preview presentation Part 1 - fixed bugs with click on name

- src/components/JobWizard/JobWizard.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- **Batch Run**: Missing parameters and data inputs for Hub functions    
Jira: https://jira.iguazeng.com/browse/ML-5262
> Fix [Batch Run] missing parameters and data inputs for Hub functions

- src/components/FeatureSetsPanel/UrlPath.js
- **Feature Store**: UI craches after checking the Partition checkbox.
Jira: https://jira.iguazeng.com/browse/ML-5225
> Fix [Feature Store] UI craches after checking the Partition checkbox.

- src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
- **Feature Store**: "Something went wrong." screen when add Feature Vector
Jira: https://jira.iguazeng.com/browse/ML-5115
> Fix [Feature Store] "Something went wrong." screen when add Feature Vector

- src/components/JobWizard/JobWizard.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- **Train model**: Auto select "auto-trainer" function
Jira: https://jira.iguazeng.com/browse/ML-5272
> Fix [Train model] auto select "auto-trainer" function

- src/api/artifacts-api.js
- src/components/RegisterArtifactModal/RegisterArtifactModal.js
- src/elements/RegisterModelModal/RegisterModelModal.js
- src/httpClient.js
revert https://jira.iguazeng.com/browse/ML-4196 from #1882
> Revert [UI] Use the new artifacts v2 endpoints

- src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
- **Batch run**: Parameters values are deleted after updating type   
Jira: [ML-4535](https://jira.iguazeng.com/browse/ML-4535)
> Fix [Batch run] parameters values are deleted after updating type

- src/components/FeatureStore/featureStore.scss
- src/scss/main.scss
- **Artifacts**: Table header is hidden during table scroll
Jira: [ML-5284](https://jira.iguazeng.com/browse/ML-5284)
> Fix [Artifacts] Table header is hidden during table scroll

- src/components/JobWizard/JobWizard.js
- src/components/JobWizard/JobWizard.util.js
- **Batch run**: Unable to re-run the job
Jira: [ML-5270](https://jira.iguazeng.com/browse/ML-5270)
> Fix [Batch run] unable to re-run the job

- src/components/FeatureSetsPanel/FeatureSetsPanelSchema/FeatureSetsPanelSchema.js
- src/components/FeatureSetsPanel/FeatureSetsPanelSchema/FeatureSetsPanelSchemaView.js
- src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
- **Feature Store**: Features entity creation   
Jira: [ML-5033](https://jira.iguazeng.com/browse/ML-5033)
> Fix [Feature Store] Features entity creation

- src/components/JobWizard/JobWizard.js
- src/components/JobWizard/JobWizard.util.js
- src/components/SheduleWizard/ScheduleWizard.js
- **Batch run**: Incorrect completion message
Jira: [ML-4986](https://jira.iguazeng.com/browse/ML-4986)
> Fix [Batch run] Incorrect completion message

- src/components/DetailsInputs/detailsInputs.util.js
- **Monitor Workflows**: UI crash on attempt to browse "Inputs" tab
Jira: https://jira.iguazeng.com/browse/ML-5244
> Fix [Monitor Workflows] UI crash on attempt to browse "Inputs" tab

- src/common/TargetPath/TargetPath.js
- src/common/TargetPath/targetPath.util.js
- src/components/Datasets/Datasets.js
- src/components/Files/Files.js
- src/components/JobWizard/JobWizard.js
- src/components/JobWizard/JobWizardSteps/JobWizardDataInputs/JobWizardDataInputs.js
- src/components/ModelsPage/Models/Models.js
- src/components/RegisterArtifactModal/RegisterArtifactModal.js
- src/elements/FormDataInputsTable/FormDataInputsRow/FormDataInputsRow.js
- src/elements/FormDataInputsTable/FormDataInputsTable.js
- src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
- src/elements/RegisterModelModal/RegisterModelModal.js
- src/utils/panelPathScheme.js
- **Batch Run**: Add "Current project" to MLRun Store Path Scheme autocoplete
Jira: https://jira.iguazeng.com/browse/ML-4978
After:
> Impl [Batch Run] Add "Current project" to MLRun Store Path Scheme autocoplete

- src/components/Datasets/datasets.util.js
- src/components/JobWizard/JobWizard.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- **Model Train**: display dataset URL conditionally
Jira: https://jira.iguazeng.com/browse/ML-5234
> Fix [Model Train] display dataset URL conditionally

- src/actions/functions.js
- src/components/Details/details.scss
- src/components/DetailsLogs/DetailsLogs.js
- src/components/FunctionsPage/Functions.js
- src/components/FunctionsPage/functions.util.js
- src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
- src/components/Project/ProjectMonitor.js
- src/utils/getFunctionLogs.js
- **Build logs**: Logs refresh is blinking too fast   
Jira: https://jira.iguazeng.com/browse/ML-4964
> Fix [Build logs] Logs refresh is blinking too fast

- src/constants.js
- **General**: Increase cancel request timeout from 60sec to 2min   
Jira: [ML-5087](https://jira.iguazeng.com/browse/ML-5087)
> Fix [General] Increase cancel request timeout from 60sec to 2min

- src/components/Table/table.scss
- **Datasets Preview**: data displaying issue
Jira: https://jira.iguazeng.com/browse/ML-5074
> Fix [Datasets][Preview] data displaying issue

- src/utils/createArtifactPreviewContent.js
- **Artifact preview**: Artifacts with "sql" extension are not previewed
Jira: [ML-4896](https://jira.iguazeng.com/browse/ML-4896)
> Fix [Artifact preview] Artifacts with "sql" extension are not previewed

- tests/features/MLFunction.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/actions/action-menu.action.js
- tests/features/common/actions/input-group.action.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/jobs-and-workflows.po.js
- tests/features/common/page-objects/models.po.js
- tests/features/common/page-objects/project.po.js
- tests/features/common/page-objects/projects.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/files.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/projectHomePage.feature
- tests/features/projectSettings.feature
- tests/features/projectsPage.feature
- tests/features/step-definitions/steps.js
- tests/features/step-definitions/table.steps.js
- tests/mockServer/data/iguazioSelf.json
- tests/mockServer/mock.js
І
- Models, Artifacts, Datasets - added check Preview, Deploy button
- Models, Artifacts, Datasets - added check Pop_Out_Button on Preview tab
- Models, Artifacts, Datasets - added check delete options state
- Models - added overview Producer and Sources Headers
- Register Models - added new path input implementation
- mock - updated postArtifact func with model_file param
- Jira: ML-4506
ІІ
- redirection to Project monitoring page
- redirection to Quick actions page
- mock - created deleteRun func according to new delete jobs API
- mock - created deleteArtifact func according to new delete artifacts API
- mock - created getIguazioSelf func
- Jira: ML-5161, ML-4667
> QA Sprint 153 done

- tests/features/MLFunction.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/actions/action-menu.action.js
- tests/features/common/actions/input-group.action.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/jobs-and-workflows.po.js
- tests/features/common/page-objects/models.po.js
- tests/features/common/page-objects/project.po.js
- tests/features/common/page-objects/projects.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/files.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/projectHomePage.feature
- tests/features/projectSettings.feature
- tests/features/projectsPage.feature
- tests/features/step-definitions/steps.js
- tests/features/step-definitions/table.steps.js
- tests/mockServer/data/iguazioSelf.json
- tests/mockServer/mock.js
**Collecting PRs into branch **development** from branch **tests**:**
* Updated tests according to requirements
- Models, Artifacts, Datasets - added check Preview, Deploy button
- Models, Artifacts, Datasets - added check Pop_Out_Button on Preview tab
- Models, Artifacts, Datasets - added check delete options state
- Models - added overview Producer and Sources Headers
- Register Models - added new puth input implementation
- mock - updated postArtifact func with model_file param
- Jira: ML-4506
* Updated tests according to requirements
- redirection to Project monitoring page
- redirection to Quick actions page
- mock - created deleteRun func according to new delete jobs API
- mock - created deleteArtifact func according to new delete artifacts API
- mock - created getIguazioSelf func
- …
> Impl [Tests] QA Sprint 153 done

- src/components/JobWizard/JobWizard.js
- src/components/JobWizard/JobWizard.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- **Train model**: Auto select "auto-trainer" function with "train" handler
Jira: https://jira.iguazeng.com/browse/ML-5328
> Fix [Train model] auto select "auto-trainer" function with "train" handler

- src/components/JobWizard/JobWizard.util.js
- **Train model**: Validation fails for auto populated dataset
Jira: https://jira.iguazeng.com/browse/ML-5333
> Fix [Train model] validation fails for auto populated dataset

- src/components/Project/ProjectMonitor.js
- **Project monitoring**: UI crash upon click on "Register artifact" via "Create new" dropdown
Jira: [ML-5354](https://jira.iguazeng.com/browse/ML-5354)
> Fix [Project monitoring] UI crash upon click on "Register artifact" via "Create new" dropdown

- src/components/JobWizard/JobWizard.util.js
- **Batch Re-run**: data inputs should be checked if they were used in running the job
Jira: https://jira.iguazeng.com/browse/ML-5344
> Fix [Batch Re-run] data inputs should be checked if they were used in running the job

- src/components/ArtifactsPreview/artifactsPreview.scss
- **Artifacts Preview**: Wrong table size
Jira: https://jira.iguazeng.com/browse/ML-5086
> Fix [Artifacts Preview] Wrong table size

- src/elements/PreviewModal/PreviewModal.js
- **Monitor Jobs**: App crashes on Preview icon click
Jira: https://jira.iguazeng.com/browse/ML-5267
> Fix [Monitor Jobs] App crashes on  Preview icon click

- src/components/JobWizard/JobWizard.util.js
- src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
- src/elements/FormParametersTable/formParametersTable.util.js
- **Batch Run**: Change map to dict in parameters types
Jira: [ML-4750](https://jira.iguazeng.com/browse/ML-4750)
> Fix [Batch Run] change map to dict in parameters types

- src/components/JobWizard/JobWizard.util.js
- src/utils/generateTemplatesCategories.js
- **Batch run**: Align "function templates" with the "functions hub"
Jira: [ML-3672](https://jira.iguazeng.com/browse/ML-3672)
> Fix [Batch run] Align "function templates" with the "functions hub"

- src/elements/ActionMenuItem/actionsMenuItem.scss
- **Artifacts**: Change text color of disabled Delete button to gray
Jira: [ML-5285](https://jira.iguazeng.com/browse/ML-5285)
> Fix [Artifacts] Change text color of disabled Delete button to gray

- src/components/FilterMenuModal/FilterMenuModal.js
- src/components/JobWizard/JobWizard.js
- **Batch run**: UI crash with "getBoundingClientRect"
Jira: [ML-5355](https://jira.iguazeng.com/browse/ML-5355)
> Fix [Batch run] UI crash with "getBoundingClientRect"

- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/Models/models.util.js
- src/components/Table/Table.js
- src/components/Table/TableHead.js
- src/components/Table/TableView.js
- src/scss/main.scss
- src/utils/createArtifactsContent.js
- **Models**: data displaying issue
Jira: https://jira.iguazeng.com/browse/ML-5073
> Fix [Models] data displaying issue

- src/components/Datasets/datasets.util.js
- src/components/Details/details.util.js
- **Datasets:** label_column should be added to Dataset details panel
Jira: [ML-5100](https://jira.iguazeng.com/browse/ML-5100)
After:
> Impl [Datasets] label_column should be added to Dataset details panel

- src/components/Project/ProjectOverview/ProjectOverview.util.js
- **Quick actions**: crash upon click on Register artifact/dataset
Jira: https://jira.iguazeng.com/browse/ML-5377
> Fix [Quick actions] crash upon click on Register artifact/dataset

- src/components/FunctionsPage/Functions.js
- **ML functions**: Function selection issue with same hash
Jira: [ML-5066](https://jira.iguazeng.com/browse/ML-5066)
> Fix [ML functions] Function selection issue with same hash

- src/components/FeatureStore/FeatureVectors/FeatureVectors.js
- src/components/FeatureStore/FeatureVectors/featureVectors.util.js
- **Feature Vectors**: Error after expanding Feature Vectors item
Jira: [ML-4930](https://jira.iguazeng.com/browse/ML-4930)
> Fix [Feature Vectors] Error after expanding Feature Vectors item

- src/components/Jobs/MonitorJobs/monitorJobs.util.js
- src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
- src/components/Jobs/jobs.util.js
- **Jobs**: "Delete" option should be hidden in the Action menu , when the job has status: Running/Pending
Jira: https://jira.iguazeng.com/browse/ML-5315
> Fix [Jobs] "Delete" option should be hidden in the Action menu , when the job has status: Running/Pending

- src/components/DetailsPreview/DetailsPreview.js
- **Feature sets**: UI crash on attempt to preview feature set
Jira: https://jira.iguazeng.com/browse/ML-5151
> Fix [Feature sets] UI crash on attempt to preview feature set

- src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
- src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.js
- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/ModelsPage.context.js
- **Model endpoint**: There should be a link to open Grafana and view full details
Jira: [ML-4573](https://jira.iguazeng.com/browse/ML-4573)
Before:
After:
> Impl [Model endpoint] there should be a link to open Grafana and view full details

- src/scss/main.scss
- **Artifacts**: Show actions when table has horizontal scroll
Jira: [ML-5393](https://jira.iguazeng.com/browse/ML-5393)
Before:
After:
> Fix [Artifacts] Show actions when table has horizontal scroll

- src/components/Table/Table.js
- **Feature Vectors**: UI crash upon searching by entity during feature vector creation
Jira: [ML-5381](https://jira.iguazeng.com/browse/ML-5381)
> Fix [Feature Vectors] UI crash upon searching by entity during feature vector creation

- src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
-**Feature Vectors**: UI crash upon expanding feature during feature vector creation
Jira: [ML-5380](https://jira.iguazeng.com/browse/ML-5380)
> Fix [Feature Vectors] UI crash upon expanding feature during feature vector creation

- src/api/artifacts-api.js
- src/reducers/artifactsReducer.js
- src/utils/handleDeleteArtifact.js
- **Artifacts**: New artifact v2 api for artifact delete
Jira: https://jira.iguazeng.com/browse/ML-5369
> Impl [Artifacts] New artifact v2 api for artifact delete

- tests/features/common-tools/common-consts.js
- tests/features/common/actions/api.actions.js
- tests/features/common/page-objects.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/jobs-and-workflows.po.js
- tests/features/featureStore.feature
- tests/features/jobsAndWorkflows.feature
- tests/mockServer/mock.js
I
Updated tests according to requirement Batch Run as a single screen, delete jobs option
- updated tests - changed action menu options for Ready, Error, Running, Pending job states
- updated tests - changed Overview headers on Jobs monitor info pane
- added tests for Delete confirmation pop-up
- updated tests - check Batch Run steps visible/enable
- Jira: ML-4664
II
Updated tests according to requirement
- updated tests - added check the notification pop-up on Feature vector creation 
- updated tests on Feature Store page
- updated tests on Jobs and Workflows page
- mock - updateed new artifacts v2 endpoints
- mock - updated register artifact postArtifact func
- mock - updated deleteArtifact func
- Jira: ML-4196, ML-4916
> QA Sprint 154 done

- src/utils/handleDeleteArtifact.js
- **Artifacts, Datasets, Models**: Successful deletion notification message
Jira: [ML-5206](https://jira.iguazeng.com/browse/ML-5206)
> Fix [Artifacts, Datasets, Models] successful deletion notification message

- src/components/Datasets/datasets.util.js
- src/components/Files/files.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- src/components/ModelsPage/Models/models.util.js
- **Artifacts**: missing delete confirmation message
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/221
Jira: [ML-5205](https://jira.iguazeng.com/browse/ML-5205)
> Fix [Artifacts] missing delete confirmation message

- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- **Batch run**: Fix labels validation
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/223
Jira: [ML-5440](https://jira.iguazeng.com/browse/ML-5440)
> Fix [Batch run] fix labels validation

- src/utils/artifacts.util.js
- **Datasets**: Change notification message on removing the tag
Jira: [ML-5406](https://jira.iguazeng.com/browse/ML-5406)
> Fix [Datasets] Change notification message on removing the tag

- src/components/Datasets/Datasets.js
- src/components/Files/Files.js
- src/components/ModelsPage/Models/models.util.js
- src/elements/ArtifactsTableRow/ArtifactsTableRow.js
- src/hooks/useSortTable.hook.js
- **Models**: Page stuck in a loading state
Jira: https://jira.iguazeng.com/browse/ML-5376
> [Fix [Models] Page stuck in a loading state

- src/components/DetailsResults/DetailsResults.js
- src/components/Table/TableHead.js
- **Table**: Remove unnecessary class from table header
Jira: https://jira.iguazeng.com/browse/ML-5364
> Fix [Table] Remove unnecessary class from table header

- src/components/Details/details.scss
- src/components/DetailsPreview/DetailsPreview.js
- src/elements/PreviewModal/PreviewModal.js
- src/elements/PreviewModal/previewModal.scss
- **Dataset**: Add indication to dataset preview
Jira: https://jira.iguazeng.com/browse/ML-5365
> Fix [Dataset] Add indication to dataset preview

- src/components/ProjectSettings/ProjectSettings.js
- src/components/ProjectSettings/projectSettings.util.js
- src/constants.js
- src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
- src/elements/MembersPopUp/MembersPopUp.js
- src/elements/MembersPopUp/membersPopUp.util.js
- src/elements/ProjectSettingsMembers/ProjectSettingsMembers.js
- src/elements/ProjectSettingsMembers/ProjectSettingsMembers.scss
- **Project Settings**: Members screen - does not take into account the owner
Jira: https://jira.iguazeng.com/browse/ML-4961
> Fix [Project settings] Members screen - does not take into account the owner

- src/components/FunctionsPage/Functions.js
- src/components/Jobs/MonitorJobs/MonitorJobs.js
- **Jobs**: Add message in case of accessing deleted item
Jira: [ML-4759](https://jira.iguazeng.com/browse/ML-4759)
> Fix [Jobs|Funcs] Add message in case of accessing deleted item

- src/actions/jobs.js
- src/components/Jobs/jobs.util.js
- **Job Overview**: Wrong function tags list
Jira: [ML-5489](https://jira.iguazeng.com/browse/ML-5489)
> Fix [Job Overview] Wrong function tags list

- src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
- src/components/FeatureSetsPanel/ScheduleFeatureSet/ScheduleFeatureSet.js
- src/components/FilterMenuModal/FilterMenuModal.js
- src/components/ScheduleJob/ScheduleJob.js
- src/utils/getDefaultSchedule.js
- **Feature Store**: Schedule content doesn't match the customized data
Jira: https://jira.iguazeng.com/browse/ML-5085
> Fix [Feature Store] Schedule content doesn't match the customized data

- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitle.js
- **Feature Store**: Target store and Passthrough checkboxes don't work properly after closing pop-up dialog
Jira: https://jira.iguazeng.com/browse/ML-4813
> Fix [Feature Store] Target store and Passthrough checkboxes don't work properly after closing pop-up dialog

- src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
- src/utils/createArtifactsContent.js
- **Model endpoints**: incorrect version definition
Jira: https://jira.iguazeng.com/browse/ML-5487
> Fix [Model endpoints] incorrect version definition

- src/elements/TableLinkCell/TableLinkCell.js
- **Datasets**: Dataset tag doesn't display on Datasets table in Name column
Jira: https://jira.iguazeng.com/browse/ML-5467
> Fix [Datasets] Dataset tag doesn't display on Datasets table in Name column

- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/files.feature
- tests/features/projectHomePage.feature
- tests/features/projectsPage.feature
- tests/mockServer/mock.js
I
Updated tests for Train model wizard
- Jira: ML-5328, ML-5234, ML-5333
II
- changed uniqueness validation and for Register artifact, Register dataset
- update messages for Register artifact, Register dataset
- updated mock server functions related to edit and delete tags according to new implementation
- removed the label value validation rules Batch Run wizard
- changed message Tag to Version Tag feature store, feature vector
- added check label validation rules on Create new project pop-up
- Jira: ML-4927, ML-4916, ML-5440, ML-4835
> QA Sprint 156 done

- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/Models/models.util.js
- src/components/Table/TableHead.js
- src/utils/createArtifactsContent.js
- **Models**: data displaying issue (headers)
Jira: https://jira.iguazeng.com/browse/ML-5073
> Fix [Models] data displaying issue (headers)

- src/reducers/artifactsReducer.js
- **Batch Run,Feature Store**: Offered tag for autofilled dataset store path does not match with dataset tag
Jira: https://jira.iguazeng.com/browse/ML-4773
> Fix [Batch Run][Feature Store] Offered tag for autofilled dataset store path does not match with dataset tag

- src/elements/FeatureValidator/FeatureValidator.js
- src/elements/FeatureValidator/featureValidatior.utils.js
- src/utils/createFeatureStoreContent.js
- **Features**: feature validator severity (warning and error) missing severity name
Jira: [ML-5575](https://jira.iguazeng.com/browse/ML-5575)
> Fix [Features] feature validator severity (warning and error) missing severity name

- package.json
- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/side-panel.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/files.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/step-definitions/table.steps.js
- tests/mockServer/mock.js
Updated tests on Feature Store, Jobs and Workflows, Datasets, Artifacts pages
- Updated Schedule content on Feature Store (ML-5085)
- Updated test with redirection (invalid project name on Datasets, Artifacts, Feature Store) (ML-4600)
- Updated mock with adding deleteRuns func
- Updated deleteArtifacts func on mock
- Updated tests on Jobs and Workflows page (locators for: Job Logs container, Logs refresh button, preview button, added sorter name button, Inputs Table, Artifacts Table, Results tab on Workflow List View; batch run - common wizard)
- Updated tests on Datasets page (train models - common wizard)
> QA Sprint 157 done 

- package.json
- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/side-panel.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/files.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/step-definitions/table.steps.js
- tests/mockServer/mock.js
> Impl [Tests] QA Sprint 157 done

- src/actions/projects.js
- src/api/jobs-api.js
- src/api/projects-api.js
- **Jobs**: Change 'runs' endpoint 'project name'
Fixed:
- Current API request: "/api/v1/runs?project={project name}"
- Required API request: "/api/v1/projects/{project name}/runs"
Jira: [ML-5331](https://jira.iguazeng.com/browse/ML-5331)
> Fix [Jobs] Change 'runs' endpoint 'project name'

- src/elements/PreviewModal/PreviewModal.js
- src/elements/PreviewModal/previewModal.scss
- src/elements/TableCell/TableCell.js
- src/utils/createArtifactsContent.js
- **Artifacts**: apply prettyBytes method for the file size on the preview and list view
Jira: https://jira.iguazeng.com/browse/ML-5465
> Fix [Artifacts] different file size on the preview and list view

- src/api/artifacts-api.js
- src/common/FormTagFilter/FormTagFilter.js
- src/common/FormTagFilter/formTagFilters.scss
- src/components/ArtifactsActionBar/ArtifactsActionBar.js
- src/components/ArtifactsActionBar/ArtifactsFilters.js
- src/components/Datasets/Datasets.js
- src/components/Datasets/DatasetsView.js
- src/components/Files/Files.js
- src/components/Files/FilesView.js
- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/Models/ModelsView.js
- src/hooks/useGetTagOptions.hook.js
- **Artifacts | Models | Datasets**: artifacts screen needs to change BE query behavior
Jira: https://jira.iguazeng.com/browse/ML-5314
> Impl [Artifacts][Models][Datasets] artifacts screen needs to change BE query behavior

- package.json
- src/common/TargetPath/targetPath.util.js
- **Batch Run**: Blank project screen after setting model target path
Jira: [ML-5591](https://jira.iguazeng.com/browse/ML-5591)
> Fix [Batch Run] Blank project screen after setting model target path

- src/api/artifacts-api.js
- src/common/FormTagFilter/FormTagFilter.js
- src/common/FormTagFilter/formTagFilters.scss
- src/components/ArtifactsActionBar/ArtifactsActionBar.js
- src/components/ArtifactsActionBar/ArtifactsFilters.js
- src/components/Datasets/Datasets.js
- src/components/Datasets/DatasetsView.js
- src/components/Files/Files.js
- src/components/Files/FilesView.js
- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/Models/ModelsView.js
- src/hooks/useGetTagOptions.hook.js
- **Artifacts | Models | Datasets**: artifacts screen needs to change BE query behavior
Backported to 1.6.x from #2224 
Jira: https://jira.iguazeng.com/browse/ML-5314
> Impl [Artifacts][Models][Datasets] artifacts screen needs to change BE query behavior `1.6.x`

- src/components/ModelsPage/Models/Models.js
- src/utils/createArtifactsContent.js
- **Models**: data displaying issue (reverted to the chips column)
Jira: https://jira.iguazeng.com/browse/ML-5073
> Fix [Models] data displaying issue (reverted to the chips column)

- src/components/ModelsPage/Models/Models.js
- src/utils/createArtifactsContent.js
- **Models**: data displaying issue (reverted to the chips column)
Backported to `1.6.x` from #2229 
Jira: https://jira.iguazeng.com/browse/ML-5073
> Fix [Models] data displaying issue (reverted to the chips column) `1.6.x`

- src/actions/jobs.js
- src/api/jobs-api.js
- src/api/tasks-api.js
- src/components/Jobs/MonitorJobs/MonitorJobs.js
- src/components/Jobs/MonitorJobs/monitorJobs.util.js
- src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
- src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
- src/components/Jobs/jobs.util.js
- src/httpClient.js
- src/scss/main.scss
- src/utils/getState.js
- src/utils/parseJob.js
- src/utils/poll.util.js
- tests/mockServer/mock.js
- **UI**: Use abort_job endpoint to abort jobs from UI
Backportred to `1.6.x` from #2233 
Jira: https://jira.iguazeng.com/browse/ML-5044
> Fix [UI] Use abort_job endpoint to abort jobs from UI `1.6.x`

- src/actions/projects.js
- src/api/projects-api.js
- src/api/tasks-api.js
- src/components/ProjectsPage/Projects.js
- src/components/ProjectsPage/ProjectsView.js
- src/components/ProjectsPage/projects.util.js
- src/reducers/tasksReducer.js
- src/scss/main.scss
- src/store/toolkitStore.js
- src/utils/poll.util.js
- tests/mockServer/mock.js
- **Projects** new API for project deletion
Jira: [ML-5587](https://jira.iguazeng.com/browse/ML-5587)
> Impl [Projects] new API for project deletion

- src/actions/projects.js
- src/api/projects-api.js
- src/api/tasks-api.js
- src/components/ProjectsPage/Projects.js
- src/components/ProjectsPage/ProjectsView.js
- src/components/ProjectsPage/projects.util.js
- src/reducers/tasksReducer.js
- src/scss/main.scss
- src/store/toolkitStore.js
- src/utils/poll.util.js
- tests/mockServer/mock.js
- **Projects** new API for project deletion
Backported to `1.6.x` from #2236 
Jira: [ML-5587](https://jira.iguazeng.com/browse/ML-5587)
> Impl [Projects] new API for project deletion `1.6.x`

- src/components/JobWizard/JobWizard.util.js
- **Batch Run**: job pod fails to mount fuse when ran via UI
Jira: https://jira.iguazeng.com/browse/ML-5599
> Fix [Batch Run] job pod fails to mount fuse when ran via UI

- src/components/FilterMenu/FilterMenu.js
- src/components/Jobs/MonitorJobs/MonitorJobs.js
- src/constants.js
- src/scss/main.scss
- **Jobs**: Auto refresh screen not worked 
Backported to `1.6.x` from #2235 
Jira: https://jira.iguazeng.com/browse/ML-4968
> Fix [Jobs] Auto refresh screen not worked `1.6.x`

- src/components/FilterMenu/FilterMenu.js
- src/components/Jobs/MonitorJobs/MonitorJobs.js
- src/constants.js
- **Jobs**: Auto refresh screen not worked 
Jira: https://jira.iguazeng.com/browse/ML-4968
> Fix [Jobs] Auto refresh screen not worked

- src/common/ActionsMenu/ActionsMenu.js
- src/components/CreateJobPage/CreateJobPage.js
- src/components/FunctionsPage/Functions.js
- src/components/FunctionsPage/FunctionsView.js
- src/components/FunctionsPage/functions.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- src/components/Jobs/MonitorJobs/monitorJobs.util.js
- src/components/Jobs/jobs.util.js
- src/constants.js
- src/elements/FunctionsTableRow/FunctionsTableRow.js
- src/utils/generateTemplatesCategories.js
- **Functions**: Functions created by SDK are in initialized state in the UI and need to be deployed
Backported to `1.6.x` from #2248 
Jira: https://jira.iguazeng.com/browse/ML-4956
> Impl [Functions] Functions created by SDK are in initialized state in the UI and need to be deployed `1.6.x`

- src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js
- **Functions**: Edit source button ui not aligned
> Fix [Functions] Edit source button ui

- src/utils/createArtifactsContent.js
- **Models**: unable to navigate to additional metrics (+)
Jira: https://jira.iguazeng.com/browse/ML-5663
> Fix [Models] unable to navigate to additional metrics (+)

- src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
- src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
- src/reducers/artifactsReducer.js
- **Artifacts**: page loader is getting stuck upon artifact register
Jira: [ML-5475](https://jira.iguazeng.com/browse/ML-5475)
> Fix [Artifacts] page loader is getting stuck upon artifact register

- src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
- src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
- src/reducers/artifactsReducer.js
- **Artifacts**: page loader is getting stuck upon artifact register
Backported to `1.6.x` from #2252 
Jira: [ML-5475](https://jira.iguazeng.com/browse/ML-5475)
> Fix [Artifacts] page loader is getting stuck upon artifact register `1.6.x`

- src/components/Datasets/datasets.util.js
- src/components/Files/files.util.js
- src/components/ModelsPage/Models/models.util.js
- **Artifacts**: Add tooltip for disabled Delete action
Jira: [ML-5248](https://jira.iguazeng.com/browse/ML-5248)
> Fix [Artifacts] Add tooltip for disabled Delete action

- src/components/Datasets/datasets.util.js
- src/components/Files/files.util.js
- src/components/ModelsPage/Models/models.util.js
- **Artifacts**: Add tooltip for disabled Delete action
Backported to `1.6.x` from #2254 
Jira: [ML-5248](https://jira.iguazeng.com/browse/ML-5248)
> Fix [Artifacts] Add tooltip for disabled Delete action `1.6.x`

- src/utils/createArtifactsContent.js
- src/utils/object.js
- src/utils/roundFloats.js
- **Model training**: model batch run scores are rounded in results view and not in models
Jira: https://jira.iguazeng.com/browse/ML-5455
> Fix [Model training] model batch run scores are rounded in results view and not in models

- src/utils/createArtifactsContent.js
- src/utils/object.js
- src/utils/roundFloats.js
- tests/mockServer/mock.js
- **Model training**: model batch run scores are rounded in results view and not in models
Backported to `1.6.x` from #2256 
Jira: https://jira.iguazeng.com/browse/ML-5455
> Fix [Model training] model batch run scores are rounded in results view and not in models `1.6.x`

- src/components/Jobs/MonitorJobs/MonitorJobs.js
- src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
- **Jobs**: change Abort Job confirm message
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/232
Jira: https://jira.iguazeng.com/browse/ML-4857
After:
> Fix [Jobs] change Abort Job confirm message

- src/utils/getNoDataMessage.js
- **General**: text on data query when there is no relevant data
Jira: https://jira.iguazeng.com/browse/ML-5308
> Fix [General] text on data query when there is no relevant data

- src/components/Datasets/Datasets.js
- **Datasets**: request is not sent when changing project via breadcrumbs
Jira: https://jira.iguazeng.com/browse/ML-5683
> Fix [Datasets] request is not sent when changing project via breadcrumbs

- src/common/DatePicker/DatePicker.js
- src/common/DatePicker/DatePickerView.js
- src/common/DatePicker/datePicker.scss
-  **Datepicker**: Position should use window size
Jira: https://jira.iguazeng.com/browse/ML-5569
> Fix [Datepicker] position should use window size

- src/components/Jobs/MonitorJobs/MonitorJobs.js
- src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
- src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
- src/components/Jobs/jobs.util.js
- **Jobs**: Change Abort Job confirm message
Backported to `1.6.x` from #2271 
Jira: https://jira.iguazeng.com/browse/ML-4857
> Fix [Jobs] change Abort Job confirm message `1.6.x`

- src/components/ProjectsPage/projects.util.js
- **Projects**: Present the root cause when project deletion fails
Jira: [ML-5707](https://jira.iguazeng.com/browse/ML-5707)
> Fix [Projects] Present the root cause when project deletion fails

- src/api/artifacts-api.js
- src/components/Datasets/Datasets.js
- src/components/Files/Files.js
- src/components/ModelsPage/Models/Models.js
- src/hooks/useGetTagOptions.hook.js
- src/reducers/artifactsReducer.js
- src/reducers/filtersReducer.js
- **Artifacts**: artifact-tags requests are not canceled when changing pages
Jira: https://jira.iguazeng.com/browse/ML-5690
> Fix [Artifacts] artifact-tags requests are not canceled when changing pages

- src/components/FunctionsPage/Functions.js
- src/components/FunctionsPage/functions.util.js
- **Functions**: removed "Run and build" quick action
Revert partial changes from #2249 
Jira: [ML-4956](https://jira.iguazeng.com/browse/ML-4956)
> Revert [Functions] Functions created by SDK are in initialized state in the UI and need to be deployed `1.6.x`

- src/components/FunctionsPage/functions.util.js
- **Functions**: move 'Deploy' button for "Serving" function to demo mode
Jira: https://jira.iguazeng.com/browse/ML-5718
> Impl [Functions] move 'Deploy' button for "Serving" function to demo mode `1.6.x`

- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/Models/models.util.js
- **Models**: bad code snippet in "Failed to deploy model" dialog
Jira: https://jira.iguazeng.com/browse/ML-5699
> Fix [Models] bad code snippet in "Failed to deploy model" dialog

- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/Models/models.util.js
- **Models**: bad code snippet in "Failed to deploy model" dialog
Backported to `1.6.x` from #2283 
Jira: https://jira.iguazeng.com/browse/ML-5699
> Fix [Models] bad code snippet in "Failed to deploy model" dialog `1.6.x`

- src/components/Jobs/MonitorJobs/MonitorJobs.js
- **Jobs**: Job overview details panel doesn't display using browsers forward button
Jira: https://jira.iguazeng.com/browse/ML-4775
> Fix [Jobs] Job overview details panel doesn't display using browsers forward button

- src/elements/RealTimePipelinesTableRow/RealTimePipelinesTableRow.js
- **Real-Time Pipelines**: Broken link to function overview
Jira: https://jira.iguazeng.com/browse/ML-5709
> Fix [Real-Time Pipelines] Broken link to function overview

- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/projectMonitoring.feature
- tests/features/quickActions.feature
- tests/features/step-definitions/table.steps.js
- tests/mockServer/mock.js
I
Updated test on Models page (ML-3584, ML-3983, ML-3808)
- updated Overview General Headers, Overview Drift Headers, Overview Sources Headers
- added putArtifact func on mock
- updated Deploy in quick links, deploy pop-up
II
new APIs
- for project deletion
- for abort job
- (commits #2236, #2262)
> QA Sprint 159 done

- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/projectMonitoring.feature
- tests/features/quickActions.feature
- tests/features/step-definitions/table.steps.js
- tests/mockServer/mock.js
* Updated tests on Models page (ML-3584, ML-3983, ML-3808)
- updated Overview General Headers, Overview Drift Headers, Overview Sources Headers
- added putArtifact func o.n mock
- updated Deploy in quick links, deploy pop-up
* new APIs
- for project deletion
- for abort job
- (commits #2236, #2262)
---------
> Impl [Tests] QA Sprint 159 done

- src/utils/panelPathScheme.js
- **Feature sets**: The Wrong validation error for incorrect datasourceformat
Jira: https://jira.iguazeng.com/browse/ML-5757
> Fix [Feature sets] The Wrong validation error for incorrect datasource format

- src/components/Project/ProjectOverview/ProjectOverview.util.js
- src/components/RegisterArtifactModal/RegisterArtifactModal.js
- **Quick Actions**: Redundant 'Are you sure?' pop-up on Register artifacts form
Jira: https://jira.iguazeng.com/browse/ML-5748
> Fix [Quick Actions] Redundant 'Are you sure?' pop-up on Register artifacts form

- src/components/DetailsArtifacts/detailsArtifacts.util.js
- **Job Artifacts**: incorrect Show Details link
Jira: https://jira.iguazeng.com/browse/ML-5773
> Fix [Job Artifacts] incorrect Show Details link

- src/components/ArtifactsActionBar/ArtifactsActionBar.js
- src/components/FilterMenuModal/FilterMenuModal.js
- src/hooks/useGetTagOptions.hook.js
- **Artifacts**: incorrect filter display after page refresh
Jira:https://jira.iguazeng.com/browse/ML-5780
> Fix [Artifacts] incorrect filter display after page refresh

- src/common/TargetPath/targetPath.util.js
- src/utils/panelPathScheme.js
- **Feature sets/Batch run**: The Wrong validation error for incorrect datasource format 
Jira: https://jira.iguazeng.com/browse/ML-5757
> Fix [Feature sets][Batch run] The Wrong validation error for incorrect datasource format 

- src/components/ProjectsPage/projects.util.js
- Projects: Redundant single quotes in delete project message
Jira: https://jira.iguazeng.com/browse/ML-5715
> Fix [Projects] Redundant single quotes in delete project message

- src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
- **Monitor Workflows**: Change title on Batch re-run wizard
Jira: [ML-5609](https://iguazio.atlassian.net/browse/ML-5609)
[ML-5609]: https://iguazio.atlassian.net/browse/ML-5609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Monitor Workflows] Change title on Batch re-run wizard

- src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
- **Project Settings**: Validation on parameter - trailing white spaces
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/247
Jira: [ML-5157](https://iguazio.atlassian.net/browse/ML-5157)
[ML-5157]: https://iguazio.atlassian.net/browse/ML-5157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Project Settings] Validation on parameter - trailing white spaces

- src/utils/createArtifact.util.js
- **Artifacts**: Refine UI text for Register Artifact
Jira: [ML-5419](https://iguazio.atlassian.net/browse/ML-5419)
[ML-5419]: https://iguazio.atlassian.net/browse/ML-5419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Artifacts] refine UI text for Register Artifact

- src/components/Datasets/datasets.util.js
- src/components/Files/files.util.js
- src/components/ModelsPage/Models/models.util.js
- **Quick link**: Error message on menu open
Jira: [ML-5798](https://iguazio.atlassian.net/browse/ML-5798)
[ML-5798]: https://iguazio.atlassian.net/browse/ML-5798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Quick link] Error message on menu open

- src/utils/createArtifactsContent.js
- **Model Endpoint**: Set empty version value when endpoint_type is router
Jira: [ML-5821](https://iguazio.atlassian.net/browse/ML-5821)
[ML-5821]: https://iguazio.atlassian.net/browse/ML-5821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Model Endpoint] Set empty version value when endpoint_type is router

- src/components/DetailsInputs/DetailsInputs.js
- **Job**: Missing preview for dataset provided with a tag
Jira: https://jira.iguazeng.com/browse/ML-5493
> Fix [Job] missing preview for dataset provided with a tag

- src/httpClient.js
- **Artifacts**: requests are not canceled when changing pages
Jira: [ML-5689](https://iguazio.atlassian.net/browse/ML-5689)
> Fix [Artifacts] requests are not canceled when changing pages

- src/scss/main.scss
- **Jobs**: Change "Aborted" job status color
Depends On:  https://github.com/iguazio/dashboard-react-controls/pull/250
Jira: [ML-5332](https://iguazio.atlassian.net/browse/ML-5332)
[ML-5332]: https://iguazio.atlassian.net/browse/ML-5332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Jobs] Change "Aborted" job status color

- tests/features/MLFunction.feature
- tests/features/common-tools/common-consts.js
- tests/features/common-tools/common-tools.js
- tests/features/common-tools/utils.js
- tests/features/common/actions/input-group.action.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/jobs-and-workflows.po.js
- tests/features/common/page-objects/ml-functions.po.js
- tests/features/common/page-objects/project-settings.po.js
- tests/features/datasets.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/projectMonitoring.feature
- tests/features/projectSettings.feature
- tests/features/projectsPage.feature
- tests/features/step-definitions/steps.js
- tests/features/step-definitions/table.steps.js
- tests/mockServer/data/projects.json
- tests/mockServer/data/secretKeys.json
- tests/mockServer/mock.js
I 
- add test for check deploy option for serving kind functions (ML-5718)
- updated tests - function create - deploy button (ML-4962)
- updated tests - changed warning message on path MLRun store (ML-5757)
- updated tests - added year (ML-5473)
- Projects - changed validation rules on labels key/value (ML-5204)
- Project Settings - changed locators on labels key/value (ML-5204)
ІІ
Added checks validation of options rules on labels key/value (Projects, Project Settings, ML-5204)
> QA Sprint 161 done

- tests/features/MLFunction.feature
- tests/features/common-tools/common-consts.js
- tests/features/common-tools/common-tools.js
- tests/features/common-tools/utils.js
- tests/features/common/actions/input-group.action.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/jobs-and-workflows.po.js
- tests/features/common/page-objects/ml-functions.po.js
- tests/features/common/page-objects/project-settings.po.js
- tests/features/datasets.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/projectMonitoring.feature
- tests/features/projectSettings.feature
- tests/features/projectsPage.feature
- tests/features/step-definitions/steps.js
- tests/features/step-definitions/table.steps.js
- tests/mockServer/data/projects.json
- tests/mockServer/data/secretKeys.json
- tests/mockServer/mock.js
* Updated tests according to requirements
- add test for check deploy option for serving kind functions (ML-5718)
- updated tests - function create - deploy button (ML-4962)
- updated tests - changed warning message on path MLRun store (ML-5757)
- updated tests - added year - passed (ML-5473)
- Projects - changed validation rules on labels key/value (ML-5204)
- Project Settings - changed locators on labels key/value (ML-5204)
* Added checks validation of options rules on labels key/value (Projects, Project Settings, ML-5204)
---------
> Impl [Tests] QA Sprint 161 done

- src/elements/ArtifactsTableRow/ArtifactsTableRow.js
- **Model endpoints**: UI crash upon navigating to model endpoints tab
Jira: https://iguazio.atlassian.net/browse/ML-5919
> Fix [Model endpoints] UI crash upon navigating to model endpoints tab

- package.json
- src/common/Combobox/ComboboxView.js
- src/common/DatePicker/DatePickerView.js
- src/common/Input/Input.js
- src/common/RangeInput/RangeInput.js
- src/common/ReactFlow/MlReactFlowNode.js
- src/common/ReactFlow/mlReactFlow.scss
- src/common/TextArea/TextArea.js
- src/components/DetailsTransformations/DetailsTransformations.js
- src/components/Pipeline/Pipeline.js
- src/components/Workflow/Workflow.js
- src/constants.js
- **Workflow**: Unclear presentation of a workflow step
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/253
Jira: https://iguazio.atlassian.net/browse/ML-5280
Before:
After:
> Fix [Workflow] Unclear presentation of a workflow step

- src/hooks/useVirtualization.hook.js
- **Artifacts**: Not all artifacts are being displayed
Jira: https://iguazio.atlassian.net/browse/ML-5942
> Fix [Artifacts] Not all artifacts are being displayed

- src/components/ProjectsPage/ProjectsMonitoring/ProjectsMonitoring.js
- src/elements/ProjectsMonitoringCounters/JobsCounters.js
- src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
- src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
- **Projects**: Split Jobs and workflows counters
Jira: [ML-5973](https://iguazio.atlassian.net/browse/ML-5973)
After:
[ML-5973]: https://iguazio.atlassian.net/browse/ML-5973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Impl [Projects] Split Jobs and workflows counters

- src/App.js
- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
- src/components/ProjectsJobsMonitoring/projectsJobsMonitoring.scss
- src/components/ProjectsJobsMonitoring/projectsJobsMotinoring.util.js
- src/constants.js
- src/elements/ContentMenu/ContentMenu.js
- **Cross projects Jobs**: Add tabs to navigate between 3 pages
Jira: https://iguazio.atlassian.net/browse/ML-5993
> Impl [Cross projects Jobs] Add tabs to navigate between 3 pages

- src/components/ProjectSettings/ProjectSettings.js
- src/elements/MembersPopUp/MembersPopUp.js
- src/elements/MembersPopUp/membersReducer.js
- src/elements/ProjectSettingsMembers/ProjectSettingsMembers.js
- **Project settings**: Unable to change myself from 'admin' role in project
Backported to `1.6.x` from #2364 
Jira: https://iguazio.atlassian.net/browse/ML-6048
> Fix [Project settings] Unable to change myself from 'admin' role in project `1.6.x`

- src/App.js
- src/common/Breadcrumbs/Breadcrumbs.js
- src/common/Breadcrumbs/breadcrumbs.util.js
- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
- src/elements/BreadcrumbsDropdown/breadcrumbsDropdown.scss
- **Cross projects Jobs**: Add breadcrumbs
Jira: https://iguazio.atlassian.net/browse/ML-6041
> Impl [Cross projects Jobs] Add breadcrumbs

- tests/features/MLFunction.feature
- tests/features/artifacts.feature
- tests/features/common/actions/common.action.js
- tests/features/common/actions/table.action.js
- tests/features/common/page-objects/feature-store.po.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/jobs-and-workflows.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/projectMonitoring.feature
- tests/features/projectSettings.feature
- tests/features/projectsPage.feature
- tests/features/quickActions.feature
- tests/features/step-definitions/table.steps.js
- tests/mockServer/mock.js
**Updated tests according to requirements**
- Feature Store, Jobs and Workflows- changed locators for name, label, status filters (ML-5829, ML-5785)
- Updated mock with new jobs monitoring API (ML-5469)
- Created tests for dataset elements visibility on table (ML-5920)
> QA Sprint 162 done

- tests/features/MLFunction.feature
- tests/features/artifacts.feature
- tests/features/common/actions/common.action.js
- tests/features/common/actions/table.action.js
- tests/features/common/page-objects/feature-store.po.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/jobs-and-workflows.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/projectMonitoring.feature
- tests/features/projectSettings.feature
- tests/features/projectsPage.feature
- tests/features/quickActions.feature
- tests/features/step-definitions/table.steps.js
- tests/mockServer/mock.js
- Feature Store, Jobs and Workflows- changed locators for name, label, status filters (ML-5829, ML-5785)
- Updated mock with new jobs monitoring API (ML-5469)
- Created tests for dataset elements visibility on table (ML-5920)
> Impl [Tetsts] QA Sprint 162 done

- src/common/ReactFlow/MlReactFlowNode.js
- src/common/ReactFlow/mlReactFlow.scss
- src/common/ReactFlow/mlReactFlow.util.js
- src/components/Pipeline/Pipeline.js
- src/components/Workflow/Workflow.js
- src/components/Workflow/workflow.util.js
- src/constants.js
- **Workflow**: Kubeflow pipeline Condition node appears incorrectly
Jira: https://iguazio.atlassian.net/browse/ML-5723
After:
> Fix [Workflow] Kubeflow pipeline Condition node appears incorrectly

- src/elements/ProjectsMonitoringCounters/JobsCounters.js
- src/elements/ProjectsMonitoringCounters/ScheduledJobsCounters.js
- src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
- **Projects**: Remove date picker from jobs counters
Jira: [ML-6104](https://iguazio.atlassian.net/browse/ML-6104)
[ML-6104]: https://iguazio.atlassian.net/browse/ML-6104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Projects] Remove date picker from jobs counters

- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoringJobs/ProjectsJobsMonitoringJobs.js
- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoringScheduled/ProjectsJobsMonitoringScheduled.js
- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoringWorkflows/ProjectsJobsMonitoringWorkflows.js
- **Cross projects Jobs**: Remove counters in Inner page
Jira: [ML-6108](https://iguazio.atlassian.net/browse/ML-6108)
[ML-6108]: https://iguazio.atlassian.net/browse/ML-6108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Impl [Cross projects Jobs] Remove counters in Inner page

- src/common/DatePicker/DatePickerView.js
- src/common/StatsCard/StatsCard.js
- src/common/StatsCard/statsCard.scss
- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
- src/components/ProjectsJobsMonitoring/projectsJobsMonitoring.scss
- src/elements/JobsMonitoringStatsCard/JobsMonitoringStatsCard.js
- src/elements/JobsMonitoringStatsCard/jobsMonitoringStatsCard.scss
- src/elements/ProjectsMonitoringCounters/JobsCounters.js
- src/elements/ProjectsMonitoringCounters/ScheduledJobsCounters.js
- src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
- src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
- **Jobs monitoring**: counters stats view
Jira: [ML-5994](https://iguazio.atlassian.net/browse/ML-5994)
[ML-5994]: https://iguazio.atlassian.net/browse/ML-5994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Jobs monitoring] counters stats view

- src/components/JobWizard/JobWizard.util.js
- **Batch Run**: Default artifact path not sourced from frontend-spec
Jira: https://iguazio.atlassian.net/browse/ML-6094
> Fix [Batch Run] Default artifact path not sourced from frontend-spec

- src/elements/ProjectsMonitoringCounters/JobsCounters.js
- src/elements/ProjectsMonitoringCounters/ScheduledJobsCounters.js
- src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
- **UI**: Add the 'data-testid' for 'See All' link per monitoring card Item
Jira: [ML-6153](https://iguazio.atlassian.net/browse/ML-6153)
[ML-6153]: https://iguazio.atlassian.net/browse/ML-6153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [UI] Add the 'data-testid' for 'See All' link per monitoring card Item

- src/App.js
- src/actions/jobs.js
- src/components/Details/DetailsHeader/DetailsHeader.js
- src/components/Jobs/MonitorJobs/MonitorJobs.js
- src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
- src/components/Jobs/jobs.util.js
- src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
- src/components/ProjectsJobsMonitoring/JobsMonitoring/jobsMonitoring.util.js
- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
- src/elements/JobsTable/JobsTable.js
- src/elements/JobsTable/jobsTable.util.js
- src/hooks/usePods.hook.js
- src/utils/createJobsContent.js
- src/utils/generateMonitoringData.js
- src/utils/getJobLogs.util.js
- **UI**: Cross-project view: internal pages (jobs)
Jira: https://iguazio.atlassian.net/browse/ML-5924, https://iguazio.atlassian.net/browse/ML-5996, https://iguazio.atlassian.net/browse/ML-5995
After:
> Impl [UI] Cross-project view: internal pages (jobs)

- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
- src/components/ProjectsJobsMonitoring/projectsJobsMonitoring.scss
- **UI**: Cross projects jobs page
> Fix [UI] Cross projects jobs page

- src/components/DetailsLogs/DetailsLogs.js
- src/elements/JobsTable/JobsTable.js
- **Jobs**: UI crushed on Details logs tab
> Fix [Jobs] UI crushed on Details logs tab

- src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
- src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.js
- **Model endpoints**: Hide Metrics tab in demo flag
Jira: [ML-6156](https://iguazio.atlassian.net/browse/ML-6156)
[ML-6156]: https://iguazio.atlassian.net/browse/ML-6156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Impl [Model endpoints] Hide Metrics tab in demo flag

- src/components/Datasets/datasets.util.js
- src/components/Details/Details.js
- src/components/DetailsArtifacts/detailsArtifacts.util.js
- src/components/DetailsInputs/detailsInputs.util.js
- src/components/Files/files.util.js
- src/components/Project/ProjectMonitor.js
- src/constants.js
- src/reducers/artifactsReducer.js
- src/utils/getUniqueIdentifier.js
- src/utils/parseUri.js
- src/utils/resources.js
- **Artifacts**: Artifact/dataset “Copy URI” returns a wrong URI
Jira: [ML-5903](https://iguazio.atlassian.net/browse/ML-5903)
[ML-5903]: https://iguazio.atlassian.net/browse/ML-5903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Artifacts] Artifact/dataset “Copy URI” returns a wrong URI

- src/components/Datasets/DatasetsView.js
- src/components/Files/FilesView.js
- src/components/ModelsPage/Models/ModelsView.js
- src/components/Table/Table.js
- src/components/Table/TableView.js
- src/hooks/useVirtualization.hook.js
- src/types.js
- **Artifacts**: Rows jump during scrolling
Jira: https://iguazio.atlassian.net/browse/ML-6149
> Fix [Artifacts] Rows jump during scrolling

- src/components/RegisterArtifactModal/RegisterArtifactModal.js
- src/elements/RegisterModelModal/RegisterModelModal.js
- **Artifacts**: An empty tag triggers the unique validation
Jira: https://iguazio.atlassian.net/browse/ML-5648
> Fix [Artifacts] An empty tag triggers the unique validation

- src/components/JobWizard/JobWizardSteps/JobWizardResources/JobWizardResources.js
- src/constants.js
- src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
- **Settings**: Add to project setting the ability to define node selectors
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/263
Jira: https://iguazio.atlassian.net/browse/ML-4880
> Impl [Settings] add to project setting the ability to define node selectors

- src/components/Files/files.util.js
- src/components/ProjectsJobsMonitoring/JobsMonitoring/jobsMonitoring.util.js
- src/constants.js
- src/reducers/artifactsReducer.js
- src/utils/resources.js
- **Artifacts**: Artifact 'Copy URI' returns a wrong URI
Jira: [ML-5903](https://iguazio.atlassian.net/browse/ML-5903)
[ML-5903]: https://iguazio.atlassian.net/browse/ML-5903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Artifacts] Artifact 'Copy URI' returns a wrong URI

- src/common/Download/DownloadContainer.js
- src/common/Download/downloadContainer.scss
- src/common/Notification/Notification.js
- src/common/Notification/notificationView.scss
- **UI**: Notification messages overlap each other
Jira: [ML-6166](https://iguazio.atlassian.net/browse/ML-6166)
[ML-6166]: https://iguazio.atlassian.net/browse/ML-6166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [UI] Notification messages overlap each other

- tests/features/artifacts.feature
- tests/features/common/actions/input-group.action.js
- tests/features/common/actions/table.action.js
- tests/features/common/components/breadcrumbs.component.js
- tests/features/common/page-objects/feature-store.po.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/projects.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/projectsPage.feature
- tests/features/step-definitions/table.steps.js
- updated test on Datasets table view due to ML-5942
- updated tests on Feature Vector created pop-up due to ML-5697
- update test with partial load due to ML-5920
- added tests to Projects page due to ML-5923
> QA Sprint 163 done

- tests/features/artifacts.feature
- tests/features/common/actions/input-group.action.js
- tests/features/common/actions/table.action.js
- tests/features/common/components/breadcrumbs.component.js
- tests/features/common/page-objects/feature-store.po.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/projects.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/projectsPage.feature
- tests/features/step-definitions/table.steps.js
Collecting PRs into branch development from branch tests:
- updated test on Datasets table view due to ML-5942
- updated tests on Feature Vector created pop-up due to ML-5697
- update test with partial load due to ML-5920
- added tests to Projects page due to ML-5923
> Impl [Tetsts] QA Sprint 163 done

- package.json
- src/common/ReactFlow/MlReactFlow.js
- src/common/ReactFlow/MlReactFlowNode.js
- src/common/ReactFlow/mlReactFlow.scss
- src/common/ReactFlow/mlReactFlow.util.js
- src/components/Datasets/datasets.scss
- src/components/Pipeline/pipeline.scss
- src/components/Workflow/Workflow.js
- src/components/Workflow/workflow.scss
- src/scss/main.scss
- **Graphs**: Add mini map
Mini map and `fit view` button were added to:
- Jobs and workflows > Monitor workflows > Workflow
- Models > Real-time pipelines > Pipeline
- Feature sets > Transformations
Jira: https://iguazio.atlassian.net/browse/ML-6222
After:
> Impl [Graphs] Add mini map

- src/common/FormTagFilter/FormTagFilter.js
- src/components/Datasets/datasets.util.js
- src/components/DetailsInfo/detailsInfo.util.js
- src/components/Files/files.util.js
- src/components/ModelsPage/Models/models.util.js
- src/scss/main.scss
- src/utils/generateArtifacts.js
- **Artifacts**: Move 'UID' to 'Producer' column
Jira: [ML-6243](https://iguazio.atlassian.net/browse/ML-6243)
Before:
After:
[ML-6243]: https://iguazio.atlassian.net/browse/ML-6243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Artifacts] Move 'UID' to 'Producer' column

- src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
- **Cross projects**: Provide Filter and timeframe for Jobs tab
Fix related to: https://github.com/mlrun/ui/pull/2401
Jira: [ML-5922](https://iguazio.atlassian.net/browse/ML-5922)
[ML-5922]: https://iguazio.atlassian.net/browse/ML-5922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [ML-5922] Replace old constant name

- src/actions/featureStore.js
- **MLRun project**: Wrong error message when trying to create Fset (with ingest)
Jira: https://iguazio.atlassian.net/browse/ML-6164
> Fix [MLRun project] wrong error message when trying to create Fset (with ingest)

- src/components/FunctionsPage/FunctionsView.js
- **ML functions**: partial load: items flicker and fail to load
Jira: https://iguazio.atlassian.net/browse/ML-6246
> Fix [ML functions] partial load: items flicker and fail to load

- src/hooks/useVirtualization.hook.js
- **General**: filters results are not displayed until scroll or refresh
Jira: https://iguazio.atlassian.net/issues/ML-6251
> Fix [General] filters results are not displayed until scroll or refresh

- src/components/ActionBar/ActionBar.js
- src/components/FilterMenu/filterMenu.settings.js
- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
- src/components/ProjectsJobsMonitoring/ScheduledMonitoring/ScheduledMonitoring.js
- src/components/ProjectsJobsMonitoring/ScheduledMonitoring/ScheduledMonitoringFilters.js
- src/reducers/filtersReducer.js
https://iguazio.atlassian.net/browse/ML-6197
> Impl [Cross projects] provide Filter and timeframe for Scheduled tab

- package.json
- src/components/DetailsInfo/DetailsInfoView.js
- src/elements/TableTypeCell/TableTypeCell.js
- **Functions**: Add 'Application' type info
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/268
Related To: https://github.com/mlrun/ui/pull/2418
Jira: [ML-6225](https://iguazio.atlassian.net/browse/ML-6225)
[ML-6225]: https://iguazio.atlassian.net/browse/ML-6225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Impl [Functions] Add 'Application' type info

- src/components/JobWizard/JobWizard.util.js
- **Job wizard**: unexpected change in 'Default artifact path' in 'Batch Run' wizard
Display `Default artifact path` in CE only
Jira: [ML-6154](https://iguazio.atlassian.net/browse/ML-6154)
[ML-6154]: https://iguazio.atlassian.net/browse/ML-6154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Job wizard] unexpected change in 'Default artifact path' in 'Batch Run' wizard `1.6.x`

- src/components/Details/DetailsTabsContent/DetailsTabsContent.js
- src/components/DetailsLogs/DetailsLogs.js
- src/components/FunctionsPage/Functions.js
- src/components/FunctionsPage/functions.util.js
- **Functions**: Add new Logs for 'Application' type
Jira: https://iguazio.atlassian.net/browse/ML-6265
After:
> Impl [Functions] Add new Logs for 'Application' type

- src/elements/PreviewModal/PreviewModal.js
- src/elements/PreviewModal/previewModal.scss
- **Preview modal**: cosmetic fixes
Jira: https://iguazio.atlassian.net/browse/ML-6378
After:
> Fix [Preview modal] cosmetic fixes

- src/actions/featureStore.js
- **MLRun project**: wrong error message when trying to create Fset
Jira: [ML-6347](https://iguazio.atlassian.net/browse/ML-6347)
[ML-6347]: https://iguazio.atlassian.net/browse/ML-6347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [MLRun project] wrong error message when trying to create Fset

- src/components/FilterMenu/FilterMenu.js
- **Jobs and workflows**: filters are not applied when switching between jobs
Jira: https://iguazio.atlassian.net/browse/ML-6176
> Fix [Jobs and workflows] filters are not applied when switching between jobs

- src/actions/featureStore.js
- src/actions/projects.js
- src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
- src/components/FeatureStore/FeatureVectors/FeatureVectors.js
- src/components/FunctionsPage/Functions.js
- src/components/FunctionsPanel/FunctionsPanel.js
- src/components/JobWizard/JobWizard.js
- src/components/JobWizard/JobWizard.util.js
- src/components/Jobs/jobs.util.js
- src/components/Project/ProjectMonitor.js
- src/components/ProjectsPage/Projects.js
- src/components/ProjectsPage/projects.util.js
- src/elements/FeaturesTablePanel/FeaturesTablePanel.js
- src/elements/JobsTable/JobsTable.js
- src/elements/ScheduledJobsTable/ScheduledJobsTable.js
- src/elements/WorkflowsTable/WorkflowsTable.js
- src/utils/artifacts.util.js
- src/utils/getNoDataMessage.js
- src/utils/jobs.util.js
- **UI**: Incorrect texts across the app
Jira: [ML-4755](https://iguazio.atlassian.net/browse/ML-4755)
[ML-4755]: https://iguazio.atlassian.net/browse/ML-4755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Impl [UI] Incorrect texts across the app

- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/Models/models.util.js
- src/components/ModelsPage/modelsPage.scss
- **Models**: revisit 'Failed to deploy model' dialog
Jira: [ML-5699](https://iguazio.atlassian.net/browse/ML-5699)
[ML-5699]: https://iguazio.atlassian.net/browse/ML-5699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Models] revisit 'Failed to deploy model' dialog

- src/components/DetailsArtifacts/DetailsArtifacts.js
- src/components/DetailsArtifacts/detailsArtifacts.util.js
- **Jobs**: List artifacts of a specific run
https://iguazio.atlassian.net/browse/ML-6419
> Impl [Jobs] List artifacts of a specific run

- src/components/ModelsPage/Models/Models.js
- src/hooks/useGetTagOptions.hook.js
- **Breadcrumbs**: request is not sent when changing project
Jira: https://iguazio.atlassian.net/browse/ML-6217
> Fix [Breadcrumbs] request is not sent when changing project

- src/components/Jobs/ScheduledJobs/ScheduledJobs.js
- **Batch Run**: The request is not sent if there are no scheduled jobs
Jira: https://iguazio.atlassian.net/browse/ML-6439
> Fix [Batch Run] The request is not sent if there are no scheduled jobs

- src/common/TagFilter/TagFilterDropdown.js
- src/components/ActionBar/ActionBar.js
- src/components/DetailsRequestedFeatures/DetailsRequestedFeaturesView.js
- src/components/FunctionsPage/FunctionsView.js
- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
- src/scss/main.scss
- **Feature Vectors**: Incorrect display of Requested Features
Jira: [ML-5978](https://iguazio.atlassian.net/browse/ML-5978)
Before:
After:
[ML-5978]: https://iguazio.atlassian.net/browse/ML-5978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Feature Vectors] Incorrect display of Requested Features

- src/components/ActionBar/ActionBar.js
- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
- **Jobs monitoring**: 'Any time' date picker filter doesn't work correctly
Jira: https://iguazio.atlassian.net/browse/ML-6443
> Fix [Jobs monitoring] 'Any time' date picker filter doesn't work correctly

- src/components/JobWizard/JobWizard.util.js
- **Jobs**: Run status contains full artifacts in response for api/v1/run/{project}/{uid}
Jira: https://iguazio.atlassian.net/browse/ML-6472
> Fix [Jobs] Run status contains full artifacts in response for api/v1/run/{project}/{uid}

- src/actions/projects.js
- src/components/ActionBar/ActionBar.js
- src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
- src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoring.js
- src/components/ProjectsPage/Projects.js
- src/components/ProjectsPage/ProjectsMonitoring/ProjectsMonitoring.js
- src/components/ProjectsPage/projects.util.js
- src/elements/ProjectCard/projectCard.util.js
- src/elements/ProjectsMonitoringCounters/JobsCounters.js
- src/elements/ProjectsMonitoringCounters/ScheduledJobsCounters.js
- src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
- src/utils/generateMonitoringData.js
- **Cross projects Jobs**: Use 'project_summaries' endpoint for counters
Jira: https://iguazio.atlassian.net/browse/ML-6446
> Impl [Cross projects Jobs] Use 'project_summaries' endpoint for counters

- src/components/DetailsArtifacts/DetailsArtifacts.js
- **Jobs**: List artifacts of a specific run with iterations
Backported to `1.6.x` from #2464 
Jira: https://iguazio.atlassian.net/browse/ML-6473
> Fix [Jobs] List artifacts of a specific run with iterations `1.6.x`

- src/components/DetailsArtifacts/DetailsArtifacts.js
- **Jobs**: List artifacts of a specific run with iterations
Jira: https://iguazio.atlassian.net/browse/ML-6473
> Fix [Jobs] List artifacts of a specific run with iterations

- src/components/SheduleWizard/scheduleWizard.util.js
- **Schedule Job**: when edit a schedule job by default the schedule change to every 10 minute
Backported to `1.6.x` from #2460 
Jira: https://iguazio.atlassian.net/browse/ML-6496
> Fix [Schedule Job] when edit a schedule job by default the schedule change to every 10 minute `1.6.x`

- package.json
- UI: bump DRC version to 2.0.8
> [UI] bump DRC version to 2.0.8

- package.json
- tests/features/MLFunction.feature
- tests/features/artifacts.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/models.po.js
- tests/features/common/page-objects/project-settings.po.js
- tests/features/common/page-objects/project.po.js
- tests/features/common/page-objects/projects.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/projectMonitoring.feature
- tests/features/projectSettings.feature
- tests/features/projectsPage.feature
- tests/features/quickActions.feature
- tests/features/step-definitions/steps.js
- tests/features/step-definitions/table.steps.js
- changed description counter selector on Feature Vector
- changed selector for remove button Run Details label table on Batch Run
- changed command column to Code Entry Point on ML Functions, Jobs detail panel due to ML-4977
- added filtering by status due to lazy loading on Monitor Jobs tab due to ML-5092
- added visibility of Recent text on Project Monitoring page
- changed selector for Sorted by filter on Models
- added preview table headers - ML-5719
- added 'Overwrite artifact?' popup - ML-6059
- added step turn Off MLRun CE mode - ML-6111
- changed Default artifact path - ML-6094
- changed selector for remove button in label table on Projects Settings General tab
- changed selector for Close button in label table on …
> Impl [Tetsts] QA Sprint 164 done

- package.json
- tests/features/artifacts.feature
- tests/features/common-tools/common-consts.js
- tests/features/common-tools/common-tools.js
- tests/features/common/page-objects/feature-store.po.js
- tests/features/common/page-objects/files.po.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/models.po.js
- tests/features/common/page-objects/side-panel.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/step-definitions/steps.js
- tests/features/step-definitions/table.steps.js
- tests/mockServer/data/pipelines.json
- tests/mockServer/data/summary.json
- moved 'UID' to 'Producer' column ML-6243
- changed option name in action menu list ML-5713
- changed action menu selection in case of expand row ML-5713
- updated 'No features found' texts - ML-4755
- added new sequence URL combobox Apply button ML-4124
- added new sequence before Partition checkbox is enabled ML-4124
- changed project_summaries endpoint ML-6446
- updated workflows name with project name - ML-5540
> Tests [QA] v1.7.0-rc17

- src/common/ReactFlow/mlReactFlow.scss
- src/elements/WorkflowsTable/WorkflowsTable.js
- **Workflow**: Wrong redirection
Jira: https://iguazio.atlassian.net/browse/ML-6407
> Fix [Workflow] Wrong redirection

- src/components/ProjectsPage/Projects.js
- src/components/ProjectsPage/ProjectsView.js
- **Projects**: Remove cross-project jobs counters from demo
Jira: [ML-5950](https://iguazio.atlassian.net/browse/ML-5950)
[ML-5950]: https://iguazio.atlassian.net/browse/ML-5950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Impl [Projects] Remove cross-project jobs counters from demo

- src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
- src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.js
- **Model endpoints**: Remove Metrics tab from demo flag
Jira: https://iguazio.atlassian.net/browse/ML-6157
> Impl [Model endpoints] Remove Metrics tab from demo flag

- src/utils/generateMonitoringData.js
- **Cross projects Jobs and Workflows**: Redundant indication on the "Filter by"
Jira: https://iguazio.atlassian.net/browse/ML-6586
> Fix [Cross projects Jobs and Workflows] Redundant indication on the "Filter by"

- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
- src/components/Workflow/Workflow.js
- src/utils/createJobsContent.js
- **Cross project Jobs**: Misc bugs
Jira: https://iguazio.atlassian.net/browse/ML-6321
> Fix [Cross project Jobs] Misc bugs

- src/elements/ProjectTable/projectTable.scss
- src/utils/getState.js
- src/utils/parseFunction.js
- **UI**: Do not show "Failed to delete" status in UI
Jira: https://iguazio.atlassian.net/browse/ML-6554
> Fix [UI] do not show "Failed to delete" status in UI

- src/common/DatePicker/DatePicker.js
- **Jobs and workflows**: filter by time does not correctly mark selected option
Jira: https://iguazio.atlassian.net/browse/ML-6186
> Fix [Jobs and workflows] filter by time does not correctly mark selected option

- src/hooks/useVirtualization.hook.js
- **Functions**: Loading gets stuck after expanding row
Jira: https://iguazio.atlassian.net/browse/ML-6445
> Fix [Functions] loading gets stuck after expanding row

- src/components/FunctionsPage/Functions.js
- **Functions**: Expanded rows data is not updated after Refresh
Jira: https://iguazio.atlassian.net/browse/ML-6444
> Fix [Functions] expanded rows data is not updated after Refresh

- src/components/FunctionsPage/functions.util.js
- **Functions**: Unexpected error during functions deletion
Jira: https://iguazio.atlassian.net/browse/ML-6622
> Fix [Functions] Unexpected error during functions deletion

- src/components/JobWizard/JobWizard.util.js
- **Batch run**: unexpected change in 'Default artifact path' 
Jira: https://iguazio.atlassian.net/browse/ML-6483
> Fix [Batch run] unexpected change in 'Default artifact path'

- src/components/ArtifactsActionBar/ArtifactsActionBar.js
- src/components/DetailsInfo/DetailsInfo.js
- src/components/ModelsPage/Models/models.util.js
- src/elements/DetailsInfoItemChip/DetailsInfoItemChip.js
- **Artifacts**: Filter by 'All' tag reverts to 'latest'
Jira: https://iguazio.atlassian.net/browse/ML-5696
> Fix [Artifacts] Filter by 'All' tag reverts to 'latest'

- src/components/Details/DetailsTabsContent/DetailsTabsContent.js
- src/components/DetailsLogs/DetailsLogs.js
- src/components/FunctionsPage/functions.util.js
- **Functions**: function build logs for untagged function
Jira: https://iguazio.atlassian.net/browse/ML-4965
> Fix [Functions] function build logs for untagged function

- src/httpClient.js
- **Artifacts**: No warning message for big response
Backported to `1.6.x`
Jira: https://iguazio.atlassian.net/browse/ML-6660
> Fix [Artifacts] No warning message for big response `1.6.x`

- src/elements/ProjectJobs/projectJobs.utils.js
- **Project monitoring**: Scheduled counter does not display data
Jira: https://iguazio.atlassian.net/browse/ML-6657
> Fix [Project monitoring] Scheduled counter does not display data

- src/components/FeatureStore/Features/Features.js
- **Feature store**: unexpected "query result is too large..." pop up message appearance
Jira: https://iguazio.atlassian.net/browse/ML-6699
> Fix [Feature store] unexpected "query result is too large..." pop up message appearance

- src/components/ActionBar/ActionBar.js
- src/components/FunctionsPage/FunctionsView.js
- **Functions**: new Function button doesn't work
Jira: https://iguazio.atlassian.net/browse/ML-6667
> Fix [Functions] new Function button doesn't work

- tests/mockServer/mock.js
- **Mock**: Add mock for deleting a function
Jira: https://iguazio.atlassian.net/browse/ML-6664
> Fix [Mock] Add mock for deleting a function

- src/elements/JobsTable/JobsTable.js
- src/elements/ScheduledJobsTable/ScheduledJobsTable.js
- **Cross-project**: Project name is not specified for Batch re-run, Edit Job
Jira: https://iguazio.atlassian.net/browse/ML-6731
> Fix [Cross-project] Project name is not specified for Batch re-run, Edit Job

- src/components/DetailsArtifacts/DetailsArtifacts.js
- **Jobs**: Get artifacts from the run status instead of using producer URI
Jira: https://iguazio.atlassian.net/browse/ML-6779
> Impl [Jobs] Get artifacts from the run status instead of using producer URI

- src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
- src/components/FeatureStore/featureStore.util.js
- **Feature Vectors**: Feature set tag disappears after applying changes
Jira: https://iguazio.atlassian.net/browse/ML-5980
> Fix [Feature Vectors] Feature set tag disappears after applying changes

- src/elements/ProjectFunctions/ProjectFunctions.js
- src/elements/ProjectTable/ProjectTable.js
- **Real-time functions (Nuclio)**: mismatch between function name and name in tooltip
Jira: https://iguazio.atlassian.net/browse/ML-6647
> Fix [Real-time functions (Nuclio)] mismatch between function name and name in tooltip

- src/elements/MetricsSelector/MetricsSelector.js
- src/elements/MetricsSelector/metricsSelector.scss
- **Metrics**: Add metric type tooltip
Jira: [ML-6791](https://iguazio.atlassian.net/browse/ML-6791)
Before:
After:
[ML-6791]: https://iguazio.atlassian.net/browse/ML-6791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Metrics] Add metric type tooltip

- src/components/DetailsArtifacts/DetailsArtifacts.js
- **Jobs**: The artifact preview is not collapsed
Jira: https://iguazio.atlassian.net/browse/ML-6603
> Fix [Jobs] The artifact preview is not collapsed

- src/common/Input/input.scss
- src/components/ProjectsPage/projects.scss
- **Batch Run, Projects**: Warning text isn't displayed on tooltip icon hover
Jira: https://iguazio.atlassian.net/browse/ML-5983
> Fix [Batch Run, Projects] Warning text isn't displayed on tooltip icon hover

- src/common/WarningMessage/WarningMessage.js
- src/common/WarningMessage/warningMessage.scss
- src/components/Datasets/Datasets.js
- src/components/Datasets/DatasetsView.js
- src/components/Files/Files.js
- src/components/Files/FilesView.js
- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/Models/ModelsView.js
- **UI**: Limit number of artifacts shown in the artifact screen
Part of: https://github.com/mlrun/ui/pull/2535
Jira: https://iguazio.atlassian.net/browse/ML-6866
> Impl [UI] Limit number of artifacts shown in the artifact screen `1.6.x`

- src/actions/workflow.js
- src/scss/main.scss
- src/utils/getState.js
- src/utils/parseWorkflows.js
- **Cross projects**: Change filters state for Error and Skipped
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/291
Jira: https://iguazio.atlassian.net/browse/ML-6709
> Fix [Cross projects] change filters state for Error and Skipped

- src/components/JobWizard/JobWizard.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
- src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
- src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
- src/elements/DetailsInfoItemChip/DetailsInfoItemChip.js
- src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
- **Batch run**: Unable to rerun batch job - blocked on 'Run Details' step
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/290
Jira: https://iguazio.atlassian.net/browse/ML-6811
> Fix [Batch run] unable to rerun batch job - blocked on 'Run Details' step

- src/components/Datasets/Datasets.js
- src/components/Datasets/DatasetsView.js
- src/components/FeatureStore/FeatureSets/FeatureSets.js
- src/components/FeatureStore/FeatureSets/FeatureSetsView.js
- src/components/FeatureStore/FeatureVectors/FeatureVectors.js
- src/components/FeatureStore/FeatureVectors/FeatureVectorsView.js
- src/components/FeatureStore/Features/Features.js
- src/components/FeatureStore/Features/FeaturesView.js
- src/components/Files/Files.js
- src/components/Files/FilesView.js
- src/components/FunctionsPage/Functions.js
- src/components/FunctionsPage/FunctionsView.js
- src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/Models/ModelsView.js
- src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
- src/components/Table/TableView.js
- src/constants.js
- src/elements/JobsTable/JobsTable.js
- src/elements/ScheduledJobsTable/ScheduledJobsTable.js
- src/elements/WorkflowsTable/WorkflowsTable.js
- src/hooks/useVirtualization.hook.js
- **Pipelines**: Data display issue after returning from graph view
Jira: https://iguazio.atlassian.net/browse/ML-6739
> Fix [Pipelines] data display issue after returning from graph view

- src/components/Jobs/jobs.util.js
- src/elements/WorkflowsTable/WorkflowsTable.js
- **Jobs and Workflows**: Delete workflow step request is not triggered
Jira: https://iguazio.atlassian.net/browse/ML-6907
> Fix [Jobs and Workflows] delete workflow step request is not triggered

- src/utils/notifications.util.js
- **UI**: Useless "RETRY" click within the overlay notification
Jira: https://iguazio.atlassian.net/browse/ML-6874
> Fix [UI] Useless "RETRY" click within the overlay notification

- src/scss/main.scss
- src/utils/getState.js
- **UI**: Serving function with status unhealthy - status is not displayed
Jira: https://iguazio.atlassian.net/browse/ML-6204
> Fix [UI] Serving function with status unhealthy - status is not displayed

- src/components/RegisterArtifactModal/RegisterArtifactModal.js
- src/elements/RegisterModelModal/RegisterModelModal.js
- **Models, Artifacts, Datasets**: Tag UID is rewritten after updating labels
Jira: https://iguazio.atlassian.net/browse/ML-5714
> Fix [Models, Artifacts, Datasets] Tag UID is rewritten after updating labels

- src/components/FunctionsPage/functions.util.js
- **Functions**: move 'Deploy' button for 'Serving' function to demo mode
Jira: [ML-6972](https://iguazio.atlassian.net/browse/ML-6972)
[ML-6972]: https://iguazio.atlassian.net/browse/ML-6972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Functions] move 'Deploy' button for 'Serving' function to demo mode

- src/api/artifacts-api.js
- src/components/Datasets/Datasets.js
- src/components/Datasets/DatasetsView.js
- src/components/Datasets/datasets.util.js
- src/components/Files/Files.js
- src/components/Files/FilesView.js
- src/components/Files/files.util.js
- src/components/FunctionsPage/Functions.js
- src/components/FunctionsPage/functions.util.js
- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/Models/ModelsView.js
- src/components/ModelsPage/Models/models.util.js
- src/components/RegisterArtifactModal/RegisterArtifactModal.js
- src/elements/RegisterModelModal/RegisterModelModal.js
- src/reducers/artifactsReducer.js
- src/utils/artifacts.util.js
- src/utils/parseArtifacts.js
- **Artifacts | Datasets | Models**: Reduce load on UI on list requests
Jira: https://iguazio.atlassian.net/browse/ML-6789
> Impl [Artifacts|Datasets|Models] Reduce load on UI on list requests

- tests/mockServer/data/funcs.json
- tests/mockServer/mock.js
- **UI**: Add mock for application Runtime
Jira: https://iguazio.atlassian.net/browse/ML-7005
> Fix [UI] Add mock for application Runtime

- src/components/Details/DetailsHeader/DetailsHeader.js
- src/elements/MetricsSelector/MetricsSelector.js
- src/elements/MetricsSelector/metricsSelector.scss
- **Models endpoints monitoring, metrics**: Use "Apply" button to get all selected metrics
Jira: https://iguazio.atlassian.net/browse/ML-6950
> Impl [Models endpoints monitoring, metrics] Use "Apply" button to get all selected metrics

- src/utils/generateMonitoringData.js
- **Jobs monitoring, scheduled**: 'No jobs found.' when filtering for the 'Past 24 hours'
Jira: https://iguazio.atlassian.net/browse/ML-7010
> Fix [Jobs monitoring, scheduled] 'No jobs found.' when filtering for the 'Past 24 hours'

- ui_ci.groovy
DEVOPS-717 Add Jenkins file for the UI-CI
> UI ci orkor

- src/components/FilterMenu/FilterMenu.js
- **UI**: Requests aren't send when project was changed
Jira: https://iguazio.atlassian.net/browse/ML-7033
> Fix [UI] Requests aren't send when project was changed

- src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
- src/components/AddToFeatureVectorPage/AddToFeatureVectorView.js
- src/components/FeatureStore/Features/Features.js
- src/components/FeatureStore/Features/features.util.js
- **Feature store**: Features request not cancelled on FV creation
Jira: https://iguazio.atlassian.net/browse/ML-6725
> Fix [Feature store] features request not cancelled on FV creation

- src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
- **UI**: bad behavior during automatic refresh in project "General" settings page
Jira: https://iguazio.atlassian.net/browse/ML-6960
> Fix [UI] bad behavior during automatic refresh in project "General" settings page

- src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
- src/components/AddToFeatureVectorPage/AddToFeatureVectorView.js
- **Create Vector**: UI partial load
Jira: https://iguazio.atlassian.net/browse/ML-6812
> Fix [Create Vector] UI partial load

- src/utils/artifacts.util.js
- **Artifacts|Datasets|Models**: Load artifact issues
Jira: https://iguazio.atlassian.net/browse/ML-7045, https://iguazio.atlassian.net/browse/ML-7046
> Fix [Artifacts|Datasets|Models] Load artifact issues

- src/components/FunctionsPage/Functions.js
- **ML Functions**: Actions "Run", "Edit", "View YAML" don't work
Jira: https://iguazio.atlassian.net/browse/ML-7048
> Fix [ML Functions] Actions "Run", "Edit", "View YAML" don't work

- src/utils/getUniqueIdentifier.js
- **Model endpoints**: multiple duplicates of items during scroll
Jira: https://iguazio.atlassian.net/browse/ML-6783
> Fix [Model endpoints] multiple duplicates of items during scroll

- src/components/FunctionsPage/functions.util.js
- tests/mockServer/mock.js
- **Functions**: Add mock for GET `functions` request
Jira: https://iguazio.atlassian.net/browse/ML-7043
> Fix [Functions] Add mock for GET `functions` request

- src/actions/details.js
- src/actions/modelEndpoints.js
- src/api/artifacts-api.js
- src/api/details-api.js
- src/api/modelEndpoints-api.js
- src/common/ActionsMenu/ActionsMenu.js
- src/common/TabsSlider/tabsSlider.scss
- src/components/Details/Details.js
- src/components/Details/DetailsHeader/DetailsHeader.js
- src/components/Details/DetailsTabsContent/DetailsTabsContent.js
- src/components/Details/details.scss
- src/components/DetailsMetrics/DetailsMetrics.js
- src/components/DetailsMetrics/DetailsMetrics.scss
- src/components/DetailsMetrics/IncvocationMetricCard.js
- src/components/FeatureStore/FeatureStore.js
- src/components/FunctionsPage/functions.util.js
- src/components/Jobs/Jobs.js
- src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
- src/components/ProjectsJobsMonitoring/projectsJobsMonitoring.scss
- src/elements/MetricsSelector/metricsSelector.scss
- src/reducers/artifactsReducer.js
- src/scss/main.scss
- **Metrics**: UI metrics UX fix
Jira: [ML-6924](https://iguazio.atlassian.net/browse/ML-6924)
Before:
After:
[ML-6924]: https://iguazio.atlassian.net/browse/ML-6924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Metrics] UI metrics UX fix

- src/components/Datasets/datasets.util.js
- src/elements/DeleteArtifactPopUp/DeleteArtifactPopUp.js
- src/utils/notifications.util.js
- tests/mockServer/mock.js
- **UI**: Delete single artifact data
Jira: https://iguazio.atlassian.net/browse/ML-7099
> Impl [UI] Delete single artifact data

- src/elements/WorkflowsTable/WorkflowsTable.js
- **Workflows, cross-projects**: Project name doesn't specify for Batch re-run
Jira: https://iguazio.atlassian.net/browse/ML-7092
> Fix [Workflows, cross-projects] Project name doesn't specify for Batch re-run

- src/components/ProjectsPage/ProjectsView.js
- src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
- **Projects**: Cannot scroll while data is fetched
Jira: https://iguazio.atlassian.net/browse/ML-7003
> Fix [Projects] Cannot scroll while data is fetched

- package.json
- src/components/DetailsMetrics/DetailsMetrics.scss
- src/components/DetailsMetrics/IncvocationMetricCard.js
- src/components/DetailsMetrics/detailsMetrics.util.js
- **Models Endpoints Monitoring, Metrics**: Percentage change calculation for Invocation graph
Depends on: https://github.com/iguazio/dashboard-react-controls/pull/299
Jira: https://iguazio.atlassian.net/browse/ML-7037
> Fix [Models Endpoints Monitoring, Metrics] Percentage change calculation for Invocation graph

- src/utils/generateMonitoringData.js
- **Jobs, cross-project**: Incorrect multiple status filter number
Jira: https://iguazio.atlassian.net/browse/ML-7125
> Fix [Jobs, cross-project] Incorrect multiple status filter number

- src/components/FilterMenu/filterMenu.settings.js
- **Cross Project- Internal Job view**:  Wrong Filter By Type list
Jira: [ML-6675](https://iguazio.atlassian.net/browse/ML-6675)
[ML-6675]: https://iguazio.atlassian.net/browse/ML-6675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Cross Project - Internal Job view]  Wrong Filter By Type list

- src/components/DetailsMetrics/DetailsMetrics.js
- src/components/DetailsMetrics/DetailsMetrics.scss
- src/components/DetailsMetrics/IncvocationMetricCard.js
- **Models endpoints monitoring, metrics**: Increase the distance between metric histogram and line chart
Jira: [ML-7176](https://iguazio.atlassian.net/browse/ML-7176), [ML-7183](https://iguazio.atlassian.net/browse/ML-7183)
Before:
After:
[ML-7176]: https://iguazio.atlassian.net/browse/ML-7176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ML-7183]: https://iguazio.atlassian.net/browse/ML-7183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Models endpoints monitoring, metrics] increase the distance between metric histogram and line chart

- src/elements/FormResourcesUnits/formResourcesUnits.util.js
- src/utils/panelResources.util.js
- **Batch Run, Function wizard**: Number input for CPU is malfunctioning
Jira: https://iguazio.atlassian.net/browse/ML-4776
> Fix [Batch Run, Function wizard] Number input for CPU is malfunctioning

- src/utils/handleDeleteArtifact.js
- **Artifacts**: The 'Retry' deletion request does not include 'deletion_strategy' data
Jira: https://iguazio.atlassian.net/browse/ML-7133
> Fix [Artifacts] The 'Retry' deletion request does not include 'deletion_strategy' data

- src/utils/getMetricChartConfig.js
- **Models endpoints monitoring, metrics**:  Y-Axis Labels Absent in Expanded Invocation Graph
Jira: https://iguazio.atlassian.net/issues/ML-6881?filter=-1
> Fix [Models endpoints monitoring, metrics]  Y-Axis Labels Absent in Expanded Invocation Graph

- Dockerfile
- **UI**: Update dockerfile base image
Jira: [ML-7186](https://iguazio.atlassian.net/browse/ML-7186)
[ML-7186]: https://iguazio.atlassian.net/browse/ML-7186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [UI] update `Dockerfile` base image

- src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoring.js
- src/elements/WorkflowsTable/WorkflowsTable.js
- **Workflows, cross-project**: Add a loader to the workflow requests
Jira: https://iguazio.atlassian.net/browse/ML-7243
> Fix [Workflows, cross-project] Add a loader to the workflow requests

- src/common/NameFilter/NameFilter.js
- src/components/FunctionsPage/Functions.js
- src/elements/DetailsInfoItem/DetailsInfoItem.js
- src/utils/createFunctionsContent.js
- src/utils/createJobsContent.js
- src/utils/createRealTimePipelinesContent.js
- src/utils/generateFunctionDetailsLink.js
- src/utils/parseUri.js
- **Functions**: Apply name filter on loading the function
Jira: https://iguazio.atlassian.net/browse/ML-7324
> Fix [Functions] Apply name filter on loading the function

- src/utils/generateMonitoringData.js
- **Cross-projects jobs/workflows**: Use `Any time` for `In Process`
Jira: https://iguazio.atlassian.net/browse/ML-7315
> Fix [Cross-projects jobs/workflows] Use `Any time` for `In Process`

- src/utils/createJobsContent.js
- src/utils/generateFunctionDetailsLink.js
- **Scheduled Jobs**: Wrong redirection to the function
Jira: https://iguazio.atlassian.net/browse/ML-7350
> Fix [Scheduled Jobs] Wrong redirection to the function

- src/components/DetailsArtifacts/detailsArtifacts.util.js
- **Cross projects**: page crash on missing job
> Fix [Cross projects] page crash on missing job

- tests/features/artifacts.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/components/breadcrumbs.component.js
- tests/features/common/page-objects.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/jobs-monitoring.po.js
- tests/features/common/page-objects/side-panel.po.js
- tests/features/datasets.feature
- tests/features/jobsMonitoring.feature
- tests/features/models.feature
- tests/features/projectMonitoring.feature
- tests/features/projectsPage.feature
- tests/features/quickActions.feature
- unify name for Filter by pop-up for all pages use
- added tests for overview Jobs Monitoring page
- updated Filter by pop-up components due to overview Jobs Monitoring page
- updated tests for Url combobox new behavior
> QA Sprint 165 done

- tests/features/artifacts.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/components/breadcrumbs.component.js
- tests/features/common/page-objects.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/jobs-monitoring.po.js
- tests/features/common/page-objects/side-panel.po.js
- tests/features/datasets.feature
- tests/features/jobsMonitoring.feature
- tests/features/models.feature
- tests/features/projectMonitoring.feature
- tests/features/projectsPage.feature
- tests/features/quickActions.feature
> Impl [Tests] QA Sprint 165 done

- src/components/DetailsMetrics/detailsMetrics.util.js
- **Models endpoints monitoring, metrics**: Update No Detection Message
Jira: [ML-7360](https://iguazio.atlassian.net/browse/ML-7360)
[ML-7360]: https://iguazio.atlassian.net/browse/ML-7360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Models endpoints monitoring, metrics] Update No Detection Message

- src/common/Chart/mlChart.scss
- src/components/DetailsMetrics/DetailsMetrics.scss
- src/scss/main.scss
- **Models Endpoints Monitoring, Metrics**: unification of tooltips appearance
Jira: https://iguazio.atlassian.net/browse/ML-7136
> Fix [Models Endpoints Monitoring, Metrics] unification of tooltips appearance

- src/components/JobWizard/JobWizard.js
- **Batch inference**: "Batch inference" button in "Deploy and monitor" quick action does not work
Jira: https://iguazio.atlassian.net/browse/ML-7412
> Fix [Batch inference] "Batch inference" button in "Deploy and monitor" quick action does not work

- src/components/JobWizard/JobWizard.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardDataInputs/JobWizardDataInputs.js
- src/components/JobWizard/JobWizardSteps/JobWizardParameters/JobWizardParameters.js
- src/components/JobsPanel/jobsPanel.util.js
- src/elements/FormDataInputsTable/FormDataInputsRow/FormDataInputsRow.js
- src/elements/FormDataInputsTable/FormDataInputsTable.js
- src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
- src/elements/FormParametersTable/FormParametersTable.js
- **Batch Run**: parameters type options and data inputs deletion issues
Jira: https://iguazio.atlassian.net/browse/ML-5156
> Fix [Batch Run] parameters type options and data inputs deletion issues

- src/actions/jobs.js
- tests/mockServer/mock.js
- **Scheduled**: Use label query param on list schedules endpoint
Jira: https://iguazio.atlassian.net/browse/ML-7364
> Fix [Scheduled] Use label query param on list schedules endpoint

- src/components/DetailsInfo/detailsInfo.util.js
- **Functions**: Map "Pods priority" values
Jira: [ML-7478](https://iguazio.atlassian.net/browse/ML-7478)
[ML-7478]: https://iguazio.atlassian.net/browse/ML-7478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Functions] Map "Pods priority" values

- src/actions/projects.js
- src/components/ProjectsPage/Projects.js
- src/components/ProjectsPage/ProjectsView.js
- **Projects**: Add a notification for newly created project
Jira: [ML-7537](https://iguazio.atlassian.net/browse/ML-7537)
After:
[ML-7537]: https://iguazio.atlassian.net/browse/ML-7537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Projects] Add a notification for newly created project

- src/elements/ProjectCard/ProjectCardView.js
- **Projects** Add "Created" to existing text in projects screen showing when project was created
Jira: [ML-7483](https://iguazio.atlassian.net/browse/ML-7483)
[ML-7483]: https://iguazio.atlassian.net/browse/ML-7483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Projects] Add "Created" to existing text in projects screen showing when project was created

- src/components/DetailsLogs/DetailsLogs.js
- src/components/DetailsLogs/Logs.js
- **Functions**: Build logs disappear
Jira: [ML-7464](https://iguazio.atlassian.net/browse/ML-7464)
[ML-7464]: https://iguazio.atlassian.net/browse/ML-7464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Functions] Build logs disappear

- src/components/JobWizard/JobWizardSteps/JobWizardDataInputs/JobWizardDataInputs.js
- src/components/JobWizard/JobWizardSteps/JobWizardParameters/JobWizardParameters.js
- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- **Batch Run**: Unexpected Application Error
Jira: https://iguazio.atlassian.net/browse/ML-7444
> Fix [Batch Run] Unexpected Application Error

- src/utils/getMetricChartConfig.js
- **UI**: Histogram X-Axis Labels Partially Missing with Navigation Bar Open 
Jira: https://iguazio.atlassian.net/browse/ML-7534
Before:
After:
> Fix [UI] Histogram X-Axis Labels Partially Missing with Navigation Bar Open 

- src/actions/featureStore.js
- src/api/featureStore-api.js
- src/components/Datasets/Datasets.js
- src/components/FeatureStore/FeatureSets/FeatureSets.js
- src/components/FeatureStore/FeatureVectors/FeatureVectors.js
- src/components/FeatureStore/Features/Features.js
- src/components/Files/Files.js
- src/components/ModelsPage/Models/Models.js
- src/hooks/useGetTagOptions.hook.js
- **Artifacts**: Artifacts-tags request issues
Jira: https://iguazio.atlassian.net/browse/ML-7575
> Fix [Artifacts] artifacts-tags request issues

- src/components/Details/details.scss
- src/components/DetailsMetrics/DetailsMetrics.scss
- src/components/DetailsMetrics/InvocationsMetricCard.js
- src/components/ProjectsPage/ProjectsMonitoring/projectsMonitoring.scss
- src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
- **Models endpoints**: Could not see full metric graph
Jira: [ML-7512](https://iguazio.atlassian.net/browse/ML-7512)
[ML-7512]: https://iguazio.atlassian.net/browse/ML-7512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Models endpoints] Could not see full metric graph

- src/components/ActionBar/ActionBar.js
- src/scss/main.scss
- **Jobs monitoring**: filters are not applied when switching between jobs list/runs list/run details
Jira: https://iguazio.atlassian.net/browse/ML-7592
> Fix [Jobs monitoring] filters are not applied when switching between jobs list/runs list/run details

- src/actions/projects.js
- **Projects**: Fix error message in case of 403 error code
Jira: https://iguazio.atlassian.net/browse/ML-7119
> Fix [Projects] Fix error message in case of 403 error code

- src/components/ProjectSettings/projectSettings.scss
- src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
- **Project settings**: No indication in the UI for invalid node selector combinations on project
Jira: [ML-7544](https://iguazio.atlassian.net/browse/ML-7544)
After:
[ML-7544]: https://iguazio.atlassian.net/browse/ML-7544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Project settings] No indication in the UI for invalid node selector combinations on project

- src/elements/MembersPopUp/MembersPopUp.js
- **Project settings**: incorrect wording upon removing member from project
Jira: [ML-7646](https://iguazio.atlassian.net/browse/ML-7646)
[ML-7646]: https://iguazio.atlassian.net/browse/ML-7646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Project settings] incorrect wording upon removing member from project

- src/components/Details/details.scss
- src/components/DetailsMetrics/DetailsMetrics.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- src/elements/MetricsSelector/MetricsSelector.js
- src/elements/MetricsSelector/metricsSelector.scss
- **Models endpoints monitoring, metrics**: disable metrics selector if mm has no metrics
Jira: [ML-7654](https://iguazio.atlassian.net/browse/ML-7654)
After:
[ML-7654]: https://iguazio.atlassian.net/browse/ML-7654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Models endpoints monitoring, metrics] disable metrics selector if mm has no metrics

- src/components/Jobs/MonitorJobs/MonitorJobs.js
- src/components/Jobs/MonitorJobs/monitorJobs.util.js
- src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
- src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
- **Jobs,Workflows**: Duplicated requests
Jira: https://iguazio.atlassian.net/browse/ML-7504
> Fix [Jobs,Workflows] Duplicated requests

- src/actions/featureStore.js
- src/actions/functions.js
- src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
- src/components/RegisterArtifactModal/RegisterArtifactModal.js
- src/elements/FeaturesTablePanel/FeaturesTablePanel.js
- **UI**: unexpected error message when user has no permission to create feature set
Jira: [ML-7375](https://iguazio.atlassian.net/browse/ML-7375)
[ML-7375]: https://iguazio.atlassian.net/browse/ML-7375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [UI] unexpected error message when user has no permission to create feature set

- src/components/DetailsInputs/DetailsInputs.js
- **Job Inputs**: incorrect list artifacts request
Jira: [ML-7628](https://iguazio.atlassian.net/browse/ML-7628)
[ML-7628]: https://iguazio.atlassian.net/browse/ML-7628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Job Inputs] incorrect list artifacts request

- src/components/DetailsInputs/DetailsInputs.js
- src/components/DetailsInputs/detailsInputs.util.js
- **Job inputs**: disable Show details action
Jira: [ML-7629](https://iguazio.atlassian.net/browse/ML-7629)
[ML-7629]: https://iguazio.atlassian.net/browse/ML-7629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Job inputs] disable Show details action

- src/components/DetailsMetrics/ApplicationMetricCard.js
- src/components/DetailsMetrics/DetailsMetrics.scss
- src/components/DetailsMetrics/InvocationsMetricCard.js
- **Models Endpoints**: Invocations toggle icon should be visible on hover
Jira: [ML-7683](https://iguazio.atlassian.net/browse/ML-7683)
[ML-7683]: https://iguazio.atlassian.net/browse/ML-7683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Impl [Models Endpoints] Invocations toggle icon should be visible on hover

- src/utils/jobs.util.js
- src/utils/parseJob.js
- tests/mockServer/data/schedules.json
- **Schedule**: page crashed due to unexpected cron tab
Jira: https://iguazio.atlassian.net/browse/ML-7560
> Fix [Schedule] page crashed due to unexpected cron tab

- tests/features/common-tools/common-consts.js
- tests/features/common/actions/input-group.action.js
- tests/features/common/page-objects.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/project-settings.po.js
- tests/features/jobsMonitoring.feature
- tests/features/models.feature
- tests/features/projectMonitoring.feature
- tests/features/projectSettings.feature
- tests/features/step-definitions/steps.js
- tests/features/step-definitions/table.steps.js
- tests/mockServer/mock.js
- updated selectors, filters, changed logic for URl combobox
- added scroll to the element steps
- updated getRuns function on mock
- added tests for metrics overview
> QA Sprint 166 done

- tests/features/common-tools/common-consts.js
- tests/features/common/actions/input-group.action.js
- tests/features/common/page-objects.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/project-settings.po.js
- tests/features/jobsMonitoring.feature
- tests/features/models.feature
- tests/features/projectMonitoring.feature
- tests/features/projectSettings.feature
- tests/features/step-definitions/steps.js
- tests/features/step-definitions/table.steps.js
- tests/mockServer/mock.js
* Updated tests according to requirements
- updated selectors, filters, changed logic for URl combobox
- added scroll to the element steps
- updated getRuns function on mock
* Added tests for metrics overview
---------
> Impl [Tests] QA Sprint 166 done

- src/components/JobWizard/JobWizard.util.js
- **Batch Run**: Parameters type options issues
Jira: https://iguazio.atlassian.net/browse/ML-5156
> Fix [Batch Run] parameters type options issues

- src/actions/featureStore.js
- **Feature store**: inconsistent "You do not have permission to create a new feature set." error message
Jira: [ML-7717](https://iguazio.atlassian.net/browse/ML-7717)
[ML-7717]: https://iguazio.atlassian.net/browse/ML-7717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Feature store] inconsistent "You do not have permission to create a new feature set." error message

- src/elements/WorkflowsTable/WorkflowsTable.js
- **Workflows**: UI - show detailed error message from pipeline
Jira: https://iguazio.atlassian.net/browse/ML-7416
> Fix [Workflows] UI - show detailed error message from pipeline

- src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
- **Batch Run**: unable to update parameter
Jira: https://iguazio.atlassian.net/browse/ML-7675
> Fix [Batch Run] unable to update parameter

- src/components/FunctionsPage/functions.util.js
- **Functions**: hide Build and run action
Jira: https://iguazio.atlassian.net/browse/ML-7625
> Fix [Functions] hide `Build and run` action

- .github/workflows/ci.yaml
- **CI/CD**: Branch Regex Pattern in CI Workflow
Jira: https://iguazio.atlassian.net/browse/ML-7733
> Fix [CI/CD] Branch Regex Pattern in CI Workflow

- src/components/JobWizard/JobWizard.util.js
- **Batch run**: Unify categories names
Jira: https://iguazio.atlassian.net/browse/ML-7748
> Fix [Batch run] Unify categories names

- src/elements/MetricsSelector/MetricsSelector.js
- **UI**: Popup closes on tooltip click
Jira: https://iguazio.atlassian.net/browse/ML-7550
> Fix [UI] Popup closes on tooltip click

- src/api/artifacts-api.js
- src/components/Files/Files.js
- src/components/Files/FilesView.js
- src/reducers/artifactsReducer.js
- src/utils/artifacts.util.js
- src/utils/searchArtifactItem.js
- tests/mockServer/mock.js
- **Artifacts**: GET /artifacts fails with 'Multiple rows were found when one or none was required' when listing artifacts
Jira: https://iguazio.atlassian.net/browse/ML-7623
> Fix [Artifacts] GET /artifacts fails with 'Multiple rows were found when one or none was required' when listing artifacts

- src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.scss
- src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
- **UI**: Overflow Issue in "Features Analysis" Table Header
Jira: [ML-7760](https://iguazio.atlassian.net/browse/ML-7760)
Before:
After:
[ML-7760]: https://iguazio.atlassian.net/browse/ML-7760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [UI] Overflow Issue in "Features Analysis" Table Header

- src/components/FunctionsPage/Functions.js
- src/components/FunctionsPanel/FunctionsPanel.js
- src/components/JobWizard/JobWizard.js
- src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
- src/elements/ArtifactsTableRow/ArtifactsTableRow.js
- src/utils/projects.js
- **UI**: Page crash when VPN is offline
Jira: https://iguazio.atlassian.net/browse/ML-6137
> Fix [UI] Page crash when VPN is offline

- tests/mockServer/mock.js
- **Mock**: Add mock to not allowed to create/update internal secrets (with mlrun key)
Jira: https://iguazio.atlassian.net/browse/ML-7819
> Tests [Mock] Add mock to not allowed to create/update internal secrets  (with mlrun key)

- src/scss/main.scss
- src/utils/getState.js
- **Jobs**: no status for "Terminating" state for workflow
Jira: https://iguazio.atlassian.net/browse/ML-7785
> Fix [Jobs] no status for "Terminating" state for workflow

- src/components/Datasets/Datasets.js
- src/components/Datasets/DatasetsView.js
- src/components/Details/DetailsHeader/DetailsHeader.js
- src/components/Files/Files.js
- src/components/Files/FilesView.js
- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/Models/ModelsView.js
- src/elements/JobsTable/JobsTable.js
- **Artifacts**: unexpected application error on full view
Jira: https://iguazio.atlassian.net/browse/ML-7849
> Fix [Artifacts] unexpected application error on full view

- src/App.js
- src/common/Download/downloadContainer.scss
- src/layout/Page/Page.js
- **Artifacts**: Download notification popup is hidden
Jira: https://iguazio.atlassian.net/browse/ML-7754
> Fix [Artifacts] Download notification popup is hidden

- src/api/workflow-api.js
- **Workflows**: The 'name-contains' query parameter is missing
Jira: https://iguazio.atlassian.net/browse/ML-7827
> Fix [Workflows] The 'name-contains' query parameter is missing

- src/components/Project/ProjectMonitor.js
- src/components/Project/ProjectOverview/ProjectOverview.js
- src/components/Project/project.utils.js
- **Project monitoring**: Missing notification for failed requests
Jira: https://iguazio.atlassian.net/browse/ML-7860
> Fix [Project monitoring] Missing notification for failed requests

- src/actions/projects.js
- src/common/ErrorMessage/ErrorMessage.js
- src/common/ErrorMessage/errorMessage.scss
- **Projects**: misleading error in "Create new project" dialog when project create fails
Jira: [ML-7862](https://iguazio.atlassian.net/browse/ML-7862)
[ML-7862]: https://iguazio.atlassian.net/browse/ML-7862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Projects] misleading error in "Create new project" dialog when project create fails

- src/actions/nuclio.js
- src/actions/projects.js
- src/api/nuclio.js
- src/api/projects-api.js
- src/components/Project/ProjectMonitor.js
- src/elements/ProjectFunctions/ProjectFunctions.js
- src/elements/ProjectJobs/ProjectJobs.js
- **Project monitoring**: requests are not canceled when changing pages
Jira: https://iguazio.atlassian.net/browse/ML-7831
> Fix [Project monitoring] requests are not canceled when changing pages

- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
- **Project Jobs Monitoring**: Change filtering by project name
Jira: https://iguazio.atlassian.net/browse/ML-7894
> Fix [Project Jobs Monitoring] Change filtering by project name

- src/components/ModelsPage/Models/models.util.js
- **Models**: incorrect delete confirmation message
Jira: [ML-7882](https://iguazio.atlassian.net/browse/ML-7882)
[ML-7882]: https://iguazio.atlassian.net/browse/ML-7882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Models] incorrect delete confirmation message

- tests/features/MLFunction.feature
- tests/features/artifacts.feature
- tests/features/common/actions/action-menu.action.js
- tests/features/common/actions/input-group.action.js
- tests/features/common/page-objects.js
- tests/features/common/page-objects/feature-store.po.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/models.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/projectMonitoring.feature
- tests/features/projectSettings.feature
- tests/features/projectsPage.feature
- tests/features/quickActions.feature
- tests/features/step-definitions/steps.js
- tests/mockServer/data/artifacts.json
- added Date Picker Filter Dropdown functionality due to Revamp ML Function page (ML-5846)
- modify tests for hint item selection (changed click to hover)
- added test for artifact Full view content
- added test for delete option on Datasets, Models
- split the test check for preview and deploy functionality
> QA Sprint 168 done

- tests/features/MLFunction.feature
- tests/features/artifacts.feature
- tests/features/common/actions/action-menu.action.js
- tests/features/common/actions/input-group.action.js
- tests/features/common/page-objects.js
- tests/features/common/page-objects/feature-store.po.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/models.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/projectMonitoring.feature
- tests/features/projectSettings.feature
- tests/features/projectsPage.feature
- tests/features/quickActions.feature
- tests/features/step-definitions/steps.js
- tests/mockServer/data/artifacts.json
- added Date Picker Filter Dropdown functionality due to Revamp Ml function page (ML-5846)
- modify tests for hint item selection (changed click to hover)
- added test for artifact Full view content
- added test for delete option on Datasets, Models
- split the test check for preview and deploy functionality
> Impl [Tests] QA Sprint 168 done

- src/elements/MetricsSelector/MetricsSelector.js
- **Models endpoints monitoring, metrics**: add a tooltip to disabled metrics selector
Jira: https://iguazio.atlassian.net/browse/ML-7711
> Fix [Models endpoints monitoring, metrics] add a tooltip to disabled metrics selector

- tests/mockServer/mock.js
- **Artifacts**: Add mock for GET artifacts request
Jira: https://iguazio.atlassian.net/browse/ML-7044
> Impl [Artifacts] Add mock for GET `artifacts` request

- src/actions/projects.js
- src/common/Breadcrumbs/Breadcrumbs.js
- src/components/ProjectsPage/Projects.js
- src/components/ProjectsPage/projects.util.js
- src/constants.js
- **Breadcrumbs**: Archived projects are displayed in the projects dropdown selection
Backported to `1.7.x` from https://github.com/mlrun/ui/pull/2747
Jira: [ML-7398](https://iguazio.atlassian.net/browse/ML-7398)
[ML-7398]: https://iguazio.atlassian.net/browse/ML-7398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Breadcrumbs] Archived projects are displayed in the projects dropdown selection `1.7.x`

- src/common/TabsSlider/TabsSlider.js
- src/components/Details/DetailsHeader/DetailsHeader.js
- **Security, UI**: detected vulnerabilities in Link component
Backported to `1.7.x` from #2750 
Jira: https://iguazio.atlassian.net/browse/ML-7885
> Fix [Security][UI] detected vulnerabilities in Link component `1.7.x`

- src/components/ArtifactsActionBar/ArtifactsFilters.js
- src/components/FilterMenu/FilterMenu.js
- tests/mockServer/mock.js
- **Models**: Change models filter by label to case insensitive
Backported to `1.7.x` from https://github.com/mlrun/ui/pull/2717
Jira: https://iguazio.atlassian.net/browse/ML-7655
> Fix [Models] Change models filter by label to case insensitive `1.7.x`

- src/common/TabsSlider/TabsSlider.js
- src/components/Details/DetailsHeader/DetailsHeader.js
- **Security**: detected vulnerabilities in Link component
Jira: [ML-7885](https://iguazio.atlassian.net/browse/ML-7885)
[ML-7885]: https://iguazio.atlassian.net/browse/ML-7885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Security][UI] detected vulnerabilities in Link component

- src/actions/projects.js
- src/common/Breadcrumbs/Breadcrumbs.js
- src/components/ProjectsPage/Projects.js
- src/components/ProjectsPage/projects.util.js
- src/constants.js
- **Breadcrumbs**: Archived projects are displayed in the projects dropdown selection
Jira: [ML-7398](https://iguazio.atlassian.net/browse/ML-7398)
[ML-7398]: https://iguazio.atlassian.net/browse/ML-7398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Breadcrumbs] Archived projects are displayed in the projects dropdown selection

- src/components/ArtifactInfoSources/ArtifactInfoSources.js
- src/components/DetailsInfo/DetailsInfo.js
- src/components/DetailsInfo/detailsInfo.scss
- src/components/DetailsInfo/detailsInfo.util.js
- src/components/DetailsInputs/DetailsInputs.js
- src/components/DetailsInputs/detailsInputs.util.js
- src/elements/DetailsInfoItem/DetailsInfoItem.js
- src/utils/generateStoreResourceLink.js
- tests/mockServer/data/artifacts.json
- **UI**: MLRun Artifact/Job Linking Broken
Jira: https://iguazio.atlassian.net/browse/ML-7782
> Fix [UI] MLRun Artifact/Job Linking Broken

- src/components/ActionBar/ActionBar.js
- **React**: add missing dependencies
Jira: https://iguazio.atlassian.net/browse/ML-7936
> Fix [React] add missing dependencies

- src/components/ActionBar/ActionBar.js
- **React**: add missing dependencies
Backported to `1.7.x` from #2763 
Jira: https://iguazio.atlassian.net/browse/ML-7936
> Fix [React] add missing dependencies `1.7.x`

- tests/features/MLFunction.feature
- tests/features/artifacts.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects/jobs-monitoring.po.js
- tests/features/common/page-objects/projects.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/jobsMonitoring.feature
- tests/features/projectMonitoring.feature
- tests/features/projectsPage.feature
- tests/features/quickActions.feature
- tests/mockServer/mock.js
Updated tests according to requirements:
- updated test data due to ML-7849
- added checks for artifacts full view pane
- updated tests with new messages
- added checks for components on Jobs monitoring page
> QA Sprint 169 done

- tests/features/MLFunction.feature
- tests/features/artifacts.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects/jobs-monitoring.po.js
- tests/features/common/page-objects/projects.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/jobsMonitoring.feature
- tests/features/projectMonitoring.feature
- tests/features/projectsPage.feature
- tests/features/quickActions.feature
- tests/mockServer/mock.js
- updated test data due to ML-7849
- added checks for artifacts full view pane
- updated tests with new messages
- added checks for components on Jobs monitoring page
> Impl [Tests] QA Sprint 169 done

- src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
- **Feature vectors**: project name is missing from the request for tags
Jira: https://iguazio.atlassian.net/browse/ML-7839
> Fix [Feature vectors] project name is missing from the request for tags

- src/components/MetricChart/MetricChart.js
- src/components/MetricChart/metricChart.util.js
- src/utils/getMetricChartConfig.js
- **Model Monitoring**: Fix model metrics multiple date values on metrics screen selection
Backported to `1.7.x` from #2771 
Jira: https://iguazio.atlassian.net/browse/ML-7813
> Fix [Model Monitoring] fix model metrics multiple date values on metrics screen selection `1.7.x`

- src/components/Jobs/jobs.util.js
- src/elements/WorkflowsTable/WorkflowsTable.js
- **Workflows**: Abort among Actions on workflow jobs with statuses completed / error / aborted
Backported to `1.7.x` from #2774 
Jira: https://iguazio.atlassian.net/browse/ML-7884
> Fix [Workflows] Abort among Actions on workflow jobs with statuses completed / error / aborted `1.7.x`

- src/components/Jobs/jobs.util.js
- src/elements/WorkflowsTable/WorkflowsTable.js
- **Workflows**: Abort among Actions on workflow jobs with statuses completed / error / aborted
Jira: https://iguazio.atlassian.net/browse/ML-7884
> Fix [Workflows] Abort among Actions on workflow jobs with statuses completed / error / aborted

- src/index.js
- **CE**: Project link is broken fails to browse to project UI
Jira: https://iguazio.atlassian.net/browse/ML-7939
> Fix [CE] project link is broken fails to browse to project UI

- src/components/FunctionsPanel/FunctionsPanel.js
- **ML Functions**: Redundant notification appears
Jira: https://iguazio.atlassian.net/browse/ML-7960
> Fix [ML Functions] Redundant notification appears

- tests/features/MLFunction.feature
- tests/features/artifacts.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects/jobs-monitoring.po.js
- tests/features/common/page-objects/projects.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/jobsMonitoring.feature
- tests/features/projectMonitoring.feature
- tests/features/projectsPage.feature
- tests/features/quickActions.feature
- tests/mockServer/mock.js
**Updated tests according to requirements:**
Backported to `1.7.x` from #2757 
- updated test data due to ML-7849
- added checks for artifacts full view pane
- updated tests with new messages
- added checks for components on Jobs monitoring page
> QA Sprint 169 done `1.7.x`

- src/components/FunctionsPage/Functions.js
- src/components/FunctionsPage/FunctionsView.js
- **Functions**: Wrong list after "Build and run" `1.7.x`
Backported to `1.7.x` from #2789 
Jira: https://iguazio.atlassian.net/browse/ML-7798?filter=-1
> Fix [Functions] wrong list after "Build and run" `1.7.x`

- src/components/FunctionsPage/Functions.js
- **Functions**: deleted ML function stays in the list after successful deletion 
Jira: [ML-7961](https://iguazio.atlassian.net/browse/ML-7961)
[ML-7961]: https://iguazio.atlassian.net/browse/ML-7961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Functions] deleted ML function stays in the list after successful deletion

- src/components/Datasets/Datasets.js
- src/components/Datasets/datasets.util.js
- src/components/Files/Files.js
- src/components/Files/files.util.js
- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/Models/models.util.js
- src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
- src/reducers/artifactsReducer.js
- src/utils/getUniqueIdentifier.js
- **Artifacts**: Redundant request on expanding the artifact
Jira: https://iguazio.atlassian.net/browse/ML-7977
> Fix [Artifacts] redundant request on expanding the artifact

- src/components/Details/details.util.js
- src/components/Jobs/jobs.util.js
- **Jobs**: run UI does not present run handler
Jira: https://iguazio.atlassian.net/browse/ML-8005
After:
> Fix [Jobs] run UI does not present run handler

- src/components/FunctionsPage/Functions.js
- **ML Functions**: There is no redirection to function overview pane
Jira: https://iguazio.atlassian.net/browse/ML-8016
> Fix [ML Functions] There is no redirection to function overview pane

- src/components/ArtifactsActionBar/ArtifactsActionBar.js
- **Artifacts**: the current artifact name is included in the request when switching between artifact pages
Jira: https://iguazio.atlassian.net/browse/ML-7978
> Fix [Artifacts] the current artifact name is included in the request when switching between artifact pages

- src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
- **UI**: "add a tag" UI should not check uniqueness but rather update the existing tag 
Jira: https://iguazio.atlassian.net/browse/ML-8012
> Fix [UI] "add a tag" UI should not check uniqueness but rather update the existing tag

- tests/features/MLFunction.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects/jobs-monitoring.po.js
- tests/features/common/page-objects/project-settings.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/jobsMonitoring.feature
- tests/features/models.feature
- tests/features/projectSettings.feature
- tests/features/projectsPage.feature
- tests/features/step-definitions/table.steps.js
- tests/mockServer/data/artifacts.json
- tests/mockServer/data/schedules.json
- tests/mockServer/dateSynchronization.js
- tests/mockServer/mock.js
- updated test Secrets table on Secrets tab due to ML-6244, ML-7819
- updated test on ML Functions with new redirection logic for function name
- updated test on Projects page with deletion messages due to ML-7939
- added tests for searching by name, project, date filter on the Jobs Monitoring page
- updated tests on the Jobs Monitoring, Projects pages due to ML-7436
- updated mock with filtering by labels for artifacts, features
> QA Sprint 170 done

- tests/features/MLFunction.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects/jobs-monitoring.po.js
- tests/features/common/page-objects/project-settings.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/jobsMonitoring.feature
- tests/features/models.feature
- tests/features/projectSettings.feature
- tests/features/projectsPage.feature
- tests/features/step-definitions/table.steps.js
- tests/mockServer/data/artifacts.json
- tests/mockServer/data/schedules.json
- tests/mockServer/dateSynchronization.js
- tests/mockServer/mock.js
- updated test Secrets table on Secrets tab due to ML-6244, ML-7819
- updated test on ML Functions with new redirection logic for function name
- updated test on Projects page with deletion messages due to ML-7939
- added tests for searching by name, project, date filter on the Jobs Monitoring page
- updated tests on the Jobs Monitoring, Projects pages due to ML-7436
- updated mock with filtering by labels for artifacts, features
> Impl [Tests] QA Sprint 170 done

- tests/features/MLFunction.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects/jobs-monitoring.po.js
- tests/features/common/page-objects/project-settings.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/jobsMonitoring.feature
- tests/features/models.feature
- tests/features/projectSettings.feature
- tests/features/projectsPage.feature
- tests/features/step-definitions/table.steps.js
- tests/mockServer/data/artifacts.json
- tests/mockServer/data/schedules.json
- tests/mockServer/dateSynchronization.js
- tests/mockServer/mock.js
- updated test Secrets table on Secrets tab due to ML-6244, ML-7819
- updated test on ML Functions with new redirection logic for function name
- updated test on Projects page with deletion messages due to ML-7939
- added tests for searching by name, project, date filter on the Jobs Monitoring page
- updated tests on the Jobs Monitoring, Projects pages due to ML-7436
- updated mock with filtering by labels for artifacts, features
> QA Sprint 170 done `1.7.x`

- package.json
- src/common/Input/Input.js
- src/components/ActionBar/ActionBar.js
- src/components/FeatureStore/FeatureVectors/FeatureVectors.js
- src/components/FunctionsPage/Functions.js
- src/components/Project/project.utils.js
- src/components/ProjectSettings/projectSettings.scss
- src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
- src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
- src/scss/main.scss
- **UI**: UI small fixes 
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/321
Jira: https://iguazio.atlassian.net/browse/ML-8019
> Fix [UI] UI small fixes

- package.json
- src/common/Input/Input.js
- src/components/ActionBar/ActionBar.js
- src/components/FeatureStore/FeatureVectors/FeatureVectors.js
- src/components/FunctionsPage/Functions.js
- src/components/Project/project.utils.js
- src/components/ProjectSettings/projectSettings.scss
- src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
- src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
- src/scss/main.scss
- **UI**: UI small fixes `1.7.x`
Backported to `1.7.x` from #2805 
Depends on: https://github.com/iguazio/dashboard-react-controls/pull/322
Jira: https://iguazio.atlassian.net/browse/ML-8019
> Fix [UI] UI small fixes `1.7.x`

- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
- **Cross project**: Runs of type 'Job' displayed in the runs list of type 'mpijob' 
Jira: https://iguazio.atlassian.net/browse/ML-8037
> Fix [Cross project] Runs of type 'Job' displayed in the runs list of type 'mpijob'

- src/utils/getState.js
- src/utils/parseJob.js
- **Jobs**: Add reason for job failure in UI next to the red status indicator
Jira: https://iguazio.atlassian.net/browse/ML-8001
> Impl [Jobs] Add reason for job failure in UI next to the red status indicator

- src/httpClient.js
- **General**: infinite loop when the BE endpoints return error
Jira: https://iguazio.atlassian.net/browse/ML-8034
> Fix [General] infinite loop when the BE endpoints return error

- src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
- src/utils/createArtifactsContent.js
- **Model Endpoints**: It takes ~35 second to fetch data 
Jira: https://iguazio.atlassian.net/browse/ML-8070
After:
> Fix [Model Endpoints] take ~35 second to fetch data

- package.json
- **Axios**: update the package
Jira: https://iguazio.atlassian.net/browse/ML-4374
> Impl [NPM] Upgrade the Axios package

- package.json
- **NPM**: Upgrade webpack package in DRC
Jira: https://iguazio.atlassian.net/browse/ML-8078
> Impl [NPM] Upgrade webpack package in DRC

- src/components/ProjectsPage/projects.util.js
- **Projects**: Wrong Jobs monitoring counters
Jira: https://iguazio.atlassian.net/browse/ML-8088
> Fix [Projects] wrong Jobs monitoring counters

- src/common/Input/Input.js
- src/components/Details/DetailsHeader/DetailsHeader.js
- src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
- src/elements/FeaturesTablePanel/FeaturesTablePanelView.js
- src/elements/FeaturesTablePanel/featuresTablePanel.scss
- src/elements/MembersPopUp/MembersPopUp.js
- **UI**: Warning icon overlay on input text
Jira: https://iguazio.atlassian.net/browse/ML-8085
> Fix [UI] Warning icon overlay on input text

- package.json
- tests/features/MLFunction.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/actions/table.action.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/jobs-monitoring.po.js
- tests/features/common/page-objects/ml-functions.po.js
- tests/features/common/page-objects/project-settings.po.js
- tests/features/common/page-objects/projects.po.js
- tests/features/datasets.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/jobsMonitoring.feature
- tests/features/models.feature
- tests/features/projectMonitoring.feature
- tests/features/projectSettings.feature
- tests/features/projectsPage.feature
- tests/features/step-definitions/table.steps.js
- tests/mockServer/data/funcs.json
- tests/mockServer/data/run.json
- tests/mockServer/data/runs.json
- tests/mockServer/dateSynchronization.js
- tests/mockServer/mock.js
- updated test on Project settings due to ML-7979
- added tests for searching by type, statuses, labels filter on the Jobs Monitoring page
- updated data for searching by type filter on the Jobs Monitoring page
- updated test with check broken link redirection on ML Functions
- added Show Untagged checkbox verify on ML Functions
- added Filter by filter verification on ML Functions
- updated label key/value verification on project card
- updated mock deleteProjectV2 with mlrun-deletion-strategy
> QA Sprint 171 done `1.7.x`

- package.json
- tests/features/MLFunction.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/actions/table.action.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/jobs-monitoring.po.js
- tests/features/common/page-objects/ml-functions.po.js
- tests/features/common/page-objects/project-settings.po.js
- tests/features/common/page-objects/projects.po.js
- tests/features/datasets.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/jobsMonitoring.feature
- tests/features/models.feature
- tests/features/projectMonitoring.feature
- tests/features/projectSettings.feature
- tests/features/projectsPage.feature
- tests/features/step-definitions/table.steps.js
- tests/mockServer/data/funcs.json
- tests/mockServer/data/run.json
- tests/mockServer/data/runs.json
- tests/mockServer/dateSynchronization.js
- tests/mockServer/mock.js
- updated test on Project settings due to ML-7979
- added tests for searching by type, statuses, labels filter on the Jobs Monitoring page
- updated data for searching by type filter on the Jobs Monitoring page
- updated test with check broken link redirection on ML Functions
- added Show Untagged checkbox verify on ML Functions
- added Filter by filter verification on ML Functions
- updated label key/value verification on project card
- updated mock deleteProjectV2 with mlrun-deletion-strategy
> QA Sprint 171 done

- src/components/Project/ProjectMonitor.js
- **Project monitoring**: Register model in demo mode with Unexpected Application Error
Jira: https://iguazio.atlassian.net/browse/ML-8092
> Fix [Project monitoring] Register model in demo mode with Unexpected Application Error

- src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
- **Settings**: Change Node Selectors more info message
Jira: https://iguazio.atlassian.net/browse/IG-23152
> Fix [Settings] Change Node Selectors more info message

- src/actions/projects.js
- **Projects**: Request 500 error message
Jira: https://iguazio.atlassian.net/browse/ML-8161
> Fix [Projects] Request 500 error message

- tests/mockServer/mock.js
- *Mock**: Update mock for creating a function from UI
Jira: https://iguazio.atlassian.net/browse/ML-8090
> Tests [Mock] Update mock for creating a function from UI

- src/httpClient.js
- tests/features/common-tools/common-tools.js
- tests/features/common/page-objects.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/projects.po.js
- tests/features/projectsPage.feature
- tests/features/support/hooks.js
- tests/mockServer/mock.js
- **Mock**: Add mock for 'unhealthy' mlrun message appear
Jira: https://iguazio.atlassian.net/browse/ML-7829
> Tests [Mock] Add mock for 'unhealthy' mlrun message appear

- src/components/DetailsResults/DetailsResults.js
- src/utils/resultsTable.js
- **Monitor Jobs**: Results columns are too wide when result it long
Jira: https://iguazio.atlassian.net/browse/ML-8107
> Fix [Monitor Jobs] results columns are too wide when result it long

- src/elements/ProjectsMonitoringCounters/JobsCounters.js
- src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
- **Monitoring] missing tooltips on counters 
Jira: https://iguazio.atlassian.net/browse/ML-8217
> Fix [Monitoring] missing tooltips on counters

- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- src/utils/scroll.util.js
- **Breadcrumbs**: Double scroll when selecting the last project
Jira: https://iguazio.atlassian.net/browse/ML-5531
> Fix [Breadcrumbs] Double scroll when selecting the last project

- tests/features/MLFunction.feature
- tests/features/artifacts.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects/feature-store.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/jobs-monitoring.po.js
- tests/features/datasets.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/jobsMonitoring.feature
- tests/features/projectMonitoring.feature
- updated test on Job and Workflows, Jobs Monitoring pages (Retry option) due to ML-8031
- updated test on Feature Store page (Cancel button) due to ML-8085
> QA Sprint 172 done

- src/components/DetailsArtifacts/detailsArtifacts.util.js
- src/components/DetailsInputs/detailsInputs.util.js
- src/utils/generateStoreResourceLink.js
- **Job Inputs, Job Artifacts**: opening a new tab outside the dashboard
Jira: https://iguazio.atlassian.net/browse/ML-8235
> Fix [Job Inputs, Job Artifacts] opening a new tab outside the dashboard

- src/components/Datasets/Datasets.js
- src/components/Datasets/DatasetsView.js
- src/components/Datasets/datasets.util.js
- src/components/Files/Files.js
- src/components/Files/FilesView.js
- src/components/Files/files.util.js
- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/Models/ModelsView.js
- src/components/ModelsPage/Models/models.util.js
- src/constants.js
- src/hooks/useInitialTableFetch.hook.js
- src/reducers/filtersReducer.js
- **Artifacts**: Change filters to use new component
Jira: https://iguazio.atlassian.net/browse/ML-8317
> Fix [Artifacts] Change filters to use new component

- src/components/Details/DetailsHeader/DetailsHeader.js
- src/utils/getState.js
- src/utils/parseJob.js
- **UI**: Error displayed as a reason for failed job `1.7.1`
Backported to `1.7.x` from #2882 
Jira: https://iguazio.atlassian.net/browse/ML-8286
> Fix [UI] Error displayed as a reason for failed job `1.7.1`

- src/components/Details/DetailsHeader/DetailsHeader.js
- src/utils/getState.js
- src/utils/parseJob.js
- **UI**: Error displayed as a reason for failed job 
Jira: https://iguazio.atlassian.net/browse/ML-8286
> Fix [UI] Error displayed as a reason for failed job

- src/App.js
- src/components/ProjectsAlerts/ProjectsAlerts.js
- src/components/ProjectsAlerts/ProjectsAlertsView.js
- **Projects ,Alerts**: Add Project Alerts page
Jira link: https://iguazio.atlassian.net/browse/ML-8298
> Impl [UI Projects Alerts] Add Project Alerts page

- src/components/Project/project.scss
- src/elements/ProjectTable/projectTable.scss
- **Project monitoring**: Adjust layout according to Figma
Jira: [ML-8377](https://iguazio.atlassian.net/browse/ML-8377)
Before:
After:
[ML-8377]: https://iguazio.atlassian.net/browse/ML-8377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Project monitoring] Adjust layout according to Figma

- src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
- **Feature store**: Fix paddings in action bar
Jira: [ML-8284](https://iguazio.atlassian.net/browse/ML-8284)
[ML-8284]: https://iguazio.atlassian.net/browse/ML-8284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Feature store] fix paddings in action bar

- src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
- src/components/ModelsPage/RealTimePipelines/realTimePipelines.util.js
- src/components/Pipeline/Pipeline.js
- **Realtime pipelines**: Reduce load on UI and BE
Jira: https://iguazio.atlassian.net/browse/ML-8371
> Impl [Realtime pipelines] Reduce load on UI and BE

- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
- src/reducers/artifactsReducer.js
- **Real time pipelines**: Filter by 'function kind'
Jira: https://iguazio.atlassian.net/browse/ML-8373
> Impl [Real time pipelines] Filter by 'function kind'

- src/elements/FormVolumesTable/formVolumesTable.util.js
- **Batch run**: Add validation checks for secrets in Batch run wizard
Jira: [ML-8469](https://iguazio.atlassian.net/browse/ML-8469)
[ML-8469]: https://iguazio.atlassian.net/browse/ML-8469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Batch run] Add validation checks for secrets in Batch run wizard

- src/elements/WorkflowsTable/WorkflowsTable.js
- **Workflows**: Success message on failed request
Jira: [ML-8513](https://iguazio.atlassian.net/browse/ML-8513)
[ML-8513]: https://iguazio.atlassian.net/browse/ML-8513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Workflows] Success message on failed request

- src/components/Jobs/MonitorJobs/monitorJobs.util.js
- src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
- src/components/Jobs/jobs.util.js
- src/elements/JobsTable/jobsTable.util.js
- src/elements/WorkflowsTable/WorkflowsTable.js
- **Jobs**: When running job of type local, we don't collect logs so "Logs" tab should not be displayed 
Jira: [ML-8467](https://iguazio.atlassian.net/browse/ML-8467)
[ML-8467]: https://iguazio.atlassian.net/browse/ML-8467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Jobs] When running job of type local, we don't collect logs so "Logs" tab should not be displayed

- src/common/Breadcrumbs/Breadcrumbs.js
- src/common/Breadcrumbs/BreadcrumbsStep/BreadcrumbsStep.js
- src/elements/BreadcrumbsDropdown/BreadcrumbsDropdown.js
- **UI**: Project request is sent 3 times
Jira: [ML-8312](https://iguazio.atlassian.net/browse/ML-8312)
Before:
After:
[ML-8312]: https://iguazio.atlassian.net/browse/ML-8312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [UI] project request is sent 3 times

- src/components/Details/DetailsHeader/DetailsHeader.js
- src/components/Details/details.scss
- **Workflows**: Single-line display issue for pipeline and job errors
Jira: [ML-8266](https://iguazio.atlassian.net/browse/ML-8266)
Before:
After:
[ML-8266]: https://iguazio.atlassian.net/browse/ML-8266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Workflows] single-line display issue for pipeline and job errors

- src/actions/projects.js
- src/components/JobWizard/JobWizard.js
- src/components/ProjectsPage/Projects.js
- src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
- **Latam**: UI failed to view large project yaml
Jira: [ML-4168](https://iguazio.atlassian.net/browse/ML-4168)
After:  
[ML-4168]: https://iguazio.atlassian.net/browse/ML-4168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Latam] UI failed to view large project yaml

- src/components/Details/DetailsHeader/DetailsHeader.js
- src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.js
- **Model Endpoints**: Missing created time in the details header
Fix to: [ML-7583](https://iguazio.atlassian.net/browse/ML-7583)
[ML-7583]: https://iguazio.atlassian.net/browse/ML-7583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Model Endpoints] Missing created time in the details header

- src/App.js
- src/common/Pagination/Pagination.js
- src/components/Jobs/Jobs.js
- src/components/Jobs/MonitorJobs/MonitorJobs.js
- src/components/Jobs/MonitorJobs/monitorJobs.util.js
- src/components/Jobs/jobs.util.js
- src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
- src/components/Table/TableView.js
- src/elements/JobsTable/JobsTable.js
- src/elements/TableTop/tableTop.scss
- src/hooks/useJobsPageData.js
- src/hooks/usePagination.hook.js
- src/utils/createJobsContent.js
- src/utils/jobs.util.js
- src/utils/link-helper.util.js
- **Jobs**: Change runs grouping behavior
Jira: https://iguazio.atlassian.net/browse/ML-8363
> Impl [Jobs] Change runs grouping behavior

- src/api/jobs-api.js
- src/elements/ScheduledJobsTable/ScheduledJobsTable.js
- src/reducers/jobReducer.js
- **Scheduled jobs**: Delete schedule silently fails with MLRunAccessDeniedError
Jira: [ML-8599](https://iguazio.atlassian.net/browse/ML-8599)
[ML-8599]: https://iguazio.atlassian.net/browse/ML-8599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Scheduled jobs] delete schedule silently fails with MLRunAccessDeniedError

- src/App.js
- src/components/Documents/Documents.js
- src/components/Documents/DocumentsView.js
- src/components/Documents/documents.util.js
- src/layout/Navbar/Navbar.utils.js
- **VectorDB**: new "Documents" page and navigation
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/344
Jira: https://iguazio.atlassian.net/browse/ML-8445
> Impl [VectorDB] new "Documents" page and navigation

- src/components/Documents/Documents.js
- src/components/Documents/DocumentsView.js
- src/components/Documents/documents.util.js
- src/constants.js
- **VectorDB**: Add "Documents" main table filters
Jira: https://iguazio.atlassian.net/browse/ML-8447
> Impl [VectorDB] Add "Documents" main table filters

- src/components/ProjectsPage/projects.util.js
- src/elements/ProjectsMonitoringCounters/JobsCounters.js
- src/elements/ProjectsMonitoringCounters/ScheduledJobsCounters.js
- src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
- src/utils/generateMonitoringData.js
- **Jobs Monitoring**: Wrong number of the total jobs and workflows
Jira: [ML-8318](https://iguazio.atlassian.net/browse/ML-8318)
[ML-8318]: https://iguazio.atlassian.net/browse/ML-8318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Jobs Monitoring] Wrong number of the total jobs and workflows

- src/elements/WorkflowsTable/WorkflowsTable.js
- **Workflows**: Missing refresh after success rerun
Jira: https://iguazio.atlassian.net/browse/ML-8633
> Fix [Workflows] Missing refresh after success rerun

- src/elements/ContentMenu/ContentMenu.js
- src/elements/ContentMenu/contentMenu.scss
- **Jobs and Workflows**: Active tab should not be clickable
Jira: [ML-8501](https://iguazio.atlassian.net/browse/ML-8501)
[ML-8501]: https://iguazio.atlassian.net/browse/ML-8501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Jobs and Workflows] active tab should not be clickable

- src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
- src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
- **Models**: Align the tabs on Models page
Jira: [ML-8581](https://iguazio.atlassian.net/browse/ML-8581)
[ML-8581]: https://iguazio.atlassian.net/browse/ML-8581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Models] Align the tabs on Models page

- src/elements/ContentMenu/ContentMenu.js
- **UI**: clickable tabs
Fix to: https://github.com/mlrun/ui/pull/2927
> Fix [UI] clickable tabs

- src/components/ProjectsPage/ProjectsMonitoring/projectsMonitoring.scss
- src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
- **Projects**: Monitoring view by Figma
Related to: https://github.com/mlrun/ui/pull/2909
Jira: [ML-8567](https://iguazio.atlassian.net/browse/ML-8567)
After:
[ML-8567]: https://iguazio.atlassian.net/browse/ML-8567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Projects] Monitoring view by Figma

- src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
- **Project settings**: Add debounce for owner input
Jira: https://iguazio.atlassian.net/browse/ML-8634
> Fix [Project settings] add debounce for owner input

- src/actions/functions.js
- src/common/Pagination/Pagination.js
- src/components/FunctionsPage/Functions.js
- src/components/FunctionsPage/FunctionsView.js
- src/components/FunctionsPage/functions.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- src/elements/JobsTable/JobsTable.js
- src/hooks/useJobsPageData.js
- **Functions**: Pagination
Jira: https://iguazio.atlassian.net/browse/ML-5329
> Impl [Functions] Pagination

- src/App.js
- src/common/ActionsMenu/ActionsMenu.js
- src/components/Details/Details.js
- src/components/Details/DetailsTabsContent/DetailsTabsContent.js
- src/components/Details/details.util.js
- src/components/DetailsInfo/DetailsInfo.js
- src/components/DetailsInfo/DetailsInfoView.js
- src/components/DetailsInfo/detailsInfo.util.js
- src/components/Documents/Documents.js
- src/components/Documents/DocumentsView.js
- src/components/Documents/documents.util.js
- src/constants.js
- src/elements/DetailsInfoItem/DetailsInfoItem.js
- **VectorDB**: Add Overview details tab
Jira: https://iguazio.atlassian.net/browse/ML-8705
> Impl [VectorDB] Add Overview details tab

- src/components/DetailsCollections/DetailsCollections.js
- src/components/DetailsCollections/detailsCollections.scss
- **VectorDB**: Add Collections Details tab
Jira: https://iguazio.atlassian.net/browse/ML-8576
> Impl [VectorDB] Add Collections Details tab

- src/elements/ProjectsMonitoringCounters/AlertsCounters.js
- **Alerts History**: Alerts activation page is broken
Jira: https://iguazio.atlassian.net/browse/ML-8653
> Fix [Alerts History] alerts activation page is broken

- src/components/ProjectsPage/ProjectsView.js
- src/components/ProjectsPage/projects.scss
- src/elements/ContentMenu/contentMenu.scss
- **Projects**: Move sort to the right
Uses: https://github.com/iguazio/dashboard-react-controls/pull/348
Jira: [ML-8696](https://iguazio.atlassian.net/browse/ML-8696)
[ML-8696]: https://iguazio.atlassian.net/browse/ML-8696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Impl [Projects] move sort to the right

- src/components/Jobs/Jobs.js
- **Jobs and Workflows**: Runtime error for action menu Monitoring option
Jira: [ML-8554](https://iguazio.atlassian.net/browse/ML-8554)
[ML-8554]: https://iguazio.atlassian.net/browse/ML-8554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Jobs and Workflows] Runtime error for action menu Monitoring option

- src/components/DetailsInfo/detailsInfo.util.js
- **Artifacts**: Inconsistent Display of Producer Info for Artifact Based on Producer Kind
Jira: [ML-8328](https://iguazio.atlassian.net/browse/ML-8328)
[ML-8328]: https://iguazio.atlassian.net/browse/ML-8328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Artifacts] Inconsistent Display of Producer Info for Artifact Based on Producer Kind

- src/utils/createAlertsContent.js
- **QA**: Alert notifications data-testid
Jira: https://iguazio.atlassian.net/browse/ML-8531
> Impl [QA] Alert notifications data-testid

- src/common/StatsCard/StatsCard.js
- src/common/StatsCard/statsCard.scss
- src/components/Project/ProjectMonitorView.js
- src/components/Project/project.scss
- src/components/ProjectsPage/ProjectsMonitoring/projectsMonitoring.scss
- src/elements/ProjectJobs/projectJobs.utils.js
- src/elements/ProjectSummaryCard/ProjectSummaryCard.js
- src/elements/ProjectsMonitoringCounters/AlertsCounters.js
- src/elements/ProjectsMonitoringCounters/JobsCounters.js
- src/elements/ProjectsMonitoringCounters/ScheduledJobsCounters.js
- src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
- src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
- src/utils/generateAlertsStats.js
- **UI**: Additional fix to #2948 
Jira: https://iguazio.atlassian.net/browse/ML-8098
> Impl [UI] Additional fix to #2948

- src/api/artifacts-api.js
- src/components/Datasets/Datasets.js
- src/components/Datasets/DatasetsView.js
- src/components/Datasets/datasets.util.js
- src/components/Documents/Documents.js
- src/components/Files/Files.js
- src/components/Files/FilesView.js
- src/components/Files/files.util.js
- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/Models/ModelsView.js
- src/components/ModelsPage/Models/models.util.js
- src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
- src/elements/DetailsPopUp/ArtifactPopUp/ArtifactPopUp.js
- src/reducers/artifactsReducer.js
- src/utils/artifacts.util.js
- **Artifacts**: Pagination
Jira: https://iguazio.atlassian.net/browse/ML-7823
> Impl [Artifacts] Pagination

- src/reducers/jobReducer.js
https://iguazio.atlassian.net/browse/ML-8620
> Fix [Jobs] The project name is undefined for 'Abort Job'

- src/components/Datasets/datasets.util.js
- src/components/Files/Files.js
- src/components/Files/FilesView.js
- src/components/Files/files.util.js
- src/components/FunctionsPage/functions.util.js
- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/Models/ModelsView.js
- src/components/ModelsPage/Models/models.util.js
- src/utils/artifacts.util.js
- **Artifacts**: Wrong artifact details after click
Jira: https://iguazio.atlassian.net/browse/ML-8807
> Fix [Artifacts] wrong artifact details after click

- src/components/Documents/Documents.js
- src/components/Documents/DocumentsView.js
- src/components/Documents/documents.util.js
- src/reducers/artifactsReducer.js
- **VectorDB**: Add pagination
Jira: https://iguazio.atlassian.net/browse/ML-8809
> Impl [VectorDB] Add pagination

- src/components/Details/details.util.js
- src/components/DetailsCollections/DetailsCollections.js
- src/components/DetailsCollections/detailsCollections.scss
- src/components/DetailsInfo/detailsInfo.scss
- src/components/Documents/Documents.js
- src/components/Documents/documents.util.js
- src/utils/getNoDataMessage.js
- **Documents**: Multiple bugs
Jira: [ML-8815](https://iguazio.atlassian.net/browse/ML-8815)
Implements: [ML-8811](https://iguazio.atlassian.net/browse/ML-8811), [ML-8813](https://iguazio.atlassian.net/browse/ML-8813), [ML-8814](https://iguazio.atlassian.net/browse/ML-8814)
After:
[ML-8815]: https://iguazio.atlassian.net/browse/ML-8815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ML-8811]: https://iguazio.atlassian.net/browse/ML-8811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ML-8813]: https://iguazio.atlassian.net/browse/ML-8813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ML-8814]: …
> Fix [Documents] multiple bugs

- src/utils/createArtifactsContent.js
- **Model Monitoring**: Drift Status isn't been showed as it was
Jira: [ML-8721](https://iguazio.atlassian.net/browse/ML-8721)
[ML-8721]: https://iguazio.atlassian.net/browse/ML-8721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Model Monitoring UI] Drift Status isn't been showed as it was

- src/components/ModelsPage/ModelEndpoints/modelEndpoints.scss
- **Model endpoints**: Main table row height in details view
> Fix [Model endpoints] Main table row height in details view

- src/components/Jobs/Jobs.js
- **Monitor Jobs**: Auto refresh is broken
Jira: https://iguazio.atlassian.net/browse/ML-8923
> Fix [Monitor Jobs] Auto refresh is broken

- tests/features/MLFunction.feature
- tests/features/artifacts.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects.js
- tests/features/common/page-objects/files.po.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/jobs-and-workflows.po.js
- tests/features/common/page-objects/projects.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/projectsPage.feature
- tests/features/step-definitions/steps.js
- tests/mockServer/data/artifacts.json
- tests/mockServer/mock.js
- updated test with redirection of source path
- updated tests with changed redirection of broken links
- updated tests with checking the error message tooltip
- updated tests with revamp of the Monitoring section
- updated test with checking the scheduled jobs deletion
- added test with checking the Abort action on the Monitor Jobs tab
- added test to check filtering by the status  of workflows on the Workflows Monitor tab
- updated tests with checking status tooltips in the Monitoring section
- added test with check components on Alerts counter box
> Tests [QA] v1.8.0-rc13

- src/common/Pagination/pagination.scss
- src/components/DetailsInfo/detailsInfo.util.js
- src/elements/AlertsTableRow/AlertsTableRow.scss
- **Alerts history**: Trigger criteria time period is "Null", expected "N/A"
Jira: [ML-8910](https://iguazio.atlassian.net/browse/ML-8910)
[ML-8910]: https://iguazio.atlassian.net/browse/ML-8910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Alerts history] Trigger criteria time period is "Null", expected "N/A"

- src/components/DetailsInfo/detailsInfo.util.js
- src/utils/createAlertsContent.js
- **Alerts history**: Trigger criteria time period format not correct - Month instead Minute
Jira: [ML-8901](https://iguazio.atlassian.net/browse/ML-8901)
[ML-8901]: https://iguazio.atlassian.net/browse/ML-8901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Alerts history] Trigger criteria time period format not correct - Month instead Minute

- src/common/Pagination/Pagination.js
- **Pagination**: Current page shouldn't be clickable
Jira: [ML-8944](https://iguazio.atlassian.net/browse/ML-8944)
[ML-8944]: https://iguazio.atlassian.net/browse/ML-8944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Pagination] Current page shouldn't be clickable

- src/components/DetailsDrillDownAlert/AlertLogsModal.js
- src/elements/AlertsTableRow/AlertsTableRow.scss
- **Alerts history**: logs popup header should not scroll
> Fix [Alerts history] logs popup header should not scroll

- src/components/FunctionsPage/functions.util.js
- src/components/JobWizard/JobWizard.js
- src/reducers/jobReducer.js
- **Functions**: Revert and fix for empty Batch run on function run
Added fix to [ML-8704](https://iguazio.atlassian.net/browse/ML-8704) previous PR: https://github.com/mlrun/ui/pull/2981
[ML-8704]: https://iguazio.atlassian.net/browse/ML-8704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Function] Revert and fix for empty Batch run on function run

- tests/mockServer/mock.js
- **Documents**: Failed request on mock
Jira: https://iguazio.atlassian.net/browse/ML-9027
> Tests [Documents] Failed request on mock

- src/components/DetailsArtifacts/DetailsArtifacts.js
- src/components/JobWizard/JobWizard.js
- src/components/Jobs/Jobs.js
- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
- src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoring.js
- src/elements/JobsTable/JobsTable.js
- src/elements/WorkflowsTable/WorkflowsTable.js
- src/reducers/jobReducer.js
- **Job Artifacts**: Artifacts tab fails to load for workflow job
Jira: https://iguazio.atlassian.net/browse/ML-8680
> Fix [Job Artifacts] artifacts tab fails to load for workflow job

- src/common/Pagination/Pagination.js
- src/components/Datasets/DatasetsView.js
- src/components/Details/DetailsHeader/DetailsHeader.js
- src/components/Documents/DocumentsView.js
- src/components/Files/FilesView.js
- src/components/FunctionsPage/FunctionsView.js
- src/components/ModelsPage/Models/ModelsView.js
- src/components/Workflow/Workflow.js
- src/elements/JobsTable/JobsTable.js
- src/utils/jobs.util.js
- src/utils/link-helper.util.js
- **Functions, Artifacts, Jobs**: Unexpected redirection
Jira: https://iguazio.atlassian.net/browse/ML-8991
> Fix [Functions, Artifacts, Jobs] Unexpected redirection

- src/common/TargetPath/targetPath.util.js
- src/components/FeatureSetsPanel/UrlPath.utils.js
- src/utils/panelPathScheme.js
- **UI**: add "Documents" support to data input path
Jira: https://iguazio.atlassian.net/browse/ML-8966
> Fix [UI] add "Documents" support to data input path

- src/hooks/useJobsPageData.js
- src/reducers/jobReducer.js
- **Jobs**: Use labels filter for job type
Jira: https://iguazio.atlassian.net/browse/ML-8789
> Fix [Jobs] Use `labels` filter for job type

- src/components/Documents/Documents.js
- src/reducers/filtersReducer.js
- **Documents**: GET ../artifact-tags request is not being made upon navigating to documents tab
Jira: https://iguazio.atlassian.net/browse/ML-8971
> Fix [Documents] GET ../artifact-tags request is not being made upon navigating to documents tab

- src/elements/BreadcrumbsDropdown/breadcrumbsDropdown.scss
- src/utils/createArtifactsContent.js
- **Documents**: Adjust columns width
Jira: [ML-9044](https://iguazio.atlassian.net/browse/ML-9044)
[ML-9044]: https://iguazio.atlassian.net/browse/ML-9044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Documents] Adjust columns width

- src/components/Documents/documents.util.js
- **Documents**: 'Model was updated successfully' appears upon updating document labels
Jira: [ML-9080](https://iguazio.atlassian.net/browse/ML-9080)
[ML-9080]: https://iguazio.atlassian.net/browse/ML-9080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Documents] 'Model was updated successfully' appears upon updating document labels

- src/components/DetailsArtifacts/detailsArtifacts.util.js
- src/elements/DetailsPopUp/ArtifactPopUp/ArtifactPopUp.js
- **Job Artifacts**: Same artifact opens for all artifacts on Show Details click
Jira: https://iguazio.atlassian.net/browse/ML-8679
> Fix [Job Artifacts] same artifact opens for all artifacts on Show Details click

- src/hooks/useAlertsPageData.js
- **Alerts**: Pagination Error Due to Failed API Response
Jira: https://iguazio.atlassian.net/browse/ML-9021?filter=-1
> Fix [Alerts] Pagination Error Due to Failed API Response

- src/common/CopyToClipboard/CopyToClipboard.js
- src/common/Download/Download.js
- **Job Artifacts** UI crash on attempt to download artifact
Jira: https://iguazio.atlassian.net/browse/ML-8958
> Fix [Job Artifacts] UI crash on attempt to download artifact

- src/elements/DetailsInfoItem/DetailsInfoItem.js
- tests/mockServer/mock.js
- **UI**: data-ellipsis isn't working in details view
Jira: https://iguazio.atlassian.net/browse/ML-8945
> Fix [UI] data-ellipsis isn't working in details view

- src/common/BlockerSpy/BlockerSpy.js
- src/common/YamlModal/YamlModal.js
- src/components/Details/Details.js
- src/elements/DetailsPopUp/DetailsPopUp.js
- **Details popup**: doesn't close on back navigation
Jira: https://iguazio.atlassian.net/browse/ML-8444
> Fix [Details popup] doesn't close on back navigation

- src/reducers/jobReducer.js
- **Batch run**: UI crash when use the Batch run button
Jira: https://iguazio.atlassian.net/browse/ML-8976
> Fix [Batch run] UI crash when use the Batch run button

- src/components/Datasets/Datasets.js
- src/components/Datasets/datasets.util.js
- src/components/Documents/Documents.js
- src/components/Documents/documents.util.js
- src/components/Files/Files.js
- src/components/Files/files.util.js
- src/components/FunctionsPage/Functions.js
- src/components/FunctionsPage/functions.util.js
- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/Models/models.util.js
- src/elements/JobsTable/JobsTable.js
- src/hooks/usePagination.hook.js
- src/utils/jobs.util.js
- **Pagination**: No redirection to the first BE page
Jira: https://iguazio.atlassian.net/browse/ML-9040
> Fix [Pagination] No redirection to the first BE page

- src/elements/JobsTableRow/JobsTableRow.js
- src/elements/TableCell/TableCell.js
- **Schedule job**: missing job status
Jira: https://iguazio.atlassian.net/browse/ML-8512
> Fix [Schedule job] missing job status

- src/utils/getNoDataMessage.js
- **Jobs**: remove redundant 'Project:' filter label
Jira: https://iguazio.atlassian.net/browse/ML-9094
> Fix [Jobs] remove redundant 'Project:' filter label

- src/components/ActionBar/ActionBar.js
- src/components/AddToFeatureVectorPage/AddToFeatureVectorView.js
- src/components/Alerts/AlertsView.js
- src/components/Datasets/DatasetsView.js
- src/components/Documents/DocumentsView.js
- src/components/FeatureStore/FeatureSets/FeatureSetsView.js
- src/components/FeatureStore/FeatureVectors/FeatureVectorsView.js
- src/components/FeatureStore/Features/FeaturesView.js
- src/components/Files/FilesView.js
- src/components/FunctionsPage/FunctionsView.js
- src/components/Jobs/Jobs.js
- src/components/Jobs/MonitorJobs/MonitorJobs.js
- src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
- src/components/ModelsPage/Models/ModelsView.js
- src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
- src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
- src/elements/JobsTable/JobsTable.js
- **Feature Store**: Setting filters does not close the details panel
Jira: https://iguazio.atlassian.net/browse/ML-8413
> Fix [Feature Store] Setting filters does not close the details panel

- src/components/Datasets/datasets.util.js
- src/components/Documents/documents.util.js
- src/components/Files/files.util.js
- src/components/ModelsPage/Models/models.util.js
- **Artifacts**: Trying to preview deleted dataset causes UI error
Jira: https://iguazio.atlassian.net/browse/ML-9120
> Fix [Artifacts] trying to preview deleted dataset causes UI error

- src/components/ArtifactInfoSources/ArtifactInfoSources.js
- src/components/ArtifactInfoSources/artifactInfoSources.scss
- **Artifacts**: Uncaught runtime error for artifact source path
Jira: https://iguazio.atlassian.net/browse/ML-8849
> Fix [Artifacts] Uncaught runtime error for artifact source path

- src/components/Project/project.scss
- src/elements/ProjectDataCard/ProjectDataCard.js
- src/elements/ProjectJobs/ProjectJobs.js
- **Project monitoring**: Change list to 7 days
Jira: [ML-9167](https://iguazio.atlassian.net/browse/ML-9167)
[ML-9167]: https://iguazio.atlassian.net/browse/ML-9167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Impl [Project monitoring] Change list to 7 days

- src/components/Project/ProjectMonitorView.js
- src/scss/main.scss
- **Project monitoring**: Jobs and workflows section height
> Fix [Project monitoring] Jobs and workflows section height

- src/components/ProjectsPage/Projects.js
- **Projects**: 'Archive' button is not clickable
Jira: [ML-9175](https://iguazio.atlassian.net/browse/ML-9175)
[ML-9175]: https://iguazio.atlassian.net/browse/ML-9175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Projects] 'Archive' button is not clickable

- src/components/Project/project.scss
- src/components/ProjectsPage/projects.util.js
- **UI**: Loading spinner is stuck upon deleting non empty project
Jira: [ML-9149](https://iguazio.atlassian.net/browse/ML-9149)
[ML-9149]: https://iguazio.atlassian.net/browse/ML-9149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [UI] loading spinner is stuck upon deleting non empty project

- src/components/Datasets/Datasets.js
- src/components/Datasets/DatasetsView.js
- src/components/Datasets/datasets.util.js
- src/components/Documents/Documents.js
- src/components/Documents/DocumentsView.js
- src/components/Documents/documents.util.js
- src/components/Files/Files.js
- src/components/Files/FilesView.js
- src/components/Files/files.util.js
- src/components/Jobs/Jobs.js
- src/components/Jobs/MonitorJobs/MonitorJobs.js
- src/components/Jobs/MonitorJobs/monitorJobs.util.js
- src/components/Jobs/jobs.util.js
- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/Models/ModelsView.js
- src/components/ModelsPage/Models/models.util.js
- src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
- src/elements/DeleteArtifactPopUp/DeleteArtifactPopUp.js
- src/elements/JobsTable/JobsTable.js
- src/elements/WorkflowsTable/WorkflowsTable.js
- src/hooks/useJobsPageData.js
- src/hooks/useRefreshAfterDelete.hook.js
- src/utils/handleDeleteArtifact.js
- **Jobs**: Main list fails to refresh after run deletion
Jira: https://iguazio.atlassian.net/browse/ML-8736
> Fix [Jobs] Main list fails to refresh after run deletion

- src/components/ActionBar/ActionBar.js
- src/components/Jobs/Jobs.js
- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
- src/reducers/filtersReducer.js
- **Jobs and Workflows, Jobs Monitoring**: The 'Auto Refresh' issues
Jira: https://iguazio.atlassian.net/browse/ML-8982
> Fix [Jobs and Workflows, Jobs Monitoring] The 'Auto Refresh' issues

- src/components/Details/Details.js
- src/components/Details/DetailsTabsContent/DetailsTabsContent.js
- src/components/Details/details.util.js
- src/components/DetailsDrillDownAlert/DetailsDrillDownAlert.js
- src/elements/DetailsInfoItem/DetailsInfoItem.js
- **Labels**: Missing labels in artifacts / feature sets popups
Jira: [ML-8664](https://iguazio.atlassian.net/browse/ML-8664)
[ML-8664]: https://iguazio.atlassian.net/browse/ML-8664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Labels] Missing labels in artifacts / feature sets popups

- src/actions/featureStore.js
- src/api/featureStore-api.js
- src/components/FeatureStore/FeatureSets/FeatureSets.js
- src/components/FeatureStore/FeatureVectors/FeatureVectors.js
- src/components/FeatureStore/Features/Features.js
- **Feature store**: Row expansion request should consider all applied filters
Jira: https://iguazio.atlassian.net/browse/ML-8753
> Fix [Feature store] row expansion request should consider all applied filters

- src/common/Notifications/Notification.js
- src/common/Notifications/notification.scss
- src/common/Notifications/notifications.scss
- **UI**: Notification is too big and goes off the screen
Jira: https://iguazio.atlassian.net/browse/ML-8900
> Fix [UI] notification is too big and goes off the screen

- src/components/DetailsInfo/DetailsInfo.js
- src/components/DetailsInfo/detailsInfo.util.js
- src/elements/DetailsPopUp/ArtifactPopUp/ArtifactPopUp.js
- **UI**: "Failed to retrieve model data" on attempt to click on "Show details" of run artifact 
Jira: https://iguazio.atlassian.net/browse/ML-8913
> Fix [UI] "Failed to retrieve model data" on attempt to click on "Show details" of run artifact

- src/elements/ArtifactsTableRow/ArtifactsTableRow.js
- src/utils/getUniqueIdentifier.js
- **Model Endpoints**: Selected element doesn't highlighted
Relates to: https://github.com/mlrun/ui/pull/3052
Jira: https://iguazio.atlassian.net/browse/ML-9218
> Fix [Model Endpoints] Selected element doesn't highlighted

- src/elements/DetailsPopUp/FunctionPopUp/FunctionPopUp.js
- **Scheduled Jobs**: Wrong hash and tag displayed on detail function pane
Jira: https://iguazio.atlassian.net/browse/ML-8638
> Fix [Scheduled Jobs] Wrong hash and tag displayed on detail function pane

- package.json
- tests/features/common-tools/common-consts.js
- tests/features/common/actions/common.action.js
- tests/features/common/page-objects.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/models.po.js
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/step-definitions/steps.js
- tests/features/step-definitions/table.steps.js
- tests/mockServer/data/pipelines.json
- tests/mockServer/data/piplineIDs.json
- tests/mockServer/mock.js
Updated the tests to meet the requirements:
- updated tests with modal transition popup
- updated tests with new action menu options (Run\'s resource monitoring, Delete run, Delete all runs)
- updated test with show all versions element
- updated tests with new implementation of tags updating
- added Alerts tab visibility on Model Endpoint info pane
> Tests [UI] QA v1.8.0-rc26

- src/common/Notifications/notifications.scss
- **UI**: Page navigation blocked by Notification pop-up
Jira: https://iguazio.atlassian.net/browse/ML-9228
> Fix [UI] Page navigation blocked by Notification pop-up

- src/elements/ProjectsMonitoringCounters/AlertsCounters.js
- src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
- **Alerts history**: Alerts counter - background color when no alerts
Jira: [ML-9137](https://iguazio.atlassian.net/browse/ML-9137)
[ML-9137]: https://iguazio.atlassian.net/browse/ML-9137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Impl [Alerts history] Alerts counter - background color when no alerts

- src/components/Alerts/AlertsFilters.js
- **Alerts**: The Event type filter doesn't align with the Entity type option
Jira: [ML-9241](https://iguazio.atlassian.net/browse/ML-9241)
[ML-9241]: https://iguazio.atlassian.net/browse/ML-9241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Alerts] The Event type filter doesn't align with the Entity type option

- src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.scss
- src/components/DetailsMetrics/DetailsMetrics.scss
- src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
- src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
- **UI**: Small css changes
- Align "No data" message in model endpoints/metrics tab to vertical center of the body 
- Remove BE request on first time node selector field focus => blur event
> Fix [UI] small css changes

- src/components/Details/details.util.js
- **Features**: Failed to open feature set
Jira: https://iguazio.atlassian.net/browse/ML-9270
> Fix [Features] Failed to open feature set

- src/elements/ProjectDataCard/ProjectDataCard.js
- **Project Monitoring**: Missing notification for "last 7 days" if no jobs are displayed
Jira: [ML-9256](https://iguazio.atlassian.net/browse/ML-9256)
[ML-9256]: https://iguazio.atlassian.net/browse/ML-9256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Project Monitoring] Missing notification for "last 7 days" if no jobs are displayed

- src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
- **UI**: Sometimes Default Node Selector isn't present on The Project Setting screen
Jira: https://iguazio.atlassian.net/browse/ML-8934
> Fix [UI] Sometimes  Default Node Selector isn't present on The Project Setting  screen

- tests/features/MLFunction.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/actions/table.action.js
- tests/features/common/page-objects/feature-store.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/ml-functions.po.js
- tests/features/common/page-objects/side-panel.po.js
- tests/features/featureStore.feature
- tests/features/step-definitions/steps.js
- tests/features/step-definitions/table.steps.js
- tests/mockServer/data/featureSets.json
- tests/mockServer/mock.js
Refined the Feature Store test suite to align with the requirements
> Tests [QA] v1.8.0-rc31 

- src/components/Details/Details.js
- src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
- **UI**: "All changes will be lost" pop up appears upon artifact register / job schedule
Depends on: https://github.com/iguazio/dashboard-react-controls/pull/366
Jira: https://iguazio.atlassian.net/browse/ML-9242
> Fix [UI] "All changes will be lost" pop up appears upon artifact register / job schedule

- src/components/Datasets/Datasets.js
- src/components/Documents/Documents.js
- src/components/Files/Files.js
- src/components/ModelsPage/Models/Models.js
- src/hooks/useRefreshAfterDelete.hook.js
- **Artifacts**: 404 on get artifact after deleting the tag
Jira: https://iguazio.atlassian.net/browse/ML-9271
> Fix [Artifacts] 404 on get artifact after deleting the tag

- Dockerfile
- **Docker**: Update Dockerfile base image from node `14.8.1-alpine` to node `20.18.2-alpine`
Jira: https://iguazio.atlassian.net/browse/ML-9298
> Infra [Docker] update build base image to `20-alpine`

- src/components/Alerts/Alerts.js
- **Alerts history**: Fix Redundant Job Logs Requests on Refresh Button in ActionBar Component
Jira: https://iguazio.atlassian.net/browse/ML-9192?filter=-1
> Fix [Alerts history] Fix Redundant Job Logs Requests on Refresh Button in ActionBar Component

- src/components/ActionBar/ActionBar.js
- src/components/ArtifactsActionBar/ArtifactsFilters.js
- src/components/Datasets/DatasetsView.js
- src/components/Details/Details.js
- src/components/Documents/DocumentsView.js
- src/components/Files/FilesView.js
- src/components/ModelsPage/Models/ModelsView.js
- src/components/Table/Table.js
- src/components/Table/TableView.js
- **Artifacts, Feature Store, Documents**: Edit mode issues 
Jira: https://iguazio.atlassian.net/browse/ML-9134
> Fix [Artifacts, Feature Store, Documents] Edit mode issues

- src/elements/DetailsPopUp/ArtifactPopUp/ArtifactPopUp.js
- src/utils/parseUri.js
- **Model-Monitoring**: UI can't access the model of the model endpoint
Jira: https://iguazio.atlassian.net/browse/ML-9322
> Fix [Model-Monitoring] UI can't access the model of the model endpoint

- src/scss/main.scss
- src/utils/getState.js
- src/utils/parseWorkflows.js
- **Workflows**: The "Retry" button doesn't work the second time for a  "completed" workflow without using 'Refresh' button
Jira: https://iguazio.atlassian.net/browse/ML-9243
> Fix [Workflows] The "Retry" button doesn't work the second time for a  "completed" workflow without using 'Refresh' button

- src/elements/DetailsPopUp/FunctionPopUp/FunctionPopUp.js
- src/utils/artifacts.util.js
- **Artifacts**: Enhance clarity of messages after overwriting
Jira: https://iguazio.atlassian.net/browse/ML-9297
> Fix [Artifacts] Enhance clarity of messages after overwriting

- src/components/Details/details.util.js
- src/components/DetailsInputs/DetailsInputs.js
- src/elements/DetailsPopUp/FunctionPopUp/FunctionPopUp.js
- src/utils/createArtifactsContent.js
- src/utils/parseUri.js
- **Model-Monitoring**: UI can't access model function
Jira: http://iguazio.atlassian.net/browse/ML-9349
> Fix [Model-Monitoring] UI can't access model function

- src/api/functions-api.js
- src/components/Details/details.util.js
- src/elements/DetailsPopUp/FunctionPopUp/FunctionPopUp.js
- src/utils/createArtifactsContent.js
- src/utils/link-helper.util.js
- **Model endpoints**: Change logic to get model function according to BE changes
Jira: https://iguazio.atlassian.net/browse/ML-9372
> Fix [Model endpoints] Change logic to get model function according to BE changes

- src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
- **Workflows**: Change a tooltip for retry action
Jira: https://iguazio.atlassian.net/browse/ML-9380
> Fix [Workflows] Change a tooltip for retry action

- src/components/ProjectSettings/ProjectSettings.js
- **Projects settings**: missing delete project button in project setting screen on CE
Jira:https://iguazio.atlassian.net/browse/ML-9391
> Fix [Projects settings] missing delete project button in project setting screen on CE

- src/components/Details/details.util.js
- src/elements/DetailsPopUp/FunctionPopUp/FunctionPopUp.js
- src/utils/createArtifactsContent.js
- src/utils/link-helper.util.js
- **Model endpoint**: incorrect function returned for request with uid
Jira: https://iguazio.atlassian.net/browse/ML-9394
> Fix [Model endpoint] incorrect function returned for request with uid

- src/elements/WorkflowsTable/WorkflowsTable.js
- **Workflows**: sometimes workflows are sorted in reverse order from oldest to newest
Jira: https://iguazio.atlassian.net/browse/ML-9395
> Fix [Workflows] sometimes workflows are sorted in reverse order from oldest to newest

- src/components/Details/DetailsHeader/DetailsHeader.js
- **Job, Artifacts**: The same artifact is opened on changing iterations
Jira: https://iguazio.atlassian.net/browse/ML-9409
> Fix [Job Artifacts] the same artifact is opened on changing iterations

- src/elements/DetailsPopUp/ArtifactPopUp/ArtifactPopUp.js
- **Artifacts**: Redundant actions in artifacts pop ups
Jira: https://iguazio.atlassian.net/browse/ML-9386
> Fix [Artifacts] redundant actions in artifacts pop ups

- src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
- **Project settings**: Remove "Owner" in CE project settings
Jira: [ML-9384](https://iguazio.atlassian.net/browse/ML-9384) 
[ML-9384]: https://iguazio.atlassian.net/browse/ML-9384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Project settings] remove "Owner" in CE project settings

- src/components/ProjectSettings/ProjectSettings.js
- **Project Settings**: missing delete project button in project setting screen on CE
Jira: https://iguazio.atlassian.net/browse/ML-9391
> Fix [Project Settings] missing delete project button in project setting screen on CE

- src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
- src/reducers/artifactsReducer.js
- **Artifacts**: 'Add a tag' pop-up triggers a redundant refresh
Jira: https://iguazio.atlassian.net/browse/ML-9387
> Fix [Artifacts] 'Add a tag' pop-up triggers a redundant refresh

- src/components/JobWizard/JobWizard.js
- src/elements/JobsTable/JobsTable.js
- src/hooks/useFiltersFromSearchParams.hook.js
- **Batch Run**: Filtering is impacted after redirection following batch run start
Jira: https://iguazio.atlassian.net/browse/ML-9438
> Fix [Batch Run] Filtering is impacted after redirection following batch run start

- tests/features/alerts.feature
- tests/features/alertsMonitoring.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects/commonPagesHeader.po.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/project.po.js
- tests/features/common/page-objects/side-panel.po.js
- tests/features/projectMonitoring.feature
- tests/features/step-definitions/steps.js
**Updated the tests to meet the requirements**:
- updated tests for Alerts, Alerts monitoring pages
- refined the Project Monitoring test suite
> Tests [QA] v1.8.0-rc33

- src/api/artifacts-api.js
- **Artifacts**: "Failed to fetch artifacts" appears in 'Batch run' -> 'Data inputs'
Jira: https://iguazio.atlassian.net/browse/ML-9489
> Fix [Artifacts] "Failed to fetch artifacts" appears in 'Batch run' -> 'Data inputs'

- tests/features/artifacts.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects/files.po.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/jobs-and-workflows.po.js
- tests/features/common/page-objects/jobs-monitoring.po.js
- tests/features/jobsAndWorkflows.feature
- tests/features/jobsMonitoring.feature
- tests/mockServer/data/schedules.json
Updated the tests to meet the requirements:
- updated tests to cover Auto Refresh checkbox behavior
- refined the Artifacts test suite
- refined the Jobs Monitoring test suite
> Tests [QA] v1.8.0-rc34

- src/reducers/artifactsReducer.js
- **Artifacts**: update "Deleting artifact failed" message when deleting artifact by "Viewer" user
Jira: https://iguazio.atlassian.net/browse/ML-9506
> Fix [Artifacts] update "Deleting artifact failed" message when deleting artifact by "Viewer" user

- src/components/DetailsInputs/DetailsInputs.js
- **Job inputs**: incorrect category used for get artifacts request
Jira: https://iguazio.atlassian.net/browse/ML-9520
> Fix [Job inputs] incorrect category used for get artifacts request

- src/components/ActionBar/ActionBar.js
- src/components/Datasets/datasets.util.js
- src/components/Details/Details.js
- src/components/Details/details.util.js
- src/components/Documents/documents.util.js
- src/components/FeatureStore/FeatureVectors/featureVectors.util.js
- src/components/Files/files.util.js
- src/components/ModelsPage/Models/models.util.js
- src/elements/ActionMenuItem/ActionsMenuItem.js
- **Artifacts**: Add a confirmation pop-up
Jira: https://iguazio.atlassian.net/browse/ML-9324
> Fix [Artifacts] Add a confirmation pop-up

- src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
- **Settings**: Error occurs on refresh setting page
Jira: https://iguazio.atlassian.net/browse/ML-9460
> Fix [Settings] Error occurs on refresh setting page

- src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
- **Project Settings**: Unknown error on entering project settings
Jira: https://iguazio.atlassian.net/browse/ML-9612
> Fix [Project Settings] Unknown error on entering project settings 

- src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoringFilters.js
- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
- src/components/ProjectsJobsMonitoring/ScheduledMonitoring/ScheduledMonitoringFilters.js
- src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoring.js
- src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoringFilters.js
- src/hooks/useJobsPageData.js
- src/reducers/workflowReducer.js
- src/utils/getNoDataMessage.js
- src/utils/jobs.util.js
- **Alerts**: Projects all option appears in no data message
Jira: https://iguazio.atlassian.net/browse/ML-9217
> Fix [Alerts] Projects all option appears in no data message

- src/elements/ProjectsMonitoringCounters/AlertsCounters.js
- src/elements/ProjectsMonitoringCounters/JobsCounters.js
- src/elements/ProjectsMonitoringCounters/ScheduledJobsCounters.js
- src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
- src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
- **UI**: Icons width changes on small screen resolution
Jira: https://iguazio.atlassian.net/browse/ML-9606
> Fix [UI] Icons width changes on small screen resolution

- src/utils/generateUsageSnippets.js
- **Feature vectors**: Usage example
Backported to `1.8.x` from `development` https://github.com/mlrun/ui/pull/3186
Jira: https://iguazio.atlassian.net/browse/ML-9546
> Fix [Feature vectors] usage example `1.8.x`

- src/utils/generateUsageSnippets.js
- **Feature vectors**: Usage example
Backported to `1.9.x` from `development` https://github.com/mlrun/ui/pull/3186
Jira: https://iguazio.atlassian.net/browse/ML-9546
> Fix [Feature vectors] usage example `1.9.x`

- src/components/DetailsPreview/DetailsPreview.js
- **Jobs monitoring**: Failed to load job artifact preview
Jira: https://iguazio.atlassian.net/browse/ML-9727
> Fix [Jobs monitoring] failed to load job artifact preview

- src/components/DetailsPreview/DetailsPreview.js
- **Jobs monitoring**: Failed to load job artifact preview
Backported to `1.8.x` from #3190
Jira: https://iguazio.atlassian.net/browse/ML-9727
> Fix [Jobs monitoring] failed to load job artifact preview `1.8.x`

- src/common/TabsSlider/TabsSlider.js
- tests/mockServer/data/run.json
- tests/mockServer/data/runs.json
- **Mock**: No db_key, uid, tag in artifact details
Jira: https://iguazio.atlassian.net/browse/ML-9698
> Fix [Mock] No db_key, uid, tag in artifact details

- src/elements/PreviewModal/PreviewModal.js
- **Preview popup**: Wrong table header 
Jira: https://iguazio.atlassian.net/browse/ML-9740
> Fix [Preview popup] Wrong table header

- src/components/DetailsDrillDownAlert/DetailsAlertsMetrics.js
- **Alerts**: Metrics data does not displayed
Jira: https://iguazio.atlassian.net/browse/ML-9762
> Fix [Alerts] Metrics data does not displayed

- src/elements/PanelCredentialsAccessKey/PanelCredentialsAccessKey.js
- **Feature store**: Checkbox is not clickable
Jira: https://iguazio.atlassian.net/browse/ML-9795
> Fix [Feature store] Checkbox is not clickable

- src/components/FunctionsPageOld/FunctionsOld.js
- **ML functions**: "This function either does not exist or was deleted" notification after applying filter
Jira: https://iguazio.atlassian.net/browse/ML-9751
> Fix [ML functions] "This function either does not exist or was deleted" notification after applying filter

- tests/features/artifacts.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects/feature-store.po.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/datasets.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/support/hooks.js
- tests/mockServer/data/alerts.json
Updated the tests to meet the latest requirements:
- updated the tests to include setting igzFullVersion in localStorage
- updated tests with info pane message
- updated tests with version history
- updated tests with new tag editing logic
> Tests [QA] v1.10.0

- src/components/FunctionsPanel/FunctionsPanelView.js
- src/elements/PanelCredentialsAccessKey/PanelCredentialsAccessKey.js
- **Feature store & Functions panels**: Checkbox is not clickable
Jira: https://iguazio.atlassian.net/browse/ML-9795
> Fix [Feature store & Functions panels] Checkbox is not clickable

- package.json
- src/App.js
- src/common/Breadcrumbs/breadcrumbs.util.js
- src/common/DatePicker/DatePicker.js
- src/components/ActionBar/ActionBar.js
- src/components/MonitoringApplication/MonitoringApplication.js
- src/components/MonitoringApplication/monitoringApplication.scss
- src/components/MonitoringApplication/monitoringApplication.util.js
- src/constants.js
- src/layout/Navbar/Navbar.utils.js
- src/utils/datePicker.util.js
- **Monitoring application**: Add Monitoring application page
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/387
Jira: https://iguazio.atlassian.net/browse/ML-9806
> Impl [Monitoring application] Add Monitoring application page

- src/components/Details/DetailsHeader/DetailsHeader.jsx
- src/elements/DetailsPopUp/JobPopUp/JobPopUp.jsx
- src/hooks/usePods.hook.js
- src/reducers/detailsReducer.js
- **Details Popup**: Redundant pending data displayed in details function header
Jira: https://iguazio.atlassian.net/browse/ML-9738
> Fix [Details Popup] Redundant pending data displayed in details function header

- src/components/Details/details.scss
- src/elements/DetailsInfoItemChip/DetailsInfoItemChip.jsx
- **Artifacts**: Align the behavior in the the labels and description editing mode
Jira: https://iguazio.atlassian.net/browse/ML-9374
> Fix [Artifacts] Align the behavior in the the labels and description editing mode

- src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
- **Projects**: 'Are you sure?' pop-up is missing `1.8.x`
Backported to `1.8.x` from #3241 
> Fix [Projects] 'Are you sure?' pop-up is missing `1.8.x`

- src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.jsx
- **Projects**: 'Are you sure?' pop-up is missing
> Fix [Projects] 'Are you sure?' pop-up is missing

- src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
- **Projects**: 'Are you sure?' pop-up is missing `1.9.x`
Backported to `1.9.x` from #3241 
> Fix [Projects] 'Are you sure?' pop-up is missing `1.9.x`

- .github/workflows/build.yaml
- .github/workflows/ci.yaml
- generate-release-notes.js
- src/common/ActionsMenu/actionsMenu.scss
- src/common/Input/Input.jsx
- src/components/AddToFeatureVectorPage/AddToFeatureVectorView.jsx
- src/components/FeatureStore/FeatureVectors/FeatureVectors.jsx
- src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.jsx
- src/types.js
- **GitHub**: Vulnerabilities after migration to Vite
Jira: https://iguazio.atlassian.net/browse/ML-9902
> Fix [GitHub] Vulnerabilities after migration to Vite

- .github/workflows/ci.yaml
- **GitHub**: Vulnerabilities after migration to Vite (v2)
Jira: https://iguazio.atlassian.net/browse/ML-9902
> Fix [GitHub] Vulnerabilities after migration to Vite (v2)

- src/layout/Navbar/Navbar.jsx
- src/layout/Navbar/Navbar.scss
- **Navbar**: Pin Icon and additional links position should remain fixed
Jira: [ML-9905](https://iguazio.atlassian.net/browse/ML-9905)
Before:
After: 
[ML-9905]: https://iguazio.atlassian.net/browse/ML-9905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Navbar] Pin Icon and additional links position should remain fixed

- src/elements/DeleteArtifactPopUp/DeleteArtifactPopUp.jsx
- **Artifacts**: Click on "X" in Delete artifact? dialog does not take effect
Jira: https://iguazio.atlassian.net/browse/ML-9919
> Fix [Artifacts] click on "X" in Delete artifact? dialog does not take effect

- src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.jsx
- src/reducers/projectReducer.js
- **Vistra**: Add more informative message when user trying to create a project and he does not have developer permission
Jira: [ML-7771](https://iguazio.atlassian.net/browse/ML-7771)
[ML-7771]: https://iguazio.atlassian.net/browse/ML-7771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Impl [Vistra] Add more informative message when user trying to create a project and he does not have developer permission

- src/components/Jobs/MonitorJobs/MonitorJobs.jsx
- src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.jsx
- **Jobs, Projects**: Confirmation messages don't appear on pages other than Jobs
Jira: https://iguazio.atlassian.net/browse/ML-9846
> Fix [Jobs, Projects] Confirmation messages don't appear on pages other than Jobs

- src/components/Details/DetailsHeader/DetailsHeader.jsx
- src/components/Details/DetailsTabsContent/DetailsTabsContent.jsx
- src/components/DetailsPods/DetailsPods.jsx
- src/elements/DetailsPopUp/JobPopUp/JobPopUp.jsx
- src/hooks/usePods.hook.js
- src/reducers/detailsReducer.js
- tests/mockServer/data/runs.json
- **Scheduled**: The project name is undefined
Jira: https://iguazio.atlassian.net/browse/ML-10007
> Fix [Scheduled] The project name is undefined

- tests/features/MLFunction.feature
- tests/features/alertsMonitoring.feature
- tests/features/artifacts.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/actions/dropdown.action.js
- tests/features/common/page-objects/commonPagesHeader.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/project-settings.po.js
- tests/features/common/page-objects/project.po.js
- tests/features/common/page-objects/projects.po.js
- tests/features/datasets.feature
- tests/features/documents.feature
- tests/features/featureStore.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/projectMonitoring.feature
- tests/features/quickActions.feature
- tests/features/step-definitions/steps.js
- tests/mockServer/data/alerts.json
Updated the tests to meet the latest requirements:
- remove the "All tags" option from the filter list on main artifact page
- updated navbar locators
> Tests [QA] v1.10.0-rc2

- src/components/JobWizard/JobWizard.jsx
- src/hooks/useJobsPageData.js
- **Scheduled**: Unexpected application error when editing a scheduled job
Depends on: https://github.com/iguazio/dashboard-react-controls/pull/407
Jira: https://iguazio.atlassian.net/browse/ML-10108
> Fix [Scheduled] Unexpected application error when editing a scheduled job

- src/elements/ContentMenu/ContentMenu.jsx
- **Projects, Jobs**: Unexpected redirection to the Projects page when clicking on tabs
Jira: https://iguazio.atlassian.net/browse/ML-10120
> Fix [Projects, Jobs] Unexpected redirection to the Projects page when clicking on tabs

- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects.js
- tests/features/common/page-objects/llm-prompts.po.js
- tests/features/common/page-objects/monitoring-app.po.js
- tests/features/llmPrompts.feature
- tests/features/monitoringApp.feature
- tests/features/projectMonitoring.feature
- tests/features/projectsPage.feature
Updated the tests to meet the latest requirements:
- updated and added test for LLM prompts and Monitoring app pages
> Tests [QA] v1.10.0-rc4

- src/components/Workflow/Workflow.jsx
- **Workflows**: Add test IDs for Terminate button
Jira : [ML-10248](https://iguazio.atlassian.net/browse/ML-10248)
[ML-10248]: https://iguazio.atlassian.net/browse/ML-10248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Impl [Workflows] Add test IDs for Terminate button

- src/elements/ProjectDataCard/ProjectDataCard.jsx
- src/elements/ProjectFunctions/ProjectFunctions.jsx
- src/elements/ProjectJobs/ProjectJobs.jsx
- src/elements/ProjectJobs/projectJobs.utils.js
- src/elements/ProjectStatistics/ProjectStatistics.jsx
- src/elements/ProjectStatistics/projectStatistics.scss
- src/elements/ProjectStatisticsCounter/ProjectStatisticsCounter.jsx
- **Project monitoring**: Update Statistic section in Per-project page
Jira: [ML-10225](https://iguazio.atlassian.net/browse/ML-10225)
Change the counters to run counters:
[ML-10225]: https://iguazio.atlassian.net/browse/ML-10225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Impl [Project monitoring] Update Statistic section in Per-project page

- src/elements/ProjectCard/projectCard.scss
- src/elements/ProjectStatisticsCounter/ProjectStatisticsCounter.jsx
- **ProjectStatisticsCounter**: Numbers Should not overflow the circle
Jira: https://iguazio.atlassian.net/browse/ML-9504
> Fix [ProjectStatisticsCounter] Numbers Should not overflow the circle

- src/components/Documents/Documents.jsx
- **Documents**: Error occurs on enter Documents page
Jira: https://iguazio.atlassian.net/browse/ML-10234
> Fix [Documents] Error occurs on enter Documents page

- src/components/MonitoringApplicationsPage/MonitoringApplications/MonitoringApplicationCounters/MonitoringApplicationCard/MonitoringApplicationCard.jsx
- src/components/MonitoringApplicationsPage/MonitoringApplications/MonitoringApplicationCounters/monitoringApplicationCounters.scss
- src/components/MonitoringApplicationsPage/MonitoringApplications/MonitoringApplicationCounters/monitoringApplicationCounters.util.jsx
- src/components/MonitoringApplicationsPage/MonitoringApplications/MonitoringApplications.jsx
- src/components/MonitoringApplicationsPage/MonitoringApplications/monitoringApplications.util.js
- **Monitoring app**: UI alignment and text updates for Figma consistency
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/416
Jira: https://iguazio.atlassian.net/browse/ML-10267
> Fix [Monitoring app] UI alignment and text updates for Figma consistency

- src/components/Alerts/Alerts.jsx
- src/elements/ProjectJobs/projectJobs.utils.js
- src/elements/ProjectStatisticsCounter/ProjectStatisticsCounter.jsx
- **UI**: Unexpected application error
Jira: https://iguazio.atlassian.net/browse/ML-10286
> Fix [UI] Unexpected application error

- src/reducers/projectReducer.js
- **Project settings**: Project secrets are not displayed
Jira: https://iguazio.atlassian.net/browse/ML-10305
> Fix [Project settings] Project secrets are not displayed

- src/elements/FormParametersTable/FormParametersRow/FormParametersRow.jsx
- **Batch run**: hyper switch discards user input
Jira: https://iguazio.atlassian.net/browse/ML-10298
> Fix [Batch run] hyper switch discards user input

- src/App.jsx
- src/common/Breadcrumbs/breadcrumbs.util.js
- src/components/Project/ProjectMonitor.jsx
- src/constants.js
- src/layout/Navbar/navbar.util.jsx
- **UI**: Remove "Quick Action" page
Jira: [ML-10400](https://iguazio.atlassian.net/browse/ML-10400)
[ML-10400]: https://iguazio.atlassian.net/browse/ML-10400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Impl [UI] Remove "Quick Action" page

- tests/mockServer/mock.js
- **Terminate**: Add mock for terminate functionality
Jira: [ML-10243](https://iguazio.atlassian.net/browse/ML-10243)
[ML-10243]: https://iguazio.atlassian.net/browse/ML-10243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Tests [Terminate] Add mock for terminate functionality

- src/api/artifacts-api.js
- src/components/Details/DetailsPromptTemplate/ArgumentsTab.jsx
- src/components/Details/DetailsPromptTemplate/PromptTab.jsx
-**LLM prompts**: Application error on Arguments tab
Jira: https://iguazio.atlassian.net/browse/ML-10389
> Fix [LLM prompts] Application error on Arguments tab

- tests/mockServer/data/iguazioProjects.json
- tests/mockServer/data/iguazioSelf.json
- tests/mockServer/data/iguazioUserRelations.json
- tests/mockServer/data/projects.json
- **Mock**: Add mock for owner component
Jira: https://iguazio.atlassian.net/browse/ML-8230
> Tests [Mock] Add mock for owner component

- package.json
- tests/features/MLFunction.feature
- tests/features/alertsMonitoring.feature
- tests/features/artifacts.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/actions/dropdown.action.js
- tests/features/common/page-objects/feature-store.po.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/monitoring-app.po.js
- tests/features/common/page-objects/projects.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/jobsMonitoring.feature
- tests/features/monitoringApp.feature
- tests/features/projectMonitoring.feature
- tests/features/projectsPage.feature
- tests/features/quickActions.feature
- tests/features/step-definitions/steps.js
- tests/features/step-definitions/table.steps.js
Updated tests to align with latest requirements:
- updated tests to reflect changes in counters
- adjusted tests for Retry Run functionality
- updated tests with Analysis tab checks on Feature Store and Datasets pages
- removed Quick actions test suite from regression run
- updated Alerts monitoring tests with new mock data
> Tests [QA] v1.10.0-rc8 

- src/elements/ProjectsMonitoringCounters/ArtifactsCounters.jsx
- src/elements/ProjectsMonitoringCounters/JobsCounters.jsx
- src/elements/ProjectsMonitoringCounters/RunsCounters.jsx
- src/elements/ProjectsMonitoringCounters/WorkflowsCounters.jsx
- **Counters**: data-testid for running / failed runs counter
Jira: [ML-10435](https://iguazio.atlassian.net/browse/ML-10435)
[ML-10435]: https://iguazio.atlassian.net/browse/ML-10435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Counters] data-testid for running / failed runs counter

- src/common/ExpandableText/ExpandableText.jsx
- src/common/ExpandableText/expandableText.scss
- src/common/SearchNavigator/SearchNavigator.jsx
- src/common/SearchNavigator/searchNavigator.util.jsx
- src/components/Details/DetailsGenerationConfiguration/DetailsGenerationConfiguration.jsx
- src/components/Details/DetailsGenerationConfiguration/detailsGenerationConfiguration.scss
- src/components/Details/DetailsPromptTemplate/ArgumentsTab.jsx
- src/components/Details/DetailsPromptTemplate/PromptTab.jsx
- src/components/Details/DetailsPromptTemplate/detailsPromptTemplate.scss
- src/layout/Navbar/navbar.util.jsx
- **LLM Prompt Artifact**: Change UI view for Prompt template
Jira: https://iguazio.atlassian.net/browse/ML-10561
> Impl [LLM Prompt Artifact] Change UI view for Prompt template

- src/components/Workflow/workflow.util.js
- src/elements/WorkflowsTable/WorkflowsTable.jsx
- **Workflows**: Revise text of "Terminating" notification
Jira: [ML-10634](https://iguazio.atlassian.net/browse/ML-10634)
[ML-10634]: https://iguazio.atlassian.net/browse/ML-10634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Workflows] Revise text of "Terminating" notification

- src/elements/ProjectStatisticsCounter/ProjectStatisticsCounter.jsx
- **Projects**: Incorrect counter data on project cards for N/A projects
Jira: [ML-10658](https://iguazio.atlassian.net/browse/ML-10658)
[ML-10658]: https://iguazio.atlassian.net/browse/ML-10658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Projects] Incorrect counter data on project cards for N/A projects

- src/elements/ProjectsMonitoringCounters/ApplicationCounters.jsx
- src/elements/ProjectsMonitoringCounters/ArtifactsCounters.jsx
- src/utils/generateMonitoringData.js
- **Counters**: runs and workflows counters are missing stats__counter class 
Jira: [ML-10646](https://iguazio.atlassian.net/browse/ML-10646)
[ML-10646]: https://iguazio.atlassian.net/browse/ML-10646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Counters] runs and workflows counters are missing stats__counter class 

- src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.jsx
- **LLM prompts**: llm-prompt MEP will link to the llm-prompt artifact and not to the model artifact
Jira: https://iguazio.atlassian.net/browse/ML-9938
> Impl [LLM prompts] llm-prompt MEP will link to the llm-prompt artifact and not to the model artifact

- src/components/Details/DetailsPromptTemplate/detailsPromptTemplate.scss
- **LLM Prompt Artifact**: Broken view of content when typing search
Jira: https://iguazio.atlassian.net/browse/ML-10652
> Fix [LLM Prompt Artifact] Broken view of content when typing search

- src/elements/ProjectsMonitoringCounters/AlertsCounters.jsx
- src/elements/ProjectsMonitoringCounters/RunsCounters.jsx
- src/elements/ProjectsMonitoringCounters/WorkflowsCounters.jsx
- **Projects, Monitoring container, Cross projects**: Change text on project card info
Jira: https://iguazio.atlassian.net/browse/ML-6521
> Fix [Projects, Monitoring container, Cross projects] Change text on project card info

- tests/mockServer/data/summary.json
- **Counters**: Add mock for project monitoring counters
Jira: [ML-10412](https://iguazio.atlassian.net/browse/ML-10412)
[ML-10412]: https://iguazio.atlassian.net/browse/ML-10412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Tests [Counters] Add mock for project monitoring counters

- src/common/ExpandableText/ExpandableText.jsx
- src/common/ExpandableText/expandableText.scss
- src/common/SearchNavigator/SearchNavigator.jsx
- src/components/Details/DetailsPromptTemplate/PromptTab.jsx
- src/components/ModelsPage/Models/models.util.jsx
- **LLM Prompt Artifact**: Content becomes expanded only when the search contains more than 1 letter
Jira: https://iguazio.atlassian.net/browse/ML-10686
> Fix [LLM Prompt Artifact] Content becomes expanded only when the search contains more than 1 letter

- src/components/MonitoringApplicationsPage/monitoringApplicationsPage.scss
- src/utils/getChartConfig.jsx
- **Monitor Applications**: Y-axis label is truncated
Jira: https://iguazio.atlassian.net/browse/ML-10747
> Fix [Monitor Applications] Y-axis label is truncated

- src/components/LLMPrompts/llmPrompts.util.jsx
- **LLM Prompt Artifact**: Remove delete
Jira: https://iguazio.atlassian.net/browse/ML-10781
> Fix [LLM Prompt Artifact] Remove delete

- src/elements/ProjectsMonitoringCounters/AlertsCounters.jsx
- **Alerts**: Counters aren't displayed if request fails
Jira: https://iguazio.atlassian.net/browse/ML-10790
> Fix [Alerts] Counters aren't displayed if request fails

- src/common/Breadcrumbs/Breadcrumbs.jsx
- src/common/Breadcrumbs/breadcrumbs.util.js
- **LLM prompts**: Breadcrumb navigation does not include LLM prompts
Jira: https://iguazio.atlassian.net/browse/ML-10777
> Fix [LLM prompts] Breadcrumb navigation does not include LLM prompts

- src/components/MonitoringApplicationsPage/MonitoringApplicationsPage.jsx
- src/components/MonitoringApplicationsPage/monitoringApplicationsPage.scss
- src/components/Project/ProjectMonitorView.jsx
- src/components/Project/project.scss
- src/components/ProjectSettings/ProjectSettings.jsx
- src/components/ProjectSettings/projectSettings.scss
- src/scss/main.scss
- **General**: Breadcrumbs are scrolled with the content
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/432
Jira: https://iguazio.atlassian.net/browse/ML-10914
> Fix [General] Breadcrumbs are scrolled with the content

- src/components/DetailsDrillDownAlert/DetailsAlertsMetrics.jsx
- **UI**: Unexpected application error on Alerts tab in Model endpoint details
Jira: https://iguazio.atlassian.net/browse/ML-10760
> Fix [UI] Unexpected application error on Alerts tab in Model endpoint details

- src/components/Details/DetailsPromptTemplate/DetailsPromptTemplate.jsx
- src/components/Details/DetailsPromptTemplate/PromptTab.jsx
- src/components/Details/DetailsPromptTemplate/detailsPromptTemplate.scss
- src/reducers/artifactsReducer.js
- **LLM Prompts**: prompt template tab is empty log llm artifact with prompt_path
Jira: https://iguazio.atlassian.net/browse/ML-10743
> Fix [LLM Prompts ] prompt template tab is empty log llm artifact with prompt_path

- src/components/Details/DetailsPromptTemplate/PromptTab.jsx
- **LLM prompts**: Add message for invalid prompt template data
Jira: https://iguazio.atlassian.net/browse/ML-10862
> Fix [LLM prompts] Add message for invalid prompt template data

- src/components/ArtifactsActionBar/ArtifactsFilters.jsx
- src/elements/TableModelCell/TableModelCell.jsx
- src/elements/TableModelCell/tableModelCell.scss
- **LLM prompts**: Model version tag doesn't clear
Jira: https://iguazio.atlassian.net/browse/ML-10866
> Fix [LLM prompts] Model version tag doesn't clear

- src/components/Details/DetailsPromptTemplate/detailsPromptTemplate.scss
- **LLM prompts**: Make search and tabs row static
Jira: https://iguazio.atlassian.net/browse/ML-10865
> Fix [LLM prompts] Make search and tabs row static

- package.json
- src/components/Alerts/Alerts.jsx
- src/components/Artifacts/Artifacts.jsx
- src/components/FunctionsPage/Functions.jsx
- src/elements/JobsTable/JobsTable.jsx
- **Artifacts**: Selected artifact shifts out of view after opening detail pane
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/434
Jira: https://iguazio.atlassian.net/browse/ML-10882
> Fix [Artifacts] Selected artifact shifts out of view after opening detail pane

- eslint.config.mjs
- package.json
- src/common/MlChart/MlChart.jsx
- src/components/RegisterArtifactModal/RegisterArtifactModal.jsx
- src/elements/DetailsPopUp/ArtifactPopUp/ArtifactPopUp.jsx
- src/elements/RegisterModelModal/RegisterModelModal.jsx
- **ESLint**: Add import/named rule, fix eslint warnings
Jira: https://iguazio.atlassian.net/browse/ML-10965
> Fix [ESLint] Add `import/named` rule, fix eslint warnings

- src/components/ProjectsPage/projects.util.jsx
- src/elements/ProjectCard/projectCard.util.js
- src/elements/ProjectJobs/projectJobs.utils.js
- src/elements/ProjectsMonitoringCounters/AlertsCounters.jsx
- **Counters**: UI crash - TypeError: Cannot read properties of undefined (reading 'endpoint_alerts_count')
Jira: [ML-10951](https://iguazio.atlassian.net/browse/ML-10951)
[ML-10951]: https://iguazio.atlassian.net/browse/ML-10951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Counters] UI crash - TypeError: Cannot read properties of undefined (reading 'endpoint_alerts_count')

- src/common/Download/DownloadContainer.jsx
- src/common/Download/downloadContainer.scss
- **Download**: Issues with the download container
Jira: https://iguazio.atlassian.net/browse/ML-10990
> Fix [Download] Issues with the download container

- src/elements/PageHeader/pageHeader.scss
- **Counters**: Add info icon to cross-project and project-screen
Small fix: Adjust icon size
Jira: [ML-10939](https://iguazio.atlassian.net/browse/ML-10939)
[ML-10939]: https://iguazio.atlassian.net/browse/ML-10939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Counters] Add info icon to cross-project and project-screen

- src/utils/createApplicationContent.jsx
- **CE**: UI crash in monitoring-app screen
Jira: https://iguazio.atlassian.net/browse/ML-11035
> Fix [CE] UI crash in monitoring-app screen

- src/components/MonitoringApplicationsPage/MonitoringApplicationsPage.jsx
- **Monitoring app**: Application view starts in middle of page after drill-down
Jira: https://iguazio.atlassian.net/browse/ML-11050
> Fix [Monitoring app] Application view starts in middle of page after drill-down

- src/components/LLMPrompts/llmPrompts.util.jsx
- src/constants.js
- src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.jsx
- src/utils/artifacts.util.js
- src/utils/createArtifact.util.js
- **LLM prompt**: Failure message not clear when try to add exist tag to prompt artifact
Jira: https://iguazio.atlassian.net/browse/ML-11031
> Fix [LLM prompt ] Failure message not clear when try to add exist tag to prompt artifact

- src/api/monitoringApplications-api.js
- **Monitoring app**: Change MEP with detections request
Jira: https://iguazio.atlassian.net/browse/ML-11070
> Fix [Monitoring app] Change MEP with detections request

- src/common/Download/DownloadItem.jsx
- src/common/Download/downloadContainer.scss
- **Artifacts**: Download notification not interactable
Depend on: https://github.com/iguazio/dashboard-react-controls/pull/440
Jira: https://iguazio.atlassian.net/browse/ML-11079
> Fix [Artifacts] Download notification not interactable

- src/components/ApplicationMetrics/ApplicationMetrics.scss
- src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
- src/utils/getNoDataMessage.js
- **UI**: Adjust 'Monitoring app' css
> Fix [UI] Adjust 'Monitoring app' css

- tests/mockServer/data/modelEndpoints.json
- tests/mockServer/mock.js
- **Model endpoints**: Update mock for model endpoint filtering by mode
Jira: https://iguazio.atlassian.net/browse/ML-11130
> Fix [Model endpoints] Update mock for model endpoint filtering by mode

- src/elements/ScheduledJobsTable/ScheduledJobsTable.jsx
- src/reducers/jobReducer.js
- **Scheduled job**: Missing loader on deletion
Jira: https://iguazio.atlassian.net/browse/ML-11163
> Fix [Scheduled job]  Missing loader on deletion

- src/common/SearchNavigator/SearchNavigator.jsx
- **LLM Prompts**: Dot in the search highlights each letter
Jira: https://iguazio.atlassian.net/browse/ML-11234
> Fix [LLM Prompts] Dot in the search highlights each letter

- src/components/MonitoringApplicationsPage/MonitoringApplications/MonitoringApplicationCounters/monitoringApplicationCounters.util.jsx
- src/reducers/projectReducer.js
- src/utils/applications.utils.js
- **UI**: “Monitoring apps” counter mismatch
Jira: https://iguazio.atlassian.net/browse/ML-11193
> Impl [UI] “Monitoring apps” counter mismatch
