- src/common/Breadcrumbs/Breadcrumbs.js
- src/components/JobsItemInternal/JobsItemInternalView.js
- src/components/JobsItemInternal/jobItemInternal.scss
- src/components/SideBar/SideBarView.js
- src/elements/ChipCell/ChipCell.js
- src/elements/JobInternalInfo/JobInternalInfo.js
- src/elements/JobInternalInputs/JobInternalInputs.js
- src/elements/JobInternalResults/JobInternalResults.js
- src/elements/JobsTable/JobsTableView.js
- src/utils/string.js
- Use template literals rather than `+` operator for string concatenation.
- Use `Object.entries` + destructuring rather than `Object.keys` with `Object.values` with synced index.
> Impl [General] Change breadcrumbs divider symbol + cleanup

- src/components/ArtifactFilterLabels/ArtifactFilterLabels.js
- src/components/ArtifactInfoMetadata/ArtifactInfoMetada.js
- src/components/ArtifactInfoMetadata/artifactinfometadata.scss
- src/components/ArtifactInfoSources/ArtifactInfoSources.js
- src/components/Artifacts/Artifacts.js
- src/components/Artifacts/artifactsData.json
- src/components/ArtifactsPreview/ArtifactsPreview.js
- src/components/Details/Details.js
- src/components/DetailsArtifacts/DetailsArtifacts.js
- src/components/DetailsInfo/DetailsInfo.js
- src/components/FilterMenu/FilterMenu.js
- src/components/JobsPage/Jobs.js
- src/elements/JobsTableRow/JobsTableRow.js
- src/elements/TableCell/TableCell.js
- Jobs › Details pane › Artifacts tab: For dataset artifacts, when there is `preview` and `header` properties, display them as the preview instead of downloading actual file and parsing it
- Artifacts › Details pane:
- Info tab:
- Producer: Expect producer kinds other than "run" (show URI and Workflow only to "run" producer kind)
- Preview tab: For dataset artifacts, when there is `preview` and `header` properties, display them as the preview instead of downloading actual file and parsing it
- Add new tab "Metadata" with table schema and statistics of fields
Replaces #51 that were mistakenly merged without squash.
> Impl [Artifacts] Add Metadata tab

- nginx/nginx.conf.tmpl
- src/actions/functions.js
- src/api/artifacts-api.js
- src/api/functions-api.js
- src/api/jobs-api.js
- src/api/projects-api.js
- src/common/Download/Download.js
- src/components/NotificationDownload/NotificationDownload.js
- src/httpClient.js
- src/setupProxy.js
- /function-catalog/catalog.json - to return the entire catalog.
- /function-catalog/aggregate/function.yaml - to get specific function.
- Also renamed `HTTP` to `Http` in methods/properties names.
> Impl [General] Enable proxying to function templates relatively

- src/components/DetailsArtifacts/DetailsArtifacts.js
For example: `user=:+admin` is sent as a search param.
Bug originated in PR https://github.com/mlrun/ui/pull/70
> Fix [Jobs] Artifacts: preview not working, wrong user value sent

- Dockerfile
- nginx/nginx.conf.tmpl
For example, add this when running docker image:
```
-e MLRUN_V3IO_ACCESS_KEY=0a55b9d4-431e-443a-848b-c20f727c9943
```
Related to PR https://github.com/mlrun/ui/pull/98
> Impl [Config] Add `x-v3io-session-key` req header to nginx proxy

- src/components/Table/Table.js
- src/utils/createJobsContent.js
https://trello.com/c/XiGOhmWX/417-jobs-wrongly-put-wf-icon-for-job-when-grouped-by-name
> [Jobs] Wrongly put WF icon for job when grouped by name

- package.json
- `MLRUN_DOCKER_REGISTRY`: for example `quay.io/` (mind the `/`). If omitted will default to dockerhub.
- `MLRUN_DOCKER_REPO`: for example `mlrun` (defaults to `iguazio`).
- `MLRUN_DOCKER_TAG`: for example `latest` (defaults to the short form of the current git commit hash).
Usage example:
```
MLRUN_DOCKER_REGISTRY=quay.io/ MLRUN_DOCKER_REPO=mlrun MLRUN_DOCKER_TAG=latest npm run docker
```
> Impl [Build] Use MLRun docker image env vars in `docker` script

- nginx/nginx.conf.tmpl
the old config with `proxy_set_header x-v3io-session-key ${MLRUN_V3IO_ACCESS_KEY};` override the `x-v3io-session-key` no matter what (even if the env var is not set)
with the new config we override the header only if the header (not the env var) is not set already
how it's working:
```
map $http_x_v3io_session_key $v3io_session_key {
default   $http_x_v3io_session_key;
""        ${MLRUN_V3IO_ACCESS_KEY};
}
```
this basically says, if the value of the `x-v3io-session-key` header (`$http_x_v3io_session_key`) is `""` assign the `$v3io_session_key` variable with the value of `${MLRUN_V3IO_ACCESS_KEY}` otherwise (`default`) assign it the header value
and afterwards we assign the variable to the header
`proxy_set_header x-v3io-session-key $v3io_session_key;`
the `map` directive is only allowed …
> Override x-v3io-session-key header only if it's empty

- src/components/Table/table.scss
- src/elements/TableLinkCell/TableLinkCell.js
https://trello.com/c/HOjISfBq/470-functions-function-hash-overlaps-other-columns
Before:
After:
> [Functions] Fixed bug when function hash overlaps other columns

- src/components/JobsPanel/JobsPanel.js
https://trello.com/c/bWjIiDpI/471-jobs-wizard-use-instead-of-for-function-link
> [Jobs] Wizard: Use `@` instead of `:` for function link

- src/scss/main.scss
https://trello.com/c/UMEDQkDG/488-general-chips-have-redundant-scrollbars
> [General] Chips have redundant scrollbars

- src/utils/createJobsContent.js
https://trello.com/c/YZzOHS8o/489-jobs-workflow-jobs-have-wrong-type-icon
Before:
After:
> [Jobs] Workflow jobs have wrong type icon

- src/utils/generateGroupLatestItem.js
When grouping functions by name, where all the different function versions are nested in a group by the same name, instead of choosing the version with `metadata.tag` of `'latest'` as the one to show on the group's row, choose the version with latest `metadata.updated` value.
> Impl [Functions] Take latest-updated version instead of by tag

- config/webpack.config.js
Getting rid of these kind of warning while building for production:
```shell
Conflicting order between:
* css ./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-4!./src/elements/HiddenChipsBlock/hiddenChipsBlock.scss
* css ./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-4!./src/common/TableActionsMenu/tableActionsMenu.scss
* css ./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!. …
```
> Disabled mini-css-extract-plugin warnings

- src/components/JobsPanel/JobsPanelView.js
- src/components/JobsPanel/jobsPanel.util.js
- src/components/JobsPanel/panelReducer.js
- src/components/JobsPanelResources/JobsPanelResources.js
- src/elements/JobsPanelVolumesTable/JobsPanelVolumesTable.js
- src/reducers/jobReducer.js
https://trello.com/c/ExbCGkee/525-create-job-volumes-wrong-model-property-name
In the body of the request to `POST /api/submit_job` the volumes were set in `function.spec.volumeMounts` instead of `function.spec.volume_mounts`.
> [Create Job] Volumes: wrong model property name

- src/api/jobs-api.js
- src/components/ScheduleJob/ScheduleJob.js
- src/components/ScheduleJob/ScheduleJobView.js
- src/components/ScheduleJobSimple/ScheduleJobSimple.js
Mon = 0, Tue = 1, Wed = 2, Thu = 3, Fri = 4, Sat = 5, Sun = 6
originated in https://github.com/mlrun/ui/pull/226
> Fix [Create Job] Schedule>Simple>Weekly: wrong day indexes

- src/components/DetailsArtifacts/DetailsArtifacts.js
https://trello.com/c/2zpasa52/532-jobs-artifacts-preview-not-reset-when-switching-jobs
> [Jobs] Artifacts: preview not reset when switching jobs

- .github/workflows/build.yaml
This will trigger a github action for each commit to development.
The github action will build this image `ghcr.io/mlrun/mlrun-ui:<latest-version>-<commit-hash>` (`latest-version` is latest released MLRun version (not RC), e.g. as of writing this - `0.5.2`)
The github action will push this image and we can see it in the mlrun organization packages.
To make this to work 2 secrets need to be set in the GH repo:
`CR_PAT` (Container registry personal access token) - I currently used PAT of mlrun-iguazio
`CR_USERNAME` - currently `mlrun-iguazio`
> Adding GH action to build image per commit to development

- src/components/JobsPage/Jobs.js
When an error occurred on `GET /api/workflows` the error was not handled correctly and caused a wrong request to be sent, such as this one:
`GET /api/workflows?page_size=100&page_token=%7B%22type%22:%22FETCH_WORKFLOWS_FAILURE%22,%22payload%22:%7B%22message%22:%22Request+failed+with+status+code+414%22,%22name%22:%22Error%22,%22stack%22:%22Error:+Request+failed+with+status+code+414%5Cn++++at+n.exports+(http:%2F%2F127.0.0.1:8080%2Fstatic%2Fjs%2F0.04bae032.chunk.js:1:4208)%5Cn++++at+n.exports+(http:%2F%2F127.0.0.1:8080%2Fstatic%2Fjs%2F0.04bae032.chunk.js:1:10108)%5Cn++++at+XMLHttpRequest.h.onreadystatechange+(http:%2F%2F127.0.0.1:8080%2Fstatic%2Fjs%2F0.04bae032.chunk.js:1:3037)%22,%22config%22:%7B%22url%22:%22%2Fworkflows%22,%22method%22:%22get%22,%22params%22:%7B%22page_size%22:100,%22page_to …
> fixed bug with recursive call

- Dockerfile
- README.md
- nginx/nginx.conf.tmpl
Added this block in the nginx configuration:
```
location /nuclio {
rewrite ^/nuclio(/|$)(.*) /$2 break;
proxy_pass ${NUCLIO_API_PROXY_URL};
}
```
This basically enabled to get to Nuclio API through the UI URL (to prevent CORS)
Any request that has the `/nuclio` prefix will be proxied to Nuclio API.
The `break` in the `rewrite` is important, without it nginx would try to handle the request after changing it (its URI) it means that for example a request to `/nuclio/api/projects` will first change its URI to `/api/projects` but then instead of going to the Nuclio API it would be "caught" by the `location /api` directive (intended for requests to MLRun API) and go to MLRun API.
`break` tells nginx to not re-handle the request after changing it
> Add proxy to Nuclio API

- Dockerfile
- README.md
the old default - `disabled` - wasn't working, the nginx failed starting, when a host is given to `proxy_pass` it must be resolvable, therefore deafulting to `http://localhost:8070` instead
> Fix [General] Default Nuclio API URL to resolvable host

- src/api/artifacts-api.js
- src/components/Artifacts/Artifacts.js
- src/components/FilterMenu/FilterMenu.js
Backports PR https://github.com/mlrun/ui/pull/251 from **development** branch into **0.5.x** branch.
> Fix [Artifacts] Refresh: `tag=latest` should not be sent

- src/elements/JobsTableRow/JobsTableRow.js
https://trello.com/c/VnL2k5MV/572-jobs-columns-unaligned-with-nested-rows
Before:
After:
> [Jobs] Columns unaligned with nested rows

- src/httpClient.js
Requests were sent relative to base public URL (`/mlrun`), for example `/mlrun/nuclio`, instead of `/nuclio` absolutely.
Relates to PR https://github.com/mlrun/ui/pull/271.
> Fix [Config] Proxy to Nuclio API not working in production

- package.json
- src/components/JobsPage/jobsData.js
- src/components/ScheduleCron/ScheduleCron.js
- src/utils/createJobsContent.js
https://trello.com/c/1eS2UK2Y/571-create-jobscheduled-job-show-human-readable-schedule
- **Scheduled Jobs**: Added "Schedule" column with a human-readable description of the cronstring of the scheduled job.
- **Create Job**: In "Cronstring" tab of scheduling a new job, add human-readable description of the entered cronstring.
> [Create Job][Scheduled Job] Show human-readable schedule

- .github/workflows/build.yaml
pretty much copy paste from https://github.com/mlrun/mlrun/pull/468
Also we were using `::set-env` so far which raised 
```
Error: The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
This PR switches to using outputs
> Impl [Pkg] Enable to trigger workflows manually

- src/components/Details/DetailsView.js
https://trello.com/c/vqO5h5xV/582-artifacts-details-download-button-missing-tooltip
**Artifacts › Details panel**: [bugfix] add missing tooltip to download action
> [Artifacts] Details: added tooltip to download button

- src/components/Details/DetailsView.js
- src/components/Details/details.scss
**Details panel:** Stick the tab headers and actions to the top when scrolling down
Before:
After:
In video:
> Impl [Details panel] Stick tab headers & actions to top on scroll

- src/common/Breadcrumbs/Breadcrumbs.js
https://trello.com/c/02R20KrE/589-breadcrumbs-crashes-when-switching-projects
> [Breadcrumbs] Crashes when switching projects

- src/components/Project/Project.js
- src/components/Project/ProjectView.js
- src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
https://trello.com/c/acmmF1ss/597-artifacts-wrong-register-dialog-heading
- **Project Overview**: Split “Register artifact” to “Register model”, “Register dataset”, & “Register file”
Before:
After:
- **Artifacts**: [bugfix] “Register artifact” heading was in all pop-up dialogs for registering models, files, & datasets, instead of having the respective heading: “Register model”, “Register dataset”, & “Register file”:
Before:
After:
> [Artifacts] Wrong register dialog heading

- src/httpClient.js
On production, when MLRUn UI Docker container is running on some **sub-domain.domain.com/mlrun**, if a request is sent to **sub-domain.domain.com/nuclio** it will not hit the Nginx proxy in MLRun UI.
Changing it back now to become **sub-domain.domain.com/mlrun/nuclio** which will proxy properly.
Reverts PR https://github.com/mlrun/ui/pull/277
> Revert [Config] Proxy to Nuclio API not working in production

- src/actions/projects.js
- src/components/ProjectsPage/Projects.js
- src/components/ProjectsPage/ProjectsView.js
- src/elements/ProjectCard/ProjectCard.js
- src/elements/ProjectCard/projectCard.util.js
- src/elements/ProjectStatistics/ProjectStatistics.js
- src/elements/ProjectStatistics/projectStatistics.scss
- src/elements/ProjectStatisticsCounter/ProjectStatisticsCounter.js
https://trello.com/c/yum7olBE/604-projects-tweak-some-counters
- **Projects**:
- Rename “Running jobs” to ”Running”
- Make “Running” and “Failed (last 24hrs)” counters count both ML jobs and Nuclio functions and add a tooltip on hover that says so, and make “Functions”
- Rename “Functions” counter to “ML functions” and make it count ML functions rather than Nuclio functions.
> [Projects] Tweaked some counters

- src/elements/ProjectArtifacts/ProjectArtifacts.js
https://trello.com/c/2QM84eae/608-project-overview-artifact-counters-are-empty-instead-of-0
- **Project Overview**: artifact counters showed no value instead of 0 when there were no artifacts
before:
after:
> [Project Overview] Artifact counters are empty instead of 0

- src/actions/projects.js
- src/api/projects-api.js
- Create: `POST /api/project` --> `POST /api/projects`
- Update: `POST /api/project/{name}` --> `PUT /api/projects/{name}`
- List: `GET /api/projects?full=yes` --> `GET /api/projects`
- Read: `GET /api/project/{name}` --> `GET /api/projects/{name}`
Response to `GET /api/projects/{name}` has no `project` property at root
Accommodates to PR https://github.com/mlrun/mlrun/pull/542
> Impl [Projects][Project Overview]  Changes to projects API

- src/components/FilterMenu/FilterMenu.js
- src/components/FilterMenu/filterMenu.settings.js
- src/elements/SelectOption/SelectOption.js
https://trello.com/c/15W7heRX/629-jobs-monitor-hide-checkboxes-from-status-filter
- **Jobs**: Remove checkboxes from the “Status” filter (as it does not really allow for multiple selection)
> [Jobs] Monitor: hidden checkboxes from status filter

- src/components/Project/ProjectView.js
https://trello.com/c/rHrxeJGX/627-project-overview-wrong-redirection-after-artifact-creation
- **Project Overview**: On the “Register Model”, “Register Dataset”, and “Register File” dialogs, after a successful registration, the user was redirected to the old general “Artifacts” screen instead of the relevant screen, Models, Datasets, or Files, respectively.
> [Project Overview] Wrong redirection after artifact creation

- src/elements/ProjectCard/ProjectCardView.js
https://trello.com/c/tUO2YMae/633-projects-project-name-overflows-its-tile
- **Projects**: Project name overflew its tile when it is one long word
Before:
After:
> [Projects] Project name overflows its tile

- src/components/Project/ProjectView.js
- src/components/Project/project.scss
https://trello.com/c/Ca8iGmFu/634-project-overview-layout-breaks-on-long-project-name
- **Project Overview**: Layout broke when project name was one long word.
Before:
After:
> [Project Overview] Layout breaks on long project name

- src/components/ProjectsPage/projectsData.js
https://trello.com/c/Dlh62nd1/664-projects-allow-delete-for-archived-projects-only
- **Projects**: Removed the “Delete” action from action menu for unarchived projects.
> [Projects] Allow delete for archived projects only

- src/components/Project/project.utils.js
- **Project overview**: Renamed quick links:
- from “Monitor jobs and workflows” to “Jobs and workflows”
- from “Schedule jobs and workflows” to “Schedule Jobs”
> Impl [Project Overview] Quick Links: rename two links

- src/components/CreateJobPage/CreateJobPageView.js
- **Create Job**: Changed placeholder of filter field to indicate that it filters by name only
Before:
After:
Jira ticket 17746
> Impl [Create Job] Indicate in filter placeholder it is by name

- src/elements/ContentMenu/contentMenu.scss
https://trello.com/c/Em0a97wG/647-general-make-entire-area-of-tab-headers-clickable
- **General**: Made the entire tab header area clickable (green+blue area in below image) instead of just the text area (blue area in below image):
> [General] Make entire area of tab headers clickable

- src/components/Table/Table.js
- **Jobs › Monitor**: No data when grouping by workflow
Bug originated in PR https://github.com/mlrun/ui/pull/332
> Fix [Jobs] Monitor: group by workflow always gives an empty list

- src/components/DetailsMetadata/detailsMetadata.scss
- src/components/DetailsMetadata/detailsMetadata.util.js
- src/components/FeatureStore/FeatureStore.js
- src/components/FeatureStore/feaureStore.util.js
- src/components/JobsPage/jobsData.js
- src/elements/ArtifactsTableRow/ArtifactsTableRow.js
- src/elements/ContentMenu/ContentMenu.js
- src/elements/ContentMenu/contentMenu.scss
- src/elements/FeatureValidator/FeatureValidator.js
- src/elements/FeatureValidator/FeatureValidator.scss
- src/elements/TableCell/TableCell.js
- src/utils/createArtifactsContent.js
- src/utils/object.js
- **Feature store**: Renamed tab headers “Datasets” to “Data sets”, “Feature-Sets” to “Feature sets”, & “Feature-Vectors” to “Feature vectors”
Before:
After:
- **Feature store**: Swap “Name” & “Labels” filters position
Before:
After:
- **Feature Sets**: Removed “Targets” column in details panel:
- **Feature Sets › Metadata**: Fixed showing description and labels of the _feature set_ instead of the specific _feature_
- **Features**: Added “Description”, “Targets” & “Validator” columns and re-ordered columns
- **Features**: Renamed “Name” column header to “Feature Name”
> Impl [Features] Add Description, Targets & Validator columns

- src/components/Project/ProjectView.js
- src/components/Project/project.scss
https://trello.com/c/3HNViuLw/659-project-overview-make-name-non-editable
- **Project Overview**: Name field is no longer editable (because backend does not support such operation)
> [Project Overview] Make name non-editable

- src/elements/ProjectCard/ProjectCard.js
Backports PR https://github.com/mlrun/ui/pull/317 from branch `development` to branch `0.5.x`
- **Projects**: Project name overflew its tile when it is one long word
Before:
After:
> Fix [Projects] Project name overflows its tile

- src/common/Combobox/combobox.scss
- src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
- src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
- src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js
- src/elements/JobsPanelTable/jobsPanelTable.scss
https://trello.com/c/RJ4k6P7e/650-create-job-data-inputs-enhance-scheme-options
- **Create Job › Data Inputs**:
- Renamed “Path Type” to “Path Scheme”.
- Renamed “store” option to “MLRun store”.
- Renamed “URL” option to “S3”.
- Added “V3IO”, “HTTP”, “HTTPS”, “Azure Storage”, & “Google Storage” options.
> [Create Job] Data Inputs: enhance scheme options

- src/components/ProjectsPage/Projects.js
- **Projects**: On `DELETE /api/projects/{project-name}` rely only on response error status code 412 and not on response body to determine whether to show the confirmation pop-up.
Jira ticket 17938
> Impl [Projects] Delete non-empty: do not rely on error text

- src/components/FilterMenu/FilterMenu.js
- **General**: Rename “Labels” filter to “Label” and reword its placeholder from “key1=value1,…” to “key or key=value”, because backend does not currently support filtering by multiple labels.
> Impl [General] Labels filter: rename to Label, reword placeholder

- src/components/ProjectsPage/Projects.js
Originates in PR https://github.com/mlrun/ui/pull/370
- **Projects**: Missing space in deleting non-empty project confirmation dialog
Before:
After:
> Fix [Projects] Delete non-empty project confirm: missing space

- package.json
- src/utils/generateTemplatesCategories.js
- **Create Job**: The same template (“bert-embeddings”) was shown twice inside the “Other” category instead of just once.
Before:
After:
> Fix [Create Job] Duplicated template in the same category

- src/components/FeatureStore/feaureStore.util.js
- **Feature Store**: Renamed tab header “Data sets” to “Datasets”
Before:
After:
> Impl [Feature Store] Rename tab header to "Datasets"

- src/components/ChipForm/ChipForm.js
- **Create Job**: On Firefox when adding a new label and attempting to apply it by clicking outside of it, the UI throws an error and does nothing — as a result the job cannot be run and the dialog cannot be closed.
Jira ticket ML-123
> Fix [Create Job] Crashes when adding a new label (Firefox only)

- src/components/Project/project.scss
- src/components/ProjectTable/projectTable.scss
- src/elements/ProjectStatistics/projectStatistics.scss
https://trello.com/c/capwBAKP/679-project-overview-visual-overlap-issues
- **Project Overview**: Layout breaks on smaller screen size
Before:
After:
> [Project Overview] Visual overlap issues

- Dockerfile
- nginx/nginx.conf.tmpl
The bug was that if nuclio service got recreated for some reason (happens on Iguazio system when restarting the nuclio app service) it means its IP were changed, before this PR the proxy was defined like:
`proxy_pass ${MLRUN_NUCLIO_API_URL};` which means that nginx does the DNS resolution only once on initialization, so if the IP changed mid run, further requests to Nuclio will fail.
In order to make nginx resolve on every request we need to set a variable to the `proxy_pass`.
But when you use a variable you also must define the resolver (see https://serverfault.com/a/593003)
It looked like our best "generic" solution for the value for the resolver is to do the first suggestion [here](https://serverfault.com/a/638855)
I did the same also for the MLRun API proxy pass.
The above add the …
> Fix [Config] Resolve proxy passes hosts on every request

- src/components/ProjectTable/ProjectTable.js
- src/elements/ProjectFunctions/ProjectFunctions.js
https://trello.com/c/5s9FSRrt/681-project-overview-trim-project-name-from-nuclio-function-name
- **Project Overview**: Trimmed project name that is prepended to Nuclio function names, in case it is the current project, and added the full name in a tooltip on hover
Before:
After:
Jira ticket ML-144
> [Project Overview] Trim project name from Nuclio function name

- src/components/JobsPanelParameters/JobsPanelParameters.js
- src/components/JobsPanelParameters/jobsPanelParameters.util.js
- src/components/JobsPanelParameters/jobsPanelParametersReducer.js
- **Create Job**: Add “int”, “float”, & “bool” options to and remove “number” option from parameter type list, and convert the values in accordance to the type:
- For type “bool”:
- if value is "True" or "False" (case insensitive) — assign `true` or `false` respectively
- otherwise stringify the given value
- For types “int” & “float”:
-  if value could be converted to a finite number — assign the number value
- otherwise stringify the given value
- For any other type — stringify the given value
- **Create Job**: `null` values were wrongly sent for non-numeric parameter values on job submission
- **Create Job**: could not change an existing parameter type, it reverted to its previous value
Jira ticket ML-151
> Fix [Create Job] Parameters: null values are wrongly sent

- src/components/DetailsTransformations/ConfigSource/ConfigSource.js
- src/components/DetailsTransformations/ConfigSteps/ConfigSteps.js
- src/components/DetailsTransformations/ConfigTargets/ConfigTargets.js
- src/components/DetailsTransformations/DetailsTransformations.js
- src/components/FeatureStore/FeatureStore.js
- src/components/FeatureStore/feaureStore.util.js
- **Feature Store**: tab headers order in details panel is inconsistent
- **Feature Sets**: UI crashes when loading Transformations tab for a feature set without `spec.graph`
> [Feature Store] Fix transformation tab with empty data. Fix tabs order

- src/elements/ArtifactsTableRow/ArtifactsTableRow.js
- src/utils/createArtifactsContent.js
https://trello.com/c/gzZFPunj/696-feature-sets-group-name-repeats-in-nested-rows
- **Feature Sets**: Removed unnecessarily-repeated name in nested rows of a group (by name)
Before:
After:
- **Feature Sets**: Added missing highlight to selected nested row
Before:
After:
> [Feature Sets] Group name repeats in nested rows, selected nested row not highlighted

- src/components/Details/details.scss
- **Details panel**: Actions stopped sticking to the top on scrolling down. Now it is fixed.
Before:
After:
Bug originates in PR https://github.com/mlrun/ui/pull/395
Original implemented in PR https://github.com/mlrun/ui/pull/283
> Fix [General] Details panel: actions not sticking to top on scroll

- src/utils/object.js
- **Jobs**: List of jobs failed to load when a job had a parameter with the value `null`.
> Fix [Jobs] Error when a job has a parameter with `null` value

- src/common/Breadcrumbs/breadcrumbs.util.js
- **Breadcrumbs**: The links “Real-time functions” and “API gateways” were statically set on build (`npm run build`). Using Docker you couldn't change them once the Docker image was ready.
Now they are dynamic: they could be set on runtime, using `docker run` and passing the environment variable `MLRUN_NUCLIO_UI_URL`.
> Fix [Breadcrumbs] Links to Nuclio are static instead of dynamic

- src/elements/BreadcrumbsDropdown/BreadcrumbsDropdown.js
https://trello.com/c/YycvZD0M/690-breadcrumbs-add-full-value-in-tooltip-on-menu-option-hover
- **Breadcrumbs**: Added tooltip with full values of cropped text when if overflows the dropdown menu‘s width
> [Breadcrumbs] Add full value in tooltip on menu option hover

- src/elements/PreviewModal/PreviewModal.js
- **Artifacts**: Added missing scheme (for example `v3io://`) to artifact path in the header of the artifact preview pop-up (which was inconsistent with the value of “Path” field in “Overview” tab that _did_ show the scheme)
Before:
After:
Jira ticket ML-227
> Fix [Artifacts] Preview: path inconsistently missing schema

- src/components/FilterMenu/FilterMenu.js
https://trello.com/c/0Drt8duv/707-jobs-filters-not-working
- **Jobs**: “Group by” and “Status” filter stopped working. Selecting any option does not change the selected one and has no effect.
Jira ticket ML-216
> [Jobs] Filters not working

- src/App.js
- src/components/DetailsArtifacts/DetailsArtifacts.js
- src/components/DetailsArtifacts/DetailsArtifactsView.js
https://trello.com/c/UdrUE3aa/708-artifacts-remove-artifacts-screen
- **Artifacts**: The old “Artifacts” screen is no longer accessible, even from URL path /projects/{project}/artifacts.
- **Jobs**: In “Artifacts” tab the “Show details” icon button now redirects to the specific screen according to the artifact‘s kind: Models (for `"kind": "model"`), Datasets (for `"kind": "dataset"`) or Files (for all others, including `"kind": ""`).
> [Artifacts] Removed Artifacts screen

- src/components/DetailsInfo/DetailsInfoView.js
- **Models, Datasets, Files**: In details panel, in “Overview” tab, under “Producer”, the link in “Uri” field was broken when it had an iteration with it (i.e. ends with a hyphen `-` and then the iteration number). Now the link is fixed and redirects to the correct job, omitting the iteration part:
> Fix [Models][Datasets][Files] Details: broken link to producer job

- src/components/DetailsPreview/DetailsPreview.js
https://trello.com/c/mNxnfENG/703-artifacts-preview-incorrect-redirection-on-pop-out
- **Models,Datasets,Files**: Preview tab: Added missing tooltip to “Pop-out” icon button
> [Artifacts] Preview: add tooltip to pop-out icon button

- src/elements/HiddenChipsBlock/HiddenChipsBlock.js
- src/elements/HiddenChipsBlock/hiddenChipsBlock.scss
- src/utils/getFirstScrollableParent.js
https://trello.com/c/urXj73cb/709-general-chip-list-pop-over-stacking-issue
- **General**: Chip list pop-over was shown underneath some elements instead of over them
Before:
After:
> [General] Chip list pop-over stacking issues

- src/components/FeatureStore/FeatureStore.js
- src/components/Files/Files.js
- src/components/Models/Models.js
- src/components/Project/ProjectView.js
- src/components/Project/project.utils.js
- src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
- src/elements/RegisterArtifactForm/RegisterArtifactForm.js
https://trello.com/c/VblfX3wK/712-modelsdatasetsfiles-register-type-remove-or-limit
- **Datasets**: Removed “Type” field and statically set `kind` to `"dataset"` on `POST`.
Before:
After:
- **Models**: Removed “Type” field and statically set `kind` to `"model"` on `POST`.
Before:
After:
- **Files**: Removed “Model” and “Dataset” options from dropdown menu of “Type” field in “Register file” pop-up.
Before:
After:
Jira ticket ML-213
> [Models][Datasets][Files] Register: Type: remove or limit

- src/utils/getArtifactPreview.js
- **Datasets**: In “Preview” tab, when the dataset has no `header` field, use the first row of its `preview` field as the header row of the displayed preview table.
> Impl [Datasets] Preview: when no `header`, use `preview` first row

- package.json
- src/api/artifacts-api.js
- src/api/jobs-api.js
- src/common/Input/input.scss
- src/components/FilterMenu/FilterMenu.js
- src/components/JobsPage/jobsData.js
- src/components/Models/models.util.js
- src/httpClient.js
- **General**: Fixed a few issues with “Labels” filters in all screens:
- Put Name filter before Labels filter in all screens with these filters.
- Rename all "Label" filter to "Labels" and reword its placeholder from "key or key-value" to "key1,key2=value,...".
- Fix some failed filtering by labels which was caused by sending `labels` URL param instead of `label`, and sending a single value with a comma-delimited list (for example: `label=a=b,c=d`) instead of repeating the `label` param for each list item (for example: `label=a=b&label=c=d`).
Jira ticket ML-214
> Fix [Filters] Inconsistent order of filters across screens

- src/components/DetailsArtifacts/DetailsArtifactsView.js
- src/components/DetailsArtifacts/detailsArtifacts.scss
https://trello.com/c/mMKjSzHx/714-jobs-artifacts-name-and-target-path-overlap
- **Jobs**: Artifacts tab: long artifact names were overlapping with the target path. Now when the name is long it will be clipped with an ellipsis `…` with the full value in a tooltip
Before:
After:
Jira ticket ML-260
> [Jobs] Artifacts: name and target path overlap

- src/components/DetailsInfo/DetailsInfoView.js
- src/components/DetailsInfo/detailsInfo.scss
- src/components/FeatureStore/featureStore.util.js
- src/components/Files/files.util.js
- src/components/Models/models.util.js
https://trello.com/c/t2XHsHL0/717-modelsdatasetsfiles-overview-rename-tree-to-uid-info
- **Models, Datasets, Files**: in “Overview” tab, rename “Tree” field to “UID” and add more-info icon with a tooltip to show some info for “UID” and “Hash” fields
Jira ticket 254
> [Models][Datasets][Files] Overview: rename Tree to UID + info

- src/components/DetailsInfo/DetailsInfoView.js
- src/components/DetailsInfo/detailsInfo.scss
- **General**: In “Overview” tab tooltip messages were capitalized (each word)
Before:
After:
> Fix [General] Overview tab: capitalized tooltip messages

- src/components/ProjectTable/ProjectTable.js
- src/components/ProjectTable/projectTable.scss
- src/elements/ProjectJobs/ProjectJobs.js
- src/elements/ProjectJobs/projectJobs.utils.js
- src/scss/main.scss
https://trello.com/c/AbdOCo7e/713-project-overview-jobs-show-status-of-up-to-last-5-runs
- **Project Overview**: In “Status” column of the “Jobs and workflows” pane, instead of showing the status of the latest job’s run only (as a text), we’re now showing the status of the last five runs, from latest on the left to earliest on the right, as colorful indicators with the status as text in a tooltip on hover
- **Jobs**: Added grey color to the colorful status indicator for “Pending” status of a job
Jira ticket 233
> [Project Overview] Jobs: Show status of up to last 5 runs

- src/components/Details/details.util.js
https://trello.com/c/3cmuYYSL/728-feature-vectors-overview-last-updated-is-n-a
- **Feature vectors**: “Last updated” field in “Overview” tab shows “N/A” although a valid value was provided in response from backend
Before:
After:
Jira ticket ML-250
> [Feature vectors] Overview: Last Updated is N/A

- src/common/LoadButton/LoadButton.js
- src/components/DetailsTransformations/DetailsTransformations.js
https://trello.com/c/T9Loi4HZ/729-feature-sets-transformations-too-much-zoom-on-init
- **Feature sets**: In “Transformations” tab, improved zoom/pan on the chart when entering the tab
Before:
After:
Jira ticket ML-250
> [Feature sets] Transformations: too much zoom on init

- src/common/Chip/Chip.js
- src/common/ErrorMessage/ErrorMessage.js
- src/common/PopUpDialog/PopUpDialog.js
- src/common/YamlModal/YamlModal.js
- src/components/Details/DetailsView.js
- src/elements/JobsPanelTitle/JobsPanelTitleView.js
- src/elements/PreviewModal/PreviewModal.js
https://trello.com/c/g7KhWKuZ/710-general-missing-close-tooltip-on-close-icon-button
- **General**: Added missing “Close” tooltip on all close icon buttons in several places
> [General] Missing "Close" tooltip on close icon button

- src/components/DetailsArtifacts/detailsArtifacts.util.js
- **Jobs**: “Artifacts” tab crashes when the job has neither `owner` nor `v3io_user` labels.
Jira ticket ML-293
> Fix [Jobs] Artifacts: crashes if job has no owner/v3io_user label

- src/components/Details/DetailsView.js
- src/components/Details/details.util.js
- src/elements/ProjectJobs/projectJobs.utils.js
- src/elements/TableLinkCell/TableLinkCell.js
- src/scss/main.scss
- **Project, Jobs**: Added “Aborted” status of job runs, with red color, and set “Start time” to “N/A” rather than “Not yet started” incase it is missing and the status is aborted
> Impl [Project][Jobs] Add "Aborted" status

- src/App.js
- src/components/Files/Files.js
- src/components/Models/Models.js
- src/components/Models/models.util.js
- src/elements/ArtifactsTableRow/ArtifactsTableRow.js
- src/utils/createArtifactsContent.js
https://trello.com/c/A3b6DyIH/737-modelsfiles-missing-tag-in-url-on-clicking-name-link
- **Models, Files**: The tag was missing from the URL path of drilling-down to a specific model/file, for example `/projects/default/files/some-file` instead of `/projects/default/files/some-file/latest`
- **Models, Files, Datasets**: All rows are marked as selected instead of the selected one only
Before:
After:
Jira tickets ML-327
> [Models][Files] Missing tag in URL on clicking name link

- nginx/nginx.conf.tmpl
Using what I did [here](https://github.com/mlrun/ui/pull/377) to make the function catalog proxy pass resolve on (every) request instead of on initialization, that way unresolvable address won't fail initialization.
It will hurt performance since we're going to resolve on every request instead of once, but that's a price we're willing to pay
Fixes https://jira.iguazeng.com/browse/ML-305
> Fix [Config] Don't fail initialization when function catalog not resolvable 

- src/layout/Content/Content.js
https://trello.com/c/5AtBi6Vd/743-general-view-yaml-dialog-not-closing-on-switching-tabs
- **Jobs, Models, Feature stores**: On multi-tab screens, the “View YAML” pop-up did not close when switching to another tab in the same screen.
Jira ticket ML-318
> [General] View YAML dialog not closing on switching tabs

- src/layout/Content/Content.js
https://trello.com/c/m58naMSq/745-feature-vectors-view-yaml-always-shows-yaml-of-first-vector
- **Feature vectors**: Selecting the “View YAML” action for _any_ item on the list always showed the YAML of the *first* item.
Jira ticket ML-317
> [Feature vectors] View YAML always shows YAML of first vector

- src/components/Artifacts/Artifacts.js
- src/components/Details/DetailsView.js
- src/components/Details/details.util.js
- src/components/DetailsArtifacts/DetailsArtifactsView.js
- src/components/DetailsArtifacts/detailsArtifacts.util.js
- src/components/FeatureStore/featureStore.util.js
- src/components/Files/Files.js
- src/components/Models/Models.js
- src/components/Models/models.util.js
- src/layout/Content/Content.js
- src/layout/Content/content.util.js
- src/utils/createArtifactsContent.js
- src/utils/parseUri.js
- **Jobs**: In “Artifacts” tab in the details panel of a job, the link of “Show details” icon button was broken and hence the “Projects” screen was open instead of the specific artifact
- **Model endpoints**: Some items were hidden on main list. Now they are all properly listed
- **Model endpoints**: View YAML pop-up dialog always showed the YAML of the _first_ item only
- **Model endpoints**: “Name” cell was empty although name exists
- **Model endpoints**: Added “UID” field to “Overview” tab
Jira ticket 348
> Fix [Jobs] Artifacts: show details link is broken

- Dockerfile
- README.md
- nginx/nginx.conf.tmpl
- nginx/run_nginx
Apparently although doing something like
```
location /function-catalog {
proxy_pass https://raw.githubusercontent.com/mlrun/functions/master;
}
```
works as expected, i.e. request to `https://ui.com/function-catalog/catalog.json` will be proxied to `https://raw.githubusercontent.com/mlrun/functions/master/catalog.json`
When using a variable to force nginx to do DNS resolving per request (done [here](https://github.com/mlrun/ui/pull/463)), it doesn't work and will proxy the request to `https://raw.githubusercontent.com/catalog.json`
Googling `nginx proxy pass variable with path` gave a lot of results, after some playing I succeeded to make it working using the `rewrite` directive
Fixes https://jira.iguazeng.com/browse/ML-347
> Fix [Config] Preserve catalog configured URI

- src/components/DetailsInfo/DetailsInfoView.js
- **Models, Datasets, Files**: In “Overview” tab, an error occurs when the producer URI is malformed (not in the form of `{project}/{uid}[-{iteration}]`)
Bug originated in PR https://github.com/mlrun/ui/pull/418
> Fix [Models][Datasets][Files] Overview: crashes on malformed URI

- src/components/JobsPage/jobsData.js
- **Jobs**: In “Schedule” tab, a button labeled “Button” was displayed
Bug originates in PR https://github.com/mlrun/ui/pull/476
> Fix [Jobs] Schedule: wrong button labeled "Button" appears

- src/components/FeatureStore/featureStore.util.js
https://trello.com/c/Mppv2cnh/749-features-should-not-have-copy-uri-action
- **Features store**: In “Features” tab, the “Copy URI” appears for features after visiting in one of the other feature-store tabs — and this action is redundant for the “Features” tab (features do not have URIs, and firing this action on them resulted in an invalid URI, such as `store://feature-sets/undefined/name`)
Before:
After:
Jira ticket ML-356
> [Features] Should not have "Copy URI" action

- .storybook/webpack.config.js
Allows to import SVG files in `.stories.js` filesof StoryBook, like: `import { ReactComponent as Caret } from '../images/dropdown.svg'`
> Impl [StoryBook] Allow import of SVG files in stories

- src/components/FeatureStore/featureStore.util.js
- src/components/Files/Files.js
- src/components/Models/Models.js
- src/components/Models/models.util.js
- src/components/Project/project.utils.js
- src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
- src/utils/handleArtifactTreeFilterChange.js
- **Project**: Register file: on successful creation, redirected to “Project Overview” screen instead of “Files” screen
- **Feature store**: After visiting the “Features” tab, then switching to any of the other tabs in the screen, the “Add to feature vector” button was unexpectedly displayed
- **Models, Datasets, Files**: After a new model/dataset/file is created successfully, it was not listed on the list (because `tag=latest` URL query param was not passed)
Jira tickets ML-351, ML-354, ML-359
> Fix [Project] Register file: wrong redirection and heading

- src/actions/projects.js
- src/api/projects-api.js
- src/elements/ProjectCard/ProjectCard.js
https://trello.com/c/iWSfzxv0/758-projects-cancel-pending-requests-on-leaving-screen
- **Projects**: Leaving the screen was frozen until all pending requests to the project cards‘ counters were completed — now they are simply canceled to allow a smoother flow
> [Projects] Cancel pending requests on leaving screen

- src/common/ChipCell/ChipCellView.js
https://trello.com/c/LL2C8OO4/731-general-chip-with-count-has-redundant-tooltip
- **General**: In chip-list component, remove the useless tooltip on hovering the chip that shows the count of hidden chips when the list overflows its container
> [General] Chip with count has redundant tooltip

- src/components/Project/project.scss
- src/components/ProjectTable/projectTable.scss
- src/elements/ProjectDataCard/ProjectDataCard.js
- src/elements/ProjectJobs/projectJobs.utils.js
- src/elements/ProjectStatistics/projectStatistics.scss
- src/elements/ProjectStatisticsCounter/ProjectStatisticsCounter.js
https://trello.com/c/bKy7pgml/755-project-avoid-having-ellipsis-on-counter-label
- **Project Overview**: In “Jobs and workflows” pane, in the counters part, the “Running workflows” counter label was always clipped with ellipsis (…) — now it is entirely visible, taking two lines (the tooltip was also removed since it is no longer needed)
Before:
After:
Jira ticket ML-363
> [Project] Avoid having ellipsis on counter label

- src/components/CreateJobPage/createJobPage.scss
- src/elements/SelectOption/SelectOption.js
https://trello.com/c/bDsVXOD3/754-create-job-dropdown-options-overlap
- **Create Job**: The dropdown menu of the project filter broke on long project names — now the dropdown menu is wider and long project names get clipped with an ellipsis (…) and have the full name shown in a tooltip on hover
Before:
After:
Jira ticket ML-365
> [Create Job] Dropdown options overlap

- src/components/FunctionsPage/Functions.js
- src/components/JobsPanel/jobsPanel.util.js
- **Create Job, Functions**: Fails on a not-yet deployed function (has no `spec` part in its JSON)
Jira ticket IG-17011
> Fix [Create Job][Functions] Fails on not-yet deployed functions

- src/components/JobsPage/jobsData.js
- **Jobs**: In “Monitor” tab, for jobs of kind “Dask”, the “Monitoring” action in the action menu still worked and opened the link even though it was disabled
Jira ticket ML-350
> Fix [Jobs] Monitor: disabled "Monitoring" action still opens link

- src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
- src/components/ProjectsPage/CreateProjectDialog/createProjectDialog.scss
https://trello.com/c/84hVF1gz/763-projects-create-new-project-buttons-distorted
- **Projects**: In “Create new project” pop-up, when an error message is shown, the buttons are distorted
Before:
After:
Jira ticket ML-378
> [Projects] Create new project: buttons distorted

- src/components/DetailsPreview/DetailsPreview.js
- src/components/DetailsTransformations/DetailsTransformations.js
- src/elements/ArtifactsTableRow/ArtifactsTableRow.js
- src/elements/JobsTableRow/JobsTableRow.js
- src/utils/createArtifactsContent.js
- src/utils/createJobsContent.js
- src/utils/generateLinkToDetailsPanel.js
https://trello.com/c/E9Ddeelj/748-feature-storejobs-retain-selected-tab-on-switching-items
- **Feature store**: In screen’s tabs “Feature sets”, “Feature vectors”, & “Datasets”, when selecting an item from the list and the details panel is open, and a nested tab other than “Overview” is active, and you select another item from, the main list (feature set, feature vector, dataset) — the active tab in the details panel used to always go to “Overview” tab, and now instead the active tab remains unchanged
Jira ticket ML-381
> [Feature store][Jobs] Retain selected tab on switching items

- src/components/CreateJobPage/CreateJobPageView.js
- src/components/CreateJobPage/createJobPage.scss
- src/elements/CreateJobCardTemplate/CreateJobCardTemplate.js
- src/elements/CreateJobCardTemplate/createJobCardTemplate.scss
https://trello.com/c/Xx8X2EOz/753-create-job-inconsistent-card-height
- **Create Job**: Function template cards changed their height when wrapping to the next line
Before:
After:
Jira ticket ML-384
> [Create Job] Inconsistent card height

- src/components/JobsPage/Jobs.js
- src/components/JobsPanel/JobsPanel.js
- src/components/JobsPanel/JobsPanelView.js
- src/components/Table/Table.js
- src/utils/createJobsContent.js
- src/utils/generateTableContent.js
https://trello.com/c/H8g2dH5Q/765-jobs-re-run-add-job-panel-for-editing
- **Jobs**: In “Monitor” tab, the “Re-run” action now does not run immediately but rather opens the job panel with all fields pre-populated with the settings from that run — allowing for the user to edit the settings before running it (or scheduling it for later!)
Jira ticket ML-340
> [Jobs] Re-run: Added job panel for editing

- src/utils/generateUri.js
- **Models, Datasets, Files**: URI was wrong (both the field value in “Overview” tab, and the value copied to clipboard on firing the “Copy URI” action):
- Used `key` instead of `db_key` for models/datasets/files
- Used `-` as iteration delimiter instead of `#`
Before:
After:
Bug originated in PR https://github.com/mlrun/ui/pull/456
Jira ticket ML-404
> Fix [Models][Datasets][Files] Wrong key and iter delimiter in URI

- src/components/FunctionsPage/Functions.js
- src/components/FunctionsPage/functions.util.js
- src/elements/FunctionsTableRow/FunctionsTableRow.js
https://trello.com/c/1QWqOXt0/773-functions-hide-run-action-for-failed-functions
- **Functions**: Hide “Run” action from functions in `Error`/`Failed` state
Continues PR https://github.com/mlrun/ui/pull/496
Jira ticket ML-258
> [Functions] Hide "Run" action for failed functions

- src/utils/getArtifactPreview.js
- **Feature vectors**: If feature vector has `status.preview` of `[]`, UI unexpectedly sent a request to `GET /api/files` with no parameters, which ultimately failed and the error was displayed. Now it simply shows a no-data message, as expected.
Before:
After:
Jira ticket ML-435
> Fix [Feature vectors] Preview: error when preview is empty

- src/components/DetailsDriftAnalysis/detailsDriftAnalysis.util.js
- src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.util.js
- **Model endpoints**: Both “Drift analysis” and “Feature analysis” tabs crashed on `null` values
In-release bug.
Originated in PRs https://github.com/mlrun/ui/pull/499 https://github.com/mlrun/ui/pull/506
> Fix [Model Endpoints] Drift and Feature analysis tabs break on nulls

- src/components/FilterMenu/FilterMenu.js
- src/components/JobsPage/Jobs.js
https://trello.com/c/6c0iKJfO/777-jobs-monitor-initially-filter-to-last-24-hours
- **Jobs**: In “Monitor” tab, default the “Start time” filter to the past 24 hours when entering this tab
Jira ticket ML-460
> [Jobs] Monitor: initially filter to last 24 hours

- src/common/Input/Input.js
- src/common/RangeInput/RangeInput.js
- src/components/JobsPanel/jobsPanel.util.js
- **Create job**: In “Resources” section in “GPU” field the label was overflowing the value; also there was an error when there was GPU value set in the function, but no memory or CPU
Before:
After:
Jira ticket ML-462
> Fix [Create job] GPU: label overflows value; Error on empty values

- src/elements/FeaturesTablePanel/FeatureTablePanleRow/FeaturesTablePanelRow.js
https://trello.com/c/b6T28goD/787-features-add-tooltips-to-icon-buttons
- **Features**: Added tooltips to the icon buttons “Set as label”, “Unset as label”, and “Remove from vector” in the vector sidebar
Continues PR https://github.com/mlrun/ui/pull/514
Jira ticket ML-13
> [Features] Add tooltips to icon buttons

- src/common/Loader/loader.scss
- src/common/PopUpDialog/popUpDialog.scss
https://trello.com/c/vpEy9jk4/767-projects-counter-loaders-in-front-of-dialog
- **Projects**: Loaders were displaying on top of the project creation pop-up instead of underneath it
Before:
After:
Jira ticket ML-371
> [Projects] Counter loaders in front of dialog

- src/elements/ArtifactsTableRow/ArtifactsTableRow.js
- src/utils/generateGroupLatestItem.js
https://trello.com/c/ajHQZXMK/782-feature-sets-sidebar-wrong-feature-set-is-marked-as-selected
- **Feature sets**: Selecting one feature set marked another as selected, sometimes even more than one
Before:
After:
Jira ticket ML-467
> [Feature sets] Sidebar: Wrong feature set is marked as selected

- src/actions/jobs.js
- src/api/jobs-api.js
- src/components/FilterMenu/FilterMenu.js
- src/components/FilterMenu/filterMenu.settings.js
- src/components/JobsPage/Jobs.js
- src/components/JobsPage/jobsData.js
- src/layout/Content/Content.js
https://trello.com/c/db0BZofE/788-jobs-status-filter-add-pending-option
- **Jobs**: In “Monitor” tab, in “Status” filter added “Pending” option
Jira ticket ML-468
> [Jobs] Status filter: add Pending option

- src/common/DatePicker/DatePicker.js
- src/common/DatePicker/DatePickerView.js
- src/common/DatePicker/datePicker.scss
- src/common/Select/select.scss
- src/components/FilterMenu/FilterMenu.js
- src/elements/SelectOption/SelectOption.js
- src/elements/SelectOption/selectOption.scss
- src/utils/datePicker.util.js
https://trello.com/c/LuHwisLU/786-jobs-monitor-add-predefined-options-to-start-from-filter
- **Jobs**: In “Monitor” tab, added a drop-down menu for “Start time” filter with predefined options in addition to the “Custom range…” option that opens the date-time range picker
Continuing PR https://github.com/mlrun/ui/pull/497
Jira ticket ML-155
> [Jobs] Monitor: Add predefined options to Start From filter

- src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
- src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
- **Data Inputs**: Names of artifacts/feature vectors in a project were duplicated (per UID they have) — now only unique names are shown (UID/tag/iteration could be then added manually, for example `:latest`, `@123456`, `#2`). Also a placeholder were added to the “MLRun store” scheme: `artifacts/my-project/my-artifact:my-tag`
Before:
After:
Jira ticket ML-463
> Impl [Data inputs] Store: Remove duplicate item names

- src/components/ArtifactsPreview/ArtifactsPreviewView.js
- src/components/ArtifactsPreview/artifactaPreview.scss
- src/components/DetailsArtifacts/detailsArtifacts.scss
- src/elements/PreviewModal/PreviewModal.js
- **Jobs**: In “Artifacts” tab of a selected job, an error occurred when previewing an artifact with tabular data where one of its data cells consisted of a composite object, for example:
```js
{
"runs": [
{
"kind": "run",
"status": {
"artifacts": [
{
"preview": [
[
"value1",
"value2",
[ // <-- a value of type: list of dictionaries
{
"foo": "bar"
}
]
]
]
}
]
}
}
]
}
```
- **Jobs**: In “Artifacts” tab of a selected job, the “Artifacts Preview” icon was obstructed by preview content.
Before:
After:
- **Jobs**: In “Artifacts” tab of a selected job, the “Artifacts Preview” icon button was moving when scrolling preview content horizontally, instead of staying in the same place.
Before:
After:
- **Jobs**: In “Artifacts” tab of a selected job, in the artifact preview modal: “undefined” was …
> Fix [Jobs] Artifacts: preview is broken for nested objects

- src/components/JobsPage/jobsData.js
- **Jobs**: In “Monitor” tab, disable the “Abort” action for Dask jobs with the tooltip “Cannot abort Dask jobs”
Continues PR https://github.com/mlrun/ui/pull/459
Jira ticket ML-409
> Impl [Jobs] Monitor: disable Abort action for Dask jobs

- src/api/jobs-api.js
- **Jobs**: In “Monitor” tab, although the “Abort” action succeeded, the UI unexpectedly showed a failed notification and an infinite loader (instead of a successful notification and temporary loader)
Bug originates in PR https://github.com/mlrun/ui/pull/522 [v0.6.3-rc6](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc6)
> Fix [Jobs] Monitor: showing error and infinite loader on success

- src/common/Breadcrumbs/Breadcrumbs.js
- src/common/Breadcrumbs/breadcrumbs.util.js
- src/components/FeatureStore/featureStore.util.js
- src/components/Models/models.util.js
- src/components/Project/project.utils.js
- **Feature store**: Removed individual “Beta” mark from tab headers in feature store and put one on the breadcrumb of the entire feature store
Before:
After:
- **Project**: In “Quick links” added “Beta” mark to “Feature store” link
Before:
After:
- **Models**: Added “Beta” mark to “Model Endpoints” tab header
Before:
After:
Jira ticket ML-478
> Impl [Feature Store][Models] Put Beta on entire feature store

- src/actions/details.js
- src/api/details-api.js
- src/components/Models/models.util.js
- **Model Endpoints**: On selecting model endpoints, their info was always fetched from one specific project (`iris-demo-michaell`) instead of dynamically using the project name their in
Bug originates in PR https://github.com/mlrun/ui/pull/499 [v0.6.3-RC3](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc3)
Jira ticket ML-482
> Fix [Model Endpoints] Always fetching from one specific project

- src/components/JobsPage/Jobs.js
- src/components/JobsPage/jobsData.js
- **Jobs**: In “Monitor” tab, in action menu, enable the “Abort” action only for jobs of kind that is included in the new `abortable_function_kinds` list from backend API‘s `GET /api/frontend-spec` endpoint
Modifies https://github.com/mlrun/ui/pull/530 [v0.6.3-RC7](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc7)
Continues https://github.com/mlrun/ui/pull/459 [v0.6.3-RC1](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc1)
Jira ticket ML-486
> Impl [Jobs] Monitor: use abortable function-kind list from BE

- src/components/JobsPage/jobsData.js
- **Jobs**: In “Monitor” tab, breaks sometimes when assigning values to some filters
Bug originated in https://github.com/mlrun/ui/pull/535
> Fix [Jobs] Sometimes breaks when changing filters

- src/actions/details.js
- src/components/DetailsDriftAnalysis/DetailsDriftAnalysis.js
- src/components/DetailsFeaturesAnalysis/DetailsFeaturesAnalysis.js
- src/components/DetailsPods/DetailsPods.js
- src/utils/generatePods.js
- **Jobs**: In “Pods” tab of the selected job, switched to always show the list of pods and their statuses instead of only showing them when at least one pod is pending.
Jira ticket ML-485
- **Jobs**: In “Pods” tab of the selected job, accommodated to API change in response to getting pods details (project level added to hierarchy)
Jira ticket ML-397
Relates to PR https://github.com/mlrun/mlrun/pull/910
Continues feature https://github.com/mlrun/ui/pull/511 [v0.6.3-RC6](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc6) ML-430
> Impl [Jobs] Pods: Always show pods, not only when pending

- src/components/Project/project.scss
- **Project Overview**: In “Quick Links” the clickable area for each link was too large, now it is just the link itself
Before:
After:
> Fix [Project] Clickable area is too large

- src/components/FunctionsPage/Functions.js
- **Functions**: Re-ordered action menu, moved “Run” before ”Delete”, which makes more sense
Before:
After:
Continues https://github.com/mlrun/ui/pull/496 [v0.6.3-rc2](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc2) ML-258
Jira ticket ML-504
> Impl [Functions] Reorder action menu: Move Delete before Run

- src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
- **Feature sets**: In “Create feature set” panel, in “Source” section, temporarily hide “Schedule” field until backend supports scheduling
Before:
After:
Continues feature https://github.com/mlrun/ui/pull/510 [v0.6.3-RC4](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc4) ML-231
Jira ticket ML-505
> Impl [Feature sets] Create: hide Schedule field from Source

- src/components/FilterMenu/FilterMenu.js
- **Jobs**: In “Monitor” tab, default the “Start time” filter to “Any time“ instead of the past 24 hours
Modifies https://github.com/mlrun/ui/pull/516 [v0.6.3-RC5](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc5) ML-460
Continues feature https://github.com/mlrun/ui/pull/497 [v0.6.3-Rc2](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc2) ML-155
Jira ticket ML-474
> [Jobs] Monitor: initially filter to "Any time"

- src/components/DetailsInfo/detailsInfo.scss
- src/components/FeatureStore/featureStore.util.js
- src/elements/DetailsInfoItem/DetailsInfoItem.js
- src/utils/generateUsageSnippets.js
https://trello.com/c/HglAHTIc/789-feature-store-enrich-usage-snippets-and-allow-to-copy
- **Feature store**: In both feature sets and vectors, in their “Overview” tab, updated the examples in the “Usage example” snippet, implanted some values in it from the selected feature set/vector, aligned the field‘s label to the the field‘s content, and added a copy-to-clipboard icon button
Continues feature https://github.com/mlrun/ui/pull/505 [v0.6.3-RC3](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc3) ML-309
Jira ticket ML-309
> [Feature store] Enrich usage snippets and allow to copy

- src/common/DatePicker/DatePicker.js
- src/components/FilterMenu/FilterMenu.js
- src/utils/datePicker.util.js
https://trello.com/c/5xUrlVIf/795-jobs-start-time-remove-upper-bound-from-past-x-options
- **Jobs**: In “Monitor” tab, in the “Start Time” filter, the predefined “Past X” — such as “Past hour”, “Past year” — had an upper bound (meaning both “from” and “to”) when requesting from backend, so newly-created jobs were not displayed after creation
Relates to feature https://github.com/mlrun/ui/pull/497 [v0.6.3-RC2](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc2) ML-155
Jira ticket ML-513
> [Jobs] Start Time: Remove upper bound from "Past X" options

- src/components/FeatureStore/featureStore.util.js
- src/components/Table/table.scss
- src/elements/ArtifactsTableRow/ArtifactsTableRow.js
- src/elements/TableLinkCell/TableLinkCell.js
- src/layout/Content/Content.js
- src/utils/createArtifactsContent.js
- src/utils/generateLinkToDetailsPanel.js
- src/utils/generateUsageSnippets.js
https://trello.com/c/YoTVHlXD/784-feature-vectors-list-breaks-on-applying-changes-and-expanding
- **Feature store**: Expanding grouped-by-name grouped had some empty “Name” cells for untagged versions, now the truncated UID is displayed for those
Before:
After:
Jira ticket ML-537
> [Feature vectors] List breaks on applying changes and expanding

- src/components/FilterMenu/filterMenu.settings.js
https://trello.com/c/BKY824cm/792-jobs-monitor-add-aborted-to-status-filter
- **Jobs**: In “Monitor” tab, added “Aborted” option to the dropdown menu of the “Status” filter
Jira ticket ML-552
> [Jobs] Monitor: add “Aborted” to Status filter

- src/components/Details/Details.js
- src/components/Details/detailsReducer.js
- src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
- src/components/DetailsRequestedFeatures/detailsRequestedFeaturesReducer.js
https://trello.com/c/GESIEfGN/812-feature-vectors-requested-features-alias-edit-issue
- **Feature vectors**: In “Requested features” tab, when a feature‘s alias was in edit mode, switching to another feature vector kept the edit mode instead of resetting. Demonstration of bug:
Jira ticket ML-487
> [Feature vectors] Requested Features: alias edit issue

- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
https://trello.com/c/qJLMvTDc/810-feature-sets-ingestion-fails-targets-uniqueness-violation
- **Feature sets**: Ingestion was failing due to name uniqueness violation of targets
Jira ticket ML-545
> [Feature sets] Ingestion fails: targets uniqueness violation

- src/api/artifacts-api.js
- **Datasets**: Sometimes expanding a grouped-by-name row would had a row which displayed an error
Before:
After:
Jira ticket ML-565
> [Datasets] Error on expanding row

- src/components/FeatureSetsPanel/FeatureSetsPanel.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitle.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
- src/components/FeatureSetsPanel/FeatureSetsPanelView.js
https://trello.com/c/6zR0A2En/816-feature-set-panel-make-tag-field-optional
- **Feature sets**: In feature set panel, turned “Version” field optional.
Jira ticket ML-567
> [Feature set panel] Made Tag field optional

- src/api/artifacts-api.js
- src/components/Details/Details.js
- src/components/Details/details.util.js
- src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
- src/components/DetailsRequestedFeatures/detailsRequestedFeatures.scss
- src/components/FeatureStore/FeatureStore.js
- src/components/FeatureStore/featureStore.util.js
https://trello.com/c/2r6pMMZ2/811-feature-vectors-requested-features-unexpected-confirmation
- **Feature vectors**: Applying changes to a feature vector (for example, after editing a requested feature’s alias) and then clicking on the “Refresh” button unexpectedly opened the “You have unsaved changes” pop-up.
Jira ticket ML-489
> [Feature vectors] Requested Features: unexpected confirmation

- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
- src/reducers/artifactReducer.js
https://trello.com/c/hY2Xda4x/809-feature-set-new-offline-target-set-by-default
- **Feature sets**: In creation new feature set panel, in “Targets” section, put “Online” target first and check it by default.
Before:
After:
Relates to feature https://github.com/mlrun/ui/pull/510 [v0.6.3-RC4](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc4) ML-231
Jira ticket ML-548
> [Feature set] New: Offline target set by default

- src/utils/generateUsageSnippets.js
- **Feature sets**: In “Overview” tab in “Usage example” field, removed a redundant `)` symbol
Before:
After:
Relates to feature https://github.com/mlrun/ui/pull/505 [v0.6.3-RC3](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc3) ML-309 
Originates in https://github.com/mlrun/ui/pull/546 [v0.6.3-RC11](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc11) ML-309
Jira ticket ML-570
> Fix [Feature sets] Overview: remove redundant ")" in snippet

- src/actions/artifacts.js
- src/api/artifacts-api.js
- src/api/functions-api.js
- src/api/jobs-api.js
- src/components/FeatureStore/FeatureStore.js
- src/components/FeatureStore/featureStore.util.js
https://trello.com/c/Hngajfj0/820-general-name-filter-should-not-use-exact-match
- **General**: Changed the “Name” filter in various screen to use **non**-exact match (`name=~value` instead of `name=value`)
Relates to backend PR https://github.com/mlrun/mlrun/pull/923 [v0.6.3-RC11](https://github.com/mlrun/mlrun/releases/tag/v0.6.3-rc11)
Jira ticket ML-573
> [General] Name filter should not use exact match

- src/elements/TableLinkCell/TableLinkCell.js
https://trello.com/c/d4yVkxdk/825-general-tables-name-is-cropped
- **General**: Values in “Name” column of various screens was cropped on overflow without an ellipsis
Before:
After:
Jira ticket ML-601
> [General] Name column: value is cropped without ellipsis 

- src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
https://trello.com/c/H5ne1m55/826-feature-sets-version-is-disregarded-on-creation
- **Feature sets**: When creating a new feature set the “Version” field was disregarded, the request was sent with an empty string for `metadata.tag` and hence the feature set was always created with tag `latest` which is the default on backend.
Related to feature https://github.com/mlrun/ui/pull/510 [v0.6.3-RC4](https://github.com/mlrun/ui/releases/tag/v0.6.3-rc4) ML-231
Jira ticket ML-604
> [Feature sets] Version is disregarded on creation

- src/actions/artifacts.js
- src/api/artifacts-api.js
- src/components/Artifacts/Artifacts.js
- src/components/Details/Details.js
- src/components/FeatureSetsPanel/FeatureSetsPanel.js
- src/components/FeatureStore/FeatureStore.js
- src/components/FeatureStore/featureStore.util.js
- src/components/Files/Files.js
- src/components/FunctionsPage/Functions.js
- src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
- src/components/Models/Models.js
- src/components/Models/models.util.js
- src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
- src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
- src/types.js
- src/utils/handleArtifactTreeFilterChange.js
https://trello.com/c/lEuUYxtA/822-data-inputs-model-endpoints-requests-contain-wrong-project-name
- **Data Inputs**: The feature vector list was empty.
Before:
After:
Jira ticket ML-606
- **Model Endpoints**: The list of model endpoints was empty.
Jira ticket ML-607
Bug originated in https://github.com/mlrun/ui/pull/558 [v0.6.4-RC5](https://github.com/mlrun/ui/releases/tag/v0.6.4-rc5) ML-432
> [Data Inputs, Model Endpoints] Requests contain wrong `project` name

- src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
https://trello.com/c/YK1swKeZ/821-data-inputs-sort-projects-and-resource-names-by-name
- **Data Inputs**: Sorting project names and resource names by name alphabetically (“Current project” sticks to the top)
Before:
After:
Jira ticket ML-393
> [Data Inputs] Sort projects and resource names by name

- src/common/Sort/sort.scss
https://trello.com/c/OsiNS6E4/830-projects-sort-projects-dropdown-is-transparent
- **Projects**: Sort-by dropdown menu had transparent background.
Before:
After:
Jira ticket ML-610
> [Projects] Sort projects dropdown is transparent

- src/components/JobsPanel/jobsPanel.util.js
https://trello.com/c/YighARU8/837-job-panel-omit-selector-when-result-is-empty
- **Job panel**: Removed `task.spec.selector` from request body when the “Result” field is empty.
Jira ticket ML-619
> [Job panel] Omit `selector` when Result is empty

- src/components/Details/details.scss
- src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
https://trello.com/c/q4ZC7t7z/834-feature-vectors-delete-feature-pop-up-isnt-aligned
- General: Pop-up dialog was mispositioned and did not cover the entire relevant area (including its backdrop overlay).
Before:
After:
Jira ticket ML-621
> [Feature Vectors] Delete feature pop-up isn't aligned

- src/layout/Content/Content.js
https://trello.com/c/pT0Atz7H/840-feature-sets-show-create-set-vector-buttons-only-on-demo
- **Feature store**: Hide “Create Set” & “Create Vector” buttons. Show them when the URL query has a `demo=true` param.
Jira ticket ML-636
> [Feature sets] Show Create Set/Vector buttons only on demo

- src/actions/artifacts.js
- src/api/artifacts-api.js
- src/components/FeatureSetsPanel/FeatureSetsPanel.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
- src/utils/generateUsageSnippets.js
https://trello.com/c/ngJBTAiS/842-feature-sets-use-tag-when-ingesting-a-feature-set
- **Feature sets**: Pass tag instead of UID to ingestion request, and add a “latest” placeholder to “Tag” field
Jira ticket ML-633
> [Feature sets] Use tag when ingesting a feature set

- src/components/Table/Table.js
- src/layout/Content/Content.js
https://trello.com/c/X1VMjPVM/831-monitor-notification-doesnt-disappear-on-schedule-job
- **Jobs**: Selecting to re-run a job and then scheduling it for later successfully ended up showing the success notification endlessly.
Jira ticket ML-641
> [Monitor] Notification doesn't disappear on "Schedule" job

- src/common/KeyValueTable/KeyValueTable.js
- src/common/KeyValueTable/keyValueTable.scss
- src/components/JobsPanel/jobsPanel.util.js
- src/components/JobsPanelAdvanced/JobsPanelAdvanced.js
- src/components/JobsPanelAdvanced/JobsPanelAdvancedView.js
- src/components/JobsPanelParameters/JobsPanelParameters.js
- src/components/JobsPanelParameters/JobsPanelParametersView.js
- src/elements/EditableAdvancedRow/EditableAdvancedRow.js
- src/elements/EditableDataInputsRow/EditableDataInputsRow.js
- src/elements/EditableParametersRow/EditableParametersRow.js
- src/elements/EditableVolumesRow/EditableVolumesRow.js
- src/elements/JobsPanelAdvancedTable/JobsPanelAdvancedTable.js
- src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js
- src/elements/JobsPanelParametersTable/JobsPanelParametersTable.js
- src/elements/JobsPanelParametersTable/JobsPanelParametersTableView.js
- src/elements/JobsPanelTable/JobsPanelTableView.js
- src/elements/VolumesTable/VolumesTableView.js
- src/scss/mixins.scss
https://trello.com/c/ByS0xSna/847-jobs-functions-add-unique-validation-by-name
- **Job panel**: In “Data Inputs”, “Parameters”, “Volumes” and “Environment variables” sections, the user could unexpectedly add two items with the same name. This is now invalid and the UI clearly shows it:
Before:
After:
Jira ticket ML-651
> [Jobs, Functions] Add unique validation by name

- src/App.js
- src/actions/artifacts.js
- src/api/artifacts-api.js
- src/components/FeatureStore/FeatureStore.js
- src/components/FeatureStore/featureStore.util.js
- src/components/Files/Files.js
- src/components/FilterMenu/FilterMenu.js
- src/components/Models/Models.js
- src/components/Models/models.util.js
- src/elements/ArtifactsTableRow/ArtifactsTableRow.js
- src/layout/Content/Content.js
- src/utils/createArtifactsContent.js
- src/utils/generateArtifacts.js
- src/utils/generateLinkToDetailsPanel.js
- src/utils/searchArtifactItem.js
https://trello.com/c/FApaYCm8/846-artifacts-use-bestiterationtrue-instead-of-iter0
- **Models, Datasets, Files**: Iterations were not properly listed. Now when the “Show iterations” is checked, all iterations are listed, and when it is unchecked, only the best iterations are listed.
Continues feature https://github.com/mlrun/ui/pull/558 [v0.6.4-RC5](https://github.com/mlrun/ui/releases/tag/v0.6.4-rc5) ML-432
Jira ticket ML-639, ML-644, ML-645
> [Artifacts] Use best_iteration=true instead of iter=0

- src/reducers/functionReducer.js
- **Functions**: Although the “Runtime” field has the only option “Job”, the value that was actually sent in the request to create the function was `'local'` instead of `'job'`.
Relates to https://github.com/mlrun/ui/pull/601 [v0.6.4-RC10](https://github.com/mlrun/ui/releases/tag/v0.6.4-rc10)
> [Functions] Default `kind` to 'job' in Save request

- src/elements/DeployModelPopUp/DeployModelPopUp.js
- src/layout/Content/Content.js
- **Models**: In the “Deploy Model” pop-up, the “Class” field is now preloaded with the default class associated to the selected serving function and in the selected tag. It also changes automatically for selecting another function or tag.
Continues feature https://github.com/mlrun/ui/pull/554 [v0.6.4-RC2](https://github.com/mlrun/ui/releases/tag/v0.6.4-rc2) ML-405
> Impl [Models] Deploy model: preload default class

- src/elements/ArtifactsTableRow/ArtifactsTableRow.js
- src/utils/createArtifactsContent.js
https://trello.com/c/nabGEGmf/851-feature-sets-show-truncated-uid-when-no-tag
- **Feature sets**: Show truncated UID for feature set versions that have no tag assigned to them.
Before:
After:
Jira ticket ML-661
> [Feature sets] Show truncated UID when no tag

- src/elements/EditableAdvancedRow/EditableAdvancedRow.js
- src/elements/EditableParametersRow/EditableParametersRow.js
- src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js
- src/elements/JobsPanelParametersTable/JobsPanelParametersTable.js
- src/elements/JobsPanelParametersTable/JobsPanelParametersTableView.js
- src/elements/JobsPanelTable/JobsPanelTableView.js
- src/elements/JobsPanelTableRow/JobsPanelTableRow.js
https://trello.com/c/6j3jVMB6/850-data-input-validation-by-name-doesnt-work
- **Data Inputs**: While the “Input Name” field was marked invalid when having a non-unique name — clicking outside the row added it to the list and unexpectedly lets two items share the same name.
Before:
After:
Jira ticket ML-662
> [Data Input] Validation by name doesn't work

- src/components/Details/details.util.js
- src/components/Models/models.util.js
https://trello.com/c/zdwlmfuS/854-models-overview-add-algorithm-and-feature-vector
- Models: In “Overview” tab, added “Algorithm” field and “Feature vector” field which has a feature-vector URI which is also a link to that vector.
Jira ticket ML-527
> [Models] Overview: add Algorithm and Feature Vector

- src/common/DatePicker/DatePicker.js
- src/common/DatePicker/DatePickerView.js
- src/common/DatePicker/datePicker.scss
https://trello.com/c/rIBzertg/852-monitor-date-picker-has-the-wrong-cursor
- **Date picker**: Hovering on the date-picker unexpectedly had a “not-allowed” cursor, instead of the a “pointer” cursor
Before:
After:
Jira ticket ML-665
> [Monitor] Date picker has the wrong cursor

- src/components/Models/models.util.js
- **Models**: Renamed “Returned Features” tab header to “Features”.
Continues https://github.com/mlrun/ui/pull/626 ML-527
> Impl [Models] Rename "Returned features" tab header to "Features"

- src/components/JobsPanelResources/JobsPanelResourcesView.js
- **Job Panel**: Moved “Node Selectors” below the Memory/CPU/GPU part, rename the heading to “Node Selector” (singular), and “Add new node selector” to “Add new entry”
Before:
After:
Continues https://github.com/mlrun/ui/pull/621 [v0.6.5-RC3](https://github.com/mlrun/ui/releases/tag/v0.6.5-rc3) ML-595
> Impl [Job Panel] Node Selectors: renames and move below Resources

- src/components/Table/table.scss
https://trello.com/c/E0zZtTWT/862-details-panel-the-main-table-pokes-behind-the-panel
- **Details Panel**: When the details panel was open, on narrow screens, part of the main table was visible behind the panel.
Before:  
After:
Jira ticket ML-704
> [Details Panel] The main table pokes behind the panel

- src/components/Details/details.util.js
https://trello.com/c/GLzfob0B/887-feature-sets-crash-on-opening-details-page
> Fix [Feature Sets] Crash on opening Details page

- src/common/Tooltip/Tooltip.js
- src/common/Tooltip/tooltip.scss
- src/components/Table/table.scss
- src/elements/TableLinkCell/TableLinkCell.js
- src/elements/TableLinkCell/tableLinkCell.scss
- src/elements/TooltipTemplate/TextTooltipTemplate.js
- src/elements/TooltipTemplate/textTooltipTemplate.scss
https://trello.com/c/cauyBUc8/895-general-tooltip-with-long-text-content-has-redundant-space
- **Tooltips**: Sometimes there was a lot of redundant empty space in tooltips.
Before:
After:
> [General] Tooltip with long text content has redundant space

- src/components/Details/details.util.js
- **Feature sets**: In “Overview” tab, the value of “Entities” field was missing a delimiter so entity names looked like one big word.
Before:
After:
Jira tikcet ML-778
> Fix [Feature sets] Overview: no delimiter in entity list

- src/components/ArtifactsPreview/ArtifactsPreviewView.js
- src/components/ArtifactsPreview/artifactsPreview.scss
- **Feature sets**: In “Preview” tab, the values for features of type boolean were missing.
Before:
After:
Jira ticket ML-825
> Fix [Feature sets] Preview: boolean values are not displayed

- src/components/Details/details.util.js
- src/components/FeatureStore/featureStore.util.js
https://trello.com/c/bGRUxS9d/898-feature-sets-overview-remove-partition-keys-field
- **Feature sets**: In “Overview” tab, removed the “Partition Keys” field.
> [Feature sets] Overview: remove Partition Keys field

- src/components/DetailsMetadata/DetailsMetadata.js
- src/components/DetailsMetadata/detailsMetadata.scss
- src/components/DetailsMetadata/detailsMetadata.util.js
- src/components/DetailsStatistics/DetailsStatistics.js
- src/components/DetailsStatistics/detailsStatistics.scss
- src/components/DetailsStatistics/detailsStatistics.util.js
- src/scss/mixins.scss
https://trello.com/c/V5kBQA9z/899-feature-setsfeature-vectors-statistics-add-icons
- **Feature sets**, **Feature vectors**: In “Statistics” tab, mark entity and label column features with the same key and target icons (respectively) that are used in “Features” tab.
> [Feature sets][Feature vectors] Statistics: add icons

- src/components/ProjectsPage/Projects.js
https://trello.com/c/7bVXBXd6/905-projects-created-project-has-no-counters
- **Projects**: After a new project has been successfully created and added to the list, its counters were always filled with hyphens.
Before:
After:
> [Projects] Created project has no counters

- src/components/Details/details.util.js
https://trello.com/c/aRmMjhKE/911-feature-vectors-overview-populate-label-column-correctly
- **Feature vectors**: In “Overview” tab, the “Label column” was always empty.
Jira ticket ML-760
> [Feature vectors] Overview: populate Label Column correctly

- src/components/DetailsInfo/DetailsInfoView.js
- src/components/DetailsInfo/detailsInfo.scss
- src/elements/DetailsInfoItem/DetailsInfoItem.js
https://trello.com/c/whMiVb0s/912-feature-sets-make-empty-description-labels-editable
- **Feature sets**: In “Overview” tab, make “Description” and “Labels” editable also when they're empty.
Jira ticket ML-547
> [Feature sets] Make empty description & labels editable

- src/components/DetailsTransformations/ConfigFunctionTemplate/ConfigFunctionTemplate.js
- src/components/DetailsTransformations/ConfigSource/ConfigSource.js
- src/components/DetailsTransformations/detailsTransformations.scss
- src/components/DetailsTransformations/detailsTransformations.util.js
https://trello.com/c/2xblQZKq/903-feature-sets-transformations-text-overflows
- **Feature sets**: In “Transformations” tab, text was overflowing outside of steps. Now it is cropped with ellipsis and a tooltip with the full value is displayed on hover.
Before:
After:
Jira ticket ML-831
> [Feature sets] Transformations: text overflows

- src/components/FeatureStore/featureStore.util.js
- src/utils/createFeatureStoreContent.js
https://trello.com/c/kkyrO6WC/910-feature-sets-show-first-two-entities-instead-of-one
- **Feature sets**: Rename “Entity” to “Entities” and display the two first entities instead of just one.
Before:
After:
Jira ticket ML-718
> [Feature sets] Show first two entities instead of one

- src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
https://trello.com/c/Pk9fQT3F/914-jobs-panel-invalid-input-icon-has-wrong-position
- **Create job**: The invalid indication icon was mispositioned in “Default Artifact Path” field.
Before:
After:
> [Jobs Panel] Invalid input icon has wrong position

- src/common/LoadButton/LoadButton.js
- src/components/Details/Details.js
- src/components/Details/DetailsView.js
- src/components/Details/details.util.js
- src/components/DetailsInfo/DetailsInfo.js
- src/components/DetailsInfo/DetailsInfoView.js
- src/components/DetailsInfo/detailsInfoReducer.js
- src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
- src/components/DetailsRequestedFeatures/detailsRequestedFeaturesReducer.js
- src/components/FeatureStore/featureStore.util.js
https://trello.com/c/QwEDAfNQ/916-feature-sets-switching-to-another-feature-set-doesnt-close-edit-mode-on-details
- **Feature sets**: Edit mode of “Description” & “Labels” fields remains active after switching to another feature set.
> [Feature Sets] Switching to another feature set doesn't close edit mode on Details

- src/utils/getState.js
- **Functions**: In “Overview” tab, the “Status” field shows the literal word “Empty” when there is no status in the backend model.
Jira ticket ML-920
> Fix [Functions] Overview: Status shows the word "empty"

- src/layout/Content/Content.js
https://trello.com/c/2CoOB0JO/923-general-expand-button-has-wrong-tooltip
- **General**: Expand/collapse all action button had an inconsistent behavior. Now Collapse All is displayed only when the entire list of expanded. If at least one item is collapsed, then the Expand All is displayed.
> [General] Expand button has wrong tooltip

- src/elements/EditableParametersRow/EditableParametersRow.js
https://trello.com/c/0LCBG41Q/924-jobs-panel-cant-edit-parameter-type-and-value-type
- **Jobs Panel**: In “Parameters” section, sometimes the user could not edit the parameter details.
> [Jobs panel] Can't edit parameter type and value type

- src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitle.js
https://trello.com/c/ONkpM9oZ/927-feature-set-panel-missing-validation-for-name
- **Feature sets**: Validation rules on feature set name were not enforced.
Jira ticket ML-884
> [Feature set panel] Missing validation for name

- src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitle.js
Backporting PR https://github.com/mlrun/ui/pull/706 from branch **development** into branch **0.6.x**:
- **Feature sets**: Validation rules on feature set name were not enforced.
Jira ticket ML-884
> Fix [Feature set panel] Missing validation for name

- src/components/DetailsInfo/detailsInfo.scss
- src/components/Table/table.scss
- src/elements/JobsPanelTable/jobsPanelTable.scss
- src/layout/Content/content.scss
- src/scss/mixins.scss
Backporting PR https://github.com/mlrun/ui/pull/711 from branch **development** into branch **0.6.x**:
- **General**: Reduce vertical spacing in various places.
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Jira ticket ML-924
> Impl [General] Reduce vertical spacing

- src/components/FunctionsPanel/FunctionsPanelView.js
- src/elements/FunctionsPanelEnvironmentVariables/FunctionsPanelEnvironmentVariables.js
https://trello.com/c/es9fJ0LN/926-function-panel-cannot-add-env-vars-on-edit-function
- **Function panel**: A new created environment variable was hidden in the list but was actually there behind the scenes and was sent when saving/deploying the function. Now it is properly visible right after adding it.
> [Function panel] Cannot add env vars on edit function

- src/components/Details/details.util.js
- **Functions**: In “Overview” tab, the “Code Origin” did not display its value even though there was a valid value for it.
Before:
After:
> Fix [Functions] Overview: Code Origin value missing

- src/components/FunctionsPanel/FunctionsPanelView.js
- src/elements/FunctionsPanelEnvironmentVariables/FunctionsPanelEnvironmentVariables.js
Backports PR https://github.com/mlrun/ui/pull/707 from branch **development** to branch **0.6.x**:
- **Function panel**: A new created environment variable was hidden in the list but was actually there behind the scenes and was sent when saving/deploying the function. Now it is properly visible right after adding it.
Jira ticket ML-905
> Fix [Function panel] Cannot add env vars on edit function

- src/elements/MembersPopUp/MembersPopUp.js
- **Project Members**: Reword tooltip, from “users” to “members”.
Before:
After:
> Impl [Project Members] Reword tooltip (users -> members)

- src/components/CreateJobPage/CreateJobPage.js
- src/components/FunctionsPage/Functions.js
- src/components/FunctionsPanel/FunctionsPanel.js
- src/components/FunctionsPanel/FunctionsPanelView.js
- src/components/JobsPage/Jobs.js
- src/components/JobsPanel/JobsPanel.js
- src/components/JobsPanel/jobsPanel.util.js
- src/components/JobsPanelResources/JobsPanelResources.js
- src/constants.js
- src/elements/FunctionsPanelResources/FunctionsPanelResources.js
- src/elements/FunctionsPanelResources/functionsPanelResources.util.js
- src/elements/VolumesTable/VolumesTable.js
Backports PR https://github.com/mlrun/ui/pull/718 from branch **development** to branch **0.6.x**:
- **Function panel**: In “Volumes” section, the “Remove” action was missing when editing an existing function.
Jira ticket ML-923
> Fix [Job panel][Function panel] Volumes: missing delete action

- src/common/Notification/Notification.js
https://trello.com/c/AzdIaWWp/930-notification-move-to-bottom-right-corner
- **Notifications**: Moved notifications to the bottom-right corner of the screen, instead of the bottom center.
> [Notification] Moved to bottom-right corner

- src/components/Details/DetailsView.js
- src/components/FeatureStore/featureStore.util.js
https://trello.com/c/OiKVt66a/932-feature-sets-refresh-doesnt-show-notification-with-changes-on-details
- **Feature sets**: When there are pending changes, there was no warning on clicking the “Refresh” icon button regarding discarding the changes.
> [Feature sets] Refresh doesn't show notification with changes on Details

- src/elements/EditableVolumesRow/EditableVolumesRow.js
- src/elements/VolumesTable/VolumesTable.js
- src/elements/VolumesTable/VolumesTableView.js
- src/elements/VolumesTable/volumesTable.util.js
- src/utils/createNewVolume.js
- src/utils/panelResources.util.js
https://trello.com/c/8SCTxxzd/933-function-panel-volumes-wrong-field-name
- **Job/Function panel**: In ”Volumes” section, when editing an existing volume the extra custom field was always labeled ”Container” regardless of the volume type. Now it is properly labeled “Config Map Name”, “Secret name” or ”Claim name” according to the volume type.
Before & after:
Jira ticket ML-921
> [Function panel] Volumes: wrong field name

- src/components/FunctionsPage/Functions.js
https://trello.com/c/RDJazjBs/938-functions-hide-edit-action-when-not-in-ready-state
- **Functions**: Hide the “Edit” action when the function is not in “Ready” state.
Jira ticket ML-966
> [Functions] Hide Edit action when not in Ready state

- src/components/FeatureSetsPanel/FeatureSetsPanelSchema/FeatureSetsPanelSchema.js
https://trello.com/c/xK1m4hzh/928-feature-set-panel-entities-have-space-in-their-name
- **Feature set panel**: The value in “Entities” field was parsed incorrectly and entity names had leading/trailing spaces.
Jira ticket ML-882
> [Feature set panel] Entities have space in their name

- src/common/Breadcrumbs/Breadcrumbs.js
https://trello.com/c/WdTYNRit/940-breadcrumbs-remove-smaller-levels
- **Breadcrumbs**: Removed the breadcrumbs that are in a lower level then the current project and screen (item name, ID, inner tab, etc.).
Before:
After:
Jira ticket ML-968
> [Breadcrumbs] Remove smaller levels

- src/components/FunctionsPanel/FunctionsPanel.js
- src/components/FunctionsPanel/FunctionsPanelView.js
- src/elements/FunctionsPanelGeneral/FunctionsPanelGeneral.js
- src/elements/FunctionsPanelResources/FunctionsPanelResources.js
- src/types.js
https://trello.com/c/ruNckLuo/942-function-panel-description-not-properly-loaded-on-edit
- **Function panel**: In “General” section, “Description” field was not pre-loaded properly, it was always empty.
Before:
After:
Jira ticket ML-974
> [Function panel] Description not properly loaded on edit

- src/utils/parseUri.js
- **Model Endpoints**: An error occurred when loading the list of model endpoints and an endpoint had a `spec.model_url` value of `null`.
> Fix [Model Endpoints] Error when an item has model_uri of null

- src/api/artifacts-api.js
- src/components/Details/details.util.js
- src/components/Models/models.util.js
- src/utils/createArtifactsContent.js
- **Model Endpoints**:  Add “Function” & “Average Latency” columns (average latency currently always empty), remove “Accuracy” column, and move “Model” column to after “Function” column. 
Jira ticket ML-911
> Impl [Model Endpoints] Remove accuracy, add Function, reorder

- src/utils/createArtifactsContent.js
- **Model Endpoints**: Show “Router” in “Version” column of router rows.
Jira ticket ML-911
Continuing PR https://github.com/mlrun/ui/pull/741
> Fix [Model Endpoints] Version: Router not displayed for routers

- src/actions/artifacts.js
- src/components/Models/models.util.js
- src/utils/generateModelEndpoints.js
https://trello.com/c/gx6ATKcC/950-model-endpoints-details-view-yaml-not-working
- **Model Endpoints**: Empty object was always displayed for “View YAML” action from within the details panel of an endpoint.
> [Model Endpoints] Details: View YAML not working

- src/utils/createArtifactsContent.js
- **Model Endpoints**: Populated “Average Latency” column. 
Jira ticket ML-911
> Impl [Model Endpoints] Populate "Average Latency" column

- src/components/FunctionsPage/Functions.js
- **Functions**: Hide “Edit” action from action menu when `demo=true` is not provided.
Jira ticket ML-1002
> Impl [Functions] Show "Edit" action on demo mode only

- src/elements/EditableVolumesRow/EditableVolumesRow.js
- src/elements/VolumesTable/VolumesTable.js
- src/elements/VolumesTable/VolumesTableView.js
https://trello.com/c/pzX1ApGE/958-volumes-make-container-name-and-resource-path-optional
- **Volumes**: For V3IO type, “Container name” and “Resource Path” fields turned optional.
Jira ticket ML-949
Continues https://github.com/mlrun/ui/pull/735 [v0.7.0-rc5](https://github.com/mlrun/ui/releases/tag/v0.7.0-rc5)
> [Volumes] Made Container Name and Resource Path optional

- src/components/Table/table.scss
https://trello.com/c/1PlEerWA/964-functions-first-row-name-cell-is-clipped-on-expand
- **Functions**: When details panel is open, expanding the first row resulted in cropped date of the function
Before:
After:
Jira ML-1025
> [Functions] First row Name cell is clipped on expand

- src/components/DetailsStatistics/DetailsStatistics.js
- src/scss/mixins.scss
https://trello.com/c/fS72LV7U/952-feature-setsfeature-vectors-histograms-add-min-max
- **Feature sets, Feature vectors**: In “Statistics” tab, added the maximum and minimum values of the y-axis in the histograms.
Before:
After:
Jira ticket ML-1026
> [Feature sets][Feature vectors] Histograms: added min/max

- src/utils/getFirstScrollableParent.js
https://trello.com/c/MWRYg3V2/966-general-chips-pop-over-is-cropped
- **Jobs**: Labels pop-over was obstructed.
Before:
After:
Jira ticket ML-1031
> [General] Chips pop-over is cropped

- src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js
- src/utils/string.js
https://trello.com/c/y9YNN58P/972-function-panel-cant-empty-build-commands
- **Function panel**: In “Code” section, the “Build Commands” field was not updated properly on saving it when it is empty.
Relates to PR https://github.com/mlrun/ui/pull/760
Jira ticket ML-967
> [Function panel] Can't empty Build Commands

- src/components/JobsPage/jobsData.js
https://trello.com/c/EUXlsQrO/970-jobs-hide-re-run-for-kind-local
- **Jobs**: Hid the “Re-run” action from jobs of kind Local.
Jira ticket ML-1041, ML-1044
> [Jobs] Hide "Re-run" for kind local

- src/elements/BreadcrumbsDropdown/BreadcrumbsDropdown.js
- src/elements/BreadcrumbsDropdown/breadcrumbsDropdown.scss
https://trello.com/c/i1A2pzRN/977-breadcrumbs-project-list-overflows-viewport
- **Breadcrumbs**: When the list was very long it overflew the viewport, now there is a maximum height with a vertical scrollbar.
Before:
After:
Jira ticket ML-1050
> [Breadcrumbs] Project list overflows viewport

- src/components/FunctionsPage/Functions.js
- **Functions**: Moved “New” button and “Edit” action to production. The `demo=true` URL query param is no longer needed to reveal these features.
Jira ticket ML-257
> Impl [Functions] Move "New" and "Edit" to production

- src/components/JobsPage/jobsData.js
- **Jobs**: “Re-run” was still showing for jobs of kind Local (when the `kind` label did not exist for the job).
Continues https://github.com/mlrun/ui/pull/768 [v0.7.0-rc15](https://github.com/mlrun/ui/releases/tag/v0.7.0-rc15)
Jira ticket ML-1044
> Fix [Jobs] "Re-run" not always hidden for kind local

- src/elements/ProjectJobs/projectJobs.utils.js
- src/elements/TableTypeCell/TableTypeCell.js
- src/utils/createJobsContent.js
https://trello.com/c/hu7yd0dw/980-project-overviewjobs-inconsistent-job-type
- **Project Overview, Jobs**: Job type was inconsistent between “Project Overview” and “Jobs” screens
Before:
After:
Jira ticket ML-1040
> [Project Overview][Jobs] Inconsistent job type

- src/common/ActionsMenu/ActionsMenu.js
- src/components/JobsPage/jobsData.js
- src/components/Table/TableView.js
https://trello.com/c/VQNhZooW/983-jobs-crashes-when-filter-by-status-error
- **Jobs**: In “Monitor” tab, error occurred when filtering by “Status” by “Error” when there were some jobs not in error state.
Jira ticket ML-1060
> [Jobs] Crashes when filter by status error

- src/components/Project/Project.js
https://trello.com/c/lmDpgMZk/982-project-overview-dont-update-project-on-label-change
- **Project Overview**: Entering value to “Summary” or “Goals” field, then refreshing the web-browser tab, then attempting to empty the value from above fields — resulted in no change to the fields. The fields retained the value instead of being empty.
> [Project overview] Project data is not updated properly

- src/components/DetailsLogs/DetailsLogs.js
- src/reducers/functionReducer.js
https://trello.com/c/IzZMSWNP/988-functions-build-log-loader-area-in-tab-only
- **Functions**: In “Build Log” tab, when the function is being deployed — display the spinning loader in the console area only instead of the entire screen. Also show the loader only until there is some contents to the log, then proceed adding new lines without showing the loader.
Before:
After:
https://user-images.githubusercontent.com/13918850/132359353-56d36dc2-4530-4983-b915-4d51cb676bbd.mp4
> [Functions] Build Log: Loader area in tab only

- src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSource.js
- src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.util.js
- src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
- src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
- src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
- src/elements/EditableDataInputsRow/EditableDataInputsRow.js
- src/elements/EditableDataInputsRow/EditableDataInputsRow.utils.js
- src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js
- src/elements/JobsPanelTable/jobsPanelTable.scss
https://trello.com/c/yDhzjqGd/985-jobs-panel-wrong-combobox-suggestions-flow-for-data-inputs
- **Data Inputs**: when using the wrong value for first step, which should be either `artifacts` or `feature-vectors` only, the UI still suggests project names as the next step instead of fail.
Before:
After:
> [Jobs panel] Wrong combobox suggestions flow for Data inputs

- src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
- src/components/FeatureSetsPanel/featureSetPanel.util.js
- **Feature set panel**: Reduce max length of “Feature Set Name” field from 63 to 56 to allow for an “_ingest” suffix for the ingestion job name, or otherwise the ingestion will fail. This will later be enforced on backend, too.
Before:
After:
Jira ticket ML-1068
> Impl [Feature set panel] Name: Reduce max length from 63 to 56

- src/scss/main.scss
- src/utils/getState.js
https://trello.com/c/EnkrBNxT/991-jobs-monitor-pending-has-no-color-indicator
- **Jobs**: In “Monitor” tab, the pending status indicator (a gray circle with “Pending” tooltip”) was missing in “Name” cells, in the header of the details panel, and it had the wrong color (blue) in the “Status” filter dropdown menu.
Before:
After:
Jira ticket ML-1072
> [Jobs] Monitor: pending has no color indicator

- src/common/ActionsMenu/ActionsMenu.js
- src/components/FunctionsPage/Functions.js
https://trello.com/c/vbBTCokQ/994-job-panel-volumes-not-reflected-properly
- **Job Panel**: Volumes are not reflected properly (for example, when attempting to run a function that had volumes before and they were removed in the latest version — the old volumes did appear in the job panel).
Relates to PR https://github.com/mlrun/ui/pull/788 [v0.7.0-rc17](https://github.com/mlrun/ui/releases/tag/v0.7.0-rc17)
Jira ticket ML-976
> [Job Panel] Volumes not reflected properly

- src/common/ActionsMenu/ActionsMenu.js
- src/common/ActionsMenu/actionsMenu.scss
https://trello.com/c/AkaPER4O/995-general-cant-open-actions-menu-for-the-last-table-item
- **General**: The action menu of the last item was cropped by the end of the viewport.
Before:
After:
> [General] Can't open actions menu for the last table item

- src/common/Breadcrumbs/Breadcrumbs.js
- src/elements/BreadcrumbsDropdown/BreadcrumbsDropdown.js
https://trello.com/c/c3wFAMWD/998-breadcrumbs-wrong-projects-list-after-erasing-search-value
- **Breadcrumbs**: Filtering project did not show relevant results after erasing characters
Before:
After:
> [Breadcrumbs] Wrong projects list after erasing search value

- src/components/FunctionsPanel/FunctionsPanel.js
- src/components/FunctionsPanel/FunctionsPanelView.js
- src/elements/FunctionsPanelCode/FunctionsPanelCode.js
- src/elements/FunctionsPanelGeneral/FunctionsPanelGeneral.js
- src/elements/FunctionsPanelGeneral/FunctionsPanelGeneralView.js
- src/elements/FunctionsPanelGeneral/functionsPanelGeneral.scss
- src/elements/NewFunctionPopUp/NewFunctionPopUp.js
- src/elements/NewFunctionPopUp/newFunctionPopUp.scss
https://trello.com/c/kmAQyQyy/1000-function-panel-pre-populate-resulting-image
- **Functions, Function panel**: Moved “Function Name” and “Tag” fields from “General” section of the function panel to the pop-over in the “Functions” screen (after clicking on the “New” button). Added the function name, tag and runtime as read-only text in the “General” section. Added default value pre-population for the “Resulting Image” field, where it gets its default value from `frontend-spec` and supplant `{project}`, `{name}` and `{tag}` with the project name, function name, and function tag, respectively.
Before:
After:
In-release (GA) for the most part.
Jira ticket ML-906, ML-1111
> [Function panel] Pre-populate Resulting Image

- src/common/Tooltip/Tooltip.js
- src/elements/TooltipTemplate/TextTooltipTemplate.js
- src/elements/TooltipTemplate/textTooltipTemplate.scss
https://trello.com/c/lGz0ECgf/992-general-tooltip-text-might-get-unexpectedly-wrapped
- **General**: Tooltips had the words in them broken into multiple lines.
Before:
After:
Jira ticket ML-889
> [General] Tooltip text might get unexpectedly wrapped

- .github/workflows/build.yaml
Following https://github.com/mlrun/mlrun/pull/1326
> Fix [Pkg] Set Build CI workflow to use git hash of 8 charaters for images tag

- src/scss/main.scss
https://trello.com/c/evTwjIDu/1005-jobs-status-filter-unaligned-option-labels
- **Jobs**: In “Monitor” tab, the “All” option label in the “Status” filter was unaligned with the rest of the option labels.
Before:
After:
> [Jobs] Status filter: unaligned option labels

- src/components/JobsPage/jobsData.js
- src/components/Table/Table.js
https://trello.com/c/LfH9vfMP/1011-jobs-error-when-grouping-by-workflows
- **Jobs**: In “Monitor” tab, setting “Group By” to “Workflows” caused an error in UI when there were workflows in the project.
> [Jobs] Error when grouping by workflows

- src/elements/FeaturesTablePanel/FeatureTablePanleRow/FeaturesTablePanelRow.js
- src/elements/FeaturesTablePanel/FeaturesTablePanel.js
https://trello.com/c/RyQdxZX7/1012-features-remove-tooltip-for-hidden-element
- **Features**: “Set as label” tooltip was unexpectedly shown when the “Set as label” action icon was hidden.
> [Features] Remove tooltip for hidden element

- src/elements/TooltipTemplate/TextTooltipTemplate.js
- src/elements/TooltipTemplate/textTooltipTemplate.scss
https://trello.com/c/xy7G4x2v/1023-general-tooltip-text-with-dashes-may-be-wrapped-incorrectly
- **General**: Tooltip close to the viewport‘s edge sometimes got broken down improperly.
Before:
After:
> [General] Tooltip text with dashes may be wrapped incorrectly

- src/actions/projects.js
- src/api/projects-api.js
- **Projects**: Fetch project summaries from newer endpoint `GET /api/project-summaries` instead of the older (and soon to be deprecated): `GET /api/projects?format=summary`.
Relates to PRs https://github.com/mlrun/mlrun/pull/1342 & https://github.com/mlrun/mlrun/pull/1347
Jira ticket ML-498
> Impl [Projects] Move to new project summaries endpoint

- src/utils/object.js
https://trello.com/c/RNnSHrrN/1022-job-panel-json-parameter-values-not-parsed-properly
- **Job panel**: In “Parameters” section, parameters of type JSON were parsed incorrectly, leading to errors on attempting to re-run a job without editing anything in the job panel.
Before:
After:
Jira ticket ML-1120
> [Job panel] JSON parameter values not parsed properly

- src/common/Tip/Tip.js
- src/common/Tip/tip.scss
https://trello.com/c/9zprc8QH/1030-functions-new-missing-validation-rules-tooltip-for-name
- **General**: Almost all tooltips stopped working, they did not show on hovering the (?) icon.
Bug originated in https://github.com/mlrun/ui/pull/805 [v0.8.0-rc2](https://github.com/mlrun/ui/releases/tag/v0.8.0-rc2)
> [General] Almost all tooltips do not show on hover

- src/components/Details/Details.js
- src/components/Details/DetailsView.js
- src/components/JobsPage/Jobs.js
- src/components/Workflow/Workflow.js
https://trello.com/c/alxJarBc/1026-feature-storemodelsfiles-unexpected-redirect-on-details-panel-close
- **Feature store, Models, Files**: Closing the details panel resulted in an unexpected redirection to “Projects” screen.
Bug originated in https://github.com/mlrun/ui/pull/804
> [Feature Store][Models][Files] Unexpected redirect on Details panel close

- src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSource.js
- src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.util.js
- src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
- src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
- src/constants.js
- src/utils/panelPathScheme.js
https://trello.com/c/sD5pBKNV/1032-data-inputs-v3io-fixed-leading-slash
- **Data Inputs**: For “V3IO” scheme, instead of having a static part of `v3io://` (2 slashes) and enforce the user input to start with another slash, have the static part have three slashes `v3io:///` and do not enforce the user input to start with a slash.
Before:
After:
Jira ticket ML-1154
> [Data Inputs] V3IO: Fixed leading slash

- src/components/ProjectsPage/projects.scss
https://trello.com/c/5IevRJHg/1027-projects-archived-projects-label-is-cropped
- **Projects**: “Archived Projects” was always cropped
Before:
After:
> [Projects] Archived Projects label is cropped

- src/components/FeatureStore/featureStore.util.js
https://trello.com/c/EXcTkbhk/1044-feature-sets-ui-crashes-on-row-expand
- **Feature sets**: Error occurred on expanding a feature-set row after visiting “Datasets” tab.
Bug originated on https://github.com/mlrun/ui/pull/816 [v0.8.0-rc3](https://github.com/mlrun/ui/releases/tag/v0.8.0-rc3) ML-1118
> [Feature sets] UI crashes on row expand

- src/App.js
- src/components/ProjectSettings/ProjectSettings.js
- src/components/ProjectSettings/projectSettings.scss
- src/components/ProjectSettings/projectSettings.util.js
- src/constants.js
- src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
- src/elements/ProjectSettingsGeneral/ProjectSettingsGeneralView.js
- src/elements/ProjectSettingsSecrets/ProjectSettingsSecrets.js
- src/elements/ProjectSettingsSecrets/ProjectSettingsSecretsView.js
- src/elements/ProjectSettingsSource/ProjectSettingsSource.js
- src/reducers/projectReducer.js
https://trello.com/c/hxwHL5GQ/1045-project-settings-add-general-and-secrets-tabs
- **Project Settings**: Split into two tabs: “General” and “Secrets”
Before:
After:
Continuing https://github.com/mlrun/ui/pull/831 [v0.8.0-rc4](https://github.com/mlrun/ui/releases/tag/v0.8.0-rc4)
Jira ticket ML-1038
> [Project Settings] Add General and Secrets tabs

- src/layout/Page/Page.js
https://trello.com/c/5L4eSIAQ/1057-general-wrong-redirection-on-mlrun-logo-click
- **General**: Clicking on the MLRun logo when address bar has `?demo=true` in the URL resulted in an error.
Continuing https://github.com/mlrun/ui/pull/804 [v0.8.0-rc3](https://github.com/mlrun/ui/releases/tag/v0.8.0-rc3) ML-688
> [General] Wrong redirection on "MLRun" logo click

- src/components/ArtifactsPreview/ArtifactsPreviewView.js
https://trello.com/c/EXdqm3rK/1056-files-project-stucks-on-entering-preview-tab
- **Models, Files, Datasets**: Previewing artifacts with a preview of type `table` might make UI hang when there is a very large amount of records. It is now limited to showing only the first 100 records.
Jira ticket ML-1221
> [Files] UI stuck on entering preview tab with numerous rows

- src/components/DetailsLogs/DetailsLogs.js
- src/reducers/jobReducer.js
https://trello.com/c/da2E52Xy/1060-jobs-two-loaders-exists-on-entering-details-logs-tab
- **Jobs**: In “Logs” tab in details panel of a job, there were two loaders instead of one.
Before:
After:
> [Jobs] Two loaders exists on entering Details Logs tab

- src/components/JobsPanel/jobsPanel.scss
- src/elements/FunctionsPanelResources/functionsPanelResources.scss
https://trello.com/c/39Xuk0l4/1054-function-panel-resources-overflows-container
- **Function panel**: In “Resources” section, “Memory Limit” field moved to the next line when selecting “millicpus” in the “CPU Unit” field.
Before:
After:
> [Function panel] Resources overflows container

- src/api/projects-iguazio-api.js
- src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
https://trello.com/c/FEJd5zlm/1072-project-overview-filter-users-selected-as-owner
- **Project Overview**: In “Change owner” pop-up, in the user auto-complete, filter to only the users who have management policy of Developer, Project Admin, or Project Read Only — as they are the only ones who should be valid as project owners.
Jira ticket ML-1204
> [Project Overview] Filter users selected as owner

- src/components/Workflow/Workflow.js
https://trello.com/c/2gpGHMCK/1082-workflows-skip-node-with-type-of-dag
- **Workflows**: In the graph view, skip the node with type of DAG, start the graph from its first child.
Before:
After:
Continuing https://github.com/mlrun/ui/pull/804 [v0.8.0-rc3](https://github.com/mlrun/ui/releases/tag/v0.8.0-rc3) ML-688
> [Workflows] Skip node with type of DAG

- generate-release-notes.js
- package.json
- **Config**: Added a new NPM script named `generate-rn` which runs the new `./generate-release-notes.js` Node script for generating release notes between two given versions and the release type (RC or GA, to know which in-release PRs to skip).
Usage examples:
```bash
MLRUN_OLD_VERSION=0.8.0-rc13 MLRUN_VERSION=0.8.0-rc14 MLRUN_RELEASE_TYPE=RC npm run generate-rn
```
```bash
MLRUN_OLD_VERSION=0.7.0 MLRUN_VERSION=0.8.0 MLRUN_RELEASE_TYPE=GA npm run generate-rn
```
```bash
MLRUN_OLD_VERSION=0.7.0 MLRUN_VERSION=0.8.0 npm run generate-rn
```
(defaults to GA)
> Impl [Config] Add `generate-rn` NPM script for release notes

- src/common/Breadcrumbs/Breadcrumbs.js
https://trello.com/c/S3Jdwddf/1121-breadcrumbs-when-changing-tab-drop-down-isnt-closing
> [Breadcrumbs] When changing tab drop-down isn't closing

- src/components/FeatureStore/featureStore.util.js
https://trello.com/c/ClTmY1U8/1180-uifeature-vector-the-preview-tab-is-empty
> [UI][Feature Vector] The 'Preview' tab is empty

- src/components/Table/table.scss
- src/elements/TableLinkCell/tableLinkCell.scss
https://trello.com/c/M6YnA8dx/1204-jobsmonitor-workflows-workload-name-is-cut-although-there-is-a-lot-of-space
> [Jobs][Monitor Workflows] workload name is cut although there is a lot of space

- src/actions/featureStore.js
https://trello.com/c/BYakc6UM/1212-feature-set-unclear-error-for-duplicated-fs-name
> [Feature set] Unclear error for duplicated FS name

- src/common/ReactFlow/mlReactFlow.scss
- src/components/Models/Models.js
- src/components/Models/models.util.js
- src/components/Pipeline/Pipeline.js
- src/components/Pipeline/PipelineView.js
- src/components/Pipeline/pipeline.scss
- src/components/Table/Table.js
- src/components/Table/TableView.js
- src/elements/FunctionsTableRow/FunctionsTableRow.js
- src/elements/TableLinkCell/TableLinkCell.js
- src/utils/createFunctionsContent.js
Part of: #865
**Real-time Pipelines]**: Avoid presentation of duplicated names
https://jira.iguazeng.com/browse/ML-1710
- Duplicated names fix: -add a collapsible row with the same logic as in "function" screen. Filter out non tags versions and show on expand row
- Make the "Router" clickable, once clicked open the right panel with some information (class name, type).
> Impl [Real-time Pipelines] Avoid presentation of duplicated names

- src/common/OptionsMenu/ValidationTemplate/ValidationTemplate.module.scss
- src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTitle/featureSetsPanelTitle.scss
- src/utils/validationService.js
- **Feature Sets**: Missing validation and tooltips in the Tag tips
Jira: [ML-1497](https://jira.iguazeng.com/browse/ML-1497)
Fix:
- -_. are the only special characters allowed (ex: rc-5, 1.0, 1_1)
- Must begin and end with a-z, A-Z, 0-9 (no valid: -rc, rc.)
> Fix [Feature Sets] Missing validation and tooltips in the Tag tips

- src/elements/ProjectJobs/projectJobs.utils.js
- **Project**:  Wrong redirection on clicking the `job` link
Pressing on job name link from a Project overview screen navigates to main projects page
https://jira.iguazeng.com/browse/ML-1735
> Fix [Project] Wrong redirection on clicking the `job` link

- src/App.js
- src/components/Details/DetailsView.js
- src/components/Jobs/Jobs.js
- src/components/Jobs/JobsView.js
- **Jobs**: Add backward compatibility for old url path to job runs details.
Related to Jira: [ML-1735](https://jira.iguazeng.com/browse/ML-1735) and [ML-1569](https://jira.iguazeng.com/browse/ML-1569)
Related to: [Fix [Project] Wrong redirection on clicking the job link #1079](https://github.com/mlrun/ui/pull/1079) and [Impl [Jobs] Jobs screen - runs display #1071](https://github.com/mlrun/ui/pull/1071)
> Fix [Jobs] Add fix for jobs routing

- src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
- **Feature Vector**: Missing loader on Add to Feature Vector screen
- Missing Loader when fetching Features
Jira: https://jira.iguazeng.com/browse/ML-1761
Before: 
After:
> Fix [UI][Feature Vector] Missing loader on Add to Feature Vector screen

- src/components/JobsPanel/jobsPanel.util.js
- src/components/JobsPanel/panelReducer.js
- src/constants.js
- **Jobs**: MLRun-kit when re-running a job the UI automatically sets the default_artifact_path to v3io
https://jira.iguazeng.com/browse/ML-1713
> Fix [Jobs] MLRun-kit when re-running a job the UI automatically sets the default_artifact_path to v3io

- src/common/ReactFlow/mlReactFlow.scss
- src/common/ReactFlow/mlReactFlow.util.js
- src/layout/Content/content.scss
- **Models**: Real-time pipeline view the rectangle are too small
Jira: [ML-1779](https://jira.iguazeng.com/browse/ML-1779)
Before:  
After:
> Fix [Models] Real-time pipeline view the rectangle are too small

- src/components/Table/Table.js
- src/components/Table/TableView.js
(cherry picked from commit 67d270b19dcbf184978fcc24b5483e4d994e7371)
Backport: [Fix [Jobs] Monitor Jobs crash when undefined (reading 'value') #1110](https://github.com/mlrun/ui/pull/1110)
> Fix [Jobs] Monitor Jobs crash when undefined (reading 'value') [Backport 0.10.x]

- src/common/KeyValueTable/keyValueTable.scss
- src/components/ProjectSettings/projectSettings.scss
- src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
- src/elements/ProjectSettingsMembers/ProjectSettingsMembers.js
- src/elements/ProjectSettingsSecrets/ProjectSettingsSecretsView.js
- **Project Settings**: 
- If user is not allowed to change members, display only members count
- Owner: Disable `Discard` button if no changes were made
> Fix [Settings] display members count

- src/httpClient.js
- **API**: Change to use versioned API paths
- For example: instead of sending GET to /api/projects to list the projects, send it to /api/v1/projects
https://jira.iguazeng.com/browse/ML-1808
> Impl [UI] Change to use versioned API paths

- src/components/Project/ProjectMonitorView.js
- **Artifacts**: redirect to 'Projects' screen instead of staying in current project upon 'Register artifact'
Jira: https://jira.iguazeng.com/browse/ML-1596
> Fix [Project Monitor] Redirect to 'Projects' screen instead of staying in current project upon 'Register artifact'

- src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
- src/elements/ChangeOwnerPopUp/changeOwnerPopUp.scss
- **Project Settings**: Previous owner access annotation appears in owner settings section
Jira: https://jira.iguazeng.com/browse/ML-1839
Before: 
After:
> Fix [Project Settings Previous owner access annotation appears in owner settings section

- src/actions/jobs.js
- **Jobs**: Clicking on artifacts return empty window and TypeError
https://jira.iguazeng.com/browse/ML-1869
Before: 
After:
> Fix [Jobs] Clicking on artifacts return empty window and TypeError

- src/elements/ProjectCard/projectCard.util.js
- **Projects**: Missing time indication for failed job/functions in the projects view
* Fix the tooltip on hover on the "failed" icon: "Failed ML jobs and nuclio functions in the last 24 hours"
Jira: [ML-1877](https://jira.iguazeng.com/browse/ML-1877)
> Fix [Projects] Missing time indication for failed job/functions in the projects view

- src/components/AddToFeatureVectorPage/addToFeatureVectorPage.util.js
- src/components/Datasets/Datasets.js
- src/components/Datasets/datasets.util.js
- src/components/FeatureStore/featureStore.util.js
- **Datasets** 
- Show iterations checkbox doesn't work 
- Change 'Label' to 'Labels'
Jira: https://jira.iguazeng.com/browse/ML-1928
Before: 
After:
> Fix [Datasets] Show iterations checkbox doesn't work

- src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
- src/utils/validationService.js
- **Feature vector**: Create Feature vector API failed when Feature tag includes dot
Jira: https://jira.iguazeng.com/browse/ML-1691
Before:
After:
> Fix [Feature vector] Create Feature vector API failed when Feature tag inсludes dot

- src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
- src/components/DetailsRequestedFeatures/detailsRequestedFeatures.scss
- src/components/DetailsRequestedFeatures/detailsRequestedFeatures.utils.js
- src/components/FeatureStore/featureStore.util.js
- src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
- src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
- src/elements/FeaturesTablePanel/featuresTablePanel.scss
- src/elements/ProjectCard/ProjectCardView.js
- src/scss/main.scss
- **Feature Vectors**: Improve add/edit Alias Behavior
Jira: [ML-1941](https://jira.iguazeng.com/browse/ML-1941)
- Hover on the FV row will display a "Delete" Icon
- If a FV "alias" cell is empty
- Add an indication (+ Icon) and a tooltip "Click to add an alias".
- Clicking the + icon will change to an input field and Hide the "Delete" row Icon.
- If a FV has an alias
- Display FV "alias" instead of the + Icon.
- Place an "edit" icon and tooltip "Click to edit" next to the FV alias.
- Click on the "edit" icon will change to an input field filled with the FV alias.
- If a FV alias field is being edited, clicking "+" or "Edit" icons of another FV alias will change the current field to its initial state and discard changes to it if made.
- If a FV alias is being added/edited - Add "Apply" …
> Impl [Feature Vectors] Improve add/edit Alias Behavior

- src/elements/FunctionsPanelResources/FunctionsPanelResources.js
- **Functions**: Empty default value of Pod priority field
Jira: [ML-1982](https://jira.iguazeng.com/browse/ML-1982)
Before:
After:
> Fix [Functions] Empty default value of Pod priority field

- src/components/ConsumerGroups/consumerGroups.util.js
- src/utils/createConsumerGroupsContent.js
- src/utils/parseV3ioStreams.js
- **Consumer groups**: Wrong value presents for Stream
Jira: [ML-1987](https://jira.iguazeng.com/browse/ML-1987)
Before:
After:
> Fix [Consumer groups] Wrong value presents for Stream

- src/common/Select/Select.js
- src/components/JobsPanelResources/JobsPanelResources.js
- src/components/JobsPanelResources/JobsPanelResourcesView.js
- src/elements/FunctionsPanelResources/FunctionsPanelResources.js
- src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
- src/utils/generateFunctionPriorityLabel.js
- src/utils/parseFunctionPriorityLabel.js
- **MLRun** Pod priority UI values
The pod priority values in UI should be changed to [Low, Medium, Hight]  instead of [`igz-workload-high', ..]
Fix Includes: 
- Jobs and workflows => New Job
- ML functions => New Job/Serving
Jira: [ML-1966](https://jira.iguazeng.com/browse/ML-1966)
Before: 
After:
> Fix [MLRun] Pod priority UI values

- src/utils/createConsumerGroupsContent.js
- src/utils/parseV3ioStreams.js
- **Consumer groups**: No data in consumer group report due to wrong API request
related To: #1191 
Jira: [ML-2060](https://jira.iguazeng.com/browse/ML-2060)
Before:
After:
> Fix [Consumer groups] No data in consumer group report due to wrong API request

- src/components/JobsPanel/jobsPanel.util.js
- **Functions**: Pod priority is changed to default (Medium) after running a mlrun function
Jira: https://jira.iguazeng.com/browse/ML-2011
Related to: #1197
> Fix [UI] Pod priority is changed to default (Medium) after running a mlrun function

- src/components/ConsumerGroup/ConsumerGroup.js
- src/components/ConsumerGroups/ConsumerGroups.js
- **Consumer groups**: Consumer Group search should be insensitive
Jira: [ML-2078](https://jira.iguazeng.com/browse/ML-2078)
Before:
After:
> Fix [Consumer groups] Consumer Group search should be insensitive

- src/common/ActionsMenu/ActionsMenu.js
- src/common/ActionsMenu/actionsMenu.scss
- src/common/RoundedIcon/RoundedIcon.js
- src/common/RoundedIcon/roundedIcon.scss
- **UI**: Table row - Keep 3 dots Icon visible while menu is open
Jira: [ML-2082](https://jira.iguazeng.com/browse/ML-2082)
Before:
After:
> Fix [UI] Table row - Keep 3 dots Icon visible while menu is open

- src/actions/featureStore.js
- src/actions/functions.js
- src/actions/jobs.js
- src/components/Jobs/Jobs.js
- **Functions**: `MLRunAccessDeniedError` for creating ML Function by user where user is member with viewer role
Jira: https://jira.iguazeng.com/browse/ML-2085
Before:
After:
> Fix [Functions] `MLRunAccessDeniedError` for creating ML Function by user where user is member with viewer role

- src/components/ConsumerGroups/ConsumerGroups.js
- **Consumer group** drill down text when 0 streams
Jira: [ML-2101](https://jira.iguazeng.com/browse/ML-2101)
Before:
After:
> Fix [Consumer group] drill down text when 0 streams

- src/components/JobsPanel/jobsPanel.scss
- src/components/JobsPanelResources/JobsPanelResourcesView.js
- src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
- src/elements/FunctionsPanelResources/functionsPanelResources.scss
- **Jobs**: misleading 'PODS TOLERATION' in mlrun UI job wizard
Backport to: 1.0.0
Jira: [ML-2088](https://jira.iguazeng.com/browse/ML-2088)
Before:
After:
> Fix [Jobs] misleading 'PODS TOLERATION' in mlrun UI job wizard

- src/components/Project/ProjectMonitorView.js
- src/elements/ProjectSummaryCard/ProjectSummaryCard.js
- **UI** Projects summaries show N/A in environment without Nuclio
Related To: #1223 
Jira: https://jira.iguazeng.com/browse/ML-2106
> Fix [UI] Projects summaries show N/A in environment without Nuclio

- src/components/JobsPanel/jobsPanel.util.js
- **Jobs Panel**: The Pods Priority dropdown doesn't have selected value
Jira: https://jira.iguazeng.com/browse/ML-2119
> Fix [Jobs Panel] The Pods Priority dropdown doesn't have selected value

- Dockerfile
- package.json
- scripts/start.js
- **General**: Projects screen is empty - 'SyntaxError: Unexpected token '<' (at main.d5697fce.js:1:1)'
Jira: https://jira.iguazeng.com/browse/ML-2156
Before:
After:
> Fix [General] Projects screen is empty - 'SyntaxError: Unexpected token '<' (at main.d5697fce.js:1:1)'

- src/components/ConsumerGroup/ConsumerGroup.js
- src/components/ConsumerGroups/ConsumerGroups.js
- **Consumer Groups**: Filter by name should be case insensitive
Jira: https://jira.iguazeng.com/browse/ML-2176
Before:
After:
> Fix [Consumer Groups] Filter by name should be case insensitive

- src/components/Details/details.util.js
- **Models**: No data for Model framework in the Model overview screen
Jira: https://jira.iguazeng.com/browse/ML-2193
Before:
After:
> Fix [Models] No data for Model framework in the Model overview screen

- src/common/ChipInput/chipInput.scss
- **Project settings**: scrolling should be inside suggestion list in 'Invite new members' screen
Jira: [ML-2235](https://jira.iguazeng.com/browse/ML-2235)
Before:
After:
> Fix [Project settings] scrolling should be inside suggestion list in 'Invite new members' screen

- src/utils/resources.js
- **Models**: Wrong naming convention for Model URI in overview screen
Jira: https://jira.iguazeng.com/browse/ML-2242
Before:
After:
> Fix [Models] Wrong naming convention for Model URI in overview screen

- src/layout/Page/PageView.js
- **ChipCell**: prevent component re-render on tabs hover
In Jobs ==> Monitor Jobs: Hover on `Tabs` or `Breadcrumbs`, the `mainResize` event is fired causing the `ChipCell` component to re-render
> Fix [ChipCell] prevent component re-render on tabs hover

- src/components/Jobs/ScheduledJobs/ScheduledJobs.js
- **Jobs**: Run now button looks like drop down
Jira: [ML-2285](https://jira.iguazeng.com/browse/ML-2285)
Before:
After:
> Fix [Jobs] Run now button looks like drop down

- src/common/Download/Download.js
- **Models**: Downloaded model file from "Project-> models" has base64 format instead of pkl
Jira: https://jira.iguazeng.com/browse/ML-2241
> Fix [Models] Downloaded model file from "Project-> models" has base64 format instead of pkl

- src/components/Datasets/datasets.util.js
- src/components/Details/details.util.js
- src/components/Files/files.util.js
- src/components/Models/models.util.js
- **Mode**: Tag Not Displayed in Model + Datasets and Artifacts Description
"add the Tag For all 3 pages, in Overview => under the Key row"
https://jira.iguazeng.com/browse/ML-2057
Before:
After:
> Impl [Artifacts] Tag Not Displayed in artifact Description

- src/components/ArtifactsPreview/artifactsPreview.scss
- src/utils/createFeatureStoreContent.js
- **Feature store**:  Preview scroll, Feature set column width
Before:
After:
> Fix [Feature store] Preview scroll, Feature set column width

- .npmignore
- Dockerfile
- README.md
- nginx/nginx.conf.tmpl
(cherry picked from commit 256e5e8745fc0eafcd7420e7f5beb982f6941f06)
> [Build] Backport support running as rootless [1.0.x]

- src/components/DetailsResults/detailsResults.scss
- **Jobs**:  Results tab - layout issue
- When List is long, horizontal scroll is at the bottom
Jira: [ML-2410](https://jira.iguazeng.com/browse/ML-2410)
Before:
After:
> Fix [Jobs] Results tab - layout issue

- .github/workflows/build.yaml
Back port for https://github.com/mlrun/ui/pull/1348
> [CI] BackPort Pull Unstable Image Version Prefix From MLRun [1.0.x]

- src/elements/ProjectSettingsSecrets/ProjectSettingsSecretsView.js
- **Project secrets**: Add Additional Information to Project Secrets screen
Jira: [ML-2444](https://jira.iguazeng.com/browse/ML-2444)
Before:   
After:
> Fix [Project secrets] Add Additional Information to Project Secrets screen

- src/components/DetailsStatistics/detailsStatistics.util.js
- src/utils/roundFloats.js
- **Feature set** std column on statistics page is empty after ingest with spark engine
**Fix:** 
- They contain the stddev label instead of std
- All values are of type string, even where a numeric would be expected (e.g. "-1.234" instead of -1.234)
Jira: [ML-2463](https://jira.iguazeng.com/browse/ML-2463)
> Fix [Feature set] std column on statistics page is empty after ingest with spark engine

- src/components/DetailsArtifacts/DetailsArtifactsView.js
- src/components/DetailsArtifacts/detailsArtifacts.util.js
- **Artifacts**: "Show Details" for artifacts with no "latest" tag is broken and forwards to the main projects screen
Backported to `1.0.x` from #1362 
Jira: https://jira.iguazeng.com/browse/ML-2477
> Fix [Artifacts] "Show Details" for artifacts with no "latest" tag is broken and forwards to the main projects screen

- src/api/jobs-api.js
- src/components/Jobs/Jobs.js
- **Jobs**: 'Failed to fetch jobs' error appears on attempt to rerun job via UI
Backport to `1.0.x` from  #1367 
Jira: [ML-2485](https://jira.iguazeng.com/browse/ML-2485)
> Fix [Jobs] 'Failed to fetch jobs' error appears on attempt to rerun job via UI

- src/components/Details/details.util.js
- src/components/DetailsInfo/DetailsInfoView.js
- src/components/Jobs/jobs.util.js
- src/utils/createJobsContent.js
- src/utils/object.js
- src/utils/parseJob.js
- **Jobs**: Wrong parsing of parameters
- **Monitor Jobs**: The Parameters data is missing in the Job overview screen for job with Hyper param
Jira: https://jira.iguazeng.com/browse/ML-2475
Related to: https://jira.iguazeng.com/browse/ML-2432
Before:
After:
> Fix [Jobs] Wrong parsing of parameters

- src/components/FeatureStore/FeatureSets/featureSets.util.js
- src/components/Models/models.util.js
- **Models**: No data for data for Unique, Top and Freq in the Statistics tab
Jira: [ML-2194](https://jira.iguazeng.com/browse/ML-2194)
Before:
After:
> Fix [Models] No data for data for Unique, Top and Freq in the Statistics tab

- src/common/Breadcrumbs/breadcrumbs.util.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
- src/elements/DeployModelPopUp/DeployModelPopUp.js
- **UI**: small fixes
1. Steps to reproduce: 
Go to Models -> Models endpoint 
Change project via breadcrumbs
Model endpoint tab should stay selected, but actual is tab become "Models"
2. Steps to reproduce:
Go to Models table -> Select "Deploy" in action menu, click "Deploy"
We got errors in console
3. Steps to reproduce:
Go to Feature Set panel -> Target Store accordion
Check "Partition" checkbox near the "Offline" path
Click "Show advanced"
Select "By key"
Select "Number of buckets"
Now click on edit icon near Offline path and then click on discard button
UI is crashed and we got errors
Jira: https://jira.iguazeng.com/browse/ML-2661
> Fix [UI] small fixes

- src/api/artifacts-api.js
- src/common/TargetPath/TargetPath.js
- src/components/RegisterArtifactModal/RegisterArtifactModal.js
- src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
- src/elements/RegisterModelPopUp/RegisterModelPopUp.js
- src/elements/RegisterModelPopUp/registerModelPopUp.scss
- **UI**: artifact/model registered via UI is using old format
Fixed:
- `TargetPath.js`: Can receive a root key or deep nested
- `Register Model`: Added name validation 
- `Register artifact/model`: Send body in new structure
Before:
After:
> Fix [UI] artifact/model registered via UI is using old format

- src/elements/NavbarLink/NavbarLink.js
- src/layout/Navbar/Navbar.utils.js
- **Navbar**: project home active state
Before: 
After:
> Fix [Navbar] project home active state

- src/components/Jobs/jobs.util.js
- src/components/JobsPanel/jobsPanel.util.js
- **Jobs**: Unable to rerun mlrun job from dashboard - job parameter passed as string instead of float
Jira: [ML-2698](https://jira.iguazeng.com/browse/ML-2698)
> Fix [Jobs] Unable to rerun mlrun job from dashboard - job parameter passed as string instead of float

- src/components/Project/ProjectOverview/ProjectOverview.util.js
- **Project Overview** "Create RT function" should navigate to "new function" wizard
Jira: [ML-2786](https://jira.iguazeng.com/browse/ML-2786)
> Fix [Project Overview] "Create RT function" should navigate to "new function" wizard

- src/components/ProjectsPage/projects.scss
- **Projects**: unexpected project cards resizing
Jira: [ML-2734](https://jira.iguazeng.com/browse/ML-2734)
Before:
After:
> Fix [Projects] unexpected project cards resizing

- src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
- **Artifacts**: add existing tag name warning
Before:
After:
> Fix [Artifacts] add existing tag name warning

- package.json
- src/layout/Header/Header.js
- src/layout/Header/header.scss
- **UI** Put MLRun icon instead of the 'M'
Backported to `1.2.x` from #1496 
Jira: [CEML-53](https://jira.iguazeng.com/browse/CEML-53)
Before:
After:
> Fix [UI] Put MLRun icon instead of the 'M'

- src/components/Datasets/datasets.util.js
- src/components/Files/files.util.js
- src/components/FilterMenu/FilterMenu.js
- src/components/ModelsPage/Models/models.util.js
- **UI**: Models screen - show iteration checkbox rename
Jira: [ML-2926](https://jira.iguazeng.com/browse/ML-2926)
Before:
After:
> Fix [UI] Models screen - show iteration checkbox rename

- src/common/Input/Input.js
- src/common/Search/Search.js
- src/components/ProjectsPage/Projects.js
- src/components/ProjectsPage/ProjectsView.js
- src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
- **Projects**: Searching a project in the UI does not find new projects
Backported to `1.2.x` from #1491 
- Added projects refresh on Search input focus
Jira: [ML-2911](https://jira.iguazeng.com/browse/ML-2911)
> Fix [Projects] Searching a project in the UI does not find new projects

- src/components/JobsPanel/jobsPanel.util.js
- **Jobs**: Creating a job using a function from a different project gets 404 - uses wrong function URI
Backported to `1.2.x` from #1505 
Jira: https://jira.iguazeng.com/browse/ML-2961
> Fix [Jobs] Creating a job using a function from a different project gets 404 - uses wrong function URI

- src/components/Datasets/Datasets.js
- src/components/Files/files.util.js
- **Artifacts**: Show iterations checkbox doesn't show any additional information
Backported to `1.2.x` from #1511 
Jira: https://jira.iguazeng.com/browse/ML-2939
> Fix [Artifacts] Show iterations checkbox doesn't show any additional information

- src/components/Project/project.scss
- src/elements/ProjectDataCard/ProjectDataCard.js
- src/elements/ProjectJobs/projectJobs.utils.js
- **Project Monitor**: Change 'See all' -> 'See all recent'
Related to fix in #1519 
Jira: [ML-3032](https://jira.iguazeng.com/browse/ML-3032)
Before:
After:
> Fix [Project Monitor] Change 'See all' -> 'See all recent'

- src/components/ArtifactsPreview/ArtifactsPreviewView.js
- src/components/ArtifactsPreview/artifactsPreview.scss
- src/utils/createArtifactPreviewContent.js
- **Models**: Preview of model shows irrelevant json with 'listdir' to the customer
Backported to `1.2.1` from #1521 
Jira: [ML-2999](https://jira.iguazeng.com/browse/ML-2999), [ML-3042](https://jira.iguazeng.com/browse/ML-3042)
> Fix [Models] Preview of model shows irrelevant json with 'listdir' to the customer `1.2.1`

- src/utils/getArtifactPreview.js
- **Artifacts**: Wrong logic for displaying preview
Backported to `1.2.1` from #1530 
Jira: https://jira.iguazeng.com/browse/ML-3049
> Fix [Artifacts] Wrong logic for displaying preview

- src/components/Table/table.scss
- **Artifacts**: Cropped name on small screens
Backported to `1.2.1` from #1534 
Jira: https://jira.iguazeng.com/browse/ML-3050
Before:
After:
> Fix [Artifacts] Cropped name on small screens

- src/components/FunctionsPage/Functions.js
- src/utils/getNoDataMessage.js
- **Functions**: writes "show untagged: true" though the checkbox is not selected
Backported to `1.2.1` from #1538 
Jira: https://jira.iguazeng.com/browse/ML-3053
> Fix [Functions] writes "show untagged: true" though the checkbox is not selected

- src/components/Details/DetailsView.js
- src/components/Details/details.util.js
- src/components/DetailsInfo/detailsInfo.util.js
- src/components/Project/ProjectMonitorView.js
- src/elements/PreviewModal/PreviewModal.js
- src/elements/ProjectJobs/projectJobs.utils.js
- src/utils/createArtifactsContent.js
- src/utils/createFeatureStoreContent.js
- src/utils/createFunctionsContent.js
- src/utils/createJobsContent.js
- src/utils/datetime.js
- **Model-endpoints**: Time is wrong in model endpoint
Backported to `1.2.1` from #1531 
Jira: https://jira.iguazeng.com/browse/ML-2984
> Fix [Model-endpoints] Time is wrong in model endpoint

- src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
- src/layout/Header/Header.js
- src/layout/Header/header.scss
- **UI** Change MLRun header
Follow up to #1496 
Backported to `1.2.1` from #1537 
Jira: [ML-3044](https://jira.iguazeng.com/browse/ML-3044)
Before:
After:
> Impl [UI] Change MLRun header `1.2.1`

- src/utils/createArtifactsContent.js
- **Models-endpoint** Uptime/Last prediction are cropped in "Model Endpoints" screen
Jira: https://jira.iguazeng.com/browse/ML-3077
> Fix [Models-endpoint] Uptime/Last prediction are cropped in "Model Endpoints" screen

- src/components/ScheduleCron/ScheduleCron.js
- src/components/SheduleWizard/ScheduleWizard.js
- src/components/SheduleWizard/ScheduleWizardCronstring.js
- src/components/SheduleWizard/scheduleWizard.scss
- src/components/Table/TableHead.js
- src/components/Table/table.scss
- src/elements/ScheduleRecurring/ScheduleRecurring.js
- src/utils/createJobsContent.js
- **Jobs**: Scheduled Jobs are triggered at +1 day
- Hide the generated cron string, i.e "At 12:00 AM, only on Sunday, Monday, Tuesday, Wednesday, and Thursday"
- Add a message under the Note and above the Input "The first weekday (0) is always Monday."
- Jobs => Schedule tab => Add tooltip to "Schedule (UTC)" Column title. Saying: "The first weekday (0) is always Monday."
Jira: https://jira.iguazeng.com/browse/ML-2878
> Fix [UI] Scheduled Jobs are triggered at +1 day

- src/components/ScheduleCron/ScheduleCron.js
- src/components/Table/TableHead.js
- src/components/Table/table.scss
- src/elements/ScheduleRecurring/ScheduleRecurring.js
- src/utils/createJobsContent.js
- **Jobs**: Scheduled Jobs are triggered at +1 day
- Hide the generated cron string, i.e "At 12:00 AM, only on Sunday, Monday, Tuesday, Wednesday, and Thursday"
- Add a message under the Note and above the Input "The first weekday (0) is always Monday."
- Jobs => Schedule tab => Add tooltip to "Schedule (UTC)" Column title. Saying: "The first weekday (0) is always Monday."
Backported to `1.2.1` from #1561 
Jira: https://jira.iguazeng.com/browse/ML-2878
> Fix [UI] Scheduled Jobs are triggered at +1 day `1.2.1`

- src/components/Details/details.scss
- src/components/DetailsLogs/DetailsLogs.js
- **Jobs**: The 'Refresh' button covers/hides the logs of the job
Backported to `1.2.1` from #1562 
Jira: [ML-3096](https://jira.iguazeng.com/browse/ML-3096) + [ML-3097](https://jira.iguazeng.com/browse/ML-3097)
Before:
After:
> Fix [Jobs] The 'Refresh' button covers/hides the logs of the job `1.2.1`

- src/components/Details/details.scss
- src/components/DetailsLogs/DetailsLogs.js
- **Jobs**: The 'Refresh' button covers/hides the logs of the job
Jira: [ML-3096](https://jira.iguazeng.com/browse/ML-3096) + [ML-3097](https://jira.iguazeng.com/browse/ML-3097)
Before:
After:
> Fix [Jobs] The 'Refresh' button covers/hides the logs of the job

- src/components/DetailsInfo/DetailsInfo.js
- src/components/DetailsInfo/DetailsInfoView.js
- src/elements/DetailsInfoItem/DetailsInfoItem.js
- **UI**: Edit a an artifact tag from the overview tab does not have exit option `1.2.1`
Backported to `1.2.1` from #1555 
Jira: [ML-3061](https://jira.iguazeng.com/browse/ML-3061)
Before:
After:
> Fix [UI] Edit a an artifact tag from the overview tab does not have exit option `1.2.1`

- src/components/DetailsInfo/DetailsInfo.js
- src/components/DetailsInfo/DetailsInfoView.js
- src/elements/DetailsInfoItem/DetailsInfoItem.js
- **UI**: Edit a an artifact tag from the overview tab does not have exit option
Jira: [ML-3061](https://jira.iguazeng.com/browse/ML-3061)
Before:
After:
> Fix [UI] Edit a an artifact tag from the overview tab does not have exit option

- src/components/Jobs/MonitorJobs/MonitorJobs.js
- src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
- src/components/Jobs/ScheduledJobs/ScheduledJobs.js
- **Jobs and Workflows**: Job Wizard fields aren't populated on `re-run`
Jira: https://jira.iguazeng.com/browse/ML-3112
Before:
After:
> Fix [Jobs and Workflows] Job Wizard fields aren't populated on `re-run`

- package.json
- src/components/RegisterArtifactModal/RegisterArtifactModal.js
- src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
- src/elements/RegisterModelModal/RegisterModelModal.js
- src/utils/artifacts.util.js
- **Artifacts**: Missing validation for an existing artifact name.
Backported to `1.2.x` from #1565  
Jira: [ML-3130](https://jira.iguazeng.com/browse/ML-3130)
Before:
After:
> Fix [UI] Model/Artifact/Datasets Missing validation for an existing artifact name `1.2.x`

- src/components/ArtifactsPreview/ArtifactsPreviewView.js
- src/components/ArtifactsPreview/artifactsPreview.scss
- src/utils/createArtifactPreviewContent.js
- src/utils/getArtifactPreview.js
- **Artifacts**: Bytes Artifact fails to show in "Preview" tab
Backported to `1.2.1` from #1567 
Jira: [ML-3106](https://jira.iguazeng.com/browse/ML-3106)
After:
> Fix [UI] Bytes Artifact fails to show in "Preview" tab `1.2.1`

- src/components/ScheduleCron/ScheduleCron.js
- src/components/Table/table.scss
- src/elements/ScheduleRecurring/ScheduleRecurring.js
- src/utils/createJobsContent.js
- **Jobs**: Change tooltip in UTC
- Change tooltip and schedule message to: "The first day of the week (0) is Monday, and not Sunday."
Jira: [ML-2878](https://jira.iguazeng.com/browse/ML-2878)
> Fix [Jobs] Schedule change tooltip in UTC

- src/components/ScheduleCron/ScheduleCron.js
- src/components/Table/table.scss
- src/elements/ScheduleRecurring/ScheduleRecurring.js
- src/utils/createJobsContent.js
- **Jobs**: Schedule change tooltip in UTC
- Change tooltip and schedule message to: "The first day of the week (0) is Monday, and not Sunday."
Backported to `1.2.1` from #1570 
Jira: [ML-2878](https://jira.iguazeng.com/browse/ML-2878)
> Fix [Jobs] Schedule change tooltip in UTC `1.2.1`

- src/utils/createArtifactPreviewContent.js
- **Artifacts**: Bytes Artifact fails to show in "Preview" tab
Related fix to #1567 
Jira: [ML-3074](https://jira.iguazeng.com/browse/ML-3074)
After:
> Fix [UI] Bytes Artifact fails to show in "Preview" tab

- src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
- src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
- **Jobs and Workflows**: K8s Pod Info Not Shown in Workflow View
Backported to `1.2.1` from #1575 
Jira: https://jira.iguazeng.com/browse/ML-3117
After:
> Fix [UI] K8s Pod Info Not Shown in Workflow View

- src/components/DetailsResults/DetailsResults.js
- src/components/DetailsResults/detailsResults.scss
- **Jobs**: text overlaps in job Results tab
Jira: https://jira.iguazeng.com/browse/ML-3148
After:
> Fix [UI] text overlaps in job Results tab

- src/layout/Header/Header.js
- src/scss/main.scss
- **CE**: MLRun CE UI doesn't show its version
Jira: [CEML-64](https://jira.iguazeng.com/browse/CEML-64)
Before:
After:
> Fix [UI CE] MLRun CE UI doesn't show its version

- src/layout/Header/Header.js
- src/scss/main.scss
- **CE**: MLRun CE UI doesn't show its version
Backported to `1.2.x` from #1586 
Jira: [CEML-64](https://jira.iguazeng.com/browse/CEML-64)
Before:
After:
> Fix [UI CE] MLRun CE UI doesn't show its version `1.2.x`

- src/common/KeyValueTable/keyValueTable.scss
- **Project Settings**: long key/value in 'Project parameters' causes 'Project settings' screen distortion
Jira: [ML-3257](https://jira.iguazeng.com/browse/ML-3257)
Before:
After:
> Fix [Project Settings] long key/value in 'Project parameters' causes 'Project settings' screen distortion

- src/components/Project/ProjectMonitorView.js
- src/components/Project/project.scss
- **Project Monitoring**: Display old layout not in demo mode
Jira: [ML-3253](https://jira.iguazeng.com/browse/ML-3253)
`Demo mode`:
`Production`:
> Fix [Project Monitoring] Display old layout not in demo mode

- src/components/Details/details.util.js
- **Jobs**: wrong value for Total iteration
Jira: [ML-3247](https://jira.iguazeng.com/browse/ML-3247)
Before:
After:
> Fix [Jobs] wrong value for Total iteration

- src/components/DetailsResults/DetailsResults.js
- src/components/DetailsResults/detailsResults.scss
- **Workflow report**: The job 'Result' field length too short
Jira: [ML-3285](https://jira.iguazeng.com/browse/ML-3285)
Before:
After:
> Fix [Workflow report] The job 'Result' field length too short

- src/components/ConsumerGroup/consumerGroup.util.js
- src/components/ConsumerGroups/consumerGroups.util.js
- src/components/Details/DetailsView.js
- src/components/Details/details.scss
- src/components/DetailsResults/DetailsResults.js
- src/components/DetailsResults/detailsResults.scss
- src/components/Table/TableView.js
- src/components/Table/table.scss
- src/elements/TableLinkCell/tableLinkCell.scss
- src/scss/main.scss
- src/utils/createArtifactsContent.js
- src/utils/createFeatureStoreContent.js
- src/utils/createFunctionsContent.js
- src/utils/createJobsContent.js
- **Artifacts**:  Align 'Name' column in Artifacts and ML function view
-  Change the 'table__item' class name on Overview panel
- "Consumer groups (v3io stream)" is always empty
Jira: [ML-2740](https://jira.iguazeng.com/browse/ML-2740) + [ML-3332](https://jira.iguazeng.com/browse/ML-3332) + [ML-3331](https://jira.iguazeng.com/browse/ML-3331)
Before:
After:
> Fix [Artifacts]  Align 'Name' column in Artifacts and ML function view

- src/components/ArtifactsPreview/ArtifactsPreviewView.js
- src/components/Details/details.util.js
- **Jobs**: make default sort by 'Iter' in 'Results' tab
Jira: [ML-3322](https://jira.iguazeng.com/browse/ML-3322)
> Fix [Jobs] make default sort by 'Iter' in 'Results' tab

- src/utils/createJobsContent.js
- **Workflow**: Use run_type value instead of type in the table
Jira: https://jira.iguazeng.com/browse/ML-3399
After:
> Fix [Workflow] Use `run_type` value instead of `type` in the table

- src/components/Details/details.scss
- **Functions**: Details Pane Header Too Short for Tab Content Width
Jira: https://jira.iguazeng.com/browse/ML-3464
Before: 
After:
> Fix [Functions] Details Pane Header Too Short for Tab Content Width

- src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.scss
- src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.util.js
- **Models Endpoints**: Histogram bars are not in place in the feature analysis tab
Jira: https://jira.iguazeng.com/browse/ML-3510
After:
> Fix [Models Endpoints] Histogram bars are not in place in the feature analysis tab

- src/components/Jobs/ScheduledJobs/ScheduledJobs.js
- src/reducers/notificationReducer.js
- src/utils/createJobsContent.js
- src/utils/getState.js
- src/utils/parseJob.js
- **Schedule**: Scheduled jobs are not shown
Happened if job's `last_run` property was an empty object (`last_run: {}`)
Jira: https://jira.iguazeng.com/browse/ML-3528
> Fix [Schedule] Scheduled jobs are not shown

- package.json
- src/components/Details/details.util.js
- src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
- **Artifacts**: Unable to set empty "Version tag"
Depends on: DRC version [v0.0.37](https://github.com/iguazio/dashboard-react-controls/releases/tag/v0.0.37)
Jira: https://jira.iguazeng.com/browse/ML-3529
After:
> Fix [Artifacts] unable to set empty "Version tag"

- src/components/Details/DetailsTabsContent/DetailsTabsContent.js
- src/components/DetailsPods/DetailsPods.js
- src/components/Jobs/MonitorJobs/monitorJobs.util.js
- src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
- src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
- src/components/Jobs/jobs.util.js
- src/elements/TableProducerCell/TableProducerCell.js
- src/utils/parseJob.js
- **Monitor Jobs**: 'No data to show' for dask job in 'Pods' tab
- After job runs and then node goes down, the pod logs are gone - need clear error message
Jira: https://jira.iguazeng.com/browse/ML-3078
Jira: https://jira.iguazeng.com/browse/ML-3561
After:
> Fix [Monitor Jobs] 'No data to show' for dask job in 'Pods' tab

- src/utils/createArtifactsContent.js
- **Datasets**: When size of an artifact is NA, the UI should display "NA", not "0 Bytes"
Jira: https://jira.iguazeng.com/browse/ML-3594
After:
> Fix [Datasets] When size of an artifact is NA, the UI should display "NA", not "0 Bytes"

- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
- **Feature Sets Panel:** Target path for partition parquet should be taken as Folder
Backported to `1.3.x` from #1673 
Jira: https://jira.iguazeng.com/browse/ML-3619
After:
> Fix [Feature Set] Target path for partition parquet should be taken as Folder `1.3.x`

- src/common/DatePicker/datePicker.scss
- src/common/TimePicker/timePicker.scss
- **Feature Set**: Tooltip icon is overlapping the input
Jira: https://jira.iguazeng.com/browse/ML-3634
Before:
After:
Added padding to the TimePicker component:
> Fix [Feature Set] Tooltip icon is overlapping the input

- src/utils/createArtifactsContent.js
- **Models**: Adjust the Average Latency calculation in model endpoints tab
Backported to `1.3.x` from #1689 
Jira: [ML-3278](https://jira.iguazeng.com/browse/ML-3278)
Before:
After:
> Impl [Models] Adjust the Average Latency calculation in model endpoints tab `1.3.x`

- .github/workflows/build.yaml
As mlrun system tests now run against 1.3.x branch as well, we need UI builds for each commit triggered automatically.
> [CI] Uncomment side branch on build

- src/common/Accordion/Accordion.js
- src/components/ArtifactsPreview/ArtifactsPreview.js
- src/components/ArtifactsPreview/ArtifactsPreviewView.js
- src/components/ArtifactsPreview/artifactsPreview.scss
- src/components/DetailsArtifacts/detailsArtifacts.scss
- src/components/DetailsInputs/DetailsInputs.js
- src/components/DetailsPreview/DetailsPreview.js
- src/elements/PreviewModal/PreviewModal.js
- src/hooks/yaml.hook.js
- src/utils/generateArtifactPreviewData.js
- **Details Preview**: 
- model-spec.yaml should not be shown
- Extra data list should be collapsed for all screens
Jira: https://jira.iguazeng.com/browse/ML-3751
Jira: https://jira.iguazeng.com/browse/ML-3752
After:
> Fix [Details Preview] model-spec.yaml should not be shown && Extra data list should be collapsed for all screens

- src/components/Details/details.util.js
- src/components/FeatureStore/FeatureSets/featureSets.util.js
NOT TO MERGE: MAY REQUIRE ADDITIONAL CHANGES (Engine type from BE)
- **Feature-sets**:  Show the engine type in the feature set overview tab
Jira: https://jira.iguazeng.com/browse/ML-1248
After:
> Impl [Feature-sets] Show the engine type in the feature set overview tab

- src/elements/FunctionCardTemplate/FunctionCardTemplate.js
- src/elements/FunctionCardTemplate/functionCardTemplate.scss
- **Job Wizard**: Batch run, hubs can't select card when click near 'chips'
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/130
**Jira**: https://jira.iguazeng.com/browse/ML-3843
> Fix [Job Wizard] Batch run, hubs can't select card when click near 'chips'

- src/components/ArtifactsActionBar/ArtifactsFilters.js
- src/components/FilterMenuModal/FilterMenuModal.js
- **FiltersModal**: 
1. fix disabled Apply button after changes
2.  Apply and Clear buttons should be disabled after set and delete data in the Labels field
3. Missing placeholder for label field in the 'Filter by' dialog
Jira: https://jira.iguazeng.com/browse/ML-3948, https://jira.iguazeng.com/browse/ML-3959, 
https://jira.iguazeng.com/browse/ML-3958
> Fix [FiltersModal] Fix bugs in filters modal

- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
- src/components/FeatureSetsPanel/FeatureSetsPanelView.js
- **Create Feature Set**: "Partition" checkbox for "External offline" does not take effect
Jira: https://jira.iguazeng.com/browse/ML-3994
> Fix [Create Feature Set] "Partition" checkbox for "External offline" does not take effect

- src/components/ModelsPage/Models/ModelsView.js
- **UI**: The old Version tag should not be deleted after click on 'Edit' button
Jira: https://jira.iguazeng.com/browse/ML-4004
> Fix [UI] The old Version tag should not be deleted after click on 'Edit' button

- src/elements/TableProducerCell/TableProducerCell.js
- **Artifacts**: Model producer name presents for kind =job only
Jira: https://jira.iguazeng.com/browse/ML-4007
> Fix [Artifacts] Model producer name presents for kind =job only

- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
- **Feature sets panel**: Fix targets behavior in passthrough mode
1. The "Offline" target should be unchecked and greyed in passthrough mode
2. Unexpected data required when passthrough is checked after setting offline targets
3. The "Online" target should be unchecked in passthrough mode
Jira: https://jira.iguazeng.com/browse/ML-4043, https://jira.iguazeng.com/browse/ML-4058, 
https://jira.iguazeng.com/browse/ML-4065
> Fix [Feature sets panel] targets behavior in passthrough mode

- src/components/ProjectsPage/Projects.js
- **Projects**: Use single projects request
- Removed unnecessary request for retrieving project names.
- Added the `format=minimal` parameter back to the `projects` request.
Jira: [ML-4078](https://jira.iguazeng.com/browse/ML-4078)
> Fix [Projects] Use single `projects` request

- src/actions/projects.js
- **UI**: Wrong navigation to the "Job and workflow"from new Project
Backported to `1.4.x` from #1804 
Jira: https://jira.iguazeng.com/browse/ML-4189
> Fix [UI] Wrong navigation to the "Job and workflow"from new Project `1.4.x`

- src/components/ArtifactsPreview/ArtifactsPreview.js
- src/components/ArtifactsPreview/ArtifactsPreviewView.js
- src/components/DetailsPreview/DetailsPreview.js
- src/components/DetailsResults/DetailsResults.js
- src/scss/main.scss
- src/utils/createArtifactPreviewContent.js
- **UI**: Preview table is hidden from view
Backported to `1.4.x` from #1806 
Jira: [ML-4193](https://jira.iguazeng.com/browse/ML-4193)
Before:
After:
> Fix [UI] Preview table is hidden from view `1.4.x`

- src/components/ArtifactsActionBar/ArtifactsFilters.js
- src/components/ArtifactsActionBar/artifactsFilters.scss
- src/components/FilterMenuModal/FilterMenuModal.js
- src/components/FilterMenuModal/filterMenuModal.scss
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- **Batch run**: Buttons are missing in the categories-list popup dialog
- Added a dynamic filter header
- Added a "Clear" button 
Jira: [ML-4268](https://jira.iguazeng.com/browse/ML-4268)
Before:
After:
> Fix [Batch run] Buttons are missing in the categories-list popup dialog

- src/components/JobWizard/JobWizard.js
- **Batch Inference**: last tab buttons are not as per requirement
Jira: [ML-4287](https://jira.iguazeng.com/browse/ML-4287)
After:
> Fix [Batch Inference] last tab buttons are not as per requirement

- src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
- src/elements/TableCell/TableCell.js
- **UI**: models/datasets - preview icon tooltip says "Artifact Preview"
Related to #1834 
Jira: [ML-4305](https://jira.iguazeng.com/browse/ML-4305)
After:
> Fix [UI] models/datasets - preview icon tooltip says "Artifact Preview"

- src/elements/FormVolumesTable/formVolumesTable.util.js
- **Batch run**: Incorrect tip message in Access Key form field during setting the resources in Batch Run
Jira: [ML-4310](https://jira.iguazeng.com/browse/ML-4310)
Before:
After:
> Fix [Batch run] Incorrect tip message in Access Key form field during setting the resources in Batch Run

- src/elements/FormResourcesUnits/FormResourcesUnits.js
- **Batch run**: No validation for a negative CPU value during setting the resources in Batch Run
Depends on: https://github.com/iguazio/dashboard-react-controls/pull/151
Jira: [ML-4308](https://jira.iguazeng.com/browse/ML-4308)
Before:
After:
> Fix [Batch run] No validation for a negative CPU value during setting the resources in Batch Run

- src/components/JobWizard/JobWizardSteps/JobWizardResources/JobWizardResources.js
- **Batch run**: incorrect "Add a node" button name in "Node selection" section of batch run
Jira: [ML-4342](https://jira.iguazeng.com/browse/ML-4342)
> Fix [Batch run] incorrect "Add a node" button name in "Node selection" section of batch run

- src/elements/FormVolumesTable/formVolumesTable.util.js
- **Batch Run**: The Container and Resource Path fields for V3IO volume should not be mandatory
Jira: [ML-4355](https://jira.iguazeng.com/browse/ML-4355)
Before:
After:
> Fix [Batch Run] The Container and Resource Path fields for V3IO volume should not be mandatory

- src/components/DetailsResults/DetailsResults.js
- **Jobs**: UI does not show boolean result in "Monitor Jobs" -> "Results"
Jira: [ML-4365](https://jira.iguazeng.com/browse/ML-4365)
Before:
After:
> Fix [Jobs] UI does not show boolean result in "Monitor Jobs" -> "Results"

- src/components/Datasets/Datasets.js
- src/components/Files/Files.js
- src/components/ModelsPage/Models/Models.js
- **UI** expand button is visible when change project on the Datasets, Artifacts and Models pages
Jira: https://jira.iguazeng.com/browse/ML-4121
After:
> Fix [UI] expand button is visible when change project on the Datasets, Artifacts and Models pages

- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
- src/constants.js
- **Feature set**: inaccurate default path for redis
Related to #1868 
Jira: [ML-4277](https://jira.iguazeng.com/browse/ML-4277)
After:
> Fix [Feature set] minor Redis path fix

- src/components/JobWizard/JobWizard.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- src/elements/FunctionsPanelCode/FunctionsPanelCode.js
- **Batch Run**: The "handler"/"method" option is missing in UI in case the function has not "entry_points"
Fixed:
- In "Create new Function": `default_handler`  = "handler" by default if no other value is supplied on **Submit**.
- In "Batch run": show by default **list** of `entry_points`, if non exist show a **text field** of function `default_handler` or "handler" if non exists.
Jira: [ML-4446](https://jira.iguazeng.com/browse/ML-4446)
Before:
After:
> Fix [Batch Run] The "handler"/"method" option is missing in UI in case the function has not "entry_points"

- src/components/DetailsResults/DetailsResults.js
- **Batch Run**: The results empty for 'random' strategy with predefined maxerror param
Jira: [ML-4528](https://jira.iguazeng.com/browse/ML-4528)
Before:
After:
> Fix [Batch Run] The results empty for 'random' strategy with predefined maxerror param

- src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
- **Real Time Pipelinesall**: child funcs appear in the table and clicking on any one of them opens the same graph
Jira: https://jira.iguazeng.com/browse/ML-4000
Before:
After:
> Fix [Real Time Pipelines] all child funcs appear in the table and clicking on any one of them opens the same graph

- src/common/Chart/MlChart.js
- src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.util.js
- **Features Analysis**: Large float values are not presented
Backported to `1.5.x` from #1923 
Jira: https://jira.iguazeng.com/browse/ML-4445
> Fix [Features Analysis] Large float values are not presented `1.5.x`

- src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.js
- **Model endpoint**: UI should display drift threshold and drift actual value
Jira: https://jira.iguazeng.com/browse/ML-4571
> Impl [Model endpoint] UI should display drift threshold and drift actual value

- src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.js
- **Model endpoint**: UI should display drift threshold and drift actual value
Backported to `1.5.x` from #1925 
Jira: https://jira.iguazeng.com/browse/ML-4571
> Impl [Model endpoint] UI should display drift threshold and drift actual value `1.5.x`

- src/components/JobWizard/JobWizard.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- src/scss/main.scss
- **Batch run**: Hide 'Build image' option, add message for 'Image name'
1. Hide 'Build a new image' option for 'Batch inference' and 'Batch run'
2. Add an explanation message for 'Image name' input
Depends On: hhttps://github.com/iguazio/dashboard-react-controls/pull/178
Backported to `1.5.x` from #1927 
Jira: [ML-4606](https://jira.iguazeng.com/browse/ML-4606)
> Fix [Batch run] Hide 'Build image' option, add message for 'Image name' `1.5`

- src/components/JobWizard/JobWizard.util.js
- src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
- **Batch run**: Changed parameter types aren't saved for rerun
Backported to `1.5.x` from #1931 
Jira: [ML-4612](https://jira.iguazeng.com/browse/ML-4612)
> Fix [Batch run] Changed parameter types aren't saved for rerun `1.5`

- src/components/Jobs/ScheduledJobs/ScheduledJobs.js
- src/utils/parseJob.js
- **Scheduled workflow**: Workflow (and not job) should have different icon and minimal editing
Backported to `1.5.x` from #1935 
Jira: [ML-4628](https://jira.iguazeng.com/browse/ML-4628)
Before:
After:
> Fix [Scheduled workflow] Workflow (and not job) should have different icon and minimal editing `1.5.x`

- src/components/Details/details.util.js
- **Jobs**: Batch Model Endpoint => overview - model, function and Feature set links are broken
Backported to `1.5.x` fron #1937 
Jira: https://jira.iguazeng.com/browse/ML-4569
> Fix [Jobs] Batch Model Endpoint => overview - model, function and Featureset links are broken `1.5.x`

- src/components/Details/details.util.js
- src/utils/createArtifactsContent.js
- src/utils/generateFunctionDetailsLink.js
- src/utils/parseUri.js
- **Model Endpoints**: Invalid Function URI link in model endpoints screen
Backported to `1.5.x` from #1939 
https://jira.iguazeng.com/browse/ML-4637
> Fix [Model Endpoints] Invalid Function URI link in model endpoints screen `1.5.x`

- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
- **Feature set**:  The target store path is incorrect `1.5.x`
Backported to `1.5.x` from #1942 
Jira: https://jira.iguazeng.com/browse/ML-4373
> Fix [Feature set] the target store path is incorrect `1.5.x`

- src/components/JobWizard/JobWizard.util.js
- src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
- **Batch run**: Mandatory parameters should be selected `1.5.x`
Backported to `1.5.x` from #1946 
Jira: [ML-4657](https://jira.iguazeng.com/browse/ML-4657)
> Fix [Batch run] Mandatory parameters should be selected `1.5`

- src/components/JobWizard/JobWizard.util.js
- src/components/JobsPanel/jobsPanel.util.js
- **Batch run**Ж Remove the '$' from Batch Inference version presentation
Backported to `1.5.x` from #1949 
Jira: https://jira.iguazeng.com/browse/ML-4591
> Fix [Batch run] Remove the '$' from Batch Inference version presentation `1.5.x`

- src/components/JobWizard/JobWizard.util.js
- **Batch run**: Batch run labels are incorrect `1.5.x`
Backported to `1.5.x` from #1952 
Jira: [ML-4663](https://jira.iguazeng.com/browse/ML-4663)
> Fix [Batch run] Batch run labels are incorrect `1.5`

- src/components/DetailsInputs/DetailsInputs.js
- src/components/JobWizard/JobWizard.util.js
- **Batch run**:  inputs issues 
1. when using batch run wizard on a stored function with an empty input, the UI pass the empty input with a value similar to the key
2. Inputs are not displayed in the inputs job tab if there has been an error with a previous input store path
Backported to `1.5.x` from #1961 
Jira: https://jira.iguazeng.com/browse/ML-4659, https://jira.iguazeng.com/browse/ML-4658, https://jira.iguazeng.com/browse/ML-4657
> Fix [Batch run] inputs issues `1.5.x`

- src/components/Datasets/Datasets.js
- src/components/ModelsPage/Models/Models.js
- **Datasets, Models** :Filter by tag isn't performed when version tag was edited
Backported to 1.5.x from #1963 
Jira: https://jira.iguazeng.com/browse/ML-4158
> Fix [Datasets and Models] Filter by tag isn't performed when version tag was edited `1.5.x`

- src/components/Details/details.scss
- **Jobs**: Missing scroll bar in jobs UI logs
Jira: [ML-4689](https://jira.iguazeng.com/browse/ML-4689)
After:
> Fix [Jobs] Missing scroll bar in jobs UI logs

- src/components/JobWizard/JobWizard.util.js
- **Batch run**: Mandatory parameters should be selected v2
Backported to `1.5.x` from #1968 
Jira: [ML-4661](https://jira.iguazeng.com/browse/ML-4661)
> Fix [Batch run] Mandatory parameters should be selected v2 `1.5.x`

- src/actions/details.js
- src/api/details-api.js
- src/hooks/usePods.hook.js
- **Jobs**: Monitor job pods view use too broad api call
Jira: https://jira.iguazeng.com/browse/ML-4693
> Fix [Jobs] Monitor job pods view use too broad api call

- src/actions/details.js
- src/api/details-api.js
- src/hooks/usePods.hook.js
- **Jobs**: Monitor job pods view use too broad api call
Backported to `1.5.x` from #1976 
Jira: https://jira.iguazeng.com/browse/ML-4693
> Fix [Jobs] Monitor job pods view use too broad api call `1.5.x`

- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- **Batch run**: Fixed labels length
Backported to `1.5.x` from #1982 
Jira: https://jira.iguazeng.com/browse/ML-4644
> Fix [Batch run] Labels issues on Bach run wizard `1.5.x`

- src/actions/projects.js
- src/components/ProjectsPage/Projects.js
- src/components/ProjectsPage/projectsData.js
- **Projects**: MLRun fails to delete project on the backend, but shows success in UI
Backported to `1.5.x` from #1836 
Jira: https://jira.iguazeng.com/browse/ML-4188
> Fix [Projects] MLRun fails to delete project on the backend, but shows success in UI `1.5.x`

- src/components/Details/details.scss
- src/components/Table/TableView.js
- src/components/Table/table.scss
- **Consumer groups**: Table width
Backported to `1.5.x` from #1986 
Jira: https://jira.iguazeng.com/browse/ML-4695
> Fix [Consumer groups] Table width `1.5.x`

- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
- **Feature Sets**: Passthrough popup appears
Backported to `1.5.x` from #1991 
Jira:https://jira.iguazeng.com/browse/ML-4154
> Fix [Feature Sets] Passthrough popup appears `1.5.x`

- src/components/Jobs/jobs.util.js
- **Jobs**: missing error reason when job abort fails
Backported to `1.5.x` from #1995 
Jira: [ML-4732](https://jira.iguazeng.com/browse/ML-4732)
Before:
After:
> Fix [Jobs] missing error reason when job abort fails `1.5.x`

- src/common/Notification/Notification.js
- src/common/Notification/NotificationView.js
- src/common/Notification/notificationView.scss
- **Notifications**: Add closing/removing manually
Backported to `1.5.x` from #1996 
Jira: [ML-4743](https://jira.iguazeng.com/browse/ML-4743)
After:
> Impl [Notifications] Add closing/removing manually `1.5.x`

- src/components/Jobs/jobs.util.js
- **Jobs**: missing error reason when job abort fails
Jira: [ML-4732](https://jira.iguazeng.com/browse/ML-4732)
Before:
After:
> Fix [Jobs] missing error reason when job abort fails

- src/common/TargetPath/targetPath.util.js
- src/constants.js
- src/elements/FormDataInputsTable/FormDataInputsRow/FormDataInputsRow.js
- **Batch inference**: The model_path input only supports store paths
Backported to `1.5.x` from #2012 
Jira: https://jira.iguazeng.com/browse/ML-4697
> Fix [Batch inference] The model_path input only supports store paths `1.5.x`

- src/actions/projects.js
- src/elements/ProjectDataCard/ProjectDataCard.js
- src/elements/ProjectJobs/ProjectJobs.js
- **Project Monitor**: mlrun long run - GET to mlrun/api/v1/runs?.. fails with 504
- Filter results by setting `start_time_from` 2 days ago
Jira: [ML-4756](https://jira.iguazeng.com/browse/ML-4756)
Before:
After:
> Fix [Project Monitor] mlrun long run - GET to mlrun/api/v1/runs?.. fails with 504

- src/actions/projects.js
- src/elements/ProjectDataCard/ProjectDataCard.js
- src/elements/ProjectJobs/ProjectJobs.js
- **Project Monitor**: mlrun long run - GET to mlrun/api/v1/runs?.. fails with 504
- Filter results by setting `start_time_from` 2 days ago
Backported to `1.5.x` from #2023 
Jira: [ML-4756](https://jira.iguazeng.com/browse/ML-4756)
Before:
After:
> Fix [Project Monitor] mlrun long run - GET to mlrun/api/v1/runs?.. fails with 504 `1.5.x`

- src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
- **Feature Store**: inaccurate validation message for redis
Jira: [ML-4868](https://jira.iguazeng.com/browse/ML-4868)
After:
> Fix [Feature Store] inaccurate validation message for redis

- src/actions/functions.js
- src/common/NameFilter/nameFilter.scss
- src/common/TargetPath/targetPath.util.js
- src/components/ArtifactsActionBar/ArtifactsActionBar.js
- src/components/Datasets/Datasets.js
- src/components/Datasets/DatasetsView.js
- src/components/Datasets/datasets.util.js
- src/components/Files/FilesView.js
- src/components/JobWizard/JobWizard.js
- src/components/JobWizard/JobWizard.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
- src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/jobWizardFunctionSelection.util.js
- src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
- src/components/ModelsPage/Models/Models.js
- src/components/ModelsPage/Models/ModelsView.js
- src/components/Project/ProjectOverview/ProjectOverview.util.js
- src/scss/main.scss
- src/utils/generateTemplatesCategories.js
- src/utils/panelPathScheme.js
- **Batch Run**: Model Training
Jira: https://jira.iguazeng.com/browse/ML-1855
After:
> Impl [Batch Run] Model Training

- src/httpClient.js
- **API**: browser caching
Backported to `1.5.x` from #2070 
Jira: [ML-4960](https://jira.iguazeng.com/browse/ML-4960)
> Fix [API] browser caching `1.5.x`

- src/components/FeatureStore/featureStore.scss
- src/components/Table/TableView.js
- src/components/Table/table.scss
- src/elements/FeaturesTablePanel/featuresTablePanel.scss
- **Features**: Incorrect panel view when adding a feature
Backported to `1.5.x` from #2064 
Jira: [ML-4898](https://jira.iguazeng.com/browse/ML-4898)
Before:
After:
> Fix [Features] incorrect panel view when adding a feature `1.5.x`

- src/common/Breadcrumbs/breadcrumbs.util.js
- src/common/ProjectDetailsHeader/ProjectDetailsHeader.js
- src/common/ProjectDetailsHeader/ProjectDetailsHeader.scss
- src/components/Project/ProjectOverview/ProjectOverview.js
- src/components/ProjectsPage/ProjectsView.js
- src/components/ProjectsPage/projects.scss
- **Quick actions**: Add breadcrumbs to Quick actions page
Jira: [ML-4990](https://jira.iguazeng.com/browse/ML-4990)
Before:
After:
> Fix [Quick actions] Add breadcrumbs to Quick actions page

- src/utils/generateUsageSnippets.js
- **UI**: feature set usage example - missing import command & project value
Jira: [ML-4944](https://jira.iguazeng.com/browse/ML-4944)
> Fix [UI] feature set usage example - missing import command & project value

- src/components/FeatureSetsPanel/FeatureSetsPanelSchema/FeatureSetsPanelSchemaView.js
- src/components/FeatureSetsPanel/FeatureSetsPanelSchema/featureSetsPanelSchema.scss
- **Feature Store**: Capitalize the first letter of the sentence in the Schema description.
Jira: [ML-5034](https://jira.iguazeng.com/browse/ML-5034)
> Fix [Feature Store] Capitalize the first letter of the sentence in the Schema description.

- src/common/Breadcrumbs/Breadcrumbs.js
- src/elements/TableLinkCell/tableLinkCell.scss
- **Breadcrumbs** page crash when project list is not loaded
- Navigate to "Artifacts" with long response time, when receiving popup "Response is too large"
- Try to open projects list from the breadcrumbs first arrow
Result: Page crash on "selectedOptionEl"
- Fix table name column UID row width
> Fix [Breadcrumbs] page crash when project list is not loaded

- src/common/Input/input.scss
- **UI**: Create feature set - schema entities tool tip is not red
Jira: [ML-4972](https://jira.iguazeng.com/browse/ML-4972)
Before:
After:
> Fix [UI] create feature set - schema entities tool tip is not red

- src/components/FunctionsPanel/FunctionsPanel.js
- **Functions Panel**: clicking on deploy should not try to build a new image
Jira: https://jira.iguazeng.com/browse/ML-5048
> Fix [Functions Panel] clicking on deploy should not try to build a new image

- src/components/JobWizard/JobWizardSteps/JobWizardResources/JobWizardResources.js
- src/elements/FormVolumesTable/FormVolumesTable.js
- **UI**: Add the 'data-testid' for 'Add volume' and 'Add node selector' buttons
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/214
Jira: [ML-5057](https://jira.iguazeng.com/browse/ML-5057)
> Fix [UI] add the 'data-testid' for 'Add volume' and 'Add node selector' buttons

- src/components/ProjectSettings/projectSettings.util.js
- **Project Settings**: "Members" tab is not present for user with "project security admin" policy   
Jira: https://jira.iguazeng.com/browse/ML-5095
> Fix [Project Settings] "Members" tab is not present for user with "project security admin" policy

- src/components/Datasets/Datasets.js
- src/components/ModelsPage/Models/Models.js
- **Breadcrumbs**: The projects pages dropdown doesn't open up after model/dataset tag editing
Jira: [ML-4777](https://jira.iguazeng.com/browse/ML-4777)
> Fix [Breadcrumbs] The projects pages dropdown doesn't open up after model/dataset tag editing

- src/utils/parseWorkflows.js
- **Workflows**: Cannot read properties of null (reading 'toLowerCase')' on attempt to filter workflows by status "All"
Jira: [ML-5384](https://jira.iguazeng.com/browse/ML-5384)
> Fix [Workflows] Cannot read properties of null (reading toLowerCase) on attempt to filter workflows by status "All"

- src/components/JobWizard/JobWizard.util.js
- src/utils/createJobsContent.js
- src/utils/parseJob.js
- **Monitor jobs**: Unnecessary context: parameter presents in UI
Jira: [ML-4780](https://jira.iguazeng.com/browse/ML-4780)
Before:
After:
> Fix [Monitor jobs] Unnecessary context: parameter presents in UI

- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/files.feature
- tests/features/projectHomePage.feature
- tests/features/projectsPage.feature
- tests/mockServer/mock.js
* Updated tests for Train model wizard
- Jira: ML-5328, ML-5234, ML-5333
* Updated tests according to requirements
- changed uniqueness validation and for Register artifact, Register dataset
- update messages for Register artifact, Register dataset
- updated mock server functions related to edit and delete tags acording to new implementation
- removed the label value validation rules Batch Run wizard
- changed message Tag to Version Tag feature store, feature vector
- added check label validation rules on Create new project pop-up
- Jira: ML-4927, ML-4916, ML-5440, ML-4835
---------
> Impl [Tests] QA Sprint 156 done

- src/components/Project/ProjectMonitorView.js
- src/components/Project/project.scss
- src/elements/ProjectSummaryCard/ProjectSummaryCard.js
- **Project monitoring**: misleading artifacts counter in project monitoring screen
Jira: https://jira.iguazeng.com/browse/ML-5312
> Fix [Project monitoring] misleading artifacts counter in project monitoring screen

- src/common/TargetPath/targetPath.util.js
- **Batch Run**: Blank project screen after setting model target path
Backported to `1.6.x` from #2226 
Jira: [ML-5591](https://jira.iguazeng.com/browse/ML-5591)
> Fix [Batch Run] Blank project screen after setting model target path `1.6.x`

- src/components/JobWizard/JobWizard.util.js
- **Batch Run**: job pod fails to mount fuse when ran via UI
Backported to `1.6.x` from #2237 
Jira: https://jira.iguazeng.com/browse/ML-5599
> Fix [Batch Run] job pod fails to mount fuse when ran via UI `1.6.x`

- src/utils/createArtifactsContent.js
- **Models**: unable to navigate to additional metrics (+)
Backported to `1.6.x` from #2250 
Jira: https://jira.iguazeng.com/browse/ML-5663
> Fix [Models] unable to navigate to additional metrics (+) `1.6.x`

- src/components/Jobs/MonitorJobs/MonitorJobs.js
- src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
- **Jobs**: change Abort Job confirm message
Backported to `1.6.x` from #2246 
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/233
Jira: https://jira.iguazeng.com/browse/ML-4857
After:
> Fix [Jobs] change Abort Job confirm message `1.6.x`

- src/utils/getNoDataMessage.js
- **General**: text on data query when there is no relevant data
Backported to `1.6.x` from #2265 
Jira: https://jira.iguazeng.com/browse/ML-5308
> Fix [General] text on data query when there is no relevant data `1.6.x`

- src/components/Datasets/Datasets.js
- **Datasets**: request is not sent when changing project via breadcrumbs
Backported to `1.6.x` from #2267 
Jira: https://jira.iguazeng.com/browse/ML-5683
> Fix [Datasets] request is not sent when changing project via breadcrumbs `1.6.x`

- src/elements/TableProducerCell/TableProducerCell.js
- **Datasets**: tooltip is not shown for short producer names
Jira: https://jira.iguazeng.com/browse/ML-5431
> Fix [Datasets] tooltip is not shown for short producer names

- src/elements/TableLinkCell/TableLinkCell.js
- src/utils/createJobsContent.js
- **Schedule Jobs**: Last run link is missing after running a scheduled job
Jira: https://jira.iguazeng.com/browse/ML-5672
> Fix [Schedule Jobs] Last run link is missing after running a scheduled job

- src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
- **Monitor Workflows**: The 'Created At' filter doesn't keep the selected type
Jira: https://jira.iguazeng.com/browse/ML-5787
> Fix [Monitor Workflows] The 'Created At' filter doesn't keep the selected type

- src/elements/MembersPopUp/MembersPopUp.js
- **Project Settings**: "Invite New Members" does not return full list of users
Backported to `1.6.x` from #2331 
Jira: https://iguazio.atlassian.net/browse/ML-5907
> Fix [Project Settings] "Invite New Members" does not return full list of users `1.6.x`

- src/elements/MembersPopUp/MembersPopUp.js
- **Project Settings**: "Invite New Members" does not return full list of users
Jira: https://iguazio.atlassian.net/browse/ML-5907
> Fix [Project Settings] "Invite New Members" does not return full list of users

- src/common/TabsSlider/tabsSlider.scss
- src/elements/ContentMenu/contentMenu.scss
- src/scss/main.scss
- **UI**: Filters row broken in small resolutions
Jira: [ML-5962](https://iguazio.atlassian.net/browse/ML-5962)
Before: 
After:
[ML-5962]: https://iguazio.atlassian.net/browse/ML-5962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [UI] Filters row broken in small resolutions

- src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
- **Project settings**: project owner changes to the last user in the list instead of the selected user
Backported to `1.6.2` from #2326 
Jira: https://iguazio.atlassian.net/browse/ML-5808
> Fix [Project settings] project owner changes to the last user in the list instead of the selected user `1.6.2`

- src/elements/MembersPopUp/MembersPopUp.js
- **Project Settings**: "Invite New Members" does not return full list of users
Backported to `1.6.2` from #2331 
Jira: https://iguazio.atlassian.net/browse/ML-5907
> Fix [Project Settings] "Invite New Members" does not return full list of users `1.6.2`

- src/utils/generateMonitoringData.js
**Projects, Monitoring container**: Jobs with 'aborted' status are not accounted for any of the the counters statuses
Jira: [ML-6097](https://iguazio.atlassian.net/browse/ML-6097)
[ML-6097]: https://iguazio.atlassian.net/browse/ML-6097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Projects, Monitoring container] Jobs with 'aborted' status are not accounted for any of the the counters statuses

- src/components/JobWizard/JobWizard.util.js
- **Batch Run**: Default artifact path not sourced from frontend-spec
Backported to `1.6.3` from #2385 
Jira: https://iguazio.atlassian.net/browse/ML-6094
> Fix [Batch Run] Default artifact path not sourced from frontend-spec `1.6.x`

- src/elements/PreviewModal/PreviewModal.js
- **UI**: Missing header columns in the artifacts preview screens
Jira: [ML-5719](https://iguazio.atlassian.net/browse/ML-5719)
Before:
After:
[ML-5719]: https://iguazio.atlassian.net/browse/ML-5719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [UI] Missing header columns in the artifacts preview screens

- package.json
- **Node Selector**: Different naming convention for Node Selector key between Nuclio and Project setting/ Mlrun func
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/270
Jira: [ML-6303](https://iguazio.atlassian.net/browse/ML-6303)
[ML-6303]: https://iguazio.atlassian.net/browse/ML-6303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Node Selector] Different naming convention for Node Selector key between Nuclio and Project setting/ Mlrun func

- src/common/DatePicker/DatePicker.js
- src/components/FilterMenu/FilterMenu.js
- src/components/Jobs/MonitorJobs/MonitorJobs.js
- src/elements/JobsTable/JobsTable.js
- src/reducers/filtersReducer.js
- **Jobs and workflows**: filter by time does not correctly mark selected option
Jira: https://iguazio.atlassian.net/browse/ML-6186
> Fix [Jobs and workflows] filter by time does not correctly mark selected option

- src/components/DetailsArtifacts/DetailsArtifacts.js
- **Jobs and Workflows**: hide 'No data to show' message during artifacts loading
Backported to `1.6.x` from #2455 
Jira: https://iguazio.atlassian.net/browse/ML-6470
> Fix [Jobs and Workflows] hide 'No data to show' message during artifacts loading `1.6.x`

- src/components/JobWizard/JobWizard.util.js
- **Jobs**: Run status contains full artifacts in response for api/v1/run/{project}/{uid}
Backported to `'1.6.x` from #2457 
Jira: https://iguazio.atlassian.net/browse/ML-6472
> Fix [Jobs] Run status contains full artifacts in response for api/v1/run/{project}/{uid} `1.6.x`

- package.json
- tests/features/MLFunction.feature
- tests/features/artifacts.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/page-objects.js
- tests/features/common/page-objects/info-pane.po.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/models.po.js
- tests/features/common/page-objects/project-settings.po.js
- tests/features/common/page-objects/project.po.js
- tests/features/common/page-objects/projects.po.js
- tests/features/datasets.feature
- tests/features/featureStore.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/models.feature
- tests/features/projectMonitoring.feature
- tests/features/projectSettings.feature
- tests/features/projectsPage.feature
- tests/features/quickActions.feature
- tests/features/step-definitions/steps.js
- tests/features/step-definitions/table.steps.js
- changed description counter selector on Feature Vector
- changed selector for remove button Run Details label table on Batch Run
- changed command column to Code Entry Point on ML Functions, Jobs detail panel due to ML-4977
- added filtering by status due to lazy loading on Monitor Jobs tab due to ML-5092
- added visibility of Recent text on Project Monitoring page
- changed selector for Sorted by filter on Models
- added preview table headers - ML-5719
- added 'Overwrite artifact?' popup - ML-6059
- added step turn Off MLRun CE mode - ML-6111
- changed Default artifact path - ML-6094
- changed selector for remove button in label table on Projects Settings General tab
- changed selector for Close button in label table on create Project popup
- …
> QA Sprint 163 done

- src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.scss
- **Feature Sets Panel**: Tooltip warning icon displays over the input text
Jira: https://iguazio.atlassian.net/browse/ML-5838
> Fix [Feature Sets Panel] Tooltip warning icon displays over the input text

- src/components/DetailsArtifacts/DetailsArtifacts.js
- **Cross projects**: No data and error 403 :Not allowed to read resource/projects/undefined')" on Jobs Artifacts screen
Jira: https://iguazio.atlassian.net/browse/ML-6681
> Fix [Cross projects] No data and error 403 :Not allowed to read resource/projects/undefined')" on Jobs Artifacts screen

- src/hooks/usePods.hook.js
- **Cross projects**: The "MLRunAccessDeniedError('Not allowed to read resource /projects/undefined')" on the  Jobs / Workflows  Overview tab
Jira: https://iguazio.atlassian.net/browse/ML-6680
> Fix [Cross projects]  The "MLRunAccessDeniedError('Not allowed to read resource /projects/undefined')" on the  Jobs / Workflows  Overview tab

- src/components/DetailsArtifacts/DetailsArtifacts.js
- **Jobs**: Get artifacts from the run status instead of using producer URI
Backported to `1.6.x` from #2519 
Jira: https://iguazio.atlassian.net/browse/ML-6779
> Fix [Jobs] Get artifacts from the run status instead of using producer URI `1.6.x`

- src/components/DetailsArtifacts/DetailsArtifacts.js
- **Jobs**: Get artifacts from the run status instead of using producer URI - updated dependency
Backported to `1.6.x` from #2519 
Jira: https://iguazio.atlassian.net/browse/ML-6779
> Fix [Jobs] Get artifacts from the run status instead of using producer URI - updated dependency `1.6.x`

- src/scss/main.scss
- src/utils/getState.js
- **Functions**: missing 'building' state indication for ML function
Jira: https://iguazio.atlassian.net/browse/ML-6645
> Fix [Functions] missing 'building' state indication for ML function

- src/elements/ProjectTable/ProjectTable.js
- **Project monitoring**: UI failure when navigating to "Project monitoring" page - TypeError: e[a].value.startsWith is not a function
Related to: https://github.com/mlrun/ui/pull/2517
Jira: https://iguazio.atlassian.net/browse/ML-6810
> Fix [Project monitoring] UI failure when navigating to "Project monitoring" page - TypeError: e[a].value.startsWith is not a function

- src/api/artifacts-api.js
- **UI**: Limit number of artifacts shown in the artifact screen
- In `1.7.0` UI + BE will Implement a different solution
Jira: https://iguazio.atlassian.net/browse/ML-6866
> Fix [UI] Limit number of artifacts shown in the artifact screen `1.6.x`

- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
- **UI**: Partition by "project_and_name" instead of "name" when list runs
Jira: https://iguazio.atlassian.net/browse/ML-6966
> Fix [UI] partition by "project_and_name" instead of "name" when list runs

- src/components/ProjectsPage/ProjectsMonitoring/ProjectsMonitoring.js
- src/elements/ProjectsMonitoringCounters/JobsCounters.js
- src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
- src/utils/generateMonitoringData.js
- **Project Monitoring**: Change general status indicator title
Jira: [ML-6900](https://iguazio.atlassian.net/browse/ML-6900)
Before:
After:
[ML-6900]: https://iguazio.atlassian.net/browse/ML-6900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Project Monitoring] change general status indicator title

- src/api/artifacts-api.js
- src/components/Datasets/datasets.util.js
- src/components/Files/files.util.js
- src/components/ModelsPage/Models/models.util.js
- src/elements/DeleteArtifactPopUp/DeleteArtifactPopUp.js
- src/reducers/artifactsReducer.js
- src/utils/getUniqueIdentifier.js
- src/utils/handleDeleteArtifact.js
- tests/mockServer/data/artifacts.json
- tests/mockServer/mock.js
- **Artifacts**: Delete artifact without a tag
Jira: https://iguazio.atlassian.net/browse/ML-7122
> Impl [Artifacts] Delete artifact without a tag

- src/utils/createArtifactsContent.js
- **Models**: misleading "Uptime" column name in "Model Endpoints" screen
Jira: [ML-7637](https://iguazio.atlassian.net/browse/ML-7637)
[ML-7637]: https://iguazio.atlassian.net/browse/ML-7637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Models] misleading "Uptime" column name in "Model Endpoints" screen

- src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
- **Model endpoints**: sort by function/name does not take effect
Jira: [ML-7634](https://iguazio.atlassian.net/browse/ML-7634)
[ML-7634]: https://iguazio.atlassian.net/browse/ML-7634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Model endpoints] sort by function/name does not take effect

- src/elements/ProjectCard/ProjectCardView.js
- **Projects**: add unique class name instead of removed project-card__labels
Jira: [ML-7720](https://iguazio.atlassian.net/browse/ML-7720)
[ML-7720]: https://iguazio.atlassian.net/browse/ML-7720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Projects] add unique class name instead of removed project-card__labels

- src/components/ProjectsPage/projects.util.js
- src/elements/ProjectsMonitoringCounters/ScheduledJobsCounters.js
- src/utils/generateMonitoringData.js
- **Projects**: Jobs monitoring 'scheduled' with type=All is inaccessible without filter
Jira: [ML-7745](https://iguazio.atlassian.net/browse/ML-7745)
Before:
After:
[ML-7745]: https://iguazio.atlassian.net/browse/ML-7745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Impl [Projects] Jobs monitoring 'scheduled' with type=All is inaccessible without filter

- src/common/ReactFlow/mlReactFlow.util.js
- **Real time pipelines**: UI crash "Cannot destructure property width of e.__rf as it is undefined." when clicking on real-time pipeline name
Jira: https://iguazio.atlassian.net/browse/ML-7780
> Fix [Real time pipelines] UI crash `Cannot destructure property width of e.__rf as it is undefined` when clicking on real-time pipeline name

- src/components/Jobs/jobs.util.js
- src/elements/JobsTable/jobsTable.util.js
- **Jobs and workflows**: Hide “node selector”from details view when the function is of type “Dask”
Jira: [ML-7794](https://iguazio.atlassian.net/browse/ML-7794)
[ML-7794]: https://iguazio.atlassian.net/browse/ML-7794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Jobs and workflows] Hide “node selector” from details view when the function is of type “Dask”

- src/components/FeatureStore/FeatureSets/FeatureSets.js
- **Feature sets**: project name is missing from the request url when navigating between feature sets
Jira: https://github.com/mlrun/ui/pull/2726
> Fix [Feature sets] project name is missing from the request url when navigating between feature sets

- src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
- **Feature vectors**: project name is missing from the request for tags
Backported to `1.7.x` from #2766 
Jira: https://iguazio.atlassian.net/browse/ML-7839
> Fix [Feature vectors] project name is missing from the request for tags `1.7.x`

- src/components/DetailsArtifacts/DetailsArtifacts.js
-  **Job Artifacts**: Project name is missing from the request url after click on Artifacts tab `1.7.x`
Backported to `1.7.x` from #2776 
Jira: https://iguazio.atlassian.net/browse/ML-7971
> Fix [Job Artifacts] project name is missing from the request url after click on Artifacts tab `1.7.x`

- src/components/DetailsArtifacts/DetailsArtifacts.js
-  **Job Artifacts**: Project name is missing from the request url after click on Artifacts tab
Jira: https://iguazio.atlassian.net/browse/ML-7971
> Fix [Job Artifacts] project name is missing from the request url after click on Artifacts tab

- src/index.js
- **CE**: Project link is broken fails to browse to project UI `1.7.x`
Backported to `1.7.x` from #2779 
Jira: https://iguazio.atlassian.net/browse/ML-7939
> Fix [CE] project link is broken fails to browse to project UI `1.7.x`

- src/components/ProjectsPage/Projects.js
- **Projects**: The 'Confirm message' is missing when deleting a project 
Jira: https://iguazio.atlassian.net/browse/ML-7939
> Fix [Projects] The 'Confirm message' is missing when deleting a project

- src/components/FunctionsPage/Functions.js
- **Functions**: deleted ML function stays in the list after successful deletion `1.7.x`
Backported to `1.7.x` from #2791 
Jira: [ML-7961](https://iguazio.atlassian.net/browse/ML-7961)
[ML-7961]: https://iguazio.atlassian.net/browse/ML-7961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Functions] deleted ML function stays in the list after successful deletion `1.7.x`

- src/components/Details/details.util.js
- src/components/Jobs/jobs.util.js
- **Jobs**: run UI does not present run handler
Backported to `1.7.x` from #2796 
Jira: https://iguazio.atlassian.net/browse/ML-8005
After:
> Fix [Jobs] run UI does not present run handler `1.7.x`

- src/components/FunctionsPage/Functions.js
- **ML Functions**: There is no redirection to function overview pane `1.7.x`
Backported to `1.7.x` from #2797 
Jira: https://iguazio.atlassian.net/browse/ML-8016
> Fix [ML Functions] There is no redirection to function overview pane `1.7.x`

- src/components/ProjectsPage/Projects.js
- **Projects**: The 'Confirm message' is missing when deleting a project 
Backported to `1.7.x` from #2783 
Jira: https://iguazio.atlassian.net/browse/ML-7939
> Fix [Projects] The 'Confirm message' is missing when deleting a project `1.7.x`

- src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
- **Cross project**: Runs of type 'Job' displayed in the runs list of type 'mpijob' `1.7.x`
Backported to `1.7.x` from #2818 
Jira: https://iguazio.atlassian.net/browse/ML-8037
> Fix [Cross project] Runs of type 'Job' displayed in the runs list of type 'mpijob' `1.7.x`

- src/httpClient.js
- **General**: infinite loop when the BE endpoints return error `1.7.x`
Backported to `1.7.x` from #2824 
Jira: https://iguazio.atlassian.net/browse/ML-8034
> Fix [General] infinite loop when the BE endpoints return error `1.7.x`

- src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
- src/utils/createArtifactsContent.js
- **Model Endpoints**: It takes ~35 second to fetch data `1.7.x`
Backported to `1.7.x` from #2830 
Jira: https://iguazio.atlassian.net/browse/ML-8070
After:
> Fix [Model Endpoints] take ~35 second to fetch data `1.7.x`

- src/common/Download/DownloadContainer.js
- src/common/Notification/Notification.js
- **UI**: Warning: findDOMNode is deprecated
Backported to `1.7.x` from #2833 
Jira: https://iguazio.atlassian.net/browse/ML-6376
> Fix [UI] Warning: findDOMNode is deprecated `1.7.x`

- src/common/Input/Input.js
- src/components/Details/DetailsHeader/DetailsHeader.js
- src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
- src/elements/FeaturesTablePanel/FeaturesTablePanelView.js
- src/elements/FeaturesTablePanel/featuresTablePanel.scss
- src/elements/MembersPopUp/MembersPopUp.js
- **UI**: Warning icon overlay on input text `1.7.x`
Backported to `1.7.x` from #2838 
Jira: https://iguazio.atlassian.net/browse/ML-8085
> Fix [UI] Warning icon overlay on input text `1.7.x`

- package.json
- tests/features/MLFunction.feature
- tests/features/common-tools/common-consts.js
- tests/features/common/actions/table.action.js
- tests/features/common/page-objects/interactive-popup.po.js
- tests/features/common/page-objects/jobs-monitoring.po.js
- tests/features/common/page-objects/ml-functions.po.js
- tests/features/common/page-objects/project-settings.po.js
- tests/features/common/page-objects/projects.po.js
- tests/features/datasets.feature
- tests/features/jobsAndWorkflows.feature
- tests/features/jobsMonitoring.feature
- tests/features/models.feature
- tests/features/projectMonitoring.feature
- tests/features/projectSettings.feature
- tests/features/projectsPage.feature
- tests/features/step-definitions/table.steps.js
- tests/mockServer/data/funcs.json
- tests/mockServer/data/run.json
- tests/mockServer/data/runs.json
- tests/mockServer/dateSynchronization.js
- tests/mockServer/mock.js
* Updated tests according to the requirements:
- updated test on Project settings due to ML-7979
- added tests for searching by type, statuses, labels filter on the Jobs Monitoring page
- updated data for searching by type filter on the Jobs Monitoring page
* Updated tests according to the requirements:
- updated test with check broken link redirection on ML Functions
- added Show Untagged checkbox verify on ML Functions
- added Filter by filter verification on ML Functions
- updated label key/value verification on project card
- updated mock deleteProjectV2 with mlrun-deletion-strategy
> Impl [Tests] QA Sprint 171 done

- src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
- **UI**: "add a tag" UI should not check uniqueness but rather update the existing tag `1.7.x`
Backported to `1.7.x` from #2806 
Jira: https://iguazio.atlassian.net/browse/ML-8012
> Fix [UI] "add a tag" UI should not check uniqueness but rather update the existing tag `1.7.1`

- src/common/ReactFlow/mlReactFlow.util.js
- src/components/ArtifactsPreview/ArtifactsPreviewView.js
- src/components/FilterMenu/filterMenu.settings.js
- src/components/FunctionsPage/functions.util.js
- src/components/Jobs/jobs.util.js
- src/components/ProjectsJobsMonitoring/JobsMonitoring/jobsMonitoring.util.js
- src/constants.js
- src/elements/FeatureValidator/featureValidatior.utils.js
- src/elements/ProjectCard/projectCard.util.js
- src/elements/ProjectFunctions/ProjectFunctions.js
- src/elements/ProjectStatistics/ProjectStatistics.js
- src/elements/WorkflowsTable/WorkflowsTable.js
- src/utils/createJobsContent.js
- src/utils/generateMonitoringData.js
- src/utils/getState.js
- src/utils/parseJob.js
- **Jobs**: Add reason for job failure in UI next to the red status indicator `1.7.1`
Backported to `1.7.x` from #2820 
Jira: https://iguazio.atlassian.net/browse/ML-8001
> Impl [Jobs] Add reason for job failure in UI next to the red status indicator `1.7.1`

- src/components/ProjectsPage/ProjectsView.js
- src/utils/generateMonitoringData.js
- **Projects**: Clicking on search text box in projects refreshes the screen
Backported to `1.7.1` from #2853 
Jira: [ML-8171](https://iguazio.atlassian.net/browse/ML-8171)
[ML-8171]: https://iguazio.atlassian.net/browse/ML-8171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Projects] Clicking on search text box in projects refreshes the screen `1.7.1`

- src/elements/ProjectsMonitoringCounters/JobsCounters.js
- src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
- **Monitoring] missing tooltips on counters `1.7.1`
Backported to `1.7.1` from #2865 
Jira: https://iguazio.atlassian.net/browse/ML-8217
> Fix [Monitoring] missing tooltips on counters `1.7.1`

- src/utils/parseJob.js
- **Jobs**: Reason for job failure is not displayed
Backported to `1.7.x` from https://github.com/mlrun/ui/pull/2870
Jira: [ML-8241](https://iguazio.atlassian.net/browse/ML-8241)
[ML-8241]: https://iguazio.atlassian.net/browse/ML-8241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Jobs] reason for job failure is not displayed `1.7.1`

- src/components/ProjectSettings/projectSettings.scss
- src/elements/ChangeOwnerPopUp/changeOwnerPopUp.scss
- src/elements/ProjectSettingsGeneral/projectSettingsGeneral.scss
- src/scss/main.scss
- **Jobs**: Break filter row by resolution
Before:
After:
> Fix [Jobs] Break filter row by resolution

- src/elements/ProjectsMonitoringCounters/JobsCounters.js
- src/elements/ProjectsMonitoringCounters/ScheduledJobsCounters.js
- src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
- src/utils/generateMonitoringData.js
- **Jobs monitoring**: "Past 24 hours" time filter is applied after click on "In process" jobs
Jira: [ML-8481](https://iguazio.atlassian.net/browse/ML-8481)
[ML-8481]: https://iguazio.atlassian.net/browse/ML-8481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Jobs monitoring] "Past 24 hours" time filter is applied after click on "In process" jobs

- src/common/Pagination/Pagination.js
- src/components/Datasets/DatasetsView.js
- src/components/Details/DetailsHeader/DetailsHeader.js
- src/components/Documents/DocumentsView.js
- src/components/Files/FilesView.js
- src/components/FunctionsPage/FunctionsView.js
- src/components/ModelsPage/Models/ModelsView.js
- src/components/Workflow/Workflow.js
- src/elements/JobsTable/JobsTable.js
- src/utils/jobs.util.js
- src/utils/link-helper.util.js
- **Pagination**: next page is broken for ML functions. datasets, artifacts & models
Jira: https://iguazio.atlassian.net/browse/ML-8863
> Fix [Pagination] next page is broken for ML functions. datasets, artifacts & models

- src/components/Details/details.util.js
- **Alerts history**: "Failed to retrieve data " when click on Job ID from Alert page
Jira: https://iguazio.atlassian.net/browse/ML-8916?filter=-1
> Fix [Alerts history] "Failed to retrieve data " when click on Job ID from Alert page

- src/components/Datasets/Datasets.js
- src/components/Datasets/datasets.util.js
- src/components/FeatureStore/FeatureSets/FeatureSets.js
- src/components/FeatureStore/FeatureSets/featureSets.util.js
- src/components/FeatureStore/FeatureVectors/FeatureVectors.js
- src/components/FeatureStore/FeatureVectors/featureVectors.util.js
- **UI**: Move analyses tabs to Demo mode in `1.8.0`
Jira: [ML-9059](https://iguazio.atlassian.net/browse/ML-9059)
[ML-9059]: https://iguazio.atlassian.net/browse/ML-9059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [UI] Move analyses tabs to Demo mode in `1.8.0`

- src/api/projects-api.js
- src/components/ProjectSettings/ProjectSettings.js
- src/components/ProjectsPage/ProjectsView.js
- src/components/ProjectsPage/projects.util.js
- **Project Settings, Projects**: The second 'confirm message' is missing when deleting a non-empty project
Jira: [ML-8295](https://iguazio.atlassian.net/browse/ML-8295)
[ML-8295]: https://iguazio.atlassian.net/browse/ML-8295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Project Settings, Projects] The second 'confirm message' is missing when deleting a non-empty project

- src/utils/createAlertsContent.js
- **Alerts history**: Alerts notifications icons need tooltip 
Jira: https://iguazio.atlassian.net/browse/ML-9103
> Fix [Alerts history] Alerts notifications icons need tooltip 

- src/common/Download/DownloadContainer.js
- src/common/Download/downloadContainer.scss
- src/common/Notifications/Notification.js
- src/common/Notifications/notification.scss
- src/common/Notifications/notifications.scss
- src/hooks/useTimeout.js
- src/scss/main.scss
- **Notifications**: Add abilities to notification
Jira: [ML-8322](https://iguazio.atlassian.net/browse/ML-8322)
[ML-8322]: https://iguazio.atlassian.net/browse/ML-8322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Impl [Notifications] Add abilities to notification

- src/elements/WorkflowsTable/WorkflowsTable.js
- **Workflows**: Once the button is pressed, the UI should disable the button for 5 seconds, and then re-query the workflow status
Jira: https://iguazio.atlassian.net/browse/ML-9168
> Fix [Workflows] Once the button is pressed, the UI should disable the button for 5 seconds, and then re-query the workflow status

- package.json
- **Wizard**: Batch run - back/next buttons does not look like "button"
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/365
**Bump DRC version to `2.2.19`**
Jira: https://iguazio.atlassian.net/browse/ML-9222
Before:
After:
> Fix [Wizard] batch run - back/next buttons does not look like "button"

- src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
- src/constants.js
- **Workflows**: The "Retry" button doesn't work the second time for a "completed" workflow without using 'Refresh' button
Jira: https://iguazio.atlassian.net/browse/ML-9243
> Fix [Workflows] The "Retry" button doesn't work the second time for a "completed" workflow without using 'Refresh' button

- package.json
Includes: https://github.com/iguazio/dashboard-react-controls/pull/368
> Bump DRC version `2.2.20`

- src/constants.js
- src/index.js
- **CE**: link to "Real time functions" (nuclio) is broken when accessing mlrun UI via http
Jira: https://iguazio.atlassian.net/browse/CEML-334
> Fix [CE] link to "Real time functions" (nuclio) is broken when accessing mlrun UI via http

- src/components/DetailsPreview/DetailsPreview.js
- **Jobs monitoring**: Failed to load job artifact preview
Backported to `1.9.x` from #3190
Jira: https://iguazio.atlassian.net/browse/ML-9727
> Fix [Jobs monitoring] failed to load job artifact preview `1.9.x`

- src/components/FunctionsPageOld/FunctionsOld.js
- **ML functions**: "This function either does not exist or was deleted" notification after applying filter
Backported to `1.8.x` from. #3205 
Jira: https://iguazio.atlassian.net/browse/ML-9751
> Fix [ML functions] "This function either does not exist or was deleted" notification after applying filter `1.8.x`

- src/components/FunctionsPageOld/FunctionsOld.js
- **UI**: Function remains in UI after it was deleted `1.8.x`
Backported to `1.8.x` from #3223 
Jira: https://iguazio.atlassian.net/browse/ML-9794
> Fix [UI] function remains in UI after it was deleted `1.8.x`

- src/components/FunctionsPageOld/FunctionsOld.js
- **UI**: Function remains in UI after it was deleted `1.9.x`
Backported to `1.9.x` from #3223 
Jira: https://iguazio.atlassian.net/browse/ML-9794
> Fix [UI] function remains in UI after it was deleted `1.9.x`

- src/components/FunctionsPageOld/FunctionsOld.js
- **UI**: Function remains in UI after it was deleted `1.8.x`
Jira: https://iguazio.atlassian.net/browse/ML-9794
> Fix [UI] function remains in UI after it was deleted

- src/components/FunctionsPageOld/FunctionsOld.js
- **ML functions**: "This function either does not exist or was deleted" notification after applying filter
Backported to `1.9.x` from #3227 
Jira: https://iguazio.atlassian.net/browse/ML-9751
> Fix [ML functions] "This function either does not exist or was deleted" notification after applying filter `1.9.x`

- package.json
- src/common/ChipForm/ChipForm.jsx
- src/common/Input/Input.jsx
- src/common/SplitButton/SplitButton.jsx
- src/common/TextArea/TextArea.jsx
- **Artifacts**: Path dropdown doesn't close when clicking outside the field
Jira: https://iguazio.atlassian.net/browse/ML-9861
> Fix [Artifacts] Path dropdown doesn't close when clicking outside the field

- package.json
- **Artifacts**: Path dropdown doesn't close when clicking outside the field `1.8.x`
Backported to `1.8.x` from #3238 
Jira: https://iguazio.atlassian.net/browse/ML-9861
> Fix [Artifacts] Path dropdown doesn't close when clicking outside the field `1.8.x`

- package.json
- **Artifacts**: Path dropdown doesn't close when clicking outside the field `1.9.x`
Backported to `1.9.x` from #3238 
Jira: https://iguazio.atlassian.net/browse/ML-9861
> Fix [Artifacts] Path dropdown doesn't close when clicking outside the field `1.9.x`

- package.json
- src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
- src/components/ProjectsPage/ProjectsView.js
- **Projects**: 'Are you sure?' pop-up is missing `1.9.x`
Backported to `1.9.x` from #3255 
> Fix [Projects] 'Are you sure?' pop-up is missing `1.9.x`

- package.json
- src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
- src/components/ProjectsPage/ProjectsView.js
- **Projects**: 'Are you sure?' pop-up is missing `1.8.x`
Backported to `1.8.x` from #3255 
> Fix [Projects] 'Are you sure?' pop-up is missing `1.8.x`

- src/elements/DeleteArtifactPopUp/DeleteArtifactPopUp.js
- **Artifacts**: Click on "X" in Delete artifact? dialog does not take effect
Backported `1.9.x` from #3261 
Jira: https://iguazio.atlassian.net/browse/ML-9919
> Fix [Artifacts] click on "X" in Delete artifact? dialog does not take effect `1.9.x`

- src/elements/DeleteArtifactPopUp/DeleteArtifactPopUp.js
- **Artifacts**: Click on "X" in Delete artifact? dialog does not take effect
Backported `1.8.x` from #3261 
Jira: https://iguazio.atlassian.net/browse/ML-9919
> Fix [Artifacts] click on "X" in Delete artifact? dialog does not take effect `1.8.x`

- src/elements/ProjectFunctions/ProjectFunctions.jsx
- **Project monitoring**: Consumer Group button leads to home page   
Jira*: [ML-10205](https://iguazio.atlassian.net/browse/ML-10205)
[ML-10205]: https://iguazio.atlassian.net/browse/ML-10205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix [Project monitoring] Consumer Group button leads to home page

- src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.jsx
- **Workflows**: Retry option should not be available during "In Process" states
Fix: Retry option disabled in terminating
Jira: [ML10440](https://iguazio.atlassian.net/browse/ML-10440)
> Fix [Workflows] Retry option should not be available during "In Process" states

- package.json
- src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.jsx
- **Projects Setting**: Redundant request for empty label data and invalid empty-key in Node Selector params
Depends On: https://github.com/iguazio/dashboard-react-controls/pull/431
Jira: https://iguazio.atlassian.net/browse/ML-10416
> Fix [Projects Setting] Redundant request for empty label data and invalid empty-key in Node Selector params

- src/components/Pipeline/Pipeline.jsx
- **Real-time pipelines**: `input_path` and `result_path` are not presented
Jira: https://iguazio.atlassian.net/browse/ML-10924
> Fix [Real-time pipelines] `input_path` and `result_path` are not presented
